import { NextRequest, NextResponse } from "next/server";

import { authorizeRequest, resolveRequestScope } from "@/modules/foundation/api-auth";
import { captureHoustonThemeIntegratedDraft } from "@/modules/glw/houston-approved-draft-capture-service";
import { getHoustonDraftState } from "@/modules/glw/houston-approved-preview-draft-repository";
import { applyApprovedHoustonPreviewToDraft, buildHoustonDraftPreflight } from "@/modules/glw/houston-approved-preview-draft-service";
import { getHoustonPublicationState } from "@/modules/glw/houston-reference-page-publication-repository";
import { buildHoustonPublicationPreflight, publishHoustonReferencePage } from "@/modules/glw/houston-reference-page-publication-service";
import { HOUSTON_H1_NORMALIZATION_REPAIR_COMMIT, HOUSTON_PUBLIC_VERIFIER_VERSION, HOUSTON_VERIFIER_REPAIR_COMMIT, resolveHoustonPublicSeoContract } from "@/modules/glw/houston-reference-page-publication";

export const dynamic = "force-dynamic";
export const maxDuration = 300;
const access = (request: NextRequest, update = false) => { const auth = authorizeRequest(request, update ? "sites:update" : "sites:read"); const scope = resolveRequestScope(request); return { auth, valid: auth.ok && scope.organizationId === "ssi" && scope.siteId === "site-ssi-projectorenclosure" && (!update || auth.roles.includes("platform_admin")) }; };
const verifierAuthority = () => ({ runtimeSha: process.env.GENESIS_RUNTIME_SHA ?? null, verifierRepairCommit: HOUSTON_VERIFIER_REPAIR_COMMIT, h1NormalizationRepairCommit: HOUSTON_H1_NORMALIZATION_REPAIR_COMMIT, publicVerifierVersion: HOUSTON_PUBLIC_VERIFIER_VERSION, seoContract: resolveHoustonPublicSeoContract(), capabilities: { genericMetaLengthRuleRemoved: true, firstProbeEvidenceImplemented: true, fullVerifierResultPersisted: true, allFailedChecksPersisted: true, notEvaluatedSupported: true, evidencePersistedBeforeRollback: true, rollbackOrderingCorrect: true, h1SemanticNormalizationRepair: true, rawAndNormalizedH1Persisted: true } });

export async function GET(request: NextRequest) { const allowed = access(request); if (!allowed.valid) return NextResponse.json({ error: allowed.auth.error ?? "Exact Houston scope required." }, { status: allowed.auth.ok ? 403 : allowed.auth.status }); const verifier = verifierAuthority(); const publication = getHoustonPublicationState(); if (publication.referenceCertifications.length) return NextResponse.json({ verifier, publication, reference: publication.referenceCertifications.at(-1), wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }); const state = getHoustonDraftState(); if (state.receipts.length) { try { const preflight = await buildHoustonPublicationPreflight(); return NextResponse.json({ verifier, state, publication, readiness: preflight.readiness, identity: preflight.identity, target: preflight.target, campaignSafety: preflight.campaignSafety, expectedPublicUrl: "https://projectorenclosure.com/fan-cooled-projector-enclosures/texas/houston/", duplicateCount: 1, approvalRequired: true, wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }); } catch (error) { return NextResponse.json({ verifier, error: error instanceof Error ? error.message : "HOUSTON_PUBLICATION_PREFLIGHT_FAILED", state, publication, wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }, { status: 409 }); } } try { const preflight = await buildHoustonDraftPreflight(); return NextResponse.json({ verifier, identity: preflight.identity, target: preflight.target, parentId: preflight.parentId, duplicateCount: 0, approvalRequired: true, wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }); } catch (error) { return NextResponse.json({ verifier, error: error instanceof Error ? error.message : "HOUSTON_DRAFT_PREFLIGHT_FAILED", wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }, { status: 409 }); } }

export async function POST(request: NextRequest) { const allowed = access(request, true); if (!allowed.valid) return NextResponse.json({ error: "Platform-admin exact Houston scope required." }, { status: 403 }); const body = await request.json().catch(() => null) as { operation?: string } | null; if (!body || Object.keys(body).length !== 1 || !["APPLY_APPROVED_HOUSTON_PREVIEW_TO_DRAFT", "CAPTURE_HOUSTON_THEME_INTEGRATED_DRAFT", "PUBLISH_OWNER_APPROVED_HOUSTON_REFERENCE_PAGE"].includes(body.operation ?? "")) return NextResponse.json({ error: "Exact Houston operation required." }, { status: 400 }); try { const result = body.operation === "APPLY_APPROVED_HOUSTON_PREVIEW_TO_DRAFT" ? await applyApprovedHoustonPreviewToDraft() : body.operation === "CAPTURE_HOUSTON_THEME_INTEGRATED_DRAFT" ? await captureHoustonThemeIntegratedDraft() : await publishHoustonReferencePage(); const publication = body.operation === "PUBLISH_OWNER_APPROVED_HOUSTON_REFERENCE_PAGE"; return NextResponse.json({ ...result, wordpressMutationPerformed: !result.reused && body.operation !== "CAPTURE_HOUSTON_THEME_INTEGRATED_DRAFT", campaignMutationPerformed: publication && !result.reused, publicationPerformed: publication && !result.reused, schedulerInvoked: false, dispatchPerformed: false, leaseCreated: false, jobCreated: false, executionCreated: false, newDispatchDateCreated: false }, { status: result.reused ? 200 : 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "HOUSTON_OPERATION_FAILED", wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, schedulerInvoked: false, dispatchPerformed: false, leaseCreated: false, jobCreated: false, executionCreated: false, newDispatchDateCreated: false }, { status: 422 }); } }
