import { NextRequest, NextResponse } from "next/server";

import { authorizeRequest, resolveRequestScope } from "@/modules/foundation/api-auth";
import { captureHoustonThemeIntegratedDraft } from "@/modules/glw/houston-approved-draft-capture-service";
import { getHoustonDraftState } from "@/modules/glw/houston-approved-preview-draft-repository";
import { applyApprovedHoustonPreviewToDraft, buildHoustonDraftPreflight } from "@/modules/glw/houston-approved-preview-draft-service";

export const dynamic = "force-dynamic";
export const maxDuration = 300;
const access = (request: NextRequest, update = false) => { const auth = authorizeRequest(request, update ? "sites:update" : "sites:read"); const scope = resolveRequestScope(request); return { auth, valid: auth.ok && scope.organizationId === "ssi" && scope.siteId === "site-ssi-projectorenclosure" && (!update || auth.roles.includes("platform_admin")) }; };

export async function GET(request: NextRequest) { const allowed = access(request); if (!allowed.valid) return NextResponse.json({ error: allowed.auth.error ?? "Exact Houston scope required." }, { status: allowed.auth.ok ? 403 : allowed.auth.status }); const state = getHoustonDraftState(); if (state.receipts.length) return NextResponse.json({ state, wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }); try { const preflight = await buildHoustonDraftPreflight(); return NextResponse.json({ identity: preflight.identity, target: preflight.target, parentId: preflight.parentId, duplicateCount: 0, approvalRequired: true, wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "HOUSTON_DRAFT_PREFLIGHT_FAILED", wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }, { status: 409 }); } }

export async function POST(request: NextRequest) { const allowed = access(request, true); if (!allowed.valid) return NextResponse.json({ error: "Platform-admin exact Houston scope required." }, { status: 403 }); const body = await request.json().catch(() => null) as { operation?: string } | null; if (!body || Object.keys(body).length !== 1 || !["APPLY_APPROVED_HOUSTON_PREVIEW_TO_DRAFT", "CAPTURE_HOUSTON_THEME_INTEGRATED_DRAFT"].includes(body.operation ?? "")) return NextResponse.json({ error: "Exact Houston draft operation required." }, { status: 400 }); try { const result = body.operation === "APPLY_APPROVED_HOUSTON_PREVIEW_TO_DRAFT" ? await applyApprovedHoustonPreviewToDraft() : await captureHoustonThemeIntegratedDraft(); return NextResponse.json({ ...result, wordpressMutationPerformed: body.operation === "APPLY_APPROVED_HOUSTON_PREVIEW_TO_DRAFT" && !result.reused, campaignMutationPerformed: false, publicationPerformed: false, schedulerInvoked: false, dispatchPerformed: false, leaseCreated: false, jobCreated: false, executionCreated: false }, { status: result.reused ? 200 : 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "HOUSTON_DRAFT_OPERATION_FAILED", wordpressMutationPerformed: false, campaignMutationPerformed: false, publicationPerformed: false, schedulerInvoked: false, dispatchPerformed: false, leaseCreated: false, jobCreated: false, executionCreated: false }, { status: 422 }); } }
