import { deriveGenesisContrastReadiness, evaluateGenesisBackgroundAwareTextContrast, requiredGenesisContrast, summarizeGenesisContrast, type GenesisRenderedContrastObservation } from "../background-aware-text-contrast";

const item = (patch: Partial<GenesisRenderedContrastObservation> = {}): GenesisRenderedContrastObservation => ({ observationId: "fixture", viewport: "1440", sectionId: "fixture", textExcerpt: "Fixture heading", backgroundType: "DARK_SOLID", backgroundLuminanceClass: "DARK", overlayPresent: false, overlayLuminanceClass: null, textRole: "H2", foregroundColor: "#fff", effectiveBackgroundColor: "#172022", requiredContrast: requiredGenesisContrast("H2"), generatedImage: false, approvedOverlay: false, source: "COMPOSITION_RENDER", ...patch });
describe("GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_V1", () => {
  test.each([["white on dark solid", item()], ["dark on light solid", item({ backgroundType: "LIGHT_SOLID", backgroundLuminanceClass: "LIGHT", foregroundColor: "#172022", effectiveBackgroundColor: "#fff" })], ["white on dark image overlay", item({ backgroundType: "IMAGE_WITH_DARK_OVERLAY", overlayPresent: true, overlayLuminanceClass: "DARK", approvedOverlay: true })], ["dark on bright image region", item({ backgroundType: "IMAGE_WITH_LIGHT_OVERLAY", backgroundLuminanceClass: "LIGHT", overlayPresent: true, overlayLuminanceClass: "LIGHT", foregroundColor: "#172022", effectiveBackgroundColor: "#f5f5f5", approvedOverlay: true })]])("passes %s", (_name, fixture) => expect(summarizeGenesisContrast(evaluateGenesisBackgroundAwareTextContrast([fixture])).state).toBe("PASS"));
  test.each([["black on dark image", item({ backgroundType: "DARK_IMAGE", foregroundColor: "#191919", effectiveBackgroundColor: null })], ["black on charcoal", item({ foregroundColor: "#191919" })], ["white on light image", item({ backgroundType: "LIGHT_IMAGE", backgroundLuminanceClass: "LIGHT", effectiveBackgroundColor: null })], ["gray body on dark", item({ textRole: "BODY_COPY", requiredContrast: 4.5, foregroundColor: "#667070" })], ["CTA failure", item({ textRole: "CTA_PRIMARY_TEXT", requiredContrast: 4.5, foregroundColor: "#f2b84b", effectiveBackgroundColor: "#fff" })]])("fails %s", (_name, fixture) => expect(summarizeGenesisContrast(evaluateGenesisBackgroundAwareTextContrast([fixture])).state).toBe("FAIL"));
  test("fails a mobile crop independently from passing desktop", () => { const results = evaluateGenesisBackgroundAwareTextContrast([item({ viewport: "1440" }), item({ viewport: "375", backgroundType: "MIXED_OR_UNKNOWN", effectiveBackgroundColor: null })]); expect(results[0].contrastPass).toBe(true); expect(results[1].contrastPass).toBe(false); });
  test("supports every text role and a resolved gradient", () => { const roles = ["EYEBROW", "H1", "H2", "H3", "DISPLAY_HEADING", "BODY_COPY", "CTA_PRIMARY_TEXT", "CTA_SECONDARY_TEXT", "CAPTION", "DISCLAIMER", "LABEL"] as const; const results = evaluateGenesisBackgroundAwareTextContrast(roles.map((textRole) => item({ observationId: textRole, textRole, requiredContrast: requiredGenesisContrast(textRole), backgroundType: "GRADIENT", foregroundColor: "#fff", effectiveBackgroundColor: "#172022" }))); expect(results).toHaveLength(roles.length); expect(results.every((result) => result.contrastPass)).toBe(true); });
  test("is site neutral for a Commercial Stainless fixture", () => { const result = evaluateGenesisBackgroundAwareTextContrast([item({ observationId: "commercial-stainless-counter-heading", sectionId: "fabrication-capability", foregroundColor: "#ffffff", effectiveBackgroundColor: "#202426", source: "HOST_RENDER" })]); expect(result[0].contrastPass).toBe(true); expect(JSON.stringify(result)).not.toMatch(/San Antonio|ProjectorEnclosure|SSI/); });
  test("blocks owner review without PASS and requires HOST_RENDER for publication", () => { expect(deriveGenesisContrastReadiness({ state: null, authority: null, hostRenderEvidenceAvailable: false })).toEqual({ ownerReviewReady: false, publicationReady: false, ownerReviewGate: "BLOCKED", publicationGate: "BLOCKED" }); expect(deriveGenesisContrastReadiness({ state: "PASS", authority: "COMPOSITION_RENDER", hostRenderEvidenceAvailable: true }).publicationReady).toBe(false); expect(deriveGenesisContrastReadiness({ state: "PASS", authority: "HOST_RENDER", hostRenderEvidenceAvailable: true })).toEqual({ ownerReviewReady: true, publicationReady: true, ownerReviewGate: "PASS", publicationGate: "PASS" }); });
});