import { evaluateGenesisBackgroundAwareTextContrast, requiredGenesisContrast, summarizeGenesisContrast, type GenesisContrastObservation } from "../background-aware-text-contrast";

const observation=(patch:Partial<GenesisContrastObservation>={}):GenesisContrastObservation=>({observationId:"fixture",viewport:"1440",sectionId:"hero",backgroundType:"IMAGE_WITH_DARK_OVERLAY",backgroundLuminanceClass:"DARK",overlayPresent:true,textRole:"H1",foregroundColor:"#fff",effectiveBackgroundColor:"#202426",requiredContrast:requiredGenesisContrast("H1"),generatedImage:true,approvedOverlay:true,authority:"GENESIS_COMPOSITION_RENDER",...patch});

describe("background-aware text contrast",()=>{
  test("passes governed image overlays and solid sections",()=>{const results=evaluateGenesisBackgroundAwareTextContrast([observation(),observation({observationId:"light",backgroundType:"LIGHT_SOLID",backgroundLuminanceClass:"LIGHT",overlayPresent:false,textRole:"BODY_COPY",foregroundColor:"#0d0f10",effectiveBackgroundColor:"#fff",requiredContrast:4.5,generatedImage:false,approvedOverlay:false}),observation({observationId:"cta",backgroundType:"DARK_SOLID",textRole:"CTA_PRIMARY_TEXT",foregroundColor:"#fff",effectiveBackgroundColor:"#c91f2b",requiredContrast:4.5,generatedImage:false,approvedOverlay:false})]);expect(summarizeGenesisContrast(results)).toMatchObject({state:"PASS",observations:3,failures:[]});});
  test("fails unresolved image regions and low contrast",()=>{const results=evaluateGenesisBackgroundAwareTextContrast([observation({backgroundType:"MIXED_OR_UNKNOWN",effectiveBackgroundColor:null,approvedOverlay:false}),observation({observationId:"low",backgroundType:"DARK_SOLID",foregroundColor:"#191c1e",effectiveBackgroundColor:"#0d0f10",approvedOverlay:false})]);expect(results.map(item=>item.failureCode)).toEqual(["IMAGE_REGION_UNRESOLVED","LOW_CONTRAST"]);expect(summarizeGenesisContrast(results).state).toBe("FAIL");});
  test("is site neutral and distinguishes evidence authority",()=>{const results=evaluateGenesisBackgroundAwareTextContrast([observation({authority:"HOST_EQUIVALENT_RENDER",viewport:"375"})]);expect(results[0]).toMatchObject({authority:"HOST_EQUIVALENT_RENDER",contrastPass:true});expect(JSON.stringify(results)).not.toMatch(/Commercial Stainless|ProjectorEnclosure|San Antonio/);});
});
