import fs from "node:fs";
import path from "node:path";

const staging=fs.readFileSync(path.join(process.cwd(),"src/modules/foundation/commercial-stainless-wave2-staging.ts"),"utf8");
const route=fs.readFileSync(path.join(process.cwd(),"src/app/api/sites/[siteId]/commercial-stainless-wave-2-staging/route.ts"),"utf8");
const page=fs.readFileSync(path.join(process.cwd(),"src/app/sites/[siteId]/build/rich-composition-wave-2-wordpress/page.tsx"),"utf8");
const component=fs.readFileSync(path.join(process.cwd(),"src/modules/foundation/CommercialStainlessWave2WordPressReview.tsx"),"utf8");

describe("Commercial Stainless Wave 2 WordPress staging contract",()=>{
  test("binds exact authorized objects and composition hashes",()=>{for(const marker of ["COMMERCIAL_STAINLESS_WAVE2_OWNER_APPROVED_WORDPRESS_STAGING_V1:APPROVED","ca7d29883cdd679502fcce63faab5224351f6da8","b2e2f2b690e3d518472bd56e08886701293314d2215838b37d7a3c7fdbf4ddc3","ac370c9f08aff1b496e16346078d0959ab92d29a4e6a36f57e0dbb54a9bac36c","ccac7e46d1c40239736c0c65ffe236bd4cbd62e3717cb7ddfd390cf395ef5f4f","ceb8b68be8125545a71e17f5a6a6ecdb0148f06180555ebaf1e0b389bb9076e2","5925c0b7c45d0b082f163c9286cb400e5ae47a35045f77cad8239f38d7206c46","const AUTHORIZED_IDS=[12,15,16,18,19]"])expect(staging).toContain(marker);});
  test("persists pre-write authority and rolls back all created revisions",()=>{expect(staging.indexOf('status:"PREPARED"')).toBeLessThan(staging.indexOf('/autosaves`,{method:"POST"'));for(const marker of ["preStageContentRaw","preStageStoredHash","preStagePublicHash","preStageRevisionIds","preStageAuthorityRecoverable","created.reverse()","REVISION_DELETE_FAILED","rollbackExecuted:true"])expect(staging).toContain(marker);});
  test("verifies exact readback, parent, public, SEO, media, and profile invariants",()=>{for(const marker of ["STAGED_CONTENT_HASH_MISMATCH","PUBLISHED_PARENT_CHANGED","PUBLIC_LEAK_DETECTED","MEDIA_POLICY_FAILED","MEDIA_AUTHORITY_MISSING","copyPreserved:true","sectionSequencePreserved:true","profilePreserved:true","featuredMediaId"])expect(staging).toContain(marker);});
  test("uses reusable contrast policy and labels render authority honestly",()=>{for(const marker of ["evaluateGenesisBackgroundAwareTextContrast","GENESIS_COMPOSITION_RENDER","HOST_EQUIVALENT_RENDER","actualNativeHostEvidenceAvailable:false","nativeHostAuthorityClaimed:false","agentInjectedCssUsed:false"])expect(staging).toContain(marker);expect(component).toContain("host-equivalent evidence, not actual native-host preview evidence");expect(component).toContain("Actual native-host evidence is not available automatically");});
  test("requires all four responsive viewports and blocks publication",()=>{for(const marker of ["widths=[1440,1024,768,375]","horizontalOverflow===0","fragmentedTextCount===0","unusableCtaCount===0","largestBlankRegion<=120"])expect(staging).toContain(marker);expect(route).toContain("STAGE_COMMERCIAL_STAINLESS_WAVE2_APPROVED_COMPOSITIONS_V1");expect(route).toContain("CERTIFY_COMMERCIAL_STAINLESS_WAVE2_HOST_EQUIVALENT_V1");expect(route).toContain("publicationMutation:false");expect(route).not.toMatch(/publishCommercial|PUBLICATION_READY|status:\s*"publish"/);});
  test("reconciles exact approved raw authorities without a WordPress or publication write",()=>{for(const marker of ["RECONCILE_COMMERCIAL_STAINLESS_WAVE2_DURABLE_AUTHORITIES_V1","approvedContentRaw","approvedHashDurablyStored:true","autosaveDependency:false","contentReconstructed:false","copyChanged:false","mediaChanged:false","PENDING_SECOND_READ","COMMERCIAL_STAINLESS_WAVE2_PUBLIC_STATE_CHANGED","publicHashAfter:verifiedAfter.publicHash"])expect(staging+route).toContain(marker);expect(route).toContain("wordpressMutation:false,publicationMutation:false");});
  test("provides one exact site-scoped staged review route with no actions",()=>{expect(page).toContain("COMMERCIAL_STAINLESS_SITE_ID");expect(page).toContain("renderCommercialStainlessWave2StagedPage");for(const marker of ["Staged WordPress authorities","Approved hash","WordPress authority","Render authority","STAGING REVIEW ONLY","Publication locked"])expect(component).toContain(marker);expect(component).not.toMatch(/<button|onClick|fetch\(/i);});
});
