jest.mock("server-only", () => ({}));

import { NextRequest } from "next/server";
import { DELETE, GET, POST } from "@/app/api/operator-session/route";
import { createScryptPasswordHash, OPERATOR_CSRF_COOKIE, OPERATOR_CSRF_HEADER, OPERATOR_SESSION_COOKIE } from "../operator-session";

const password = "correct horse battery staple";
beforeEach(async () => { process.env.GCP_FOUNDATION_PERSISTENCE_DIR = `${process.cwd()}/.gcp-foundation-data-test-session-api-${expect.getState().currentTestName?.replace(/\W+/g, "-")}`; process.env.GENESIS_OPERATOR_DIRECTORY_JSON = JSON.stringify([{ principalId: "operator-001", email: "operator@example.com", roles: ["platform_admin"], passwordHash: await createScryptPasswordHash(password, Buffer.alloc(16, 9)) }]); });

test("login creates bounded strict cookies and status returns only server principal data", async () => { const login = await POST(new NextRequest("http://localhost:3004/api/operator-session", { method: "POST", headers: { origin: "http://localhost:3004", "content-type": "application/json" }, body: JSON.stringify({ identity: "operator@example.com", password }) })); expect(login.status).toBe(200); const cookies = login.headers.getSetCookie(); const sessionCookie = cookies.find((value) => value.startsWith(`${OPERATOR_SESSION_COOKIE}=`)); const csrfCookie = cookies.find((value) => value.startsWith(`${OPERATOR_CSRF_COOKIE}=`)); expect(sessionCookie).toMatch(/HttpOnly/i); expect(sessionCookie).toMatch(/SameSite=Strict/i); expect(sessionCookie).toMatch(/Max-Age=3600/i); expect(csrfCookie).not.toMatch(/HttpOnly/i); expect(csrfCookie).toMatch(/SameSite=Strict/i); const cookieHeader = cookies.map((value) => value.split(";")[0]).join("; "); const status = await GET(new NextRequest("http://localhost:3004/api/operator-session", { headers: { cookie: cookieHeader } })); expect(await status.json()).toMatchObject({ state: "AUTHENTICATED", authenticated: true, principal: { principalId: "operator-001", email: "operator@example.com", roles: ["platform_admin"], authenticationAuthority: "GENESIS_SERVER_SESSION_V1" } }); });
test("authenticated status check renews bounded cookies and extends session expiry", async () => {
	const login = await POST(new NextRequest("http://localhost:3004/api/operator-session", { method: "POST", headers: { origin: "http://localhost:3004", "content-type": "application/json" }, body: JSON.stringify({ identity: "operator@example.com", password }) }));
	const loginBody = await login.json() as { principal: { expiresAt: string } };
	const cookieHeader = login.headers.getSetCookie().map((value) => value.split(";")[0]).join("; ");
	const status = await GET(new NextRequest("http://localhost:3004/api/operator-session", { headers: { cookie: cookieHeader } }));
	const statusBody = await status.json() as { state: string; principal: { expiresAt: string } };
	expect(status.status).toBe(200);
	expect(statusBody.state).toBe("AUTHENTICATED");
	expect(new Date(statusBody.principal.expiresAt).getTime()).toBeGreaterThanOrEqual(new Date(loginBody.principal.expiresAt).getTime());
	const renewedCookies = status.headers.getSetCookie();
	expect(renewedCookies.some((value) => value.startsWith(`${OPERATOR_SESSION_COOKIE}=`) && /Max-Age=3600/i.test(value))).toBe(true);
	expect(renewedCookies.some((value) => value.startsWith(`${OPERATOR_CSRF_COOKIE}=`) && /Max-Age=3600/i.test(value))).toBe(true);
});
test("login denies cross-origin and invalid credentials before creating cookies", async () => { const crossOrigin = await POST(new NextRequest("https://genesis.example/api/operator-session", { method: "POST", headers: { origin: "https://attacker.example", "content-type": "application/json" }, body: JSON.stringify({ identity: "operator@example.com", password }) })); expect(crossOrigin.status).toBe(403); expect(crossOrigin.headers.getSetCookie()).toHaveLength(0); const invalid = await POST(new NextRequest("https://genesis.example/api/operator-session", { method: "POST", headers: { origin: "https://genesis.example", "content-type": "application/json" }, body: JSON.stringify({ identity: "operator@example.com", password: "incorrect password" }) })); expect(invalid.status).toBe(401); });
test("HTTPS login marks both session transport cookies Secure", async () => { const login = await POST(new NextRequest("https://genesis.example/api/operator-session", { method: "POST", headers: { origin: "https://genesis.example", "content-type": "application/json" }, body: JSON.stringify({ identity: "operator@example.com", password }) })); expect(login.headers.getSetCookie()).toHaveLength(2); expect(login.headers.getSetCookie().every((cookie) => /Secure/i.test(cookie))).toBe(true); });
test("logout requires same-origin session-bound CSRF and revokes the session", async () => { const login = await POST(new NextRequest("https://genesis.example/api/operator-session", { method: "POST", headers: { origin: "https://genesis.example", "content-type": "application/json" }, body: JSON.stringify({ identity: "operator@example.com", password }) })); const values = Object.fromEntries(login.headers.getSetCookie().map((value) => value.split(";")[0].split("="))); const cookie = `${OPERATOR_SESSION_COOKIE}=${values[OPERATOR_SESSION_COOKIE]}; ${OPERATOR_CSRF_COOKIE}=${values[OPERATOR_CSRF_COOKIE]}`; const logout = await DELETE(new NextRequest("https://genesis.example/api/operator-session", { method: "DELETE", headers: { origin: "https://genesis.example", cookie, [OPERATOR_CSRF_HEADER]: values[OPERATOR_CSRF_COOKIE] } })); expect(logout.status).toBe(200); const status = await GET(new NextRequest("https://genesis.example/api/operator-session", { headers: { cookie } })); expect(status.status).toBe(401); expect(await status.json()).toMatchObject({ state: "SESSION_REVOKED", authenticated: false }); });