import { applyPublicHostLinkStatus, classifyPublicHostLink, discoverPublicHostLinks, replayPersistedHrefEvidence } from "../public-host-link-classification";

const documentUrl = "https://projectorenclosure.com/current/"; const internalHosts = ["projectorenclosure.com", "www.projectorenclosure.com"];
const classify = (sourceElementType: string, href: string, rel: string[] = []) => classifyPublicHostLink({ sourceElementType, href, rel, documentUrl, internalHosts });
describe("public host link classification", () => {
  test.each([[200, "PASS"], [404, "FAIL"], [500, "FAIL"]] as const)("internal anchor status %i produces %s", (status, result) => { const link = applyPublicHostLinkStatus(classify("a", "/real-page/"), status); expect(link).toMatchObject({ classification: "NAVIGATIONAL_ANCHOR", validationPolicy: "VALIDATE_INTERNAL_NAVIGATION", result, httpStatus: status }); });
  test("classifies WordPress discovery and protocol endpoints outside navigation", () => { expect(applyPublicHostLinkStatus(classify("link", "/wp-json/oembed/1.0/embed", ["alternate"]), 400)).toMatchObject({ classification: "WORDPRESS_DISCOVERY_METADATA", validationPolicy: "NOT_APPLICABLE_TO_NAVIGATION", result: "NOT_APPLICABLE", httpStatus: 400 }); expect(applyPublicHostLinkStatus(classify("link", "/xmlrpc.php", ["pingback"]), 405)).toMatchObject({ classification: "PROTOCOL_ENDPOINT", validationPolicy: "NOT_APPLICABLE_TO_NAVIGATION", result: "NOT_APPLICABLE", httpStatus: 405 }); });
  test("classifies resources, SEO, discovery, external, non-http, and local navigation", () => { expect(classify("link", "/style.css", ["stylesheet"]).classification).toBe("MEDIA_RESOURCE"); expect(classify("link", "/canonical/", ["canonical"])).toMatchObject({ classification: "CANONICAL_OR_SEO_LINK", validationPolicy: "SEO_AUTHORITY" }); expect(classify("link", "/feed/", ["alternate"])).toMatchObject({ classification: "WORDPRESS_DISCOVERY_METADATA", validationPolicy: "NOT_APPLICABLE_TO_NAVIGATION" }); expect(classify("a", "https://example.com/").classification).toBe("EXTERNAL_LINK"); expect(classify("a", "mailto:test@example.com").classification).toBe("NON_HTTP_NAVIGATION"); expect(classify("a", "tel:123").classification).toBe("NON_HTTP_NAVIGATION"); expect(classify("a", "#section").classification).toBe("LOCAL_DOCUMENT_NAVIGATION"); });
  test("fails closed for unknown same-site anchors, dev, preview, invalid, and network errors", () => { expect(classify("a", "/unknown-page/")).toMatchObject({ classification: "NAVIGATIONAL_ANCHOR", validationPolicy: "VALIDATE_INTERNAL_NAVIGATION" }); expect(classify("a", "http://localhost:3003/dev")).toMatchObject({ validationPolicy: "FAIL_INVALID_NAVIGATION", reason: "DEVELOPMENT_TARGET" }); expect(classify("a", "/?preview=true")).toMatchObject({ validationPolicy: "FAIL_INVALID_NAVIGATION", reason: "PREVIEW_OR_ADMIN_TARGET" }); expect(classify("a", "http://[")).toMatchObject({ validationPolicy: "FAIL_INVALID_NAVIGATION", reason: "INVALID_URL" }); expect(applyPublicHostLinkStatus(classify("a", "/network/"), null, true)).toMatchObject({ result: "FAIL", reason: "NETWORK_ERROR" }); });
  test("discovers source element and rel authority from DOM", () => { const links = discoverPublicHostLinks({ html: '<a href="/page/">Page</a><link rel="canonical" href="/canonical/"><link rel="alternate" type="application/json+oembed" href="/wp-json/oembed/1.0/embed"><link rel="stylesheet" href="/style.css">', documentUrl, internalHosts }); expect(links).toHaveLength(4); expect(links.map((item) => item.sourceElementType)).toEqual(["a", "link", "link", "link"]); expect(links[1].rel).toEqual(["canonical"]); });
  test("replays V2 false positives as non-navigational", () => { const replay = replayPersistedHrefEvidence({ responses: [{ url: "https://projectorenclosure.com/wp-json/oembed/1.0/embed", status: 400, ok: false }, { url: "https://projectorenclosure.com/xmlrpc.php", status: 405, ok: false }, { url: "https://projectorenclosure.com/valid/", status: 200, ok: true }], documentUrl, internalHosts }); expect(replay).toMatchObject({ exactSourceElementAuthorityAvailable: false, previousFalsePositiveEndpointsClassifiedCorrectly: true, actualNavigationalBrokenLinks: 0, otherV2RealLinkFailures: [], result: "PASS" }); });
});