import { createObservedPublicVerifierFetch, redactVerifierUrl, serializePublicVerifierError, type PublicVerifierFetchEvidence, type PublicVerifierFetchPhase } from "../public-verifier-fetch-observability";

const failure = (name: string, message: string, code: string, cause?: unknown) => Object.assign(new Error(message, cause ? { cause } : undefined), { name, code, errno: -1, syscall: "connect", address: "127.0.0.1", port: 443, socket: { localAddress: "127.0.0.1", localPort: 50000, remoteAddress: "127.0.0.1", remotePort: 443, remoteFamily: "IPv4", timeout: 30000, bytesWritten: 128, bytesRead: 0 } });
const runFailure = async (phase: PublicVerifierFetchPhase, error: Error, url = "https://example.test/path?token=secret") => { const records: PublicVerifierFetchEvidence[] = []; const observed = createObservedPublicVerifierFetch({ record: (item) => records.push(item), fetcher: jest.fn().mockRejectedValue(error), attemptIdFactory: () => "forced-observability-attempt-001" }); await expect(observed({ verificationReceiptId: "verification-receipt-001", phase, url, init: { method: "GET", redirect: "follow", cache: "no-store", signal: AbortSignal.timeout(30_000) }, attemptNumber: 1, timeoutMs: 30_000 })).rejects.toBe(error); return records; };

describe("public verifier fetch observability", () => {
  test.each([
    ["DNS", "CANONICAL_PUBLIC_READ", failure("TypeError", "fetch failed", "ENOTFOUND", failure("Error", "getaddrinfo ENOTFOUND example.test", "ENOTFOUND"))],
    ["CONNECTION_REFUSED", "INTERNAL_LINK_FETCH", failure("TypeError", "fetch failed", "ECONNREFUSED", failure("Error", "connect ECONNREFUSED 127.0.0.1:443", "ECONNREFUSED"))],
    ["TLS_SOCKET", "MEDIA_FETCH", failure("TypeError", "fetch failed", "UND_ERR_SOCKET", failure("SocketError", "other side closed", "UND_ERR_SOCKET"))],
    ["TIMEOUT", "PUBLIC_CONVERGENCE_READ", failure("TimeoutError", "The operation was aborted due to timeout", "UND_ERR_CONNECT_TIMEOUT")],
    ["ABORT", "ROLLBACK_VERIFICATION_READ", failure("AbortError", "This operation was aborted", "ABORT_ERR")],
    ["NESTED_UNDICI", "SEO_OR_CANONICAL_FETCH", failure("TypeError", "fetch failed", "ERR_FETCH", failure("ConnectTimeoutError", "Connect Timeout Error", "UND_ERR_CONNECT_TIMEOUT"))],
  ] as const)("persists %s failure identity and nested cause", async (_fixture, phase, error) => {
    const records = await runFailure(phase, error); const request = records[0]; const failed = records[1];
    expect(request).toMatchObject({ attemptId: "forced-observability-attempt-001", verificationReceiptId: "verification-receipt-001", phase, event: "REQUEST", method: "GET", attemptNumber: 1, timeoutMs: 30000 });
    expect(failed).toMatchObject({ attemptId: request.attemptId, phase, event: "ERROR", url: "https://example.test/path?token=%5BREDACTED%5D" });
    expect(failed.error).toMatchObject({ name: error.name, message: error.message, code: error.code, errno: -1, syscall: "connect", address: "127.0.0.1", port: 443 });
    expect(failed.error?.stack).toContain(error.name); expect(failed.runtimeSha).toMatch(/^[a-f0-9]{64}$/); expect(failed.nodeVersion).toBe(process.version); expect(failed.fetchImplementation).toContain("node-native-fetch:undici-"); expect(failed.error?.socket?.remoteAddress).toBe("127.0.0.1");
    if (error.cause) expect(failed.error?.cause).not.toBeNull();
    expect(JSON.stringify(records)).not.toContain("secret");
  });

  test.each(["CANONICAL_PUBLIC_READ", "INTERNAL_LINK_FETCH"] as const)("retains phase and URL for %s failure", async (phase) => { const records = await runFailure(phase, failure("TypeError", "fetch failed", "UND_ERR_SOCKET"), `https://example.test/${phase.toLowerCase()}`); expect(records.at(-1)).toMatchObject({ phase, url: `https://example.test/${phase.toLowerCase()}`, event: "ERROR" }); });

  test("persists response and body completion without storing the body", async () => { const records: PublicVerifierFetchEvidence[] = []; const fetcher = jest.fn(async (_url: string | URL | Request, init?: RequestInit) => { expect(init).toMatchObject({ redirect: "manual", cache: "no-store" }); return new Response("bounded body", { status: 404, headers: { "cache-control": "private, no-store", "content-type": "text/plain", server: "fixture" } }); }); const observed = createObservedPublicVerifierFetch({ record: (item) => records.push(item), fetcher, attemptIdFactory: () => "response-attempt-001" }); const result = await observed({ verificationReceiptId: "verification-receipt-001", phase: "CANONICAL_PUBLIC_READ", url: "https://example.test/missing", init: { redirect: "manual", cache: "no-store" }, attemptNumber: 1, timeoutMs: null }); expect(await result.text("CANONICAL_BODY_READ")).toBe("bounded body"); result.recordValidation("SEO_OR_CANONICAL_FETCH"); expect(records.map((item) => item.event)).toEqual(["REQUEST", "RESPONSE", "BODY_COMPLETE", "VALIDATION"]); expect(records[1].response).toMatchObject({ status: 404, finalUrl: "https://example.test/missing", cacheClassification: "PRIVATE_NO_STORE", bodyReadComplete: false }); expect(records[2].response).toMatchObject({ bodyReadComplete: true, bodyBytes: 12 }); expect(JSON.stringify(records)).not.toContain("bounded body"); });

  test("persists response-body-read failure with nested cause", async () => { const bodyCause = failure("SocketError", "terminated", "UND_ERR_SOCKET"); const response = new Response(new ReadableStream({ start(controller) { controller.error(failure("TypeError", "Body is unusable", "ERR_BODY", bodyCause)); } }), { status: 200 }); const records: PublicVerifierFetchEvidence[] = []; const observed = createObservedPublicVerifierFetch({ record: (item) => records.push(item), fetcher: jest.fn().mockResolvedValue(response), attemptIdFactory: () => "body-failure-attempt-001" }); const result = await observed({ verificationReceiptId: "verification-receipt-001", phase: "CANONICAL_PUBLIC_READ", url: "https://example.test/body", init: { signal: AbortSignal.timeout(30_000) }, attemptNumber: 1, timeoutMs: 30_000 }); await expect(result.text("CANONICAL_BODY_READ")).rejects.toThrow("Body is unusable"); expect(records.at(-1)).toMatchObject({ attemptId: "body-failure-attempt-001", phase: "CANONICAL_BODY_READ", event: "ERROR", error: { name: "TypeError", message: "Body is unusable", code: "ERR_BODY", cause: { name: "SocketError", code: "UND_ERR_SOCKET" } } }); });

  test("serializes aggregate causes and redacts URL credentials", () => { const aggregate = Object.assign(new Error("fetch failed"), { errors: [failure("Error", "first", "ECONNRESET"), failure("Error", "second", "ETIMEDOUT")] }); expect(serializePublicVerifierError(aggregate).cause).toHaveLength(2); expect(redactVerifierUrl("https://user:password@example.test/path?nonce=abc&safe=1")).toBe("https://example.test/path?nonce=%5BREDACTED%5D&safe=1"); });
});