import { compositionProfileForPageType, createRichPageCompositionPlan, evaluateRichPageComposition, mediaExpectationFromAssignments, validateRichPageCompositionPlan } from "../rich-page-composition";
import type { RenderedVisualCaptureEvidence } from "../rendered-visual-certification";

const capture = (viewportClass: "DESKTOP" | "MOBILE", width: number, contentWidth: number): RenderedVisualCaptureEvidence => ({ captureId: viewportClass, viewportClass, viewportWidth: width, viewportHeight: 900, documentWidth: width, documentHeight: 3000, primaryContentBounds: { x: (width-contentWidth)/2, y: 0, width: contentWidth, height: 3000 }, horizontalOverflow: 0, screenshotArtifact: { reference: "a", sha256: "a".repeat(64), byteSize: 1, width, height: 900, mediaType: "image/png" }, capturedAt: new Date().toISOString(), source: { origin: "https://example.com", pathname: "/" }, renderer: { engine: "test", version: null, userAgent: null }, hero: { authority: "SEMANTIC_HERO", present: true, bounds: { x: 0, y: 0, width: contentWidth, height: 600 }, headingBounds: { x: 20, y: 20, width: 500, height: 100 }, headingLineCount: 2, primaryCtaBounds: null, mediaBounds: null, mediaBeforeHero: null, containerAligned: true }, media: [], sections: [300, 700, 500, 700].map((sectionWidth,index)=>({ sectionId:`s${index}`,bounds:{x:0,y:index*500,width:Math.min(sectionWidth,contentWidth),height:400},headingBounds:null,headingLineCount:null,contentBounds:null,mediaBounds:null,gapBefore:40 })) });
const identity = { organizationId:"o",siteId:"s",pageId:"p",pageRevisionIdentity:"r1",canonicalPath:"/p",jobId:"j",wordpressObjectId:"1" };

describe("Rich Page Composition V1",()=>{
  it("maps existing page types to site-neutral profiles",()=>{ expect(compositionProfileForPageType("city_service")).toBe("LOCATION_SERVICE"); expect(compositionProfileForPageType("OFFERING")).toBe("PRODUCT_SERVICE"); expect(compositionProfileForPageType("MARKET")).toBe("MARKET_INDUSTRY"); expect(compositionProfileForPageType("CAPABILITIES")).toBe("CAPABILITY"); expect(compositionProfileForPageType("HOME")).toBe("LANDING_CONVERSION"); expect(compositionProfileForPageType("article")).toBe("EDITORIAL_RESOURCE"); });
  it("binds an exact revision and rejects stale identity",()=>{ const plan=createRichPageCompositionPlan({planId:"plan",identity,pageType:"city_service",media:[],decisionSource:"test",evidenceReferences:[]}); expect(plan.contract).toBe("site-page-composition-plan-v1"); expect(()=>validateRichPageCompositionPlan(plan,"r2")).toThrow("RICH_PAGE_COMPOSITION_PLAN_STALE"); });
  it("does not fabricate product authority and preserves legacy contextual state",()=>{ const product=mediaExpectationFromAssignments({role:"PRODUCT_AUTHORITY",requirement:"REQUIRED",slotId:"product",assignments:[],pageRevisionIdentity:"r1",authorityAvailable:true}); const contextual=mediaExpectationFromAssignments({role:"CONTEXTUAL_IN_USE",requirement:"DESIRED",slotId:"context",assignments:[],pageRevisionIdentity:"r1",legacy:{mediaId:"41",provenance:"LEGACY_FEATURED"}}); expect(product.readiness).toBe("NOT_WIRED"); expect(contextual.readiness).toBe("LEGACY"); const plan=createRichPageCompositionPlan({planId:"p",identity,pageType:"city_service",media:[product,contextual],decisionSource:"test",evidenceReferences:[]}); expect(plan.validationState).toBe("BLOCKED"); expect(plan.blockers).toContain("PRODUCT_AUTHORITY_NOT_WIRED"); });
  it("consumes generated contextual assignments only with their PRODUCT_TRUTH grounding intact",()=>{ const assignment={assignmentId:"a",organizationId:"o",siteId:"s",buildSessionId:"b",pageId:"p",pageRevisionId:"r1",slotId:"context",role:"CONTEXTUAL_IN_USE",asset:{type:"GENERATED",provider:"provider",model:"model",generationJobId:"job",effectivePrompt:"bounded",referenceInputs:[{referenceId:"product",role:"PRODUCT_TRUTH",sha256:"a".repeat(64)}],outputSha256:"b".repeat(64)},metadata:{altText:"alt",caption:null,title:"title",description:"description"},approval:{candidateId:"c",approvedBy:"owner",approvedAt:new Date().toISOString()},wordpressReceipt:null,createdAt:new Date().toISOString()} as const; const media=mediaExpectationFromAssignments({role:"CONTEXTUAL_IN_USE",requirement:"DESIRED",slotId:"context",assignments:[assignment],pageRevisionIdentity:"r1"}); expect(media).toMatchObject({readiness:"READY",assignmentId:"a"}); expect(media.provenance).toContain("PRODUCT_TRUTH_GROUNDED"); });
  it("distinguishes page canvas from prose measure and evaluates bounded composition evidence",()=>{ const plan=createRichPageCompositionPlan({planId:"p",identity,pageType:"city_service",cta:{label:"Quote",destination:"/quote"},media:[],decisionSource:"test",evidenceReferences:[]}); const findings=evaluateRichPageComposition({plan,captures:[capture("DESKTOP",1440,640),capture("MOBILE",375,340)],duplicateOpeningMedia:false,cardWidths:[300],proseWidths:[680],headerWidth:640,primaryCtaDistinct:true}); expect(findings.find(x=>x.code==="DESKTOP_CANVAS_UTILIZATION")?.state).toBe("WARNING"); expect(findings.find(x=>x.code==="TEXT_MEASURE")?.state).toBe("PASS"); expect(findings.find(x=>x.code==="DUPLICATE_OPENING_MEDIA")?.state).toBe("PASS"); expect(findings.find(x=>x.code==="RESPONSIVE_COMPOSITION")?.state).toBe("PASS"); expect(findings.find(x=>x.code==="GLOBAL_CTA_HIERARCHY")?.state).toBe("PASS"); });
  it("uses NOT_EVALUATED when selectors or semantic bounds are absent",()=>{ const plan=createRichPageCompositionPlan({planId:"p",identity,pageType:"article",media:[],decisionSource:"test",evidenceReferences:[]}); const findings=evaluateRichPageComposition({plan,captures:[],duplicateOpeningMedia:null,cardWidths:null,proseWidths:null,headerWidth:null,primaryCtaDistinct:null}); expect(findings.filter(x=>x.state==="NOT_EVALUATED").length).toBeGreaterThan(5); });
  it("exposes every V1 composition concern without site-specific design tokens",()=>{ const plan=createRichPageCompositionPlan({planId:"p",identity,pageType:"city_service",media:[],decisionSource:"approved evidence",evidenceReferences:[]}); const findings=evaluateRichPageComposition({plan,captures:[capture("DESKTOP",1440,1200),capture("MOBILE",375,340)],duplicateOpeningMedia:false,cardWidths:[300],proseWidths:[680],headerWidth:1180,primaryCtaDistinct:true}); const codes=new Set(findings.map(item=>item.code)); for(const code of ["DESKTOP_CANVAS_UTILIZATION","DUPLICATE_OPENING_MEDIA","SECTION_WIDTH_VARIATION","TEXT_MEASURE","SPLIT_SECTION_PROPORTION","CARD_SCALE","VISUAL_RHYTHM","CTA_PROMINENCE","RESPONSIVE_COMPOSITION","GLOBAL_HEADER_ALIGNMENT","GLOBAL_CTA_HIERARCHY"]) expect(codes.has(code)).toBe(true); expect(JSON.stringify(plan)).not.toMatch(/commercial stainless|rocklin|dallas|#d62828|1240/i); });
});