graph LR
  sales-->src_lib_gba_manufacturing_repository_ts
  sales-->src_lib_gba_manufacturing_runtime_ts
  sales-->src_lib_gba_marketing_repository_ts
  sales-->src_lib_gba_marketing_runtime_ts
  sales-->src_lib_gba_operations_repository_ts
  sales-->src_lib_gba_operations_runtime_ts
  finance-->src_lib_gba_executive_repository_ts
  finance-->src_lib_gba_executive_runtime_ts
  finance-->src_lib_gba_manufacturing_repository_ts
  finance-->src_lib_gba_manufacturing_runtime_ts
  finance-->src_lib_gba_marketing_repository_ts
  finance-->src_lib_gba_marketing_runtime_ts
  finance-->src_lib_gba_operations_repository_ts
  finance-->src_lib_gba_operations_runtime_ts
  finance-->src_lib_gba_sales_repository_ts
  finance-->src_lib_gba_sales_runtime_ts
  customer_success-->src_lib_gba_executive_repository_ts
  customer_success-->src_lib_gba_executive_runtime_ts
  customer_success-->src_lib_gba_finance_repository_ts
  customer_success-->src_lib_gba_finance_runtime_ts
  customer_success-->src_lib_gba_manufacturing_repository_ts
  customer_success-->src_lib_gba_manufacturing_runtime_ts
  customer_success-->src_lib_gba_marketing_repository_ts
  customer_success-->src_lib_gba_marketing_runtime_ts
  customer_success-->src_lib_gba_operations_repository_ts
  customer_success-->src_lib_gba_operations_runtime_ts
  customer_success-->src_lib_gba_sales_repository_ts
  customer_success-->src_lib_gba_sales_runtime_ts
