graph TD
  api_transport-->business_agents
  api_transport-->domain_kernel
  api_transport-->enterprise_agents
  api_transport-->runtime_services
  application_ui-->application_ui
  application_ui-->business_agents
  application_ui-->domain_kernel
  application_ui-->enterprise_agents
  application_ui-->platform_orchestration
  application_ui-->runtime_services
  application_ui-->shared_infrastructure
  business_agents-->business_agents
  business_agents-->domain_kernel
  business_agents-->enterprise_agents
  business_agents-->platform_orchestration
  business_agents-->runtime_services
  compiler_generation-->compiler_generation
  compiler_generation-->shared_infrastructure
  domain_kernel-->domain_kernel
  domain_kernel-->platform_orchestration
  domain_kernel-->runtime_services
  domain_kernel-->shared_infrastructure
  enterprise_agents-->enterprise_agents
  enterprise_agents-->platform_orchestration
  enterprise_agents-->runtime_services
  platform_orchestration-->platform_orchestration
  platform_orchestration-->runtime_services
  runtime_services-->platform_orchestration
  runtime_services-->runtime_services
  shared_infrastructure-->application_ui
  shared_infrastructure-->compiler_generation
  shared_infrastructure-->domain_kernel
  shared_infrastructure-->shared_infrastructure
  tests-->api_transport
  tests-->application_ui
  tests-->business_agents
  tests-->compiler_generation
  tests-->domain_kernel
  tests-->enterprise_agents
  tests-->platform_orchestration
