graph LR
  agent_api_ts-->agent_models_ts
  agent_api_ts-->agent_repository_ts
  agent_api_ts-->agent_runtime_ts
  agent_api_ts-->auth_ts
  agent_api_ts-->capability_registry_ts
  agent_api_ts-->resolver_ts
  agent_api_ts-->runtime_ts
  agent_api_ts-->tool_framework_ts
  agent_repository_ts-->agent_models_ts
  agent_repository_ts-->prisma_ts
  agent_runtime_ts-->agent_models_ts
  agent_runtime_ts-->agent_repository_ts
  agent_runtime_ts-->capability_registry_ts
  agent_runtime_ts-->context_builder_ts
  agent_runtime_ts-->permission_engine_ts
  agent_runtime_ts-->planning_engine_ts
  agent_runtime_ts-->tool_framework_ts
  capability_registry_ts-->agent_models_ts
  context_builder_ts-->agent_models_ts
  context_builder_ts-->agent_models_ts
  context_framework_ts-->agent_models_ts
  context_framework_ts-->memory_models_ts
  context_framework_ts-->memory_registry_ts
  context_framework_ts-->memory_repository_ts
  memory_api_ts-->auth_ts
  memory_api_ts-->context_framework_ts
  memory_api_ts-->memory_models_ts
  memory_api_ts-->memory_registry_ts
  memory_api_ts-->memory_repository_ts
  memory_api_ts-->resolver_ts
  memory_api_ts-->runtime_ts
  memory_models_ts-->agent_models_ts
  memory_registry_ts-->agent_models_ts
  memory_registry_ts-->memory_models_ts
  memory_registry_ts-->memory_repository_ts
  memory_repository_ts-->memory_models_ts
  memory_repository_ts-->prisma_ts
  orchestration_api_ts-->agent_models_ts
  orchestration_api_ts-->agent_repository_ts
  orchestration_api_ts-->agent_runtime_ts
  orchestration_api_ts-->auth_ts
  orchestration_api_ts-->capability_registry_ts
  orchestration_api_ts-->orchestration_models_ts
  orchestration_api_ts-->orchestration_repository_ts
  orchestration_api_ts-->orchestration_runtime_ts
  orchestration_api_ts-->resolver_ts
  orchestration_api_ts-->runtime_ts
  orchestration_api_ts-->tool_framework_ts
  orchestration_models_ts-->agent_models_ts
  orchestration_repository_ts-->orchestration_models_ts
  orchestration_repository_ts-->prisma_ts
  orchestration_runtime_ts-->agent_models_ts
  orchestration_runtime_ts-->agent_runtime_ts
  orchestration_runtime_ts-->orchestration_models_ts
  orchestration_runtime_ts-->orchestration_repository_ts
  permission_engine_ts-->agent_models_ts
  permission_engine_ts-->agent_models_ts
  planning_engine_ts-->agent_models_ts
  planning_engine_ts-->capability_registry_ts
  tool_api_ts-->auth_ts
