graph LR
  business_agents-->business_agents
  business_agents-->domain
  business_agents-->enterprise_agents
  business_agents-->glw
  business_agents-->platform
  compiler-->compiler
  compiler-->knowledge
  compiler-->registries
  core-->core
  core-->registries
  domain-->domain
  domain-->glw
  domain-->platform
  enterprise_agents-->enterprise_agents
  enterprise_agents-->glw
  enterprise_agents-->platform
  glw-->glw
  glw-->platform
  knowledge-->knowledge
  knowledge-->registries
  messaging-->glw
  messaging-->platform
  other-->compiler
  platform-->glw
  platform-->platform
  registries-->business_agents
  registries-->compiler
  registries-->core
  registries-->domain
  registries-->enterprise_agents
  registries-->glw
  registries-->platform
  registries-->registries
  registries-->src_app
  src_app-->business_agents
  src_app-->domain
  src_app-->enterprise_agents
  src_app-->glw
  src_app-->messaging
  src_app-->platform
  src_app-->registries
  src_app-->src_app
  tests-->business_agents
  tests-->compiler
  tests-->domain
  tests-->enterprise_agents
  tests-->glw
  tests-->knowledge
  tests-->messaging
  tests-->platform
