const base = process.env.GLW_N8N_BASE_URL ?? process.env.GLW_N8N_PAGE_WEBHOOK_URL?.replace(/\/webhook\/.*$/, "");
const apiKey = process.env.GLW_N8N_API_KEY;
const executionId = "65597";
const response = await fetch(`${base}/api/v1/executions/${executionId}?includeData=true`, { headers: { "X-N8N-API-KEY": apiKey ?? "" } });
const text = await response.text();
const needles = ["Send GLW Completion Callback", "callback", "qaChecks", "wordpressStatus", "requestedPublishingMode", "disposition", "qaFailureReasons"];
const hits = {};
for (const needle of needles) hits[needle] = text.includes(needle);
const callbackIndex = text.indexOf("Send GLW Completion Callback");
const aroundCallback = callbackIndex >= 0 ? text.slice(Math.max(0, callbackIndex - 1200), callbackIndex + 3000) : null;
console.log(JSON.stringify({ hits, aroundCallback }, null, 2));