export const GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT = "GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_V1" as const;
export const NATIVE_HOST_RENDER_AUTHORITY_CONTRACT = "NATIVE_HOST_RENDER_AUTHORITY_V1" as const;
export const GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CSS = `[data-genesis-background-luminance="dark"]{--genesis-heading-color:#fff;--genesis-copy-color:#f5f7f7;--genesis-accent-color:#f2b84b}[data-genesis-background-luminance="light"]{--genesis-heading-color:#191919;--genesis-copy-color:#313b3b;--genesis-accent-color:#7f1d18}[data-genesis-background-luminance] :is(h1,h2,h3){color:var(--genesis-heading-color)!important}[data-genesis-background-luminance] :is(.saw-copy,.saw-note){color:var(--genesis-copy-color)!important}[data-genesis-background-luminance] .saw-kicker{color:var(--genesis-accent-color)!important}[data-genesis-accent-treatment="light"]{--genesis-accent-color:#fff}`;

export type GenesisBackgroundType = "LIGHT_SOLID" | "DARK_SOLID" | "LIGHT_IMAGE" | "DARK_IMAGE" | "IMAGE_WITH_LIGHT_OVERLAY" | "IMAGE_WITH_DARK_OVERLAY" | "GRADIENT" | "MIXED_OR_UNKNOWN";
export type GenesisLuminanceClass = "LIGHT" | "DARK" | "MIXED_OR_UNKNOWN";
export type GenesisTextRole = "EYEBROW" | "H1" | "H2" | "H3" | "DISPLAY_HEADING" | "BODY_COPY" | "CTA_PRIMARY_TEXT" | "CTA_SECONDARY_TEXT" | "CAPTION" | "DISCLAIMER" | "LABEL";
export type GenesisResolvedTextTreatment = "LIGHT_PRIMARY" | "LIGHT_SECONDARY" | "DARK_PRIMARY" | "DARK_SECONDARY" | "ACCENT_ON_DARK" | "ACCENT_ON_LIGHT" | "CTA_ACCENT_DARK_TEXT" | "CTA_OUTLINE_LIGHT" | "UNRESOLVED";
export type GenesisRenderAuthority = "STATIC_CSS_EXPECTATION" | "GENESIS_COMPOSITION_RENDER" | "HOST_EQUIVALENT_RENDER" | "ACTUAL_NATIVE_HOST_RENDER" | "HOST_RENDER";
export type GenesisCascadeDeclaration = { selector: string; property: "color"; value: string; important: boolean; specificity: readonly [number, number, number, number]; order: number; source: string };
export type GenesisRenderedContrastObservation = { observationId: string; viewport: string; sectionId: string; textExcerpt: string; domIdentity: { tagName: string; id: string | null; classList: readonly string[] }; backgroundType: GenesisBackgroundType; backgroundLuminanceClass: GenesisLuminanceClass; overlayPresent: boolean; overlayLuminanceClass: GenesisLuminanceClass | null; textRole: GenesisTextRole; foregroundColor: string; effectiveBackgroundColor: string | null; requiredContrast: number; generatedImage: boolean; approvedOverlay: boolean; source: GenesisRenderAuthority; matchedColorDeclarations: readonly GenesisCascadeDeclaration[]; winningColorDeclaration: GenesisCascadeDeclaration | null };
export type GenesisContrastResult = GenesisRenderedContrastObservation & { contrastRatio: number | null; contrastPass: boolean; resolvedTextTreatment: GenesisResolvedTextTreatment; failureCode: "LOW_CONTRAST" | "IMAGE_REGION_UNRESOLVED" | null };

const parse = (value: string) => { const hex = value.trim().match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i); if (hex) { const full = hex[1].length === 3 ? [...hex[1]].map((item) => item + item).join("") : hex[1]; return [0, 2, 4].map((index) => Number.parseInt(full.slice(index, index + 2), 16)); } const rgb = value.match(/rgba?\(\s*(\d+)[, ]+\s*(\d+)[, ]+\s*(\d+)/i); return rgb ? [Number(rgb[1]), Number(rgb[2]), Number(rgb[3])] : null; };
const luminance = (value: string) => { const color = parse(value); if (!color) return null; const channels = color.map((item) => { const channel = item / 255; return channel <= .04045 ? channel / 12.92 : ((channel + .055) / 1.055) ** 2.4; }); return .2126 * channels[0] + .7152 * channels[1] + .0722 * channels[2]; };
export const genesisContrastRatio = (foreground: string, background: string) => { const values = [luminance(foreground), luminance(background)]; if (values.some((item) => item === null)) return null; const [high, low] = (values as number[]).sort((left, right) => right - left); return (high + .05) / (low + .05); };
export const requiredGenesisContrast = (role: GenesisTextRole) => ["DISPLAY_HEADING", "H1", "H2", "H3"].includes(role) ? 3 : role === "LABEL" || role === "CAPTION" ? 3 : 4.5;
function treatment(input: GenesisRenderedContrastObservation): GenesisResolvedTextTreatment { const light = input.backgroundLuminanceClass === "DARK"; if (input.textRole === "EYEBROW") return light ? "ACCENT_ON_DARK" : "ACCENT_ON_LIGHT"; if (input.textRole === "CTA_PRIMARY_TEXT") return "CTA_ACCENT_DARK_TEXT"; if (input.textRole === "CTA_SECONDARY_TEXT") return "CTA_OUTLINE_LIGHT"; if (["BODY_COPY", "CAPTION", "DISCLAIMER", "LABEL"].includes(input.textRole)) return light ? "LIGHT_SECONDARY" : "DARK_SECONDARY"; return light ? "LIGHT_PRIMARY" : "DARK_PRIMARY"; }
export function evaluateGenesisBackgroundAwareTextContrast(observations: readonly GenesisRenderedContrastObservation[]): GenesisContrastResult[] { return observations.map((item) => { const unresolvedImage = ["LIGHT_IMAGE", "DARK_IMAGE", "MIXED_OR_UNKNOWN"].includes(item.backgroundType) && (!item.effectiveBackgroundColor || !item.approvedOverlay); const ratio = unresolvedImage || !item.effectiveBackgroundColor ? null : genesisContrastRatio(item.foregroundColor, item.effectiveBackgroundColor); const contrastPass = ratio !== null && ratio >= item.requiredContrast; return { ...item, contrastRatio: ratio, contrastPass, resolvedTextTreatment: contrastPass ? treatment(item) : "UNRESOLVED", failureCode: unresolvedImage ? "IMAGE_REGION_UNRESOLVED" : contrastPass ? null : "LOW_CONTRAST" }; }); }
export function summarizeGenesisContrast(results: readonly GenesisContrastResult[]) { const failures = results.filter((item) => !item.contrastPass); return { contract: GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT, state: results.length > 0 && failures.length === 0 ? "PASS" as const : "FAIL" as const, observations: results.length, failures }; }
const authorityRank: Record<GenesisRenderAuthority, number> = { STATIC_CSS_EXPECTATION: 1, GENESIS_COMPOSITION_RENDER: 2, HOST_EQUIVALENT_RENDER: 3, HOST_RENDER: 3, ACTUAL_NATIVE_HOST_RENDER: 4 };
export function normalizeGenesisRenderAuthority(value: GenesisRenderAuthority): Exclude<GenesisRenderAuthority, "HOST_RENDER"> { return value === "HOST_RENDER" ? "HOST_EQUIVALENT_RENDER" : value; }
export function selectAuthoritativeContrastEvidence<T extends { authority: GenesisRenderAuthority; state: "PASS" | "FAIL" }>(evidence: readonly T[]) { return [...evidence].sort((left, right) => authorityRank[right.authority] - authorityRank[left.authority]).at(0) ?? null; }
export function deriveGenesisContrastReadiness(input: { state: "PASS" | "FAIL" | null; authority: GenesisRenderAuthority | null; nativeHostEvidenceAvailable: boolean; higherAuthorityContradiction: boolean; styleSettlementStable?: boolean }) { const authority = input.authority ? normalizeGenesisRenderAuthority(input.authority) : null; const stable = input.styleSettlementStable !== false; const ownerReviewReady = input.state === "PASS" && stable && !input.higherAuthorityContradiction && (!input.nativeHostEvidenceAvailable || authority === "ACTUAL_NATIVE_HOST_RENDER"); const publicationReady = ownerReviewReady && authority === "ACTUAL_NATIVE_HOST_RENDER"; return { ownerReviewReady, publicationReady, ownerReviewGate: ownerReviewReady ? "PASS" as const : "BLOCKED" as const, publicationGate: publicationReady ? "PASS" as const : "BLOCKED" as const, authoritativeSource: authority }; }