export const GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT = "GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_V1" as const;

export type GenesisBackgroundType = "LIGHT_SOLID" | "DARK_SOLID" | "LIGHT_IMAGE" | "DARK_IMAGE" | "IMAGE_WITH_LIGHT_OVERLAY" | "IMAGE_WITH_DARK_OVERLAY" | "GRADIENT" | "MIXED_OR_UNKNOWN";
export type GenesisLuminanceClass = "LIGHT" | "DARK" | "MIXED_OR_UNKNOWN";
export type GenesisTextRole = "EYEBROW" | "H1" | "H2" | "H3" | "DISPLAY_HEADING" | "BODY_COPY" | "CTA_PRIMARY_TEXT" | "CTA_SECONDARY_TEXT" | "CAPTION" | "DISCLAIMER" | "LABEL";
export type GenesisRenderAuthority = "STATIC_CSS_EXPECTATION" | "GENESIS_COMPOSITION_RENDER" | "HOST_EQUIVALENT_RENDER" | "ACTUAL_NATIVE_HOST_RENDER";
export type GenesisContrastObservation = { observationId: string; viewport: string; sectionId: string; backgroundType: GenesisBackgroundType; backgroundLuminanceClass: GenesisLuminanceClass; overlayPresent: boolean; textRole: GenesisTextRole; foregroundColor: string; effectiveBackgroundColor: string | null; requiredContrast: number; generatedImage: boolean; approvedOverlay: boolean; authority: GenesisRenderAuthority };
export type GenesisContrastResult = GenesisContrastObservation & { contrastRatio: number | null; contrastPass: boolean; failureCode: "LOW_CONTRAST" | "IMAGE_REGION_UNRESOLVED" | null };

function parseColor(value: string): number[] | null { const hex=value.trim().match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);if(hex){const full=hex[1].length===3?[...hex[1]].map(item=>item+item).join(""):hex[1];return[0,2,4].map(index=>Number.parseInt(full.slice(index,index+2),16));}const rgb=value.match(/rgba?\(\s*(\d+)[, ]+\s*(\d+)[, ]+\s*(\d+)/i);return rgb?[Number(rgb[1]),Number(rgb[2]),Number(rgb[3])]:null; }
function luminance(value:string):number|null{const color=parseColor(value);if(!color)return null;const channels=color.map(item=>{const channel=item/255;return channel<=.04045?channel/12.92:((channel+.055)/1.055)**2.4;});return .2126*channels[0]+.7152*channels[1]+.0722*channels[2];}
export function genesisContrastRatio(foreground:string,background:string):number|null{const values=[luminance(foreground),luminance(background)];if(values.some(item=>item===null))return null;const[high,low]=(values as number[]).sort((left,right)=>right-left);return(high+.05)/(low+.05);}
export function requiredGenesisContrast(role:GenesisTextRole):number{return["DISPLAY_HEADING","H1","H2","H3","LABEL","CAPTION"].includes(role)?3:4.5;}
export function evaluateGenesisBackgroundAwareTextContrast(observations:readonly GenesisContrastObservation[]):GenesisContrastResult[]{return observations.map(item=>{const unresolvedImage=["LIGHT_IMAGE","DARK_IMAGE","MIXED_OR_UNKNOWN"].includes(item.backgroundType)&&(!item.effectiveBackgroundColor||!item.approvedOverlay);const contrastRatio=unresolvedImage||!item.effectiveBackgroundColor?null:genesisContrastRatio(item.foregroundColor,item.effectiveBackgroundColor);const contrastPass=contrastRatio!==null&&contrastRatio>=item.requiredContrast;return{...item,contrastRatio,contrastPass,failureCode:unresolvedImage?"IMAGE_REGION_UNRESOLVED":contrastPass?null:"LOW_CONTRAST"};});}
export function summarizeGenesisContrast(results:readonly GenesisContrastResult[]){const failures=results.filter(item=>!item.contrastPass);return{contract:GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT,state:results.length>0&&failures.length===0?"PASS" as const:"FAIL" as const,observations:results.length,failures};}
