import "server-only";

import { deepClone, FoundationPersistenceConflictError, loadPersistedState, savePersistedState } from "./foundation-persistence";
import { captureGovernedRenderedPage, type CaptureMediaAssignment } from "./governed-render-capture-browser";
import { deriveGenesisContrastReadiness, evaluateGenesisBackgroundAwareTextContrast, GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT, summarizeGenesisContrast, type GenesisContrastResult } from "./background-aware-text-contrast";

const VIEWPORTS = [{ name: "DESKTOP_1440", width: 1440, height: 1024, viewportClass: "DESKTOP" as const }, { name: "DESKTOP_1024", width: 1024, height: 900, viewportClass: "DESKTOP" as const }, { name: "TABLET_768", width: 768, height: 1024, viewportClass: "DESKTOP" as const }, { name: "MOBILE_375", width: 375, height: 812, viewportClass: "MOBILE" as const }];
export type GenesisBackgroundAwareContrastCertification = { certificationId: string; contract: typeof GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT; identity: { organizationId: string; siteId: string; pageId: string; renderedContentHash: string; authority: "COMPOSITION_RENDER" | "HOST_RENDER" }; captures: readonly { viewport: string; width: number; height: number; results: readonly GenesisContrastResult[]; failures: number }[]; state: "PASS" | "FAIL"; failureCount: number; ownerReviewReady: boolean; publicationReady: boolean; generatedImageReevaluationPerformed: boolean; createdAt: string };
type State = { certifications: GenesisBackgroundAwareContrastCertification[] };
const NAMESPACE = "genesis-background-aware-text-contrast-v1"; const seed = (): State => ({ certifications: [] });
function save(certification: GenesisBackgroundAwareContrastCertification) { for (let attempt = 0; attempt < 8; attempt += 1) { const loaded = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); const existing = loaded.state.certifications.find((item) => item.certificationId === certification.certificationId); if (existing) return deepClone(existing); try { savePersistedState({ namespace: NAMESPACE, state: { certifications: [...loaded.state.certifications, certification] }, expectedRevision: loaded.revision }); return deepClone(certification); } catch (error) { if (!(error instanceof FoundationPersistenceConflictError) || attempt === 7) throw error; } } throw new Error("BACKGROUND_CONTRAST_CAS_EXHAUSTED"); }
export function listGenesisBackgroundAwareContrastCertifications() { return deepClone(loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }).state.certifications); }

export async function captureGenesisBackgroundAwareTextContrast(input: { certificationId: string; identity: GenesisBackgroundAwareContrastCertification["identity"]; targetUrl: string; allowedOrigins: readonly string[]; internalGenesisOrigin?: string; internalAuthorization?: { header: string; value: string }; mediaAssignments: readonly CaptureMediaAssignment[] }) {
  const existing = listGenesisBackgroundAwareContrastCertifications().find((item) => item.certificationId === input.certificationId); if (existing) return { certification: existing, reused: true };
  const captures = [];
  for (const viewport of VIEWPORTS) { const result = await captureGovernedRenderedPage({ targetUrl: input.targetUrl, allowedOrigins: input.allowedOrigins, internalGenesisOrigin: input.internalGenesisOrigin, internalAuthorization: input.internalAuthorization, viewportClass: viewport.viewportClass, viewport, captureId: `${input.certificationId}-${viewport.name.toLowerCase()}`, mediaAssignments: input.mediaAssignments }); const evaluated = evaluateGenesisBackgroundAwareTextContrast(result.themeIntegration.backgroundAwareTextContrast); captures.push({ viewport: viewport.name, width: viewport.width, height: viewport.height, results: evaluated, failures: evaluated.filter((item) => !item.contrastPass).length }); }
  const all = captures.flatMap((item) => item.results); const summary = summarizeGenesisContrast(all); const readiness = deriveGenesisContrastReadiness({ state: summary.state, authority: input.identity.authority, hostRenderEvidenceAvailable: input.identity.authority === "HOST_RENDER" }); const certification: GenesisBackgroundAwareContrastCertification = { certificationId: input.certificationId, contract: GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT, identity: input.identity, captures, state: summary.state, failureCount: summary.failures.length, ownerReviewReady: readiness.ownerReviewReady, publicationReady: readiness.publicationReady, generatedImageReevaluationPerformed: all.some((item) => item.generatedImage), createdAt: new Date().toISOString() }; return { certification: save(certification), reused: false };
}