import "server-only";

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { deepClone, FoundationPersistenceConflictError, loadPersistedState, savePersistedState } from "./foundation-persistence";
import { resolvePersistenceRoot } from "./foundation-persistence";
import { captureGovernedRenderedPage, type CaptureMediaAssignment } from "./governed-render-capture-browser";
import { deriveGenesisContrastReadiness, evaluateGenesisBackgroundAwareTextContrast, GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT, summarizeGenesisContrast, type GenesisContrastResult } from "./background-aware-text-contrast";

const VIEWPORTS = [{ name: "DESKTOP_1440", width: 1440, height: 1024, viewportClass: "DESKTOP" as const }, { name: "DESKTOP_1024", width: 1024, height: 900, viewportClass: "DESKTOP" as const }, { name: "TABLET_768", width: 768, height: 1024, viewportClass: "DESKTOP" as const }, { name: "MOBILE_375", width: 375, height: 812, viewportClass: "MOBILE" as const }];
export type GenesisBackgroundAwareContrastCertification = { certificationId: string; contract: typeof GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT; identity: { organizationId: string; siteId: string; pageId: string; renderedContentHash: string; authority: import("./background-aware-text-contrast").GenesisRenderAuthority }; captures: readonly { viewport: string; width: number; height: number; results: readonly GenesisContrastResult[]; failures: number; styleSettlementStable: boolean; styleSettlementSamples: number; screenshotComputedStyleCorrelationId: string; screenshotArtifact: { reference: string; sha256: string; width: number; height: number } }[]; state: "PASS" | "FAIL"; failureCount: number; ownerReviewReady: boolean; publicationReady: boolean; generatedImageReevaluationPerformed: boolean; createdAt: string };
type State = { certifications: GenesisBackgroundAwareContrastCertification[] };
const NAMESPACE = "genesis-background-aware-text-contrast-v1"; const seed = (): State => ({ certifications: [] });
function save(certification: GenesisBackgroundAwareContrastCertification) { for (let attempt = 0; attempt < 8; attempt += 1) { const loaded = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); const existing = loaded.state.certifications.find((item) => item.certificationId === certification.certificationId); if (existing) return deepClone(existing); try { savePersistedState({ namespace: NAMESPACE, state: { certifications: [...loaded.state.certifications, certification] }, expectedRevision: loaded.revision }); return deepClone(certification); } catch (error) { if (!(error instanceof FoundationPersistenceConflictError) || attempt === 7) throw error; } } throw new Error("BACKGROUND_CONTRAST_CAS_EXHAUSTED"); }
export function listGenesisBackgroundAwareContrastCertifications() { return deepClone(loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }).state.certifications); }
const artifactHash = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
function storeContrastArtifact(certificationId: string, viewport: string, bytes: Uint8Array, width: number, height: number) { const sha256 = artifactHash(bytes); const reference = `background-aware-contrast-artifacts/${certificationId}/${viewport.toLowerCase()}-${sha256.slice(0, 12)}.png`; const path = join(resolvePersistenceRoot(), ...reference.split("/")); mkdirSync(dirname(path), { recursive: true }); if (existsSync(path) && artifactHash(readFileSync(path)) !== sha256) throw new Error("BACKGROUND_CONTRAST_ARTIFACT_COLLISION"); if (!existsSync(path)) writeFileSync(path, bytes); return { reference, sha256, width, height }; }

export async function captureGenesisBackgroundAwareTextContrast(input: { certificationId: string; identity: GenesisBackgroundAwareContrastCertification["identity"]; targetUrl: string; allowedOrigins: readonly string[]; internalGenesisOrigin?: string; internalAuthorization?: { header: string; value: string }; mediaAssignments: readonly CaptureMediaAssignment[]; nativeHostEvidenceAvailable?: boolean; higherAuthorityContradiction?: boolean }) {
  const existing = listGenesisBackgroundAwareContrastCertifications().find((item) => item.certificationId === input.certificationId); if (existing) return { certification: existing, reused: true };
  const captures = [];
  for (const viewport of VIEWPORTS) { const result = await captureGovernedRenderedPage({ targetUrl: input.targetUrl, allowedOrigins: input.allowedOrigins, internalGenesisOrigin: input.internalGenesisOrigin, internalAuthorization: input.internalAuthorization, viewportClass: viewport.viewportClass, viewport, captureId: `${input.certificationId}-${viewport.name.toLowerCase()}`, mediaAssignments: input.mediaAssignments }); const evaluated = evaluateGenesisBackgroundAwareTextContrast(result.themeIntegration.backgroundAwareTextContrast); captures.push({ viewport: viewport.name, width: viewport.width, height: viewport.height, results: evaluated, failures: evaluated.filter((item) => !item.contrastPass).length, styleSettlementStable: result.styleSettlement.stable, styleSettlementSamples: result.styleSettlement.samples, screenshotComputedStyleCorrelationId: result.screenshotComputedStyleCorrelationId, screenshotArtifact: storeContrastArtifact(input.certificationId, viewport.name, result.bytes, result.imageWidth, result.imageHeight) }); }
  const all = captures.flatMap((item) => item.results); const stable = captures.every((item) => item.styleSettlementStable); const summary = summarizeGenesisContrast(all); const effectiveState = stable ? summary.state : "FAIL" as const; const readiness = deriveGenesisContrastReadiness({ state: effectiveState, authority: input.identity.authority, nativeHostEvidenceAvailable: input.nativeHostEvidenceAvailable ?? false, higherAuthorityContradiction: input.higherAuthorityContradiction ?? false, styleSettlementStable: stable }); const certification: GenesisBackgroundAwareContrastCertification = { certificationId: input.certificationId, contract: GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT, identity: input.identity, captures, state: effectiveState, failureCount: summary.failures.length + (stable ? 0 : 1), ownerReviewReady: readiness.ownerReviewReady, publicationReady: readiness.publicationReady, generatedImageReevaluationPerformed: all.some((item) => item.generatedImage), createdAt: new Date().toISOString() }; return { certification: save(certification), reused: false };
}