import type {
  ProductCategory,
  ProductConfiguration,
  ProductManufacturer,
} from "./types";

const CREATED_AT = "2026-07-29T00:00:00.000Z";

export const FOUNDATION_CATEGORIES: readonly ProductCategory[] = [
  {
    categoryId: "cat-led-displays",
    organizationId: "led-display-warehouse",
    name: "LED Displays",
    slug: "led-displays",
    description: "Core LED display offerings.",
    parentCategoryId: null,
    status: "active",
    sortOrder: 1,
    siteAssignments: ["site-led-display-warehouse-production"],
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    categoryId: "cat-indoor-led",
    organizationId: "led-display-warehouse",
    name: "Indoor LED",
    slug: "indoor-led",
    description: "Indoor display solutions.",
    parentCategoryId: "cat-led-displays",
    status: "active",
    sortOrder: 2,
    siteAssignments: ["site-led-display-warehouse-production"],
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    categoryId: "cat-outdoor-led",
    organizationId: "led-display-warehouse",
    name: "Outdoor LED",
    slug: "outdoor-led",
    description: "Outdoor display solutions.",
    parentCategoryId: "cat-led-displays",
    status: "active",
    sortOrder: 3,
    siteAssignments: ["site-led-display-warehouse-production"],
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    categoryId: "cat-digital-spheres",
    organizationId: "led-display-warehouse",
    name: "Digital Spheres",
    slug: "digital-spheres",
    description: "Digital sphere systems.",
    parentCategoryId: null,
    status: "active",
    sortOrder: 4,
    siteAssignments: ["site-led-display-warehouse-production"],
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    categoryId: "cat-oled-displays",
    organizationId: "led-display-warehouse",
    name: "OLED Displays",
    slug: "oled-displays",
    description: "OLED display products.",
    parentCategoryId: null,
    status: "active",
    sortOrder: 5,
    siteAssignments: ["site-led-display-warehouse-production"],
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    categoryId: "cat-kiosks",
    organizationId: "led-display-warehouse",
    name: "Digital Kiosks",
    slug: "digital-kiosks",
    description: "Kiosk systems.",
    parentCategoryId: null,
    status: "active",
    sortOrder: 6,
    siteAssignments: ["site-led-display-warehouse-production"],
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
];

export const FOUNDATION_MANUFACTURERS: readonly ProductManufacturer[] = [
  {
    manufacturerId: "mfr-ledw-internal",
    organizationId: "led-display-warehouse",
    name: "LED Display Warehouse",
    displayName: "LED Display Warehouse",
    slug: "led-display-warehouse",
    website: "https://leddisplaywarehouse.com",
    status: "active",
    businessGenomeReference: null,
    notes: "Application-level manufacturer reference.",
  },
  {
    manufacturerId: "mfr-custom-fabrication",
    organizationId: "led-display-warehouse",
    name: "Custom Fabrication Partner",
    displayName: "Custom Fabrication Partner",
    slug: "custom-fabrication-partner",
    website: null,
    status: "active",
    businessGenomeReference: null,
    notes: "Placeholder manufacturer reference for custom solutions.",
  },
];

export const FOUNDATION_PRODUCTS: readonly ProductConfiguration[] = [
  {
    productId: "prod-indoor-led-video-wall",
    organizationId: "led-display-warehouse",
    productName: "Indoor LED Video Wall",
    displayName: "Indoor LED Video Wall",
    slug: "indoor-led-video-wall",
    sku: "LEDW-INDOOR-WALL",
    modelNumber: null,
    shortDescription: "Configurable indoor LED video wall foundation product.",
    fullDescription: "Application-level product record for indoor LED video wall offerings.",
    productType: "led_display",
    productFamily: "video-walls",
    categoryIds: ["cat-led-displays", "cat-indoor-led"],
    manufacturerId: "mfr-ledw-internal",
    brandReference: "brand-led-display-warehouse",
    lifecycleState: "configuring",
    catalogStatus: "incomplete",
    enabled: false,
    visibility: "internal",
    featured: false,
    primarySiteId: "site-led-display-warehouse-production",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    siteAssignments: [
      {
        siteId: "site-led-display-warehouse-production",
        enabledForSite: true,
        siteSpecificSlug: "indoor-led-video-wall",
        siteSpecificDisplayName: "Indoor LED Video Wall",
        siteSpecificShortDescription: "Indoor LED wall.",
        visibility: "internal",
        featured: false,
        sortOrder: 1,
        categoryIds: ["cat-led-displays", "cat-indoor-led"],
        defaultContentType: "article",
        publicationStatus: "not_ready",
        seoProfileReference: null,
        promptProfileReference: null,
        imageProfileReference: null,
        pricingDisplayMode: "request_quote",
        lastReadinessEvaluation: null,
        lastPublicationReference: null,
      },
    ],
    media: {
      primaryImageReference: null,
      galleryImageReferences: [],
      videoReferences: [],
    },
    documents: {
      technicalDrawingReferences: [],
      specSheetReferences: [],
      brochureReferences: [],
      manualReferences: [],
      installationGuideReferences: [],
      warrantyDocumentReferences: [],
    },
    specifications: [],
    seoProfileReference: null,
    promptProfileReference: null,
    businessGenomeObjectReference: null,
    sourceEvidenceReference: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    publishedAt: null,
    notes: "Development fixture - non-production values.",
  },
  {
    productId: "prod-outdoor-led-video-wall",
    organizationId: "led-display-warehouse",
    productName: "Outdoor LED Video Wall",
    displayName: "Outdoor LED Video Wall",
    slug: "outdoor-led-video-wall",
    sku: "LEDW-OUTDOOR-WALL",
    modelNumber: null,
    shortDescription: "Configurable outdoor LED video wall foundation product.",
    fullDescription: "Application-level product record for outdoor LED video wall offerings.",
    productType: "led_display",
    productFamily: "video-walls",
    categoryIds: ["cat-led-displays", "cat-outdoor-led"],
    manufacturerId: "mfr-ledw-internal",
    brandReference: "brand-led-display-warehouse",
    lifecycleState: "draft",
    catalogStatus: "incomplete",
    enabled: false,
    visibility: "hidden",
    featured: false,
    primarySiteId: "site-secondary-test-placeholder",
    assignedSiteIds: ["site-secondary-test-placeholder"],
    siteAssignments: [
      {
        siteId: "site-secondary-test-placeholder",
        enabledForSite: false,
        siteSpecificSlug: "outdoor-led-video-wall",
        siteSpecificDisplayName: "Outdoor LED Video Wall",
        siteSpecificShortDescription: "Outdoor LED wall.",
        visibility: "hidden",
        featured: false,
        sortOrder: 2,
        categoryIds: ["cat-led-displays", "cat-outdoor-led"],
        defaultContentType: "article",
        publicationStatus: "disabled",
        seoProfileReference: null,
        promptProfileReference: null,
        imageProfileReference: null,
        pricingDisplayMode: "request_quote",
        lastReadinessEvaluation: null,
        lastPublicationReference: null,
      },
    ],
    media: {
      primaryImageReference: null,
      galleryImageReferences: [],
      videoReferences: [],
    },
    documents: {
      technicalDrawingReferences: [],
      specSheetReferences: [],
      brochureReferences: [],
      manualReferences: [],
      installationGuideReferences: [],
      warrantyDocumentReferences: [],
    },
    specifications: [],
    seoProfileReference: null,
    promptProfileReference: null,
    businessGenomeObjectReference: null,
    sourceEvidenceReference: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    publishedAt: null,
    notes: "Development fixture with disabled test-site assignment.",
  },
  {
    productId: "prod-indoor-digital-sphere",
    organizationId: "led-display-warehouse",
    productName: "Indoor Digital Sphere",
    displayName: "Indoor Digital Sphere",
    slug: "indoor-digital-sphere",
    sku: "LEDW-INDOOR-SPHERE",
    modelNumber: null,
    shortDescription: "Indoor digital sphere foundation product.",
    fullDescription: "Application-level product record for indoor digital sphere offerings.",
    productType: "digital_sphere",
    productFamily: "spheres",
    categoryIds: ["cat-digital-spheres"],
    manufacturerId: "mfr-custom-fabrication",
    brandReference: "brand-led-display-warehouse",
    lifecycleState: "draft",
    catalogStatus: "incomplete",
    enabled: false,
    visibility: "internal",
    featured: false,
    primarySiteId: "site-led-display-warehouse-production",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    siteAssignments: [],
    media: { primaryImageReference: null, galleryImageReferences: [], videoReferences: [] },
    documents: {
      technicalDrawingReferences: [],
      specSheetReferences: [],
      brochureReferences: [],
      manualReferences: [],
      installationGuideReferences: [],
      warrantyDocumentReferences: [],
    },
    specifications: [],
    seoProfileReference: null,
    promptProfileReference: null,
    businessGenomeObjectReference: null,
    sourceEvidenceReference: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    publishedAt: null,
    notes: "Development fixture.",
  },
  {
    productId: "prod-outdoor-digital-sphere",
    organizationId: "led-display-warehouse",
    productName: "Outdoor Digital Sphere",
    displayName: "Outdoor Digital Sphere",
    slug: "outdoor-digital-sphere",
    sku: "LEDW-OUTDOOR-SPHERE",
    modelNumber: null,
    shortDescription: "Outdoor digital sphere foundation product.",
    fullDescription: "Application-level product record for outdoor digital sphere offerings.",
    productType: "digital_sphere",
    productFamily: "spheres",
    categoryIds: ["cat-digital-spheres"],
    manufacturerId: "mfr-custom-fabrication",
    brandReference: "brand-led-display-warehouse",
    lifecycleState: "draft",
    catalogStatus: "incomplete",
    enabled: false,
    visibility: "internal",
    featured: false,
    primarySiteId: "site-led-display-warehouse-production",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    siteAssignments: [],
    media: { primaryImageReference: null, galleryImageReferences: [], videoReferences: [] },
    documents: {
      technicalDrawingReferences: [],
      specSheetReferences: [],
      brochureReferences: [],
      manualReferences: [],
      installationGuideReferences: [],
      warrantyDocumentReferences: [],
    },
    specifications: [],
    seoProfileReference: null,
    promptProfileReference: null,
    businessGenomeObjectReference: null,
    sourceEvidenceReference: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    publishedAt: null,
    notes: "Development fixture.",
  },
  {
    productId: "prod-transparent-oled-display",
    organizationId: "led-display-warehouse",
    productName: "Transparent OLED Display",
    displayName: "Transparent OLED Display",
    slug: "transparent-oled-display",
    sku: "LEDW-TRANSPARENT-OLED",
    modelNumber: null,
    shortDescription: "Transparent OLED foundation product.",
    fullDescription: "Application-level product record for transparent OLED offerings.",
    productType: "oled_display",
    productFamily: "oled",
    categoryIds: ["cat-oled-displays"],
    manufacturerId: null,
    brandReference: "brand-led-display-warehouse",
    lifecycleState: "draft",
    catalogStatus: "review_required",
    enabled: false,
    visibility: "internal",
    featured: false,
    primarySiteId: "site-led-display-warehouse-production",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    siteAssignments: [],
    media: { primaryImageReference: null, galleryImageReferences: [], videoReferences: [] },
    documents: {
      technicalDrawingReferences: [],
      specSheetReferences: [],
      brochureReferences: [],
      manualReferences: [],
      installationGuideReferences: [],
      warrantyDocumentReferences: [],
    },
    specifications: [],
    seoProfileReference: null,
    promptProfileReference: null,
    businessGenomeObjectReference: null,
    sourceEvidenceReference: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    publishedAt: null,
    notes: "Development fixture requiring manufacturer review.",
  },
  {
    productId: "prod-outdoor-digital-kiosk",
    organizationId: "led-display-warehouse",
    productName: "Outdoor Digital Kiosk",
    displayName: "Outdoor Digital Kiosk",
    slug: "outdoor-digital-kiosk",
    sku: "LEDW-OUTDOOR-KIOSK",
    modelNumber: null,
    shortDescription: "Outdoor kiosk foundation product.",
    fullDescription: "Application-level product record for outdoor kiosk offerings.",
    productType: "kiosk",
    productFamily: "kiosks",
    categoryIds: ["cat-kiosks"],
    manufacturerId: "mfr-ledw-internal",
    brandReference: "brand-led-display-warehouse",
    lifecycleState: "draft",
    catalogStatus: "incomplete",
    enabled: false,
    visibility: "internal",
    featured: false,
    primarySiteId: "site-led-display-warehouse-production",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    siteAssignments: [],
    media: { primaryImageReference: null, galleryImageReferences: [], videoReferences: [] },
    documents: {
      technicalDrawingReferences: [],
      specSheetReferences: [],
      brochureReferences: [],
      manualReferences: [],
      installationGuideReferences: [],
      warrantyDocumentReferences: [],
    },
    specifications: [],
    seoProfileReference: null,
    promptProfileReference: null,
    businessGenomeObjectReference: null,
    sourceEvidenceReference: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    publishedAt: null,
    notes: "Development fixture.",
  },
];
