import type { CommercialStainlessWordPressStageRecord } from "./commercial-stainless-wordpress-staging";
import type { CommercialStainlessWordPressPublicationReceipt } from "./commercial-stainless-wordpress-publication";

export type CommercialStainlessWordPressWave1ReviewItem = { record: CommercialStainlessWordPressStageRecord; currentHtml: string; stagedHtml: string; desktopHeight: number; mobileHeight: number };

function Frame({ title, width, height, html }: { title: string; width: number; height: number; html: string }) {
  return <div className="overflow-auto border border-zinc-700 bg-zinc-900 p-3"><p className="mb-3 text-xs font-semibold uppercase text-zinc-400">{width}px · actual WordPress render</p><iframe title={title} srcDoc={html} scrolling="no" style={{ width, height }} className="max-w-none border-0 bg-white" /></div>;
}

export function CommercialStainlessWordPressWave1Review({ items, receipts }: { items: CommercialStainlessWordPressWave1ReviewItem[]; receipts: CommercialStainlessWordPressPublicationReceipt[] }) {
  return <section className="space-y-6">
    <header className="border border-zinc-800 bg-zinc-950 p-6"><p className="text-xs font-semibold uppercase text-red-400">Commercial Stainless WordPress Wave 1</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-white">Approved compositions and public receipts</h1><p className="mt-2 max-w-3xl text-sm text-zinc-300">Each page remains independently gated by exact revision, public semantic, and public visual certification. Owner-review-ready repairs are not publication authority.</p></div><span className="border border-emerald-600 px-3 py-2 text-xs font-semibold text-emerald-200">PUBLICATION CONTROLLED</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-zinc-500">Authorized objects</dt><dd className="text-white">{items.length}</dd></div><div><dt className="text-zinc-500">Publication completed</dt><dd className="text-emerald-300">{receipts.filter((receipt) => receipt.publishedAt).length} / 5</dd></div><div><dt className="text-zinc-500">Public certified</dt><dd className="text-emerald-300">{receipts.filter((receipt) => receipt.status === "PUBLIC_CERTIFIED").length} / 5</dd></div><div><dt className="text-zinc-500">Autosave revisions</dt><dd className="text-white">{items.map((item) => item.record.autosaveId).join(", ")}</dd></div><div><dt className="text-zinc-500">Rollback</dt><dd className="text-emerald-300">READY</dd></div></dl></header>
    <section className="overflow-x-auto border border-zinc-800 bg-zinc-950"><table className="w-full min-w-[880px] text-left text-sm"><thead className="border-b border-zinc-800 text-xs uppercase text-zinc-500"><tr><th className="p-3">Object</th><th className="p-3">Revision</th><th className="p-3">Prepublication</th><th className="p-3">Latest publication receipt</th><th className="p-3">Public certification</th><th className="p-3">Review</th></tr></thead><tbody>{items.map(({ record }) => { const receipt = receipts.filter((item) => item.wordpressObjectId === record.wordpressObjectId).sort((left, right) => right.updatedAt.localeCompare(left.updatedAt))[0]; return <tr key={record.wordpressObjectId} className="border-t border-zinc-800"><td className="p-3 text-white">{record.wordpressObjectId}</td><td className="p-3 text-zinc-300">{record.autosaveId}</td><td className={record.status === "OWNER_REVIEW_READY" ? "p-3 text-amber-300" : "p-3 text-emerald-300"}>{record.status === "OWNER_REVIEW_READY" ? "OWNER REVIEW ONLY" : "PREPUBLICATION READY"}</td><td className={receipt?.status === "ROLLED_BACK" || receipt?.status === "BLOCKED" ? "p-3 text-amber-300" : receipt?.publishedAt ? "p-3 text-emerald-300" : "p-3 text-zinc-500"}>{receipt?.status.replaceAll("_", " ") ?? "NOT ATTEMPTED"}</td><td className={receipt?.status === "PUBLIC_CERTIFIED" ? "p-3 text-emerald-300" : "p-3 text-zinc-500"}>PUBLIC {receipt?.status === "PUBLIC_CERTIFIED" ? "CERTIFIED" : "NOT CERTIFIED"}</td><td className="p-3"><a href={record.currentPublicUrl} target="_blank" rel="noreferrer" className="font-semibold text-red-300 underline">REVIEW PUBLIC PAGE</a></td></tr>; })}</tbody></table></section>
    <div className="space-y-8">{items.map(({ record, currentHtml, stagedHtml, desktopHeight, mobileHeight }) => <article key={record.stageId} className="border border-zinc-800 bg-zinc-950"><header className="border-b border-zinc-800 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-red-400">{record.targetProfile.replaceAll("_", " ")}</p><h2 className="mt-1 text-xl font-semibold text-white">WordPress object {record.wordpressObjectId}</h2><p className="mt-1 text-xs text-zinc-500">Autosave {record.autosaveId} · {new URL(record.currentPublicUrl).pathname}</p></div><span className={record.status === "PUBLICATION_READY" ? "text-xs font-semibold text-emerald-300" : "text-xs font-semibold text-amber-300"}>{record.status.replaceAll("_", " ")}</span></div><dl className="mt-4 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-6"><div><dt className="text-zinc-500">SEO</dt><dd className="text-emerald-300">{record.seoHashPreserved ? "PRESERVED" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Canonical</dt><dd className="text-emerald-300">{record.canonicalPreserved ? "PRESERVED" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Media</dt><dd className="text-emerald-300">{record.mediaPreserved ? "PRESERVED" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Links</dt><dd className="text-emerald-300">CERTIFIED</dd></div><div><dt className="text-zinc-500">Public body</dt><dd className="text-emerald-300">{record.publicBodyChanged === false ? "UNCHANGED" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Rollback</dt><dd className="text-emerald-300">{record.rollbackReady ? "READY" : "BLOCKED"}</dd></div></dl></header><details className="border-b border-zinc-800 p-5"><summary className="cursor-pointer font-semibold text-white">Desktop evidence</summary><div className="mt-4 grid gap-4 xl:grid-cols-2"><Frame title={`WordPress ${record.wordpressObjectId} current desktop`} width={1440} height={desktopHeight} html={currentHtml} /><Frame title={`WordPress ${record.wordpressObjectId} staged desktop`} width={1440} height={desktopHeight} html={stagedHtml} /></div></details><details className="p-5"><summary className="cursor-pointer font-semibold text-white">Mobile evidence</summary><div className="mt-4 grid gap-4 lg:grid-cols-2"><Frame title={`WordPress ${record.wordpressObjectId} current mobile`} width={375} height={mobileHeight} html={currentHtml} /><Frame title={`WordPress ${record.wordpressObjectId} staged mobile`} width={375} height={mobileHeight} html={stagedHtml} /></div></details></article>)}</div>
    <section className="border-l-4 border-emerald-500 bg-emerald-950/20 p-6"><p className="text-xs font-semibold uppercase text-emerald-300">Wave 1 Publication</p><h2 className="mt-2 text-xl font-semibold text-white">Publication receipts are recorded page by page.</h2><p className="mt-2 text-sm text-zinc-300">Wave 2 and Wave 3 remain locked. No additional mutation action is exposed here.</p></section>
  </section>;
}