import type { CommercialStainlessWave2Stage } from "./commercial-stainless-wave2-rollout";

function Frame({ title, width, height, html }: { title: string; width: number; height: number; html: string }) {
  return <div className="overflow-auto border border-zinc-700 bg-zinc-900 p-3"><p className="mb-3 text-xs font-semibold uppercase text-zinc-400">{width}px · complete preview</p><iframe title={title} srcDoc={html} scrolling="no" style={{ width, height }} className="max-w-none border-0 bg-white" /></div>;
}

export function CommercialStainlessWave2Review({ stages, diversity }: { stages: CommercialStainlessWave2Stage[]; diversity: { profileCount: number; heroVariantCount: number; sectionSequenceVariantCount: number; mediaLayoutVariantCount: number; ctaPlacementVariantCount: number } }) {
  return <section className="space-y-6">
    <header className="border border-zinc-800 bg-zinc-950 p-6"><p className="text-xs font-semibold uppercase text-red-400">Commercial Stainless Controlled Rollout</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-white">Wave 2 owner review</h1><p className="mt-2 max-w-3xl text-sm text-zinc-300">Five profile-specific compositions apply the certified Wave 1 host, media, spacing, and responsive rules. This surface cannot publish or mutate WordPress.</p></div><span className="border border-amber-600 px-3 py-2 text-xs font-semibold text-amber-200">OWNER REVIEW ONLY</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-zinc-500">Pages</dt><dd className="text-white">{stages.length}</dd></div><div><dt className="text-zinc-500">Profiles</dt><dd className="text-white">{diversity.profileCount}</dd></div><div><dt className="text-zinc-500">Hero variants</dt><dd className="text-white">{diversity.heroVariantCount}</dd></div><div><dt className="text-zinc-500">Section sequences</dt><dd className="text-white">{diversity.sectionSequenceVariantCount}</dd></div><div><dt className="text-zinc-500">Publication</dt><dd className="text-emerald-300">FALSE</dd></div></dl></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><article className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">Media layouts</p><strong className="text-xl text-white">{diversity.mediaLayoutVariantCount}</strong></article><article className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">CTA patterns</p><strong className="text-xl text-white">{diversity.ctaPlacementVariantCount}</strong></article><article className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">Ready</p><strong className="text-xl text-emerald-300">{stages.filter(stage => stage.status === "OWNER_REVIEW_READY").length} / 5</strong></article></section>
    <section className="overflow-x-auto border border-zinc-800 bg-zinc-950"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-zinc-800 text-xs uppercase text-zinc-500"><tr><th className="p-3">Object</th><th className="p-3">Path</th><th className="p-3">Profile</th><th className="p-3">Composition hash</th><th className="p-3">Media</th><th className="p-3">Responsive</th><th className="p-3">Readiness</th></tr></thead><tbody>{stages.map(stage => <tr key={stage.stageId} className="border-t border-zinc-800"><td className="p-3 text-white">{stage.wordpressObjectId}</td><td className="p-3 text-zinc-300">{stage.path}</td><td className="p-3 text-red-300">{stage.profile.replaceAll("_", " ")}</td><td className="max-w-48 break-all p-3 font-mono text-xs text-zinc-400">{stage.compositionHash}</td><td className={stage.mediaPolicy.pass ? "p-3 text-emerald-300" : "p-3 text-amber-300"}>{stage.mediaPolicy.pass ? `${stage.mediaInstances.length} GOVERNED` : "BLOCKED"}</td><td className="p-3 text-emerald-300">1440 · 1024 · 768 · 375</td><td className={stage.status === "OWNER_REVIEW_READY" ? "p-3 text-emerald-300" : "p-3 text-amber-300"}>{stage.status.replaceAll("_", " ")}</td></tr>)}</tbody></table></section>
    <div className="space-y-8">{stages.map(stage => <article key={stage.stageId} className="border border-zinc-800 bg-zinc-950"><header className="border-b border-zinc-800 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-red-400">{stage.profile.replaceAll("_", " ")}</p><h2 className="mt-1 text-xl font-semibold text-white">WordPress object {stage.wordpressObjectId}</h2><p className="mt-1 text-xs text-zinc-500">{stage.path}</p></div><span className={stage.status === "OWNER_REVIEW_READY" ? "text-xs font-semibold text-emerald-300" : "text-xs font-semibold text-amber-300"}>{stage.status.replaceAll("_", " ")}</span></div><dl className="mt-4 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-zinc-500">Hero</dt><dd className="text-zinc-200">{stage.heroVariant.replaceAll("_", " ")}</dd></div><div><dt className="text-zinc-500">Media layout</dt><dd className="text-zinc-200">{stage.mediaLayout.replaceAll("_", " ")}</dd></div><div><dt className="text-zinc-500">CTA pattern</dt><dd className="text-zinc-200">{stage.ctaPlacement.replaceAll("_", " ")}</dd></div><div><dt className="text-zinc-500">Host preflight</dt><dd className={stage.hostPreflight.pass ? "text-emerald-300" : "text-amber-300"}>{stage.hostPreflight.pass ? "PASS" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Media policy</dt><dd className={stage.mediaPolicy.pass ? "text-emerald-300" : "text-amber-300"}>{stage.mediaPolicy.pass ? "PASS" : "BLOCKED"}</dd></div></dl><p className="mt-3 text-xs text-zinc-500">Sequence: {stage.sectionSequence.join(" → ")}</p></header><details className="border-b border-zinc-800 p-5"><summary className="cursor-pointer font-semibold text-white">Desktop evidence</summary><div className="mt-4 grid gap-4 xl:grid-cols-2"><Frame title={`Wave 2 WordPress ${stage.wordpressObjectId} current desktop`} width={1440} height={stage.desktopHeight} html={stage.currentHtml} /><Frame title={`Wave 2 WordPress ${stage.wordpressObjectId} proposed desktop`} width={1440} height={stage.desktopHeight} html={stage.proposedHtml} /></div></details><details className="p-5"><summary className="cursor-pointer font-semibold text-white">Mobile evidence</summary><div className="mt-4 grid gap-4 xl:grid-cols-2"><Frame title={`Wave 2 WordPress ${stage.wordpressObjectId} current mobile`} width={375} height={stage.mobileHeight} html={stage.currentHtml} /><Frame title={`Wave 2 WordPress ${stage.wordpressObjectId} proposed mobile`} width={375} height={stage.mobileHeight} html={stage.proposedHtml} /></div></details></article>)}</div>
    <section className="border-l-4 border-amber-500 bg-amber-950/20 p-6"><p className="text-xs font-semibold uppercase text-amber-300">Owner action required</p><h2 className="mt-2 text-xl font-semibold text-white">Review Wave 2 compositions</h2><p className="mt-2 text-sm text-zinc-300">No staging, Apply, Publish, Wave 3, or WordPress mutation action is exposed here.</p></section>
  </section>;
}
