import type { CommercialStainlessWordPressStageRecord } from "./commercial-stainless-wordpress-staging";

export type CommercialStainlessWordPressWave1ReviewItem = { record: CommercialStainlessWordPressStageRecord; currentHtml: string; stagedHtml: string; desktopHeight: number; mobileHeight: number };

function Frame({ title, width, height, html }: { title: string; width: number; height: number; html: string }) {
  return <div className="overflow-auto border border-zinc-700 bg-zinc-900 p-3"><p className="mb-3 text-xs font-semibold uppercase text-zinc-400">{width}px · actual WordPress render</p><iframe title={title} srcDoc={html} scrolling="no" style={{ width, height }} className="max-w-none border-0 bg-white" /></div>;
}

export function CommercialStainlessWordPressWave1Review({ items }: { items: CommercialStainlessWordPressWave1ReviewItem[] }) {
  return <section className="space-y-6">
    <header className="border border-zinc-800 bg-zinc-950 p-6"><p className="text-xs font-semibold uppercase text-red-400">Commercial Stainless WordPress Staging</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-white">Wave 1 actual autosave renders</h1><p className="mt-2 max-w-3xl text-sm text-zinc-300">These proposed pages are rendered from private native WordPress autosaves. Their published parent objects remain online and unchanged.</p></div><span className="border border-amber-600 px-3 py-2 text-xs font-semibold text-amber-200">PUBLICATION UNAVAILABLE</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-zinc-500">Staged objects</dt><dd className="text-white">{items.length}</dd></div><div><dt className="text-zinc-500">Public parents</dt><dd className="text-emerald-300">PUBLISHED / PRESERVED</dd></div><div><dt className="text-zinc-500">Autosave revisions</dt><dd className="text-white">{items.map((item) => item.record.autosaveId).join(", ")}</dd></div><div><dt className="text-zinc-500">Publication mutation</dt><dd className="text-emerald-300">FALSE</dd></div><div><dt className="text-zinc-500">Rollback</dt><dd className="text-emerald-300">READY</dd></div></dl></header>
    <div className="space-y-8">{items.map(({ record, currentHtml, stagedHtml, desktopHeight, mobileHeight }) => <article key={record.stageId} className="border border-zinc-800 bg-zinc-950"><header className="border-b border-zinc-800 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-red-400">{record.targetProfile.replaceAll("_", " ")}</p><h2 className="mt-1 text-xl font-semibold text-white">WordPress object {record.wordpressObjectId}</h2><p className="mt-1 text-xs text-zinc-500">Autosave {record.autosaveId} · {new URL(record.currentPublicUrl).pathname}</p></div><span className={record.status === "PUBLICATION_READY" ? "text-xs font-semibold text-emerald-300" : "text-xs font-semibold text-amber-300"}>{record.status.replaceAll("_", " ")}</span></div><dl className="mt-4 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-6"><div><dt className="text-zinc-500">SEO</dt><dd className="text-emerald-300">{record.seoHashPreserved ? "PRESERVED" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Canonical</dt><dd className="text-emerald-300">{record.canonicalPreserved ? "PRESERVED" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Media</dt><dd className="text-emerald-300">{record.mediaPreserved ? "PRESERVED" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Links</dt><dd className="text-emerald-300">CERTIFIED</dd></div><div><dt className="text-zinc-500">Public body</dt><dd className="text-emerald-300">{record.publicBodyChanged === false ? "UNCHANGED" : "BLOCKED"}</dd></div><div><dt className="text-zinc-500">Rollback</dt><dd className="text-emerald-300">{record.rollbackReady ? "READY" : "BLOCKED"}</dd></div></dl></header><details className="border-b border-zinc-800 p-5"><summary className="cursor-pointer font-semibold text-white">Desktop evidence</summary><div className="mt-4 grid gap-4 xl:grid-cols-2"><Frame title={`WordPress ${record.wordpressObjectId} current desktop`} width={1440} height={desktopHeight} html={currentHtml} /><Frame title={`WordPress ${record.wordpressObjectId} staged desktop`} width={1440} height={desktopHeight} html={stagedHtml} /></div></details><details className="p-5"><summary className="cursor-pointer font-semibold text-white">Mobile evidence</summary><div className="mt-4 grid gap-4 lg:grid-cols-2"><Frame title={`WordPress ${record.wordpressObjectId} current mobile`} width={375} height={mobileHeight} html={currentHtml} /><Frame title={`WordPress ${record.wordpressObjectId} staged mobile`} width={375} height={mobileHeight} html={stagedHtml} /></div></details></article>)}</div>
    <section className="border-l-4 border-amber-500 bg-amber-950/20 p-6"><p className="text-xs font-semibold uppercase text-amber-300">Separate Owner Gate</p><h2 className="mt-2 text-xl font-semibold text-white">Review WordPress Wave 1 staging.</h2><p className="mt-2 text-sm text-zinc-300">Publication readiness is evidence only. Publication remains unauthorized and no publication control is available.</p></section>
  </section>;
}