import "server-only";

import { createHash } from "node:crypto";

import { normalizeWordPressApiBaseUrl } from "./authenticated-wordpress-read-authority";
import { COMMERCIAL_STAINLESS_ORIGIN, COMMERCIAL_STAINLESS_SITE_ID } from "./commercial-stainless-rich-composition";
import { listCommercialStainlessWave2AuthorityEvidence, listCommercialStainlessWave2WordPressStageRecords } from "./commercial-stainless-wave2-staging";
import { listCommercialStainlessWordPressPublicationReceipts } from "./commercial-stainless-wordpress-publication";
import { deepClone, loadPersistedState, savePersistedState } from "./foundation-persistence";
import { evaluateSemanticMediaReuse, extractRenderedMediaInstances } from "./semantic-media-reuse-policy";
import type { SiteConfiguration } from "./types";
import { resolveWordPressCredentialReference } from "./wordpress-credential-resolver";
import { verifyWordPressTemplateStructure } from "./wordpress-post-content-publication-verifier";

export const COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_OPERATION = "COMMERCIAL_STAINLESS_WAVE2_OBJECT12_RETRY_AND_RESUME_V2";
export const COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_IMPLEMENTATION_SHA = "bcd1ec3f50bf238cc967d6d58d4e5ca478734492";
export const COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_ORDER = [12, 15, 16, 18, 19] as const;
export const COMMERCIAL_STAINLESS_HOMEPAGE_BASELINE_HASH = "a6bbe8f0db6080c2732cb4baec7bba5d361ebacfc40a16815c655cef8f0e4508";
export const COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_HASHES = new Map<number, string>([
  [12, "b2e2f2b690e3d518472bd56e08886701293314d2215838b37d7a3c7fdbf4ddc3"],
  [15, "ac370c9f08aff1b496e16346078d0959ab92d29a4e6a36f57e0dbb54a9bac36c"],
  [16, "ccac7e46d1c40239736c0c65ffe236bd4cbd62e3717cb7ddfd390cf395ef5f4f"],
  [18, "ceb8b68be8125545a71e17f5a6a6ecdb0148f06180555ebaf1e0b389bb9076e2"],
  [19, "5925c0b7c45d0b082f163c9286cb400e5ae47a35045f77cad8239f38d7206c46"],
]);

const NAMESPACE = "commercial-stainless-wave2-object12-retry-and-resume-v2";
const TARGETS = [
  { id: 12, path: "/commercial-stainless-counters/", slug: "commercial-stainless-counters" },
  { id: 15, path: "/mobile-and-modular-stainless-workstations/", slug: "mobile-and-modular-stainless-workstations" },
  { id: 16, path: "/stainless-countertop/", slug: "stainless-countertop" },
  { id: 18, path: "/markets/foodservice/", slug: "foodservice" },
  { id: 19, path: "/markets/healthcare/", slug: "healthcare" },
] as const;

type WpValue = { raw?: string; rendered?: string };
type WpPage = { id?: number; status?: string; slug?: string; link?: string; featured_media?: number; content?: WpValue; yoast_head_json?: { title?: string; description?: string; canonical?: string; robots?: Record<string, string> } };
type Headers = Record<string, string | null>;
export type Wave2PublicRead = { timestamp: string; httpStatus: number; finalUrl: string; responseHeaders: Headers; cacheClassification: "FRESH_EXPECTED" | "INDETERMINATE"; bodyComplete: boolean; publicRenderHash: string; predicateMatrix: Record<string, boolean>; failedPredicates: string[] };
export type Wave2ViewportCertification = { width: 1440 | 1024 | 768 | 375; pass: boolean; horizontalOverflow: number; globalHeaderCount: number; themePageTitleVisible: number; genesisHeroVisible: number; semanticH1Count: number; duplicatePrimaryHeadingCount: number; globalFooterCount: number; brokenMedia: number; overlapCount: number; fragmentedHeadingCount: number; unusableCtaCount: number; emptySectionCount: number; largestBlankRegion: number; darkOnDarkFailures: number; lightOnLightFailures: number; unreadableTextFailures: number };
export type Wave2VisualCertification = { certificationId: string; authority: "ACTUAL_PUBLIC_HOST_RENDER"; viewports: Wave2ViewportCertification[] };
export type Wave2PublicationReceipt = { receiptId: string; operation: typeof COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_OPERATION; wordpressObjectId: number; expectedHash: string; prePublicationHash: string; publicUrl: string; status: "PREPARED" | "PUBLISHED_PENDING_VISUAL" | "PUBLIC_CERTIFIED" | "BLOCKED"; publicationAttempted: boolean; wordpressContentMutation: false; contentReconstructed: false; copyChanged: false; mediaChanged: false; prePublication: { contentRaw: string; status: string; slug: string; canonical: string; seoTitle: string; metaDescription: string; indexability: string; featuredMedia: number; publicHash: string }; convergenceReads: Wave2PublicRead[]; convergence: "PASS" | "FAIL"; visual: Wave2VisualCertification | null; rollbackExecuted: false; rollbackVerified: boolean; blockers: string[]; createdAt: string; updatedAt: string };
type State = { receipts: Wave2PublicationReceipt[] };

const sha = (value: string) => createHash("sha256").update(value).digest("hex");
const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
const main = (html: string) => html.match(/<main\b[^>]*>[\s\S]*?<\/main>/i)?.[0] ?? "";
const canonical = (html: string) => text(html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)/i)?.[1]);
const robots = (page: WpPage) => Object.values(page.yoast_head_json?.robots ?? {}).join(",");
function auth(username: string, password: string) { return `Basic ${Buffer.from(`${username}:${password}`, "utf8").toString("base64")}`; }
function authority(site: SiteConfiguration) { if (site.organizationId !== "rj-metal" || site.siteId !== COMMERCIAL_STAINLESS_SITE_ID || site.domain !== "commercialstainlesscounters.com") throw new Error("WAVE2_PUBLICATION_SCOPE_MISMATCH"); const credential = resolveWordPressCredentialReference(site.integrations.wordpressCredentialReference); if (!credential || !site.integrations.wordpressApiBaseUrl) throw new Error("WAVE2_PUBLICATION_AUTHORITY_REQUIRED"); return { apiBase: normalizeWordPressApiBaseUrl(site.integrations.wordpressApiBaseUrl), headers: { Accept: "application/json", Authorization: auth(credential.username, credential.applicationPassword), "Cache-Control": "no-cache, no-store", Pragma: "no-cache" } }; }
async function pageRead(apiBase: string, headers: Record<string, string>, id: number) { const response = await fetch(`${apiBase}/pages/${id}?context=edit&_fields=id,status,slug,link,featured_media,content,yoast_head_json&_wave2pub=${crypto.randomUUID()}`, { headers, cache: "no-store", signal: AbortSignal.timeout(30_000) }); return { status: response.status, body: response.ok ? await response.json() as WpPage : null }; }
async function publicRead(url: string) { const response = await fetch(`${url}?_wave2pub=${crypto.randomUUID()}`, { cache: "no-store", redirect: "follow", signal: AbortSignal.timeout(30_000) }); return { status: response.status, finalUrl: response.url, headers: { age: response.headers.get("age"), cacheControl: response.headers.get("cache-control"), etag: response.headers.get("etag"), lastModified: response.headers.get("last-modified"), server: response.headers.get("server"), date: response.headers.get("date") }, html: await response.text() }; }
function load() { return loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: () => ({ receipts: [] }) }); }
function save(receipt: Wave2PublicationReceipt) { for (let attempt = 0; attempt < 8; attempt += 1) { const loaded = load(); const index = loaded.state.receipts.findIndex((item) => item.receiptId === receipt.receiptId); if (index >= 0) loaded.state.receipts[index] = receipt; else loaded.state.receipts.push(receipt); try { savePersistedState({ namespace: NAMESPACE, state: loaded.state, expectedRevision: loaded.revision }); return deepClone(receipt); } catch (error) { if (attempt === 7) throw error; } } throw new Error("WAVE2_PUBLICATION_CAS_EXHAUSTED"); }
export function listCommercialStainlessWave2PublicationReceipts() { return deepClone(load().state.receipts); }
export function summarizeCommercialStainlessWave2PublicationReceipt(receipt: Wave2PublicationReceipt) { return { ...receipt, prePublication: { ...receipt.prePublication, contentRaw: undefined } }; }

async function inspectPublic(url: string, expectedHash: string): Promise<Wave2PublicRead> {
  const response = await publicRead(url); const structure = verifyWordPressTemplateStructure({ html: response.html, expectedH1Count: 1, expectedIdentityClass: "wr-page" }); const bodyComplete = /<\/html>\s*$/i.test(response.html); const media = evaluateSemanticMediaReuse({ instances: extractRenderedMediaInstances({ html: main(response.html), origin: url }), declarations: [] }); const themeTitleVisible = /<(?:h1|h2)\b[^>]*(?:wp-block-post-title|entry-title)/i.test(main(response.html)); const heroVisible = /class=["'][^"']*\bwr-hero\b/i.test(main(response.html)); const themeFeatured = /class=["'][^"']*\bwp-block-post-featured-image\b/i.test(main(response.html)); const devLinks = /https?:\/\/(?:localhost|127\.0\.0\.1|[^/\s"']*\.local)(?::\d+)?/i.test(response.html); const matrix = { http200: response.status === 200, canonical: canonical(response.html) === url, bodyComplete, globalHeaderCount: structure.globalHeaderCount === 1, globalFooterCount: structure.globalFooterCount === 1, h1Count: structure.h1Count === 1, richPage: structure.pageIdentityCount === 1, themeTitleSuppressed: !themeTitleVisible, genesisHeroVisible: heroVisible, themeFeaturedImageSuppressed: !themeFeatured, mediaPolicy: media.pass && media.hostDuplicateMediaCount === 0 && media.accidentalDuplicationCount === 0 && media.unresolvedDuplicationCount === 0, noDevLinks: !devLinks, expectedStoredHash: expectedHash.length === 64 }; const failedPredicates = Object.entries(matrix).filter(([, pass]) => !pass).map(([name]) => name); return { timestamp: new Date().toISOString(), httpStatus: response.status, finalUrl: response.finalUrl, responseHeaders: response.headers, cacheClassification: failedPredicates.length === 0 ? "FRESH_EXPECTED" : "INDETERMINATE", bodyComplete, publicRenderHash: sha(main(response.html)), predicateMatrix: matrix, failedPredicates };
}

export async function publishCommercialStainlessWave2Page(site: SiteConfiguration, wordpressObjectId: number) {
  const target = TARGETS.find((item) => item.id === wordpressObjectId); if (!target) throw new Error(`WAVE2_UNAUTHORIZED_OBJECT:${wordpressObjectId}`); const expectedHash = COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_HASHES.get(wordpressObjectId); if (!expectedHash) throw new Error(`WAVE2_APPROVED_HASH_MISSING:${wordpressObjectId}`); const receipts = listCommercialStainlessWave2PublicationReceipts(); const existing = receipts.find((item) => item.wordpressObjectId === wordpressObjectId); if (existing?.status === "PUBLIC_CERTIFIED" || existing?.status === "PUBLISHED_PENDING_VISUAL") return existing; if (existing) throw new Error(`WAVE2_PUBLICATION_REVIEW_REQUIRED:${wordpressObjectId}:${existing.status}`); const index = COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_ORDER.indexOf(wordpressObjectId as never); const prior = COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_ORDER.slice(0, index); if (!prior.every((id) => receipts.some((receipt) => receipt.wordpressObjectId === id && receipt.status === "PUBLIC_CERTIFIED"))) throw new Error(`WAVE2_SEQUENTIAL_STOP:${wordpressObjectId}`);
  const wave1 = listCommercialStainlessWordPressPublicationReceipts(); if (![24, 11, 13, 17, 23].every((id) => wave1.some((receipt) => receipt.wordpressObjectId === id && receipt.status === "PUBLIC_CERTIFIED"))) throw new Error("WAVE1_PRESERVATION_GATE_FAILED"); const stage = listCommercialStainlessWave2WordPressStageRecords().find((item) => item.wordpressObjectId === wordpressObjectId); const durable = listCommercialStainlessWave2AuthorityEvidence().find((item) => item.wordpressObjectId === wordpressObjectId && item.approvedHashDurablyStored && !item.autosaveDependency); if (!stage || !stage.mediaPolicy.pass || !durable || sha(durable.approvedContentRaw) !== expectedHash) throw new Error(`WAVE2_DURABLE_AUTHORITY_FAILED:${wordpressObjectId}`);
  const resolved = authority(site); const [pageResult, publicBefore, homepage] = await Promise.all([pageRead(resolved.apiBase, resolved.headers, wordpressObjectId), publicRead(`${COMMERCIAL_STAINLESS_ORIGIN}${target.path}`), pageRead(resolved.apiBase, resolved.headers, 10)]); const page = pageResult.body ?? {}; const raw = text(page.content?.raw); const homeRaw = text(homepage.body?.content?.raw); const expectedUrl = `${COMMERCIAL_STAINLESS_ORIGIN}${target.path}`; const preflight = pageResult.status === 200 && Number(page.id) === wordpressObjectId && text(page.status) === "publish" && text(page.slug) === target.slug && new URL(text(page.link)).pathname === target.path && sha(raw) === expectedHash && raw === durable.approvedContentRaw && canonical(publicBefore.html) === expectedUrl && text(page.yoast_head_json?.title) === stage.seoIdentity.title && text(page.yoast_head_json?.description) === stage.seoIdentity.metaDescription && robots(page) === stage.seoIdentity.indexability && Number(page.featured_media) === stage.featuredMediaId && homepage.status === 200 && sha(homeRaw) === COMMERCIAL_STAINLESS_HOMEPAGE_BASELINE_HASH; if (!preflight) throw new Error(`WAVE2_PREPUBLICATION_GATE_FAILED:${wordpressObjectId}`);
  const now = new Date().toISOString(); let receipt = save({ receiptId: `csc-wave2-object12-retry-resume-v2-${wordpressObjectId}-${expectedHash.slice(0, 12)}`, operation: COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_OPERATION, wordpressObjectId, expectedHash, prePublicationHash: sha(raw), publicUrl: expectedUrl, status: "PREPARED", publicationAttempted: true, wordpressContentMutation: false, contentReconstructed: false, copyChanged: false, mediaChanged: false, prePublication: { contentRaw: raw, status: text(page.status), slug: text(page.slug), canonical: canonical(publicBefore.html), seoTitle: text(page.yoast_head_json?.title), metaDescription: text(page.yoast_head_json?.description), indexability: robots(page), featuredMedia: Number(page.featured_media), publicHash: sha(main(publicBefore.html)) }, convergenceReads: [], convergence: "FAIL", visual: null, rollbackExecuted: false, rollbackVerified: true, blockers: [], createdAt: now, updatedAt: now });
  const reads: Wave2PublicRead[] = []; for (let attempt = 0; attempt < 5 && (reads.length < 2 || reads.slice(-2).some((read) => read.cacheClassification !== "FRESH_EXPECTED")); attempt += 1) { const read = await inspectPublic(expectedUrl, expectedHash); reads.push(read); receipt = save({ ...receipt, convergenceReads: reads, updatedAt: read.timestamp }); } const converged = reads.length >= 2 && reads.slice(-2).every((read) => read.cacheClassification === "FRESH_EXPECTED" && read.publicRenderHash === reads.at(-1)!.publicRenderHash); if (!converged) { save({ ...receipt, status: "BLOCKED", convergenceReads: reads, convergence: "FAIL", rollbackVerified: true, blockers: ["PUBLIC_CONVERGENCE_FAILED"], updatedAt: new Date().toISOString() }); throw new Error(`WAVE2_PUBLIC_CONVERGENCE_FAILED:${wordpressObjectId}`); } return save({ ...receipt, status: "PUBLISHED_PENDING_VISUAL", convergenceReads: reads, convergence: "PASS", updatedAt: new Date().toISOString() });
}

export async function certifyCommercialStainlessWave2Page(site: SiteConfiguration, wordpressObjectId: number, visual: Wave2VisualCertification, receiptId: string) {
  const receipt = listCommercialStainlessWave2PublicationReceipts().find((item) => item.receiptId === receiptId && item.wordpressObjectId === wordpressObjectId); if (!receipt || receipt.status !== "PUBLISHED_PENDING_VISUAL" || visual.authority !== "ACTUAL_PUBLIC_HOST_RENDER" || !visual.certificationId.trim()) throw new Error(`WAVE2_VISUAL_CERTIFICATION_BLOCKED:${wordpressObjectId}`); const widths = [1440, 1024, 768, 375]; const pass = visual.viewports.length === 4 && widths.every((width) => visual.viewports.some((item) => item.width === width && item.pass && item.horizontalOverflow === 0 && item.globalHeaderCount === 1 && item.themePageTitleVisible === 0 && item.genesisHeroVisible === 1 && item.semanticH1Count === 1 && item.duplicatePrimaryHeadingCount === 0 && item.globalFooterCount === 1 && item.brokenMedia === 0 && item.overlapCount === 0 && item.fragmentedHeadingCount === 0 && item.unusableCtaCount === 0 && item.emptySectionCount === 0 && item.largestBlankRegion <= 120 && item.darkOnDarkFailures === 0 && item.lightOnLightFailures === 0 && item.unreadableTextFailures === 0)); const resolved = authority(site); const page = await pageRead(resolved.apiBase, resolved.headers, wordpressObjectId); const stillExact = page.status === 200 && sha(text(page.body?.content?.raw)) === receipt.expectedHash; if (!pass || !stillExact) { save({ ...receipt, status: "BLOCKED", visual, rollbackVerified: stillExact, blockers: [...receipt.blockers, !pass ? "ACTUAL_PUBLIC_VISUAL_FAILED" : "STORED_HASH_CHANGED"], updatedAt: new Date().toISOString() }); throw new Error(`WAVE2_VISUAL_CERTIFICATION_FAILED:${wordpressObjectId}`); } return save({ ...receipt, status: "PUBLIC_CERTIFIED", visual, rollbackVerified: true, updatedAt: new Date().toISOString() });
}
