import type { CommercialStainlessPageProfilePlan, CommercialStainlessWave1Stage } from "./commercial-stainless-wave1-rollout";

function Frame({ title, width, height, html }: { title: string; width: number; height: number; html: string }) {
  return <div className="overflow-auto border border-zinc-700 bg-zinc-900 p-3"><p className="mb-3 text-xs font-semibold uppercase text-zinc-400">{width}px · complete staged page</p><iframe title={title} srcDoc={html} scrolling="no" style={{ width, height }} className="max-w-none border-0 bg-white" /></div>;
}

export function CommercialStainlessWave1Review({ stages, profileMap, diversity }: { stages: CommercialStainlessWave1Stage[]; profileMap: CommercialStainlessPageProfilePlan[]; diversity: { heroVariantCount: number; sectionSequenceVariantCount: number; mediaLayoutVariantCount: number; ctaPlacementVariantCount: number } }) {
  const wave2 = profileMap.filter((item) => item.wave === "WAVE_2");
  const wave3 = profileMap.filter((item) => item.wave === "WAVE_3");
  const home = profileMap.find((item) => item.wave === "PRESERVE_HOME");
  return <section className="space-y-6">
    <header className="border border-zinc-800 bg-zinc-950 p-6"><p className="text-xs font-semibold uppercase text-red-400">Commercial Stainless Controlled Rollout</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-white">Wave 1 owner review</h1><p className="mt-2 max-w-3xl text-sm text-zinc-300">Five profile-specific local staged equivalents use the owner-approved Design-Build system. No WordPress object was updated and no publication action exists here.</p></div><span className="border border-amber-600 px-3 py-2 text-xs font-semibold text-amber-200">STOP AFTER WAVE 1</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-zinc-500">Approved reference</dt><dd className="break-all text-white">{stages[0]?.approvedDesignReferenceSha}</dd></div><div><dt className="text-zinc-500">Pages staged</dt><dd className="text-white">{stages.length}</dd></div><div><dt className="text-zinc-500">Profiles covered</dt><dd className="text-white">{new Set(stages.map((stage) => stage.targetProfile)).size}</dd></div><div><dt className="text-zinc-500">WordPress mutation</dt><dd className="text-emerald-300">FALSE</dd></div><div><dt className="text-zinc-500">Publication</dt><dd className="text-emerald-300">FALSE</dd></div></dl></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><article className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">Hero variants</p><strong className="text-xl text-white">{diversity.heroVariantCount}</strong></article><article className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">Section sequences</p><strong className="text-xl text-white">{diversity.sectionSequenceVariantCount}</strong></article><article className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">Media layouts</p><strong className="text-xl text-white">{diversity.mediaLayoutVariantCount}</strong></article><article className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs text-zinc-500">CTA placements</p><strong className="text-xl text-white">{diversity.ctaPlacementVariantCount}</strong></article></section>
    <div className="space-y-8">{stages.map((stage) => <article key={stage.stageId} className="border border-zinc-800 bg-zinc-950"><header className="border-b border-zinc-800 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-red-400">{stage.targetProfile.replaceAll("_", " ")}</p><h2 className="mt-1 text-xl font-semibold text-white">{stage.page.title}</h2><p className="mt-1 text-xs text-zinc-500">WordPress {stage.page.wordpressObjectId} · {new URL(stage.page.url).pathname}</p></div><span className="text-xs font-semibold text-amber-300">{stage.status.replaceAll("_", " ")}</span></div><dl className="mt-4 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-zinc-500">Hero</dt><dd className="text-zinc-200">{stage.heroVariant.replaceAll("_", " ")}</dd></div><div><dt className="text-zinc-500">Media layout</dt><dd className="text-zinc-200">{stage.mediaLayout.replaceAll("_", " ")}</dd></div><div><dt className="text-zinc-500">CTA pattern</dt><dd className="text-zinc-200">{stage.ctaPlacement.replaceAll("_", " ")}</dd></div><div><dt className="text-zinc-500">SEO</dt><dd className="text-emerald-300">{stage.seoHashBefore === stage.seoHashAfter ? "PRESERVED" : "MISMATCH"}</dd></div><div><dt className="text-zinc-500">Media</dt><dd className="text-emerald-300">{stage.media.length} RESOLVED</dd></div></dl><p className="mt-3 text-xs text-zinc-500">Sequence: {stage.sectionSequence.join(" → ")}</p></header><details className="border-b border-zinc-800 p-5"><summary className="cursor-pointer font-semibold text-white">Desktop before / after</summary><div className="mt-4 grid gap-4 xl:grid-cols-2"><Frame title={`${stage.page.title} current desktop`} width={1440} height={stage.desktopHeight} html={stage.currentHtml} /><Frame title={`${stage.page.title} proposed desktop`} width={1440} height={stage.desktopHeight} html={stage.proposedHtml} /></div></details><details className="p-5"><summary className="cursor-pointer font-semibold text-white">Mobile before / after</summary><div className="mt-4 grid gap-4 lg:grid-cols-2"><Frame title={`${stage.page.title} current mobile`} width={375} height={stage.mobileHeight} html={stage.currentHtml} /><Frame title={`${stage.page.title} proposed mobile`} width={375} height={stage.mobileHeight} html={stage.proposedHtml} /></div></details></article>)}</div>
    <section className="border border-zinc-800 bg-zinc-950"><header className="border-b border-zinc-800 p-5"><h2 className="text-lg font-semibold text-white">Remaining 14-page profile map</h2><p className="mt-1 text-sm text-zinc-400">Intent and media authority recorded before any live mutation.</p></header><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="text-xs uppercase text-zinc-500"><tr><th className="p-3">ID</th><th className="p-3">URL</th><th className="p-3">Current</th><th className="p-3">Target</th><th className="p-3">Primary intent / CTA</th><th className="p-3">Media roles</th><th className="p-3">Wave</th></tr></thead><tbody>{profileMap.map((item) => <tr key={item.wordpressObjectId} className="border-t border-zinc-800"><td className="p-3 font-mono text-zinc-300">{item.wordpressObjectId}</td><td className="p-3 text-white">{new URL(item.url).pathname}</td><td className="p-3 text-zinc-400">{item.currentProfile.replaceAll("_", " ")}</td><td className="p-3 text-emerald-300">{item.targetProfile.replaceAll("_", " ")}</td><td className="p-3 text-zinc-300">{item.primaryIntent}<strong className="mt-1 block text-white">{item.primaryCta}</strong></td><td className="p-3 text-zinc-400">{item.requiredMediaRoles.join(" · ")}</td><td className="p-3 text-zinc-300">{item.wave.replaceAll("_", " ")}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 lg:grid-cols-3"><article className="border border-emerald-900 bg-emerald-950/15 p-5"><p className="text-xs font-semibold uppercase text-emerald-300">Homepage Preservation</p><h2 className="mt-2 font-semibold text-white">{home ? new URL(home.url).pathname : "/"}</h2><p className="mt-2 text-sm text-zinc-300">Approved homepage remains unchanged and outside future rollout waves.</p></article><article className="border border-zinc-800 bg-zinc-950 p-5"><p className="text-xs font-semibold uppercase text-zinc-400">Wave 2 Plan Only</p><p className="mt-2 text-sm text-zinc-300">{wave2.map((item) => `${item.wordpressObjectId} ${new URL(item.url).pathname}`).join(" · ")}</p></article><article className="border border-zinc-800 bg-zinc-950 p-5"><p className="text-xs font-semibold uppercase text-zinc-400">Wave 3 Plan Only</p><p className="mt-2 text-sm text-zinc-300">{wave3.map((item) => `${item.wordpressObjectId} ${new URL(item.url).pathname}`).join(" · ")}</p></article></section>
    <section className="border-l-4 border-amber-500 bg-amber-950/20 p-6"><p className="text-xs font-semibold uppercase text-amber-300">Owner Review Required</p><h2 className="mt-2 text-xl font-semibold text-white">Review all five staged page compositions.</h2><p className="mt-2 text-sm text-zinc-300">No Apply, Publish, Wave 2, or WordPress action is available. A separate owner decision is required.</p></section>
  </section>;
}