import type { CommercialStainlessPageInventoryItem, CommercialStainlessRichPreview, CommercialStainlessRolloutPlanItem } from "./commercial-stainless-rich-composition";

function Frame({ title, width, height, src, srcDoc }: { title: string; width: number; height: number; src?: string; srcDoc?: string }) {
  return <div data-full-page-comparison className="overflow-auto border border-zinc-700 bg-zinc-900 p-3"><p className="mb-3 text-xs font-semibold uppercase text-zinc-400">{width}px viewport · full page</p><iframe title={title} src={src} srcDoc={srcDoc} scrolling="no" style={{ width, height }} className="max-w-none border-0 bg-white" /></div>;
}

export function CommercialStainlessRichCompositionReview({ preview, inventory, rollout }: { preview: CommercialStainlessRichPreview; inventory: CommercialStainlessPageInventoryItem[]; rollout: CommercialStainlessRolloutPlanItem[] }) {
  return <section className="space-y-6">
    <header className="border border-zinc-800 bg-zinc-950 p-6"><p className="text-xs font-semibold uppercase text-red-400">Commercial Stainless Rich Composition Proof</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-white">Design-Build Fabrication comparison</h1><p className="mt-2 max-w-3xl text-sm text-zinc-300">Compare the complete current public page with a preview-only future composition generated from existing approved content, links, media, and the exact live global shell. No Apply or bulk rollout control exists.</p></div><span className="border border-amber-700 px-3 py-2 text-xs font-semibold text-amber-200">OWNER REVIEW REQUIRED</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><div><dt className="text-zinc-500">WordPress object</dt><dd className="text-white">{preview.page.wordpressObjectId}</dd></div><div><dt className="text-zinc-500">URL</dt><dd className="break-all text-white">{preview.page.currentCanonical}</dd></div><div><dt className="text-zinc-500">Current canvas</dt><dd className="text-white">{preview.geometry.currentCanvasWidth}px</dd></div><div><dt className="text-zinc-500">Proposed canvas</dt><dd className="text-white">{preview.geometry.proposedCanvasWidth}px</dd></div><div><dt className="text-zinc-500">Current header gap</dt><dd className="text-amber-300">{preview.geometry.currentHeaderToContentGap}px</dd></div><div><dt className="text-zinc-500">Proposed hero gap</dt><dd className="text-emerald-300">{preview.geometry.proposedHeaderToHeroGap}px</dd></div><div><dt className="text-zinc-500">Mutation</dt><dd className="text-emerald-300">NONE</dd></div></dl></header>
    <section className="grid gap-4 lg:grid-cols-2"><article className="border border-zinc-800 bg-zinc-950 p-5"><p className="text-xs font-semibold uppercase text-zinc-500">Current Public Page</p><h2 className="mt-2 text-xl font-semibold text-white">Narrow legacy composition</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-zinc-300">{preview.page.currentVisualWeaknesses.map((item) => <li key={item}>{item}</li>)}</ul></article><article className="border border-emerald-900 bg-emerald-950/15 p-5"><p className="text-xs font-semibold uppercase text-emerald-300">Proposed Rich Composition</p><h2 className="mt-2 text-xl font-semibold text-white">Wide Design-Build profile</h2><p className="mt-3 text-sm text-zinc-300">One global header, integrated image hero, value band, offering grid, process, capability split, industries, project inputs, and a strong quote CTA.</p></article></section>
    <section className="space-y-4"><header><p className="text-xs font-semibold uppercase text-zinc-500">Desktop Comparison</p><h2 className="mt-1 text-xl font-semibold text-white">Complete before and after at 1440</h2></header><div className="grid gap-4 xl:grid-cols-2"><Frame title="Current Design-Build desktop" width={1440} height={preview.geometry.fullPageHeights.currentDesktop} src={preview.page.url} /><Frame title="Proposed Design-Build desktop" width={1440} height={preview.geometry.fullPageHeights.proposedDesktop} srcDoc={preview.html} /></div></section>
    <section className="space-y-4"><header><p className="text-xs font-semibold uppercase text-zinc-500">Mobile Comparison</p><h2 className="mt-1 text-xl font-semibold text-white">Complete before and after at 375</h2></header><div className="grid gap-4 lg:grid-cols-2"><Frame title="Current Design-Build mobile" width={375} height={preview.geometry.fullPageHeights.currentMobile} src={preview.page.url} /><Frame title="Proposed Design-Build mobile" width={375} height={preview.geometry.fullPageHeights.proposedMobile} srcDoc={preview.html} /></div></section>
    <details className="border border-zinc-800 bg-zinc-950 p-5"><summary className="cursor-pointer font-semibold text-white">Complete tablet and compact-desktop previews</summary><div className="mt-4 grid gap-4"><Frame title="Proposed Design-Build 1024" width={1024} height={preview.geometry.fullPageHeights.proposed1024} srcDoc={preview.html} /><Frame title="Proposed Design-Build 768" width={768} height={preview.geometry.fullPageHeights.proposed768} srcDoc={preview.html} /></div></details>
    <section className="border border-zinc-800 bg-zinc-950 p-5"><h2 className="text-lg font-semibold text-white">Preservation and provenance</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-zinc-500">SEO hash</dt><dd className="break-all text-emerald-300">{preview.seoHashBefore === preview.seoHashAfter ? "PRESERVED" : "MISMATCH"}</dd></div><div><dt className="text-zinc-500">Canonical</dt><dd className="text-emerald-300">PRESERVED</dd></div><div><dt className="text-zinc-500">Header/footer</dt><dd className="text-emerald-300">ONE GLOBAL SHELL</dd></div><div><dt className="text-zinc-500">New media</dt><dd className="text-emerald-300">0</dd></div></dl><h3 className="mt-5 text-xs font-semibold uppercase text-zinc-400">Existing media reused</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{preview.media.map((item) => <article key={item.id} className="border border-zinc-800 p-3 text-xs"><p className="font-semibold text-white">Media {item.id} · {item.role.replaceAll("_", " ")}</p><p className="mt-1 text-zinc-400">{item.provenance.replaceAll("_", " ")}</p><p className="mt-1 break-all text-zinc-500">{item.url}</p></article>)}</div><h3 className="mt-5 text-xs font-semibold uppercase text-zinc-400">Links retained in preview context</h3><p className="mt-2 text-sm text-zinc-300">{preview.preservedLinks.join(" · ")}</p></section>
    <section className="border border-zinc-800 bg-zinc-950"><header className="border-b border-zinc-800 p-5"><h2 className="text-lg font-semibold text-white">15-page profile inventory</h2><p className="mt-1 text-sm text-zinc-400">All objects remain published and unchanged. This table is planning authority only.</p></header><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="text-xs uppercase text-zinc-500"><tr><th className="p-3">ID</th><th className="p-3">Page</th><th className="p-3">Current profile</th><th className="p-3">Recommended</th><th className="p-3">Media</th><th className="p-3">Internal links</th></tr></thead><tbody>{inventory.map((item) => <tr key={item.wordpressObjectId} className="border-t border-zinc-800"><td className="p-3 font-mono text-zinc-300">{item.wordpressObjectId}</td><td className="p-3"><p className="font-semibold text-white">{item.title}</p><p className="text-xs text-zinc-500">{new URL(item.url).pathname}</p></td><td className="p-3 text-zinc-400">{item.currentCompositionProfile.replaceAll("_", " ")}</td><td className="p-3 text-emerald-300">{item.recommendedNewProfile.replaceAll("_", " ")}</td><td className="p-3 text-zinc-300">{item.currentMedia.id}</td><td className="p-3 text-zinc-300">{item.currentInternalLinks.length}</td></tr>)}</tbody></table></div></section>
    <section className="border border-zinc-800 bg-zinc-950"><header className="border-b border-zinc-800 p-5"><h2 className="text-lg font-semibold text-white">Remaining 14-page rollout plan</h2><p className="mt-1 text-sm text-zinc-400">Planning only. No page is queued or mutable from this route.</p></header><div className="grid gap-px bg-zinc-800 lg:grid-cols-2">{rollout.map((item) => <article key={item.canonicalPath} className="bg-zinc-950 p-5"><p className="text-xs font-semibold uppercase text-red-400">{item.profile.replaceAll("_", " ")}</p><h3 className="mt-1 font-semibold text-white">{item.page}</h3><p className="mt-1 text-xs text-zinc-500">{item.canonicalPath}</p><p className="mt-3 text-sm text-zinc-300">{item.heroTreatment}</p><p className="mt-2 text-xs text-zinc-500">Sections: {item.keySections.join(" · ")}</p><p className="mt-2 text-xs text-zinc-500">Special: {item.specialConsiderations}</p></article>)}</div></section>
    <section className="border-l-4 border-amber-500 bg-amber-950/20 p-6"><p className="text-xs font-semibold uppercase text-amber-300">Owner Review Stop</p><h2 className="mt-2 text-xl font-semibold text-white">Review the Design-Build proof before any rollout.</h2><p className="mt-2 text-sm text-zinc-300">This route intentionally has no Apply, Publish, Generate Media, or Apply All control. Approval and any later implementation require a separate owner-authorized task.</p></section>
  </section>;
}