import type {
  CustomerAddressRecord,
  CustomerConfiguration,
  CustomerContactRecord,
} from "./types";

const CREATED_AT = "2026-07-29T00:00:00.000Z";

export const FOUNDATION_CUSTOMERS: readonly CustomerConfiguration[] = [
  {
    customerId: "cust-ledw-stadium-group",
    organizationId: "led-display-warehouse",
    accountName: "Stadium Growth Group",
    legalName: "Stadium Growth Group LLC",
    accountCode: "LEDW-CUST-0001",
    accountType: "direct",
    lifecycleState: "active",
    enabled: true,
    primarySiteId: "site-led-display-warehouse-production",
    associatedSiteIds: [
      "site-led-display-warehouse-production",
      "site-led-display-warehouse-staging",
    ],
    primaryContactId: "contact-stadium-amy",
    billingAddressId: "addr-stadium-billing",
    shippingAddressId: "addr-stadium-shipping",
    communicationPreferences: {
      emailEnabled: true,
      smsEnabled: false,
      phoneEnabled: true,
      marketingOptIn: false,
      operationalAlertsEnabled: true,
      invoiceNoticesEnabled: true,
      preferredFrequency: "realtime",
      timezone: "America/Chicago",
    },
    taxExempt: false,
    tags: ["enterprise", "sports", "priority"],
    notes: "Primary strategic account for large venue deployments.",
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    customerId: "cust-ledw-retail-pilot",
    organizationId: "led-display-warehouse",
    accountName: "Retail Pilot Holdings",
    legalName: null,
    accountCode: "LEDW-CUST-0002",
    accountType: "dealer",
    lifecycleState: "prospect",
    enabled: true,
    primarySiteId: "site-led-display-warehouse-staging",
    associatedSiteIds: ["site-led-display-warehouse-staging"],
    primaryContactId: null,
    billingAddressId: null,
    shippingAddressId: null,
    communicationPreferences: {
      emailEnabled: true,
      smsEnabled: false,
      phoneEnabled: false,
      marketingOptIn: true,
      operationalAlertsEnabled: false,
      invoiceNoticesEnabled: false,
      preferredFrequency: "weekly",
      timezone: null,
    },
    taxExempt: false,
    tags: ["pilot", "prospect"],
    notes: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
];

export const FOUNDATION_CUSTOMER_CONTACTS: readonly CustomerContactRecord[] = [
  {
    contactId: "contact-stadium-amy",
    customerId: "cust-ledw-stadium-group",
    organizationId: "led-display-warehouse",
    fullName: "Amy Richardson",
    role: "operations",
    title: "Director of Venue Operations",
    email: "amy.richardson@stadiumgroup.example",
    phone: "+1-312-555-0141",
    preferredContact: true,
    decisionMaker: true,
    enabled: true,
    notes: "Coordinates installation windows and maintenance windows.",
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    contactId: "contact-stadium-faye",
    customerId: "cust-ledw-stadium-group",
    organizationId: "led-display-warehouse",
    fullName: "Faye Carrington",
    role: "finance",
    title: "Controller",
    email: "faye.carrington@stadiumgroup.example",
    phone: "+1-312-555-0182",
    preferredContact: false,
    decisionMaker: false,
    enabled: true,
    notes: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
];

export const FOUNDATION_CUSTOMER_ADDRESSES: readonly CustomerAddressRecord[] = [
  {
    addressId: "addr-stadium-billing",
    customerId: "cust-ledw-stadium-group",
    organizationId: "led-display-warehouse",
    label: "Stadium Group Billing",
    addressType: "billing",
    line1: "1150 Commerce Ave",
    line2: "Suite 310",
    city: "Chicago",
    region: "IL",
    postalCode: "60606",
    countryCode: "US",
    siteId: "site-led-display-warehouse-production",
    defaultBilling: true,
    defaultShipping: false,
    enabled: true,
    notes: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    addressId: "addr-stadium-shipping",
    customerId: "cust-ledw-stadium-group",
    organizationId: "led-display-warehouse",
    label: "Stadium Group Receiving",
    addressType: "shipping",
    line1: "2290 Dockside Park",
    line2: null,
    city: "Chicago",
    region: "IL",
    postalCode: "60607",
    countryCode: "US",
    siteId: "site-led-display-warehouse-production",
    defaultBilling: false,
    defaultShipping: true,
    enabled: true,
    notes: "Deliver weekdays 8am-3pm.",
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
];
