import type {
  IntegrationProfileAssignmentRecord,
  IntegrationProfileConfiguration,
} from "./types";

const CREATED_AT = "2026-07-29T00:00:00.000Z";

export const FOUNDATION_INTEGRATION_PROFILES: readonly IntegrationProfileConfiguration[] = [
  {
    profileId: "profile-publishing-ledw-default",
    profileType: "publishing",
    organizationId: "led-display-warehouse",
    profileName: "LEDW Publishing Default",
    description: "Default publishing profile composed from reusable profile references.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: true,
    references: {
      credentialReference: null,
      workflowReference: null,
      promptReference: null,
      providerReference: null,
      brandReference: null,
      workflowProfileReference: "profile-workflow-ledw-default",
      wordpressProfileReference: "profile-wordpress-ledw-default",
      promptProfileReference: "profile-prompt-commercial-product",
      imageProfileReference: "profile-image-apple-product",
      seoProfileReference: "profile-seo-ledw-default",
      analyticsProfileReference: "profile-analytics-ledw-default",
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: null,
      typographyReference: null,
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: null,
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: null,
      outputContractReference: null,
      retryPolicyReference: null,
      executionTimeoutReference: null,
      environmentReference: null,
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Configuration-only composition profile.",
  },
  {
    profileId: "profile-wordpress-ledw-default",
    profileType: "wordpress",
    organizationId: "led-display-warehouse",
    profileName: "LEDW WordPress Default",
    description: "WordPress publication configuration references.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: true,
    references: {
      credentialReference: "credref-ledw-wordpress-prod",
      workflowReference: null,
      promptReference: null,
      providerReference: "provider-wordpress",
      brandReference: null,
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: null,
      typographyReference: null,
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: null,
      baseUrlReference: "urlref-ledw-wordpress-api",
      authorReference: "authorref-ledw-default",
      categoryReference: "catref-ledw-default",
      postStatusReference: "poststatus-draft",
      featuredImagePolicyReference: "feature-image-required",
      imageInsertionPolicyReference: "image-insertion-inline-after-summary",
      yoastPolicyReference: "yoast-ledw-default",
      inputContractReference: null,
      outputContractReference: null,
      retryPolicyReference: null,
      executionTimeoutReference: null,
      environmentReference: "environment-production",
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Stores only references. No credential values.",
  },
  {
    profileId: "profile-workflow-ledw-default",
    profileType: "workflow",
    organizationId: "led-display-warehouse",
    profileName: "LEDW Workflow Default",
    description: "Workflow orchestration contract references.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: true,
    references: {
      credentialReference: null,
      workflowReference: "workflowref-publication-default",
      promptReference: null,
      providerReference: "provider-n8n",
      brandReference: null,
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: null,
      typographyReference: null,
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: null,
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: "contractref-workflow-input-v1",
      outputContractReference: "contractref-workflow-output-v1",
      retryPolicyReference: "retrypolicy-standard-3",
      executionTimeoutReference: "timeout-policy-30s",
      environmentReference: "environment-production",
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Execution references only.",
  },
  {
    profileId: "profile-prompt-commercial-product",
    profileType: "prompt",
    organizationId: "led-display-warehouse",
    profileName: "Commercial Product Prompt",
    description: "Reusable prompt identity for commercial product content.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: true,
    references: {
      credentialReference: null,
      workflowReference: null,
      promptReference: "promptref-commercial-product-v1",
      providerReference: "provider-openai-text",
      brandReference: "brandref-ledw-core",
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: "profile-seo-ledw-default",
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: null,
      typographyReference: null,
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: null,
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: "contractref-prompt-commercial-input",
      outputContractReference: "contractref-prompt-commercial-output",
      retryPolicyReference: null,
      executionTimeoutReference: null,
      environmentReference: null,
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Reference-only prompt identity.",
  },
  {
    profileId: "profile-prompt-technical-datasheet",
    profileType: "prompt",
    organizationId: "led-display-warehouse",
    profileName: "Technical Datasheet Prompt",
    description: "Prompt identity for technical datasheet outputs.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: false,
    references: {
      credentialReference: null,
      workflowReference: null,
      promptReference: "promptref-technical-datasheet-v1",
      providerReference: "provider-openai-text",
      brandReference: "brandref-ledw-core",
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: "profile-seo-ledw-default",
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: null,
      typographyReference: null,
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: null,
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: "contractref-prompt-tech-input",
      outputContractReference: "contractref-prompt-tech-output",
      retryPolicyReference: null,
      executionTimeoutReference: null,
      environmentReference: null,
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Can override inherited prompt profile at product level.",
  },
  {
    profileId: "profile-image-apple-product",
    profileType: "image",
    organizationId: "led-display-warehouse",
    profileName: "Apple Product Image Style",
    description: "Reusable image-generation style profile reference for product renderings.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: true,
    references: {
      credentialReference: null,
      workflowReference: null,
      promptReference: "imgpromptref-apple-product",
      providerReference: "provider-openai-image",
      brandReference: "brandref-ledw-core",
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: "palette-neutral-light",
      typographyReference: "type-modern-sans",
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: "assetref-image-style-apple-product",
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: "contractref-image-input-v1",
      outputContractReference: "contractref-image-output-v1",
      retryPolicyReference: "retrypolicy-standard-3",
      executionTimeoutReference: "timeout-policy-60s",
      environmentReference: "environment-production",
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Image generation references only. No generation in GCP.",
  },
  {
    profileId: "profile-image-industrial",
    profileType: "image",
    organizationId: "led-display-warehouse",
    profileName: "Industrial Image Style",
    description: "Reusable industrial visual style references.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: false,
    references: {
      credentialReference: null,
      workflowReference: null,
      promptReference: "imgpromptref-industrial",
      providerReference: "provider-openai-image",
      brandReference: "brandref-ledw-core",
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: "palette-industrial-metal",
      typographyReference: "type-industrial-sans",
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: "assetref-image-style-industrial",
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: "contractref-image-input-v1",
      outputContractReference: "contractref-image-output-v1",
      retryPolicyReference: "retrypolicy-standard-3",
      executionTimeoutReference: "timeout-policy-60s",
      environmentReference: "environment-production",
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Supports industrial scene style references.",
  },
  {
    profileId: "profile-image-lifestyle",
    profileType: "image",
    organizationId: "led-display-warehouse",
    profileName: "Lifestyle Image Style",
    description: "Reusable lifestyle visual style references.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: false,
    references: {
      credentialReference: null,
      workflowReference: null,
      promptReference: "imgpromptref-lifestyle",
      providerReference: "provider-openai-image",
      brandReference: "brandref-ledw-core",
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: "palette-lifestyle-soft",
      typographyReference: "type-lifestyle-serif",
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: "assetref-image-style-lifestyle",
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: "contractref-image-input-v1",
      outputContractReference: "contractref-image-output-v1",
      retryPolicyReference: "retrypolicy-standard-3",
      executionTimeoutReference: "timeout-policy-60s",
      environmentReference: "environment-production",
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Supports lifestyle scene style references.",
  },
  {
    profileId: "profile-seo-ledw-default",
    profileType: "seo",
    organizationId: "led-display-warehouse",
    profileName: "LEDW SEO Default",
    description: "Default SEO strategy references.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: true,
    references: {
      credentialReference: null,
      workflowReference: null,
      promptReference: null,
      providerReference: null,
      brandReference: "brandref-ledw-core",
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      analyticsProfileReference: null,
      titleStrategyReference: "titlestrategy-ledw-product-v1",
      metaStrategyReference: "metastrategy-ledw-product-v1",
      schemaReference: "schemaref-product-ledw-v1",
      openGraphReference: "ogref-ledw-product-v1",
      slugStrategyReference: "slugstrategy-ledw-kebab-v1",
      canonicalPolicyReference: "canonical-policy-site-primary",
      logoReference: null,
      colorPaletteReference: null,
      typographyReference: null,
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: null,
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: "yoast-ledw-default",
      inputContractReference: null,
      outputContractReference: null,
      retryPolicyReference: null,
      executionTimeoutReference: null,
      environmentReference: null,
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "SEO references only. No generation.",
  },
  {
    profileId: "profile-brand-ledw-default",
    profileType: "brand",
    organizationId: "led-display-warehouse",
    profileName: "LEDW Brand Default",
    description: "Brand identity references.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: true,
    references: {
      credentialReference: null,
      workflowReference: null,
      promptReference: null,
      providerReference: null,
      brandReference: "brandref-ledw-core",
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: "assetref-ledw-logo-primary",
      colorPaletteReference: "palette-ledw-core",
      typographyReference: "type-ledw-primary",
      voiceReference: "voice-ledw-formal-technical",
      defaultCtaReference: "cta-ledw-contact-sales",
      assetReference: "assetref-ledw-brand-kit-v1",
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: null,
      outputContractReference: null,
      retryPolicyReference: null,
      executionTimeoutReference: null,
      environmentReference: null,
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Brand assets are references only.",
  },
  {
    profileId: "profile-analytics-ledw-default",
    profileType: "analytics",
    organizationId: "led-display-warehouse",
    profileName: "LEDW Analytics Default",
    description: "Analytics provider and contract references.",
    status: "active",
    enabled: true,
    version: "1.0.0",
    assignedSiteIds: ["site-led-display-warehouse-production"],
    defaultForOrganization: true,
    references: {
      credentialReference: "credref-ledw-analytics-prod",
      workflowReference: null,
      promptReference: null,
      providerReference: "provider-ga4",
      brandReference: null,
      workflowProfileReference: null,
      wordpressProfileReference: null,
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      analyticsProfileReference: null,
      titleStrategyReference: null,
      metaStrategyReference: null,
      schemaReference: null,
      openGraphReference: null,
      slugStrategyReference: null,
      canonicalPolicyReference: null,
      logoReference: null,
      colorPaletteReference: null,
      typographyReference: null,
      voiceReference: null,
      defaultCtaReference: null,
      assetReference: null,
      baseUrlReference: null,
      authorReference: null,
      categoryReference: null,
      postStatusReference: null,
      featuredImagePolicyReference: null,
      imageInsertionPolicyReference: null,
      yoastPolicyReference: null,
      inputContractReference: "contractref-analytics-input-v1",
      outputContractReference: "contractref-analytics-output-v1",
      retryPolicyReference: "retrypolicy-standard-3",
      executionTimeoutReference: "timeout-policy-15s",
      environmentReference: "environment-production",
    },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Analytics references only.",
  },
];

export const FOUNDATION_INTEGRATION_PROFILE_ASSIGNMENTS: readonly IntegrationProfileAssignmentRecord[] = [
  {
    assignmentId: "profile-assignment-site-publishing-ledw",
    organizationId: "led-display-warehouse",
    targetType: "site",
    targetId: "site-led-display-warehouse-production",
    siteId: "site-led-display-warehouse-production",
    profileType: "publishing",
    profileId: "profile-publishing-ledw-default",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Default publishing profile for primary site.",
  },
  {
    assignmentId: "profile-assignment-site-wordpress-ledw",
    organizationId: "led-display-warehouse",
    targetType: "site",
    targetId: "site-led-display-warehouse-production",
    siteId: "site-led-display-warehouse-production",
    profileType: "wordpress",
    profileId: "profile-wordpress-ledw-default",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: null,
  },
  {
    assignmentId: "profile-assignment-site-workflow-ledw",
    organizationId: "led-display-warehouse",
    targetType: "site",
    targetId: "site-led-display-warehouse-production",
    siteId: "site-led-display-warehouse-production",
    profileType: "workflow",
    profileId: "profile-workflow-ledw-default",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: null,
  },
  {
    assignmentId: "profile-assignment-site-prompt-ledw",
    organizationId: "led-display-warehouse",
    targetType: "site",
    targetId: "site-led-display-warehouse-production",
    siteId: "site-led-display-warehouse-production",
    profileType: "prompt",
    profileId: "profile-prompt-commercial-product",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: null,
  },
  {
    assignmentId: "profile-assignment-site-image-ledw",
    organizationId: "led-display-warehouse",
    targetType: "site",
    targetId: "site-led-display-warehouse-production",
    siteId: "site-led-display-warehouse-production",
    profileType: "image",
    profileId: "profile-image-apple-product",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: null,
  },
  {
    assignmentId: "profile-assignment-site-seo-ledw",
    organizationId: "led-display-warehouse",
    targetType: "site",
    targetId: "site-led-display-warehouse-production",
    siteId: "site-led-display-warehouse-production",
    profileType: "seo",
    profileId: "profile-seo-ledw-default",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: null,
  },
  {
    assignmentId: "profile-assignment-site-brand-ledw",
    organizationId: "led-display-warehouse",
    targetType: "site",
    targetId: "site-led-display-warehouse-production",
    siteId: "site-led-display-warehouse-production",
    profileType: "brand",
    profileId: "profile-brand-ledw-default",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: null,
  },
  {
    assignmentId: "profile-assignment-site-analytics-ledw",
    organizationId: "led-display-warehouse",
    targetType: "site",
    targetId: "site-led-display-warehouse-production",
    siteId: "site-led-display-warehouse-production",
    profileType: "analytics",
    profileId: "profile-analytics-ledw-default",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: null,
  },
  {
    assignmentId: "profile-assignment-product-indoor-prompt",
    organizationId: "led-display-warehouse",
    targetType: "product",
    targetId: "prod-indoor-led-video-wall",
    siteId: "site-led-display-warehouse-production",
    profileType: "prompt",
    profileId: "profile-prompt-technical-datasheet",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Product-specific prompt override.",
  },
  {
    assignmentId: "profile-assignment-product-indoor-image",
    organizationId: "led-display-warehouse",
    targetType: "product",
    targetId: "prod-indoor-led-video-wall",
    siteId: "site-led-display-warehouse-production",
    profileType: "image",
    profileId: "profile-image-industrial",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Product-specific image style override.",
  },
  {
    assignmentId: "profile-assignment-category-led-seo",
    organizationId: "led-display-warehouse",
    targetType: "category",
    targetId: "cat-led-displays",
    siteId: "site-led-display-warehouse-production",
    profileType: "seo",
    profileId: "profile-seo-ledw-default",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Category SEO reference assignment.",
  },
  {
    assignmentId: "profile-assignment-page-template-prompt",
    organizationId: "led-display-warehouse",
    targetType: "page_template",
    targetId: "landing-page-default",
    siteId: "site-led-display-warehouse-production",
    profileType: "prompt",
    profileId: "profile-prompt-commercial-product",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Future page object profile assignment reference.",
  },
  {
    assignmentId: "profile-assignment-blog-template-prompt",
    organizationId: "led-display-warehouse",
    targetType: "blog_template",
    targetId: "blog-post-default",
    siteId: "site-led-display-warehouse-production",
    profileType: "prompt",
    profileId: "profile-prompt-commercial-product",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Future blog object profile assignment reference.",
  },
  {
    assignmentId: "profile-assignment-media-hero-image",
    organizationId: "led-display-warehouse",
    targetType: "media",
    targetId: "media-hero-banner-template",
    siteId: "site-led-display-warehouse-production",
    profileType: "image",
    profileId: "profile-image-lifestyle",
    inherited: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Media profile assignment reference.",
  },
];
