import type {
  InventoryCountRecord,
  InventoryLocationConfiguration,
  InventoryMovementRecord,
  InventoryReservationRecord,
  InventoryStockRecord,
} from "./types";

const CREATED_AT = "2026-07-29T00:00:00.000Z";

export const FOUNDATION_INVENTORY_LOCATIONS: readonly InventoryLocationConfiguration[] = [
  {
    locationId: "loc-ssi-main-warehouse",
    organizationId: "led-display-warehouse",
    siteId: "site-led-display-warehouse-production",
    locationName: "SSI Main Warehouse",
    displayName: "SSI Main Warehouse",
    locationCode: "SSI-WH-01",
    locationType: "warehouse",
    addressReference: null,
    timeZone: null,
    lifecycleState: "active",
    healthStatus: "operational",
    enabled: true,
    fulfillmentCapable: true,
    reservationCapable: true,
    receivingCapable: true,
    shippingCapable: true,
    defaultLocation: true,
    parentLocationId: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Development fixture, non-production inventory location.",
  },
  {
    locationId: "loc-ledw-virtual-inventory",
    organizationId: "led-display-warehouse",
    siteId: "site-led-display-warehouse-production",
    locationName: "LED Display Warehouse Virtual Inventory",
    displayName: "Virtual Inventory",
    locationCode: "LEDW-VIRTUAL-01",
    locationType: "virtual",
    addressReference: null,
    timeZone: null,
    lifecycleState: "active",
    healthStatus: "operational",
    enabled: true,
    fulfillmentCapable: false,
    reservationCapable: true,
    receivingCapable: false,
    shippingCapable: false,
    defaultLocation: false,
    parentLocationId: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Development fixture, non-production virtual inventory location.",
  },
  {
    locationId: "loc-damaged-inspection-hold",
    organizationId: "led-display-warehouse",
    siteId: "site-led-display-warehouse-production",
    locationName: "Damaged and Inspection Hold",
    displayName: "Damaged and Hold",
    locationCode: "LEDW-DMG-01",
    locationType: "damaged_goods",
    addressReference: null,
    timeZone: null,
    lifecycleState: "active",
    healthStatus: "degraded",
    enabled: true,
    fulfillmentCapable: false,
    reservationCapable: false,
    receivingCapable: true,
    shippingCapable: false,
    defaultLocation: false,
    parentLocationId: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Development fixture, non-production damaged/hold location.",
  },
  {
    locationId: "loc-in-transit",
    organizationId: "led-display-warehouse",
    siteId: null,
    locationName: "In Transit",
    displayName: "In Transit",
    locationCode: "LEDW-TRANSIT-01",
    locationType: "transit",
    addressReference: null,
    timeZone: null,
    lifecycleState: "active",
    healthStatus: "unknown",
    enabled: true,
    fulfillmentCapable: false,
    reservationCapable: false,
    receivingCapable: true,
    shippingCapable: true,
    defaultLocation: false,
    parentLocationId: null,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
    notes: "Development fixture, non-production transit location.",
  },
];

export const FOUNDATION_INVENTORY_STOCK: readonly InventoryStockRecord[] = [
  {
    inventoryRecordId: "stock-prod-indoor-led-video-wall-ssi",
    organizationId: "led-display-warehouse",
    productId: "prod-indoor-led-video-wall",
    locationId: "loc-ssi-main-warehouse",
    siteId: "site-led-display-warehouse-production",
    skuSnapshot: "LEDW-INDOOR-WALL",
    unitOfMeasure: "ea",
    onHandQuantity: 24,
    reservedQuantity: 4,
    availableQuantity: 20,
    incomingQuantity: 5,
    allocatedQuantity: 0,
    damagedQuantity: 0,
    inspectionHoldQuantity: 0,
    backorderedQuantity: 0,
    reorderPoint: 10,
    reorderQuantity: 20,
    safetyStock: 6,
    maximumStock: null,
    stockStatus: "in_stock",
    lastCountedAt: null,
    lastMovementAt: null,
    version: 1,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    inventoryRecordId: "stock-prod-outdoor-led-video-wall-ssi",
    organizationId: "led-display-warehouse",
    productId: "prod-outdoor-led-video-wall",
    locationId: "loc-ssi-main-warehouse",
    siteId: "site-led-display-warehouse-production",
    skuSnapshot: "LEDW-OUTDOOR-WALL",
    unitOfMeasure: "ea",
    onHandQuantity: 6,
    reservedQuantity: 1,
    availableQuantity: 5,
    incomingQuantity: 0,
    allocatedQuantity: 0,
    damagedQuantity: 0,
    inspectionHoldQuantity: 0,
    backorderedQuantity: 0,
    reorderPoint: 8,
    reorderQuantity: 15,
    safetyStock: 4,
    maximumStock: null,
    stockStatus: "low_stock",
    lastCountedAt: null,
    lastMovementAt: null,
    version: 1,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    inventoryRecordId: "stock-prod-transparent-oled-display-virtual",
    organizationId: "led-display-warehouse",
    productId: "prod-transparent-oled-display",
    locationId: "loc-ledw-virtual-inventory",
    siteId: "site-led-display-warehouse-production",
    skuSnapshot: "LEDW-TRANSPARENT-OLED",
    unitOfMeasure: "ea",
    onHandQuantity: 0,
    reservedQuantity: 0,
    availableQuantity: 0,
    incomingQuantity: 2,
    allocatedQuantity: 0,
    damagedQuantity: 0,
    inspectionHoldQuantity: 0,
    backorderedQuantity: 0,
    reorderPoint: 2,
    reorderQuantity: 4,
    safetyStock: 1,
    maximumStock: null,
    stockStatus: "incoming",
    lastCountedAt: null,
    lastMovementAt: null,
    version: 1,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
];

export const FOUNDATION_INVENTORY_MOVEMENTS: readonly InventoryMovementRecord[] = [];
export const FOUNDATION_INVENTORY_RESERVATIONS: readonly InventoryReservationRecord[] = [];
export const FOUNDATION_INVENTORY_COUNTS: readonly InventoryCountRecord[] = [];
