export const MARKET_INTELLIGENCE_CONTRACT = "site-market-intelligence-v1" as const;
export const MARKET_PRODUCT_OPPORTUNITY_CONTRACT = "site-market-product-opportunity-v1" as const;
export const CROSS_SELL_GRAPH_CONTRACT = "site-market-cross-sell-graph-v1" as const;
export const SITE_OPPORTUNITY_BLUEPRINT_CONTRACT = "site-opportunity-blueprint-v1" as const;

export type MarketSignalClass = "VERTICAL_PRESENCE" | "INFRASTRUCTURE_GROWTH" | "VENUE_ECOSYSTEM" | "EDUCATION_ECOSYSTEM" | "SPORTS_ECOSYSTEM" | "MUSEUM_ATTRACTION_ECOSYSTEM" | "HOSPITALITY_ECOSYSTEM" | "CORPORATE_DEVELOPMENT" | "EVENTS_EXPERIENTIAL" | "OUTDOOR_ENVIRONMENT" | "CLIMATE_EXPOSURE" | "BUILDING_ACTIVITY" | "TECHNOLOGY_ADOPTION" | "PUBLIC_SECTOR" | "CONVENTION_TOURISM" | "COMMERCIAL_REAL_ESTATE" | (string & {});
export type OpportunityConfidence = "HIGH" | "MEDIUM" | "LOW" | "INSUFFICIENT_EVIDENCE";
export type RecommendedUse = "SITE_PRIMARY" | "SITE_SECONDARY" | "CAMPAIGN_CANDIDATE" | "PAGE_PRIMARY" | "PAGE_SUPPORTING" | "CROSS_SELL" | "DO_NOT_USE";
export type MarketIdentity = { marketId: string; geography: { city: string | null; state: string; region: string; countryCode: string }; scope: string };
export type MarketEvidence = { evidenceId: string; url: string; publisher: string; sourceClass: "GOVERNMENT" | "OFFICIAL_INSTITUTION" | "OFFICIAL_VENUE" | "OWNER_AUTHORITY" | "APPROVED_CATALOG"; observedClaim: string; retrievedAt: string; validThrough: string; httpStatus: number };
export type MarketSignal = { signalId: string; signalClass: MarketSignalClass; statement: string; buyerVerticals: readonly string[]; evidenceIds: readonly string[]; evidenceStrength: "STRONG" | "MODERATE" | "WEAK"; freshness: "CURRENT" | "STALE" | "RESEARCH_REQUIRED" };
export type SiteMarketIntelligence = { contract: typeof MARKET_INTELLIGENCE_CONTRACT; schemaVersion: 1; intelligenceId: string; organizationId: string; market: MarketIdentity; researchRevision: number; evidence: readonly MarketEvidence[]; signals: readonly MarketSignal[]; competitiveIntensity: "HIGH" | "MEDIUM" | "LOW" | "NOT_EVALUATED"; createdAt: string; provenance: string };
export type CatalogAuthorityItem = { catalogItemId: string; organizationId: string; siteId: string | null; name: string; kind: "PRODUCT" | "SERVICE" | "CAPABILITY" | "SITE_SOLUTION"; authorityState: "APPROVED" | "UNAPPROVED"; authorityReference: string | null; supportedApplications: readonly string[]; buyerVerticals: readonly string[] };
export type MarketApplicationMapping = { applicationId: string; signalIds: readonly string[]; state: "SUPPORTED" | "INSUFFICIENT_EVIDENCE"; rationale: string };
export type OpportunityScoreComponent = { dimension: "MARKET_EVIDENCE_STRENGTH" | "VERTICAL_FIT" | "APPLICATION_FIT" | "PRODUCT_FIT" | "LOCAL_CONDITION_FIT" | "COMMERCIAL_INTENT" | "CATALOG_AUTHORITY_CONFIDENCE"; value: Exclude<OpportunityConfidence, "INSUFFICIENT_EVIDENCE"> | "INSUFFICIENT"; rationale: string; evidenceIds: readonly string[] };
export type SiteMarketProductOpportunity = { contract: typeof MARKET_PRODUCT_OPPORTUNITY_CONTRACT; schemaVersion: 1; opportunityId: string; organizationId: string; market: MarketIdentity; buyerVertical: string; signalIds: readonly string[]; applicationId: string; catalogItemId: string | null; catalogAuthorityReference: string | null; whyMarket: string; whyBuyer: string; whyApplication: string; whyProduct: string; whyConfidence: string; confidence: OpportunityConfidence; scoreComponents: readonly OpportunityScoreComponent[]; recommendedUsage: readonly RecommendedUse[]; crossSellAdjacencyIds: readonly string[]; freshness: "CURRENT" | "STALE" | "RESEARCH_REQUIRED"; evidenceIds: readonly string[]; risks: readonly string[]; createdAt: string };
export type MarketCrossSellGraph = { contract: typeof CROSS_SELL_GRAPH_CONTRACT; schemaVersion: 1; graphId: string; organizationId: string; marketId: string; edges: readonly { adjacencyId: string; fromCatalogItemId: string; toCatalogItemId: string; applicationId: string; reasonType: "SAME_APPLICATION" | "SAME_BUYER_VERTICAL" | "SAME_PROJECT_PHASE" | "SAME_ENVIRONMENT" | "COMPLEMENTARY_HARDWARE" | "UPSTREAM_DOWNSTREAM_SOLUTION" | "SAME_PURCHASING_INTENT"; reason: string; authorityReferences: readonly string[]; confidence: OpportunityConfidence }[]; createdAt: string };
export type SiteOpportunityBlueprint = { contract: typeof SITE_OPPORTUNITY_BLUEPRINT_CONTRACT; schemaVersion: 1; blueprintId: string; organizationId: string; market: MarketIdentity; catalogScope: readonly string[]; priorityProducts: readonly string[]; priorityVerticals: readonly string[]; applications: readonly string[]; pageArchitecture: readonly string[]; internalLinkRecommendations: readonly { from: string; to: string; reason: string }[]; conversionStrategy: readonly string[]; mediaStrategy: readonly string[]; themeContextStrategy: readonly string[]; evidence: readonly MarketEvidence[]; evidenceIds: readonly string[]; confidence: OpportunityConfidence; freshness: "CURRENT" | "STALE" | "RESEARCH_REQUIRED"; mutationAuthorized: false; createdAt: string };
export type CampaignDiscoveryRecommendation = { marketId: string; productId: string; applicationId: string; targetBuyer: string; evidenceIds: readonly string[]; confidence: OpportunityConfidence; recommendedScope: string; geographyGranularity: "REGION" | "STATE" | "CITY"; reason: string; risks: readonly string[]; ownerApprovalRequired: true; campaignMutationAuthorized: false };
export type PageStrategyRecommendation = { pageId: string; primaryApplication: string | null; supportingApplications: readonly string[]; crossSellCatalogItemIds: readonly string[]; rejectedAdjacencies: readonly { applicationId: string; reason: string }[]; internalLinkIds: readonly string[]; localAuthorityLinkIds: readonly string[]; mediaRoles: readonly string[]; ctaIntent: string; compositionAuthorityPreserved: true; mutationAuthorized: false };

const required = (value: string, code: string) => { if (!value.trim()) throw new Error(code); return value.trim(); };
const freshness = (evidence: readonly MarketEvidence[], now: string) => evidence.length === 0 ? "RESEARCH_REQUIRED" as const : evidence.some((item) => Date.parse(item.validThrough) < Date.parse(now)) ? "STALE" as const : "CURRENT" as const;
const confidenceRank: Record<OpportunityConfidence | "INSUFFICIENT", number> = { INSUFFICIENT_EVIDENCE: 0, INSUFFICIENT: 0, LOW: 1, MEDIUM: 2, HIGH: 3 };

export function validateMarketIntelligence(intelligence: SiteMarketIntelligence, now = new Date().toISOString()): SiteMarketIntelligence {
  required(intelligence.intelligenceId, "MARKET_INTELLIGENCE_ID_REQUIRED"); required(intelligence.organizationId, "MARKET_ORGANIZATION_REQUIRED"); required(intelligence.market.marketId, "MARKET_ID_REQUIRED");
  const ids = new Set(intelligence.evidence.map((item) => item.evidenceId)); for (const item of intelligence.evidence) { new URL(item.url); if (item.httpStatus < 200 || item.httpStatus >= 400 || !item.observedClaim.trim() || !Number.isFinite(Date.parse(item.validThrough))) throw new Error("MARKET_EVIDENCE_INVALID"); }
  for (const signal of intelligence.signals) { if (!signal.evidenceIds.length || signal.evidenceIds.some((id) => !ids.has(id))) throw new Error("MARKET_SIGNAL_PROVENANCE_REQUIRED"); const sources = intelligence.evidence.filter((item) => signal.evidenceIds.includes(item.evidenceId)); const expected = freshness(sources, now); if (signal.freshness !== expected) throw new Error("MARKET_SIGNAL_FRESHNESS_INVALID"); }
  return structuredClone(intelligence);
}

export function mapMarketSignalsToApplications(input: { intelligence: SiteMarketIntelligence; rules: readonly { applicationId: string; requiredSignalClasses: readonly MarketSignalClass[]; rationale: string }[]; now?: string }): MarketApplicationMapping[] {
  const intelligence = validateMarketIntelligence(input.intelligence, input.now); return input.rules.map((rule) => { const signals = intelligence.signals.filter((signal) => signal.freshness === "CURRENT" && rule.requiredSignalClasses.includes(signal.signalClass)); return { applicationId: rule.applicationId, signalIds: signals.map((signal) => signal.signalId), state: rule.requiredSignalClasses.every((type) => signals.some((signal) => signal.signalClass === type)) ? "SUPPORTED" : "INSUFFICIENT_EVIDENCE", rationale: rule.rationale }; });
}

function deriveConfidence(components: readonly OpportunityScoreComponent[]): OpportunityConfidence { if (components.some((item) => item.value === "INSUFFICIENT")) return "INSUFFICIENT_EVIDENCE"; const values = components.map((item) => confidenceRank[item.value]); const minimum = Math.min(...values); const average = values.reduce((sum, value) => sum + value, 0) / values.length; return minimum >= 2 && average >= 2.5 ? "HIGH" : minimum >= 1 && average >= 1.7 ? "MEDIUM" : "LOW"; }

export function createMarketProductOpportunity(input: Omit<SiteMarketProductOpportunity, "contract" | "schemaVersion" | "confidence" | "whyConfidence" | "freshness"> & { intelligence: SiteMarketIntelligence; application: MarketApplicationMapping; catalogItem: CatalogAuthorityItem | null; now?: string }): SiteMarketProductOpportunity {
  const intelligence = validateMarketIntelligence(input.intelligence, input.now); const evidenceIds = new Set(intelligence.evidence.map((item) => item.evidenceId)); if (!input.evidenceIds.length || input.evidenceIds.some((id) => !evidenceIds.has(id)) || input.signalIds.some((id) => !intelligence.signals.some((signal) => signal.signalId === id)) || input.scoreComponents.some((component) => !component.evidenceIds.length || component.evidenceIds.some((id) => !evidenceIds.has(id)))) throw new Error("MARKET_OPPORTUNITY_PROVENANCE_REQUIRED");
  if (/\b(?:leading|best|number one|#1|customer(?:s)? in|installed at|completed project|(?:local|[a-z]+) office)\b/i.test([input.whyMarket, input.whyBuyer, input.whyApplication, input.whyProduct].join(" "))) throw new Error("UNSUPPORTED_MARKET_CLAIM_FORBIDDEN");
  const compatible = Boolean(input.catalogItem?.authorityState === "APPROVED" && input.catalogItem.authorityReference && input.catalogItem.supportedApplications.includes(input.application.applicationId) && (input.catalogItem.buyerVerticals.includes(input.buyerVertical) || input.catalogItem.buyerVerticals.includes("*"))); const components = input.scoreComponents.map((item) => item.dimension === "CATALOG_AUTHORITY_CONFIDENCE" && !compatible ? { ...item, value: "INSUFFICIENT" as const, rationale: "No approved compatible catalog authority is available for this application and buyer." } : item); const confidence = input.application.state === "SUPPORTED" && compatible ? deriveConfidence(components) : "INSUFFICIENT_EVIDENCE";
  const recommendedUsage = confidence === "INSUFFICIENT_EVIDENCE" ? ["DO_NOT_USE" as const] : input.recommendedUsage.filter((item) => item !== "DO_NOT_USE");
  return { contract: MARKET_PRODUCT_OPPORTUNITY_CONTRACT, schemaVersion: 1, opportunityId: input.opportunityId, organizationId: input.organizationId, market: structuredClone(input.market), buyerVertical: input.buyerVertical, signalIds: [...input.signalIds], applicationId: input.application.applicationId, catalogItemId: compatible ? input.catalogItem!.catalogItemId : null, catalogAuthorityReference: compatible ? input.catalogItem!.authorityReference : null, whyMarket: required(input.whyMarket, "MARKET_EXPLANATION_REQUIRED"), whyBuyer: required(input.whyBuyer, "BUYER_EXPLANATION_REQUIRED"), whyApplication: required(input.whyApplication, "APPLICATION_EXPLANATION_REQUIRED"), whyProduct: compatible ? required(input.whyProduct, "PRODUCT_EXPLANATION_REQUIRED") : "No approved compatible catalog item is currently available.", whyConfidence: confidence === "INSUFFICIENT_EVIDENCE" ? "The evidence or approved catalog compatibility chain is incomplete." : `Confidence is ${confidence} because each score dimension is explicit and the weakest supported component is ${components.reduce((lowest, item) => confidenceRank[item.value] < confidenceRank[lowest.value] ? item : lowest).dimension}.`, confidence, scoreComponents: components, recommendedUsage, crossSellAdjacencyIds: [...input.crossSellAdjacencyIds], freshness: intelligence.signals.some((signal) => input.signalIds.includes(signal.signalId) && signal.freshness === "STALE") ? "STALE" : intelligence.signals.some((signal) => input.signalIds.includes(signal.signalId) && signal.freshness === "RESEARCH_REQUIRED") ? "RESEARCH_REQUIRED" : "CURRENT", evidenceIds: [...input.evidenceIds], risks: [...input.risks], createdAt: input.createdAt };
}

export function createCrossSellGraph(input: MarketCrossSellGraph, catalog: readonly CatalogAuthorityItem[]): MarketCrossSellGraph { const approved = new Set(catalog.filter((item) => item.authorityState === "APPROVED").map((item) => item.catalogItemId)); for (const edge of input.edges) if (!approved.has(edge.fromCatalogItemId) || !approved.has(edge.toCatalogItemId) || !edge.reason.trim() || !edge.authorityReferences.length) throw new Error("CROSS_SELL_AUTHORITY_REQUIRED"); return structuredClone(input); }
export function createSiteOpportunityBlueprint(input: Omit<SiteOpportunityBlueprint, "contract" | "schemaVersion" | "mutationAuthorized">): SiteOpportunityBlueprint { const evidenceIds = new Set(input.evidence.map((item) => item.evidenceId)); if (!input.catalogScope.length || !input.evidenceIds.length || input.evidenceIds.some((id) => !evidenceIds.has(id)) || !input.pageArchitecture.length || !input.conversionStrategy.length) throw new Error("SITE_OPPORTUNITY_BLUEPRINT_INCOMPLETE"); return { contract: SITE_OPPORTUNITY_BLUEPRINT_CONTRACT, schemaVersion: 1, ...structuredClone(input), mutationAuthorized: false }; }
export function createCampaignDiscoveryRecommendations(opportunities: readonly SiteMarketProductOpportunity[]): CampaignDiscoveryRecommendation[] { return opportunities.filter((item) => item.confidence === "HIGH" && item.recommendedUsage.includes("CAMPAIGN_CANDIDATE") && item.catalogItemId).map((item) => ({ marketId: item.market.marketId, productId: item.catalogItemId!, applicationId: item.applicationId, targetBuyer: item.buyerVertical, evidenceIds: [...item.evidenceIds], confidence: item.confidence, recommendedScope: item.market.scope, geographyGranularity: item.market.geography.city ? "CITY" : "REGION", reason: `${item.whyMarket} ${item.whyApplication} ${item.whyProduct}`, risks: [...item.risks], ownerApprovalRequired: true, campaignMutationAuthorized: false })); }
export function createPageStrategyRecommendation(input: PageStrategyRecommendation): PageStrategyRecommendation { if (input.primaryApplication && input.rejectedAdjacencies.some((item) => item.applicationId === input.primaryApplication)) throw new Error("PAGE_STRATEGY_CONFLICT"); return structuredClone(input); }
export function createCrossSellRecommendations(input: { currentCatalogItemId: string; applicationId: string; graph: MarketCrossSellGraph }): MarketCrossSellGraph["edges"] { return input.graph.edges.filter((edge) => edge.fromCatalogItemId === input.currentCatalogItemId && edge.applicationId === input.applicationId && edge.confidence !== "INSUFFICIENT_EVIDENCE"); }