import type {
  CommandPaletteAction,
  EnterpriseSearchItem,
  NavigationItem,
} from "./types";

export const FOUNDATION_NAVIGATION_ITEMS: readonly NavigationItem[] = [
  {
    id: "mission-control",
    label: "Mission Control",
    href: "/",
    requiredPermissions: ["workspace:view"],
  },
  {
    id: "companies",
    label: "Companies",
    href: "/companies",
    requiredPermissions: ["workspace:view"],
  },
  {
    id: "sites",
    label: "Sites",
    href: "/sites",
    requiredPermissions: ["sites:read"],
  },
  {
    id: "products",
    label: "Products",
    href: "/products",
    requiredPermissions: ["products:read"],
  },
  {
    id: "categories",
    label: "Categories",
    href: "/categories",
    requiredPermissions: ["products:manage_categories"],
  },
  {
    id: "manufacturers",
    label: "Manufacturers",
    href: "/manufacturers",
    requiredPermissions: ["products:manage_manufacturers"],
  },
  {
    id: "inventory",
    label: "Inventory",
    href: "/inventory",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "customers",
    label: "Customers",
    href: "/customers",
    requiredPermissions: ["customers:read"],
  },
  {
    id: "quotes",
    label: "Quotes",
    href: "/quotes",
    requiredPermissions: ["quotes:read"],
  },
  {
    id: "orders",
    label: "Sales Orders",
    href: "/orders",
    requiredPermissions: ["orders:read"],
  },
  {
    id: "work-orders",
    label: "Work Orders",
    href: "/work-orders",
    requiredPermissions: ["work_orders:read"],
  },
  {
    id: "production-jobs",
    label: "Production Jobs",
    href: "/production-jobs",
    requiredPermissions: ["production_jobs:read"],
  },
  {
    id: "operations",
    label: "Operations",
    href: "/operations",
    requiredPermissions: ["operations:read"],
  },
  {
    id: "profiles",
    label: "Profiles",
    href: "/profiles",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "settings",
    label: "Settings",
    href: "/settings",
    requiredPermissions: ["settings:view"],
  },
  {
    id: "notifications",
    label: "Notifications",
    href: "/notifications",
    requiredPermissions: ["notifications:view"],
  },
  {
    id: "audit",
    label: "Audit",
    href: "/audit",
    requiredPermissions: ["audit:view"],
  },
  {
    id: "search",
    label: "Enterprise Search",
    href: "/search",
    requiredPermissions: ["search:use"],
  },
];

export const FOUNDATION_COMMANDS: readonly CommandPaletteAction[] = [
  {
    id: "open-companies",
    label: "Open Companies",
    description: "Switch to the organization catalog",
    href: "/companies",
    requiredPermissions: ["workspace:view", "command_palette:use"],
  },
  {
    id: "open-sites",
    label: "Open Sites",
    description: "Review multi-site status and readiness",
    href: "/sites",
    requiredPermissions: ["sites:read", "command_palette:use"],
  },
  {
    id: "open-products",
    label: "Open Products",
    description: "Review product catalog foundations and readiness",
    href: "/products",
    requiredPermissions: ["products:read", "command_palette:use"],
  },
  {
    id: "open-new-product",
    label: "Create New Product",
    description: "Open bounded product creation foundation",
    href: "/products/new",
    requiredPermissions: ["products:create", "command_palette:use"],
  },
  {
    id: "open-categories",
    label: "Open Categories",
    description: "Review and govern catalog categories",
    href: "/categories",
    requiredPermissions: ["products:manage_categories", "command_palette:use"],
  },
  {
    id: "open-manufacturers",
    label: "Open Manufacturers",
    description: "Review and govern manufacturer references",
    href: "/manufacturers",
    requiredPermissions: ["products:manage_manufacturers", "command_palette:use"],
  },
  {
    id: "open-inventory",
    label: "Open Inventory",
    description: "View product-location stock and availability",
    href: "/inventory",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-inventory-locations",
    label: "Open Locations",
    description: "Review inventory location states and capabilities",
    href: "/inventory/locations",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-inventory-movements",
    label: "Open Movements",
    description: "Review and govern inventory movement records",
    href: "/inventory/movements",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-inventory-movement-new",
    label: "Create Movement",
    description: "Create a bounded inventory movement",
    href: "/inventory/movements/new",
    requiredPermissions: ["inventory:create_movement", "command_palette:use"],
  },
  {
    id: "open-inventory-reservations",
    label: "Open Reservations",
    description: "View and release inventory reservations",
    href: "/inventory/reservations",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-product-inventory",
    label: "Open Product Inventory",
    description: "Open inventory for a selected product",
    href: "/products",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-customers",
    label: "Open Customers",
    description: "Review customer accounts, contacts, addresses, and readiness",
    href: "/customers",
    requiredPermissions: ["customers:read", "command_palette:use"],
  },
  {
    id: "open-new-customer",
    label: "Create New Customer",
    description: "Open bounded customer account creation foundation",
    href: "/customers/new",
    requiredPermissions: ["customers:create", "command_palette:use"],
  },
  {
    id: "open-customer-contacts",
    label: "Open Customer Contacts",
    description: "Review contact governance records for customer accounts",
    href: "/customers",
    requiredPermissions: ["contacts:read", "command_palette:use"],
  },
  {
    id: "open-customer-addresses",
    label: "Open Customer Addresses",
    description: "Review customer address and site association records",
    href: "/customers",
    requiredPermissions: ["addresses:read", "command_palette:use"],
  },
  {
    id: "open-quotes",
    label: "Open Quotes",
    description: "Review quotation lifecycle, pricing snapshots, and approvals",
    href: "/quotes",
    requiredPermissions: ["quotes:read", "command_palette:use"],
  },
  {
    id: "open-new-quote",
    label: "Create New Quote",
    description: "Create bounded quote records with revision and audit tracking",
    href: "/quotes/new",
    requiredPermissions: ["quotes:create", "command_palette:use"],
  },
  {
    id: "open-quote-audit",
    label: "Open Quote Audit",
    description: "Review quote lifecycle and approval events",
    href: "/quotes",
    requiredPermissions: ["quotes:view_audit", "command_palette:use"],
  },
  {
    id: "open-orders",
    label: "Open Sales Orders",
    description: "Review sales commitments, approvals, releases, and audit timelines",
    href: "/orders",
    requiredPermissions: ["orders:read", "command_palette:use"],
  },
  {
    id: "open-new-order",
    label: "Create Sales Order",
    description: "Create bounded sales order commitments and preserve quote lineage",
    href: "/orders/new",
    requiredPermissions: ["orders:create", "command_palette:use"],
  },
  {
    id: "open-order-audit",
    label: "Open Sales Order Audit",
    description: "Inspect sales order revisions, approvals, and release events",
    href: "/orders",
    requiredPermissions: ["orders:view_audit", "command_palette:use"],
  },
  {
    id: "open-work-orders",
    label: "Open Work Orders",
    description: "Review manufacturing commitments, lifecycle progress, and lineage",
    href: "/work-orders",
    requiredPermissions: ["work_orders:read", "command_palette:use"],
  },
  {
    id: "open-new-work-order",
    label: "Create Work Order",
    description: "Create bounded manufacturing commitments from approved sales orders",
    href: "/work-orders/new",
    requiredPermissions: ["work_orders:create", "command_palette:use"],
  },
  {
    id: "open-work-order-audit",
    label: "Open Work Order Audit",
    description: "Inspect work order revisions, releases, pauses, and cancellations",
    href: "/work-orders",
    requiredPermissions: ["work_orders:view_audit", "command_palette:use"],
  },
  {
    id: "open-production-jobs",
    label: "Open Production Jobs",
    description: "Review authorized execution units and their deterministic lifecycle state",
    href: "/production-jobs",
    requiredPermissions: ["production_jobs:read", "command_palette:use"],
  },
  {
    id: "open-new-production-job",
    label: "Create Production Job",
    description: "Create execution-authorizing production jobs from released work orders",
    href: "/production-jobs/new",
    requiredPermissions: ["production_jobs:create", "command_palette:use"],
  },
  {
    id: "open-production-job-audit",
    label: "Open Production Job Audit",
    description: "Inspect production job revisions, release actions, pauses, and cancellations",
    href: "/production-jobs",
    requiredPermissions: ["production_jobs:view_audit", "command_palette:use"],
  },
  {
    id: "open-operations",
    label: "Open Operations",
    description: "Review manufacturing operations and deterministic lifecycle state",
    href: "/operations",
    requiredPermissions: ["operations:read", "command_palette:use"],
  },
  {
    id: "open-new-operation",
    label: "Create Operation",
    description: "Create an operation from a production job without executing work",
    href: "/operations/new",
    requiredPermissions: ["operations:create", "command_palette:use"],
  },
  {
    id: "open-operation-audit",
    label: "Open Operation Audit",
    description: "Inspect operation revisions, lifecycle events, and lineage",
    href: "/operations",
    requiredPermissions: ["operations:view_audit", "command_palette:use"],
  },
  {
    id: "open-profiles",
    label: "Open Profiles",
    description: "Review reusable integration profiles and readiness",
    href: "/profiles",
    requiredPermissions: ["profiles:read", "command_palette:use"],
  },
  {
    id: "open-publishing-profiles",
    label: "Open Publishing Profiles",
    description: "Review publishing profile assignments and blockers",
    href: "/profiles/publishing",
    requiredPermissions: ["profiles:read", "command_palette:use"],
  },
  {
    id: "open-routings",
    label: "Open Routings",
    description: "Review manufacturing process definitions and version history",
    href: "/routings",
    requiredPermissions: ["routings:read", "command_palette:use"],
  },
  {
    id: "open-new-routing",
    label: "Create Routing",
    description: "Define ordered operation sequences without execution authority",
    href: "/routings/new",
    requiredPermissions: ["routings:create", "command_palette:use"],
  },
  {
    id: "open-routing-audit",
    label: "Open Routing Audit",
    description: "Inspect routing revisions, lifecycle transitions, and version lineage",
    href: "/routings",
    requiredPermissions: ["routings:view_audit", "command_palette:use"],
  },
  {
    id: "operations-search",
    title: "Operations",
    subtitle: "Discrete manufacturing step definitions within production jobs",
    href: "/operations",
    scope: "operations",
  },
  {
    id: "routings-search",
    title: "Routings",
    subtitle: "Repeatable manufacturing process definitions with version lineage",
    href: "/routings",
    scope: "routings",
  },
  {
    id: "open-wordpress-profiles",
    label: "Open WordPress Profiles",
    description: "Review WordPress profile references",
    href: "/profiles/wordpress",
    requiredPermissions: ["profiles:read", "command_palette:use"],
  },
  {
    id: "open-workflow-profiles",
    label: "Open Workflow Profiles",
    description: "Review workflow profile references",
    href: "/profiles/workflows",
    requiredPermissions: ["profiles:read", "command_palette:use"],
  },
  {
    id: "open-settings",
    label: "Open Settings",
    description: "Review workspace and organization settings",
    href: "/settings",
    requiredPermissions: ["settings:view", "command_palette:use"],
  },
  {
    id: "open-new-site",
    label: "Create New Site",
    description: "Open bounded site creation foundation",
    href: "/sites/new",
    requiredPermissions: ["sites:create", "command_palette:use"],
  },
  {
    id: "open-notifications",
    label: "Open Notifications",
    description: "Review organization and system alerts",
    href: "/notifications",
    requiredPermissions: ["notifications:view", "command_palette:use"],
  },
  {
    id: "open-audit",
    label: "Open Audit",
    description: "View governance and lifecycle events",
    href: "/audit",
    requiredPermissions: ["audit:view", "command_palette:use"],
  },
  {
    id: "open-search",
    label: "Open Enterprise Search",
    description: "Search organizations, sites, users, and settings",
    href: "/search",
    requiredPermissions: ["search:use", "command_palette:use"],
  },
];

export const FOUNDATION_SEARCH_INDEX: readonly EnterpriseSearchItem[] = [
  {
    id: "settings-workspace",
    title: "Workspace Settings",
    subtitle: "Govern workspace defaults and operator controls",
    href: "/settings",
    scope: "settings",
    requiredPermissions: ["settings:view"],
  },
  {
    id: "notifications-center",
    title: "Notifications Center",
    subtitle: "Review event alerts and acknowledge notices",
    href: "/notifications",
    scope: "all",
    requiredPermissions: ["notifications:view"],
  },
  {
    id: "audit-view",
    title: "Audit Event Foundation",
    subtitle: "Inspect governance event outcomes",
    href: "/audit",
    scope: "all",
    requiredPermissions: ["audit:view"],
  },
  {
    id: "sites-multi-site",
    title: "Multi-Site Management",
    subtitle: "List and govern site status, health, and readiness",
    href: "/sites",
    scope: "sites",
    requiredPermissions: ["sites:read"],
  },
  {
    id: "sites-new",
    title: "Create Site Foundation",
    subtitle: "Configure non-secret fields for a new site",
    href: "/sites/new",
    scope: "sites",
    requiredPermissions: ["sites:create"],
  },
  {
    id: "products-registry",
    title: "Product Registry",
    subtitle: "Govern products, site assignments, and readiness",
    href: "/products",
    scope: "products",
    resultType: "product",
    supportingIdentifier: "catalog",
    readinessIndicator: "unknown",
    requiredPermissions: ["products:read"],
  },
  {
    id: "products-new",
    title: "Create Product Foundation",
    subtitle: "Register bounded product records with no secret values",
    href: "/products/new",
    scope: "products",
    resultType: "product",
    supportingIdentifier: "create",
    readinessIndicator: "unknown",
    requiredPermissions: ["products:create"],
  },
  {
    id: "categories-registry",
    title: "Category Registry",
    subtitle: "Manage category hierarchy and site assignments",
    href: "/categories",
    scope: "categories",
    resultType: "category",
    supportingIdentifier: "taxonomy",
    readinessIndicator: "unknown",
    requiredPermissions: ["products:manage_categories"],
  },
  {
    id: "manufacturers-registry",
    title: "Manufacturer Registry",
    subtitle: "Manage manufacturer references for catalog products",
    href: "/manufacturers",
    scope: "manufacturers",
    resultType: "manufacturer",
    supportingIdentifier: "partner",
    readinessIndicator: "unknown",
    requiredPermissions: ["products:manage_manufacturers"],
  },
  {
    id: "inventory-registry",
    title: "Inventory Registry",
    subtitle: "Review stock, reservations, and availability",
    href: "/inventory",
    scope: "inventory",
    resultType: "inventory",
    supportingIdentifier: "stock",
    readinessIndicator: "unknown",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "inventory-locations",
    title: "Inventory Locations",
    subtitle: "Manage location capability and lifecycle state",
    href: "/inventory/locations",
    scope: "locations",
    resultType: "location",
    supportingIdentifier: "location",
    readinessIndicator: "unknown",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "inventory-movements",
    title: "Inventory Movements",
    subtitle: "Track receipts, transfers, adjustments, and reversals",
    href: "/inventory/movements",
    scope: "movements",
    resultType: "movement",
    supportingIdentifier: "movement",
    readinessIndicator: "unknown",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "inventory-reservations",
    title: "Inventory Reservations",
    subtitle: "Track and release held stock allocations",
    href: "/inventory/reservations",
    scope: "reservations",
    resultType: "reservation",
    supportingIdentifier: "reservation",
    readinessIndicator: "unknown",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "customers-registry",
    title: "Customer Account Registry",
    subtitle: "Search customer account records and lifecycle readiness",
    href: "/customers",
    scope: "customers",
    resultType: "customer",
    supportingIdentifier: "account",
    readinessIndicator: "unknown",
    requiredPermissions: ["customers:read"],
  },
  {
    id: "customers-new",
    title: "Create Customer Foundation",
    subtitle: "Register bounded customer account records",
    href: "/customers/new",
    scope: "customer_accounts",
    resultType: "customer",
    supportingIdentifier: "create",
    readinessIndicator: "unknown",
    requiredPermissions: ["customers:create"],
  },
  {
    id: "quotes-registry",
    title: "Quote Registry",
    subtitle: "Search quote lifecycle, customer assignment, and commercial status",
    href: "/quotes",
    scope: "quotes",
    resultType: "quote",
    supportingIdentifier: "registry",
    readinessIndicator: "unknown",
    requiredPermissions: ["quotes:read"],
  },
  {
    id: "quotes-new",
    title: "Create Quote Foundation",
    subtitle: "Create bounded quote records with immutable pricing snapshots",
    href: "/quotes/new",
    scope: "quote_registry",
    resultType: "quote",
    supportingIdentifier: "create",
    readinessIndicator: "unknown",
    requiredPermissions: ["quotes:create"],
  },
  {
    id: "quote-lines",
    title: "Quote Line Editor",
    subtitle: "Maintain quote line snapshots and pricing deltas",
    href: "/quotes",
    scope: "quote_lines",
    resultType: "quote_line",
    supportingIdentifier: "lines",
    readinessIndicator: "unknown",
    requiredPermissions: ["quotes:update_lines"],
  },
  {
    id: "quote-revisions",
    title: "Quote Revision Timeline",
    subtitle: "Track revision history and state transitions",
    href: "/quotes",
    scope: "quote_revisions",
    resultType: "quote_revision",
    supportingIdentifier: "revisions",
    readinessIndicator: "unknown",
    requiredPermissions: ["quotes:create_revision"],
  },
  {
    id: "quote-audit",
    title: "Quote Audit Viewer",
    subtitle: "Inspect quote approvals, presentations, and conversion requests",
    href: "/quotes",
    scope: "quote_audit",
    resultType: "quote_audit",
    supportingIdentifier: "audit",
    readinessIndicator: "unknown",
    requiredPermissions: ["quotes:view_audit"],
  },
  {
    id: "orders-registry",
    title: "Sales Order Registry",
    subtitle: "Search sales order lifecycle, quote lineage, and commitment status",
    href: "/orders",
    scope: "orders",
    resultType: "order",
    supportingIdentifier: "registry",
    readinessIndicator: "unknown",
    requiredPermissions: ["orders:read"],
  },
  {
    id: "orders-new",
    title: "Create Sales Order Foundation",
    subtitle: "Create durable sales commitments from accepted quote lineage",
    href: "/orders/new",
    scope: "order_registry",
    resultType: "order",
    supportingIdentifier: "create",
    readinessIndicator: "unknown",
    requiredPermissions: ["orders:create"],
  },
  {
    id: "order-revisions",
    title: "Sales Order Revision History",
    subtitle: "Track controlled revisions and deterministic lifecycle transitions",
    href: "/orders",
    scope: "order_revisions",
    resultType: "order_revision",
    supportingIdentifier: "revisions",
    readinessIndicator: "unknown",
    requiredPermissions: ["orders:revise"],
  },
  {
    id: "order-audit",
    title: "Sales Order Audit Viewer",
    subtitle: "Inspect order approvals, releases, cancellations, and published events",
    href: "/orders",
    scope: "order_audit",
    resultType: "order_audit",
    supportingIdentifier: "audit",
    readinessIndicator: "unknown",
    requiredPermissions: ["orders:view_audit"],
  },
  {
    id: "work-orders-registry",
    title: "Work Order Registry",
    subtitle: "Search manufacturing commitments, lineage, and lifecycle progress",
    href: "/work-orders",
    scope: "work_orders",
    resultType: "work_order",
    supportingIdentifier: "registry",
    readinessIndicator: "unknown",
    requiredPermissions: ["work_orders:read"],
  },
  {
    id: "work-orders-new",
    title: "Create Work Order Foundation",
    subtitle: "Create durable manufacturing commitments from sales order lineage",
    href: "/work-orders/new",
    scope: "work_order_registry",
    resultType: "work_order",
    supportingIdentifier: "create",
    readinessIndicator: "unknown",
    requiredPermissions: ["work_orders:create"],
  },
  {
    id: "work-order-revisions",
    title: "Work Order Revision History",
    subtitle: "Track controlled revisions and deterministic manufacturing transitions",
    href: "/work-orders",
    scope: "work_order_revisions",
    resultType: "work_order_revision",
    supportingIdentifier: "revisions",
    readinessIndicator: "unknown",
    requiredPermissions: ["work_orders:revise"],
  },
  {
    id: "work-order-audit",
    title: "Work Order Audit Viewer",
    subtitle: "Inspect work order lifecycle mutations and versioned enterprise events",
    href: "/work-orders",
    scope: "work_order_audit",
    resultType: "work_order_audit",
    supportingIdentifier: "audit",
    readinessIndicator: "unknown",
    requiredPermissions: ["work_orders:view_audit"],
  },
  {
    id: "production-jobs-registry",
    title: "Production Job Registry",
    subtitle: "Search execution-authorized jobs, upstream lineage, and status progression",
    href: "/production-jobs",
    scope: "production_jobs",
    resultType: "production_job",
    supportingIdentifier: "registry",
    readinessIndicator: "unknown",
    requiredPermissions: ["production_jobs:read"],
  },
  {
    id: "production-jobs-new",
    title: "Create Production Job Foundation",
    subtitle: "Create bounded execution jobs from released work-order authority",
    href: "/production-jobs/new",
    scope: "production_job_registry",
    resultType: "production_job",
    supportingIdentifier: "create",
    readinessIndicator: "unknown",
    requiredPermissions: ["production_jobs:create"],
  },
  {
    id: "production-job-revisions",
    title: "Production Job Revision History",
    subtitle: "Track controlled revisions and deterministic execution-state transitions",
    href: "/production-jobs",
    scope: "production_job_revisions",
    resultType: "production_job_revision",
    supportingIdentifier: "revisions",
    readinessIndicator: "unknown",
    requiredPermissions: ["production_jobs:revise"],
  },
  {
    id: "production-job-audit",
    title: "Production Job Audit Viewer",
    subtitle: "Inspect append-only job audit trails and published execution events",
    href: "/production-jobs",
    scope: "production_job_audit",
    resultType: "production_job_audit",
    supportingIdentifier: "audit",
    readinessIndicator: "unknown",
    requiredPermissions: ["production_jobs:view_audit"],
  },
  {
    id: "customer-contacts-registry",
    title: "Customer Contacts",
    subtitle: "Search customer contact references and communication readiness",
    href: "/customers",
    scope: "customer_contacts",
    resultType: "contact",
    supportingIdentifier: "contact",
    readinessIndicator: "unknown",
    requiredPermissions: ["contacts:read"],
  },
  {
    id: "customer-addresses-registry",
    title: "Customer Addresses",
    subtitle: "Search customer address records and default billing/shipping coverage",
    href: "/customers",
    scope: "customer_addresses",
    resultType: "address",
    supportingIdentifier: "address",
    readinessIndicator: "unknown",
    requiredPermissions: ["addresses:read"],
  },
  {
    id: "profiles-registry",
    title: "Integration Profile Registry",
    subtitle: "Search publishing, WordPress, workflow, prompt, image, SEO, brand, and analytics profiles",
    href: "/profiles",
    scope: "profiles",
    resultType: "profile",
    supportingIdentifier: "configuration",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-publishing",
    title: "Publishing Profiles",
    subtitle: "Search publishing profile composition references",
    href: "/profiles/publishing",
    scope: "publishing_profiles",
    resultType: "profile",
    supportingIdentifier: "publishing",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-wordpress",
    title: "WordPress Profiles",
    subtitle: "Search WordPress base URL and credential references",
    href: "/profiles/wordpress",
    scope: "wordpress_profiles",
    resultType: "profile",
    supportingIdentifier: "wordpress",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-workflows",
    title: "Workflow Profiles",
    subtitle: "Search workflow provider and contract references",
    href: "/profiles/workflows",
    scope: "workflow_profiles",
    resultType: "profile",
    supportingIdentifier: "workflow",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-prompts",
    title: "Prompt Profiles",
    subtitle: "Search reusable prompt identity references",
    href: "/profiles/prompts",
    scope: "prompt_profiles",
    resultType: "profile",
    supportingIdentifier: "prompt",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-images",
    title: "Image Profiles",
    subtitle: "Search reusable image style references",
    href: "/profiles/images",
    scope: "image_profiles",
    resultType: "profile",
    supportingIdentifier: "image",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-seo",
    title: "SEO Profiles",
    subtitle: "Search SEO title, meta, schema, and canonical strategy references",
    href: "/profiles/seo",
    scope: "seo_profiles",
    resultType: "profile",
    supportingIdentifier: "seo",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-brands",
    title: "Brand Profiles",
    subtitle: "Search brand logo, palette, typography, and voice references",
    href: "/profiles/brands",
    scope: "brand_profiles",
    resultType: "profile",
    supportingIdentifier: "brand",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-analytics",
    title: "Analytics Profiles",
    subtitle: "Search analytics provider and contract references",
    href: "/profiles/analytics",
    scope: "analytics_profiles",
    resultType: "profile",
    supportingIdentifier: "analytics",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "organization-registry",
    title: "Organization Context",
    subtitle: "Switch and scope application workspace",
    href: "/companies",
    scope: "organizations",
    requiredPermissions: ["organization:switch"],
  },
];
