import type {
  CommandPaletteAction,
  EnterpriseSearchItem,
  NavigationItem,
} from "./types";

export const FOUNDATION_NAVIGATION_ITEMS: readonly NavigationItem[] = [
  {
    id: "mission-control",
    label: "Mission Control",
    href: "/",
    requiredPermissions: ["workspace:view"],
  },
  {
    id: "companies",
    label: "Companies",
    href: "/companies",
    requiredPermissions: ["workspace:view"],
  },
  {
    id: "sites",
    label: "Sites",
    href: "/sites",
    requiredPermissions: ["sites:read"],
  },
  {
    id: "products",
    label: "Products",
    href: "/products",
    requiredPermissions: ["products:read"],
  },
  {
    id: "categories",
    label: "Categories",
    href: "/categories",
    requiredPermissions: ["products:manage_categories"],
  },
  {
    id: "manufacturers",
    label: "Manufacturers",
    href: "/manufacturers",
    requiredPermissions: ["products:manage_manufacturers"],
  },
  {
    id: "inventory",
    label: "Inventory",
    href: "/inventory",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "customers",
    label: "Customers",
    href: "/customers",
    requiredPermissions: ["customers:read"],
  },
  {
    id: "profiles",
    label: "Profiles",
    href: "/profiles",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "settings",
    label: "Settings",
    href: "/settings",
    requiredPermissions: ["settings:view"],
  },
  {
    id: "notifications",
    label: "Notifications",
    href: "/notifications",
    requiredPermissions: ["notifications:view"],
  },
  {
    id: "audit",
    label: "Audit",
    href: "/audit",
    requiredPermissions: ["audit:view"],
  },
  {
    id: "search",
    label: "Enterprise Search",
    href: "/search",
    requiredPermissions: ["search:use"],
  },
];

export const FOUNDATION_COMMANDS: readonly CommandPaletteAction[] = [
  {
    id: "open-companies",
    label: "Open Companies",
    description: "Switch to the organization catalog",
    href: "/companies",
    requiredPermissions: ["workspace:view", "command_palette:use"],
  },
  {
    id: "open-sites",
    label: "Open Sites",
    description: "Review multi-site status and readiness",
    href: "/sites",
    requiredPermissions: ["sites:read", "command_palette:use"],
  },
  {
    id: "open-products",
    label: "Open Products",
    description: "Review product catalog foundations and readiness",
    href: "/products",
    requiredPermissions: ["products:read", "command_palette:use"],
  },
  {
    id: "open-new-product",
    label: "Create New Product",
    description: "Open bounded product creation foundation",
    href: "/products/new",
    requiredPermissions: ["products:create", "command_palette:use"],
  },
  {
    id: "open-categories",
    label: "Open Categories",
    description: "Review and govern catalog categories",
    href: "/categories",
    requiredPermissions: ["products:manage_categories", "command_palette:use"],
  },
  {
    id: "open-manufacturers",
    label: "Open Manufacturers",
    description: "Review and govern manufacturer references",
    href: "/manufacturers",
    requiredPermissions: ["products:manage_manufacturers", "command_palette:use"],
  },
  {
    id: "open-inventory",
    label: "Open Inventory",
    description: "View product-location stock and availability",
    href: "/inventory",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-inventory-locations",
    label: "Open Locations",
    description: "Review inventory location states and capabilities",
    href: "/inventory/locations",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-inventory-movements",
    label: "Open Movements",
    description: "Review and govern inventory movement records",
    href: "/inventory/movements",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-inventory-movement-new",
    label: "Create Movement",
    description: "Create a bounded inventory movement",
    href: "/inventory/movements/new",
    requiredPermissions: ["inventory:create_movement", "command_palette:use"],
  },
  {
    id: "open-inventory-reservations",
    label: "Open Reservations",
    description: "View and release inventory reservations",
    href: "/inventory/reservations",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-product-inventory",
    label: "Open Product Inventory",
    description: "Open inventory for a selected product",
    href: "/products",
    requiredPermissions: ["inventory:read", "command_palette:use"],
  },
  {
    id: "open-customers",
    label: "Open Customers",
    description: "Review customer accounts, contacts, addresses, and readiness",
    href: "/customers",
    requiredPermissions: ["customers:read", "command_palette:use"],
  },
  {
    id: "open-new-customer",
    label: "Create New Customer",
    description: "Open bounded customer account creation foundation",
    href: "/customers/new",
    requiredPermissions: ["customers:create", "command_palette:use"],
  },
  {
    id: "open-customer-contacts",
    label: "Open Customer Contacts",
    description: "Review contact governance records for customer accounts",
    href: "/customers",
    requiredPermissions: ["contacts:read", "command_palette:use"],
  },
  {
    id: "open-customer-addresses",
    label: "Open Customer Addresses",
    description: "Review customer address and site association records",
    href: "/customers",
    requiredPermissions: ["addresses:read", "command_palette:use"],
  },
  {
    id: "open-profiles",
    label: "Open Profiles",
    description: "Review reusable integration profiles and readiness",
    href: "/profiles",
    requiredPermissions: ["profiles:read", "command_palette:use"],
  },
  {
    id: "open-publishing-profiles",
    label: "Open Publishing Profiles",
    description: "Review publishing profile assignments and blockers",
    href: "/profiles/publishing",
    requiredPermissions: ["profiles:read", "command_palette:use"],
  },
  {
    id: "open-wordpress-profiles",
    label: "Open WordPress Profiles",
    description: "Review WordPress profile references",
    href: "/profiles/wordpress",
    requiredPermissions: ["profiles:read", "command_palette:use"],
  },
  {
    id: "open-workflow-profiles",
    label: "Open Workflow Profiles",
    description: "Review workflow profile references",
    href: "/profiles/workflows",
    requiredPermissions: ["profiles:read", "command_palette:use"],
  },
  {
    id: "open-settings",
    label: "Open Settings",
    description: "Review workspace and organization settings",
    href: "/settings",
    requiredPermissions: ["settings:view", "command_palette:use"],
  },
  {
    id: "open-new-site",
    label: "Create New Site",
    description: "Open bounded site creation foundation",
    href: "/sites/new",
    requiredPermissions: ["sites:create", "command_palette:use"],
  },
  {
    id: "open-notifications",
    label: "Open Notifications",
    description: "Review organization and system alerts",
    href: "/notifications",
    requiredPermissions: ["notifications:view", "command_palette:use"],
  },
  {
    id: "open-audit",
    label: "Open Audit",
    description: "View governance and lifecycle events",
    href: "/audit",
    requiredPermissions: ["audit:view", "command_palette:use"],
  },
  {
    id: "open-search",
    label: "Open Enterprise Search",
    description: "Search organizations, sites, users, and settings",
    href: "/search",
    requiredPermissions: ["search:use", "command_palette:use"],
  },
];

export const FOUNDATION_SEARCH_INDEX: readonly EnterpriseSearchItem[] = [
  {
    id: "settings-workspace",
    title: "Workspace Settings",
    subtitle: "Govern workspace defaults and operator controls",
    href: "/settings",
    scope: "settings",
    requiredPermissions: ["settings:view"],
  },
  {
    id: "notifications-center",
    title: "Notifications Center",
    subtitle: "Review event alerts and acknowledge notices",
    href: "/notifications",
    scope: "all",
    requiredPermissions: ["notifications:view"],
  },
  {
    id: "audit-view",
    title: "Audit Event Foundation",
    subtitle: "Inspect governance event outcomes",
    href: "/audit",
    scope: "all",
    requiredPermissions: ["audit:view"],
  },
  {
    id: "sites-multi-site",
    title: "Multi-Site Management",
    subtitle: "List and govern site status, health, and readiness",
    href: "/sites",
    scope: "sites",
    requiredPermissions: ["sites:read"],
  },
  {
    id: "sites-new",
    title: "Create Site Foundation",
    subtitle: "Configure non-secret fields for a new site",
    href: "/sites/new",
    scope: "sites",
    requiredPermissions: ["sites:create"],
  },
  {
    id: "products-registry",
    title: "Product Registry",
    subtitle: "Govern products, site assignments, and readiness",
    href: "/products",
    scope: "products",
    resultType: "product",
    supportingIdentifier: "catalog",
    readinessIndicator: "unknown",
    requiredPermissions: ["products:read"],
  },
  {
    id: "products-new",
    title: "Create Product Foundation",
    subtitle: "Register bounded product records with no secret values",
    href: "/products/new",
    scope: "products",
    resultType: "product",
    supportingIdentifier: "create",
    readinessIndicator: "unknown",
    requiredPermissions: ["products:create"],
  },
  {
    id: "categories-registry",
    title: "Category Registry",
    subtitle: "Manage category hierarchy and site assignments",
    href: "/categories",
    scope: "categories",
    resultType: "category",
    supportingIdentifier: "taxonomy",
    readinessIndicator: "unknown",
    requiredPermissions: ["products:manage_categories"],
  },
  {
    id: "manufacturers-registry",
    title: "Manufacturer Registry",
    subtitle: "Manage manufacturer references for catalog products",
    href: "/manufacturers",
    scope: "manufacturers",
    resultType: "manufacturer",
    supportingIdentifier: "partner",
    readinessIndicator: "unknown",
    requiredPermissions: ["products:manage_manufacturers"],
  },
  {
    id: "inventory-registry",
    title: "Inventory Registry",
    subtitle: "Review stock, reservations, and availability",
    href: "/inventory",
    scope: "inventory",
    resultType: "inventory",
    supportingIdentifier: "stock",
    readinessIndicator: "unknown",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "inventory-locations",
    title: "Inventory Locations",
    subtitle: "Manage location capability and lifecycle state",
    href: "/inventory/locations",
    scope: "locations",
    resultType: "location",
    supportingIdentifier: "location",
    readinessIndicator: "unknown",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "inventory-movements",
    title: "Inventory Movements",
    subtitle: "Track receipts, transfers, adjustments, and reversals",
    href: "/inventory/movements",
    scope: "movements",
    resultType: "movement",
    supportingIdentifier: "movement",
    readinessIndicator: "unknown",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "inventory-reservations",
    title: "Inventory Reservations",
    subtitle: "Track and release held stock allocations",
    href: "/inventory/reservations",
    scope: "reservations",
    resultType: "reservation",
    supportingIdentifier: "reservation",
    readinessIndicator: "unknown",
    requiredPermissions: ["inventory:read"],
  },
  {
    id: "customers-registry",
    title: "Customer Account Registry",
    subtitle: "Search customer account records and lifecycle readiness",
    href: "/customers",
    scope: "customers",
    resultType: "customer",
    supportingIdentifier: "account",
    readinessIndicator: "unknown",
    requiredPermissions: ["customers:read"],
  },
  {
    id: "customers-new",
    title: "Create Customer Foundation",
    subtitle: "Register bounded customer account records",
    href: "/customers/new",
    scope: "customer_accounts",
    resultType: "customer",
    supportingIdentifier: "create",
    readinessIndicator: "unknown",
    requiredPermissions: ["customers:create"],
  },
  {
    id: "customer-contacts-registry",
    title: "Customer Contacts",
    subtitle: "Search customer contact references and communication readiness",
    href: "/customers",
    scope: "customer_contacts",
    resultType: "contact",
    supportingIdentifier: "contact",
    readinessIndicator: "unknown",
    requiredPermissions: ["contacts:read"],
  },
  {
    id: "customer-addresses-registry",
    title: "Customer Addresses",
    subtitle: "Search customer address records and default billing/shipping coverage",
    href: "/customers",
    scope: "customer_addresses",
    resultType: "address",
    supportingIdentifier: "address",
    readinessIndicator: "unknown",
    requiredPermissions: ["addresses:read"],
  },
  {
    id: "profiles-registry",
    title: "Integration Profile Registry",
    subtitle: "Search publishing, WordPress, workflow, prompt, image, SEO, brand, and analytics profiles",
    href: "/profiles",
    scope: "profiles",
    resultType: "profile",
    supportingIdentifier: "configuration",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-publishing",
    title: "Publishing Profiles",
    subtitle: "Search publishing profile composition references",
    href: "/profiles/publishing",
    scope: "publishing_profiles",
    resultType: "profile",
    supportingIdentifier: "publishing",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-wordpress",
    title: "WordPress Profiles",
    subtitle: "Search WordPress base URL and credential references",
    href: "/profiles/wordpress",
    scope: "wordpress_profiles",
    resultType: "profile",
    supportingIdentifier: "wordpress",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-workflows",
    title: "Workflow Profiles",
    subtitle: "Search workflow provider and contract references",
    href: "/profiles/workflows",
    scope: "workflow_profiles",
    resultType: "profile",
    supportingIdentifier: "workflow",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-prompts",
    title: "Prompt Profiles",
    subtitle: "Search reusable prompt identity references",
    href: "/profiles/prompts",
    scope: "prompt_profiles",
    resultType: "profile",
    supportingIdentifier: "prompt",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-images",
    title: "Image Profiles",
    subtitle: "Search reusable image style references",
    href: "/profiles/images",
    scope: "image_profiles",
    resultType: "profile",
    supportingIdentifier: "image",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-seo",
    title: "SEO Profiles",
    subtitle: "Search SEO title, meta, schema, and canonical strategy references",
    href: "/profiles/seo",
    scope: "seo_profiles",
    resultType: "profile",
    supportingIdentifier: "seo",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-brands",
    title: "Brand Profiles",
    subtitle: "Search brand logo, palette, typography, and voice references",
    href: "/profiles/brands",
    scope: "brand_profiles",
    resultType: "profile",
    supportingIdentifier: "brand",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "profiles-analytics",
    title: "Analytics Profiles",
    subtitle: "Search analytics provider and contract references",
    href: "/profiles/analytics",
    scope: "analytics_profiles",
    resultType: "profile",
    supportingIdentifier: "analytics",
    readinessIndicator: "unknown",
    requiredPermissions: ["profiles:read"],
  },
  {
    id: "organization-registry",
    title: "Organization Context",
    subtitle: "Switch and scope application workspace",
    href: "/companies",
    scope: "organizations",
    requiredPermissions: ["organization:switch"],
  },
];
