import type { VisualAuthorityReference } from "./visual-product-authority";

export const PROJECTORENCLOSURE_OWNER_SOURCE_AUTHORITY_VERSION = "projectorenclosure-owner-source-authority-v1" as const;

export type OwnerSourceClass = "OWNER_DOCUMENT" | "OWNER_SIGNOFF" | "OWNER_SPECIFICATION" | "OWNER_MEASUREMENT" | "OWNER_PHOTOGRAPH" | "OWNER_ARCHIVE" | "UNKNOWN_OWNER_SOURCE";
export type OwnerSourceProduct = "HUSH" | "DEFENDER" | "CLIMATE_CONTROLLED" | "UST_HUSH" | "PROJECTOR_CAGE" | "INTEGRATOR" | "HOMELINE_XS";
export type OwnerFactClass = "IDENTITY" | "MODEL" | "DIMENSIONS" | "WEIGHT" | "CONSTRUCTION" | "COOLING_METHOD" | "AIRFLOW" | "SERVICE_ACCESS" | "DOOR_ACCESS" | "MOUNTING" | "PROJECTOR_FIT" | "ELECTRICAL" | "POWER" | "OPERATING_CONDITIONS" | "ENVIRONMENTAL_LIMITS" | "SECURITY" | "LOCKING" | "INSULATION" | "AC_CLIMATE_CONTROL" | "INSTALLATION" | "COMPATIBILITY" | "OPTIONS" | "CUSTOMIZATION" | "WARRANTY" | "OTHER_VERIFIED_FACT";
export type OwnerFactDisposition = "NEW_VERIFIED" | "CONFIRMS_EXISTING" | "DUPLICATE" | "CONFLICT" | "AMBIGUOUS" | "STALE_OR_SUPERSEDED" | "INSUFFICIENT_EVIDENCE";
export type FamilyAuthorityStatus = "VERIFIED_PRODUCT_AUTHORITY" | "PARTIAL_PRODUCT_AUTHORITY" | "MISSING_PRODUCT_AUTHORITY" | "CONFLICTED_AUTHORITY";

export type OwnerSourceRecord = {
  sourceId: string;
  filename: string;
  sha256: string;
  byteSize: number;
  modifiedAt: string;
  sourceClass: OwnerSourceClass;
  products: readonly OwnerSourceProduct[];
  extractionStatus: "EXTRACTED" | "INVENTORIED" | "DUPLICATE_REGISTERED" | "REJECTED";
  duplicateOf: string | null;
  locator: string;
  notes?: string;
};

export type OwnerAuthorityFact = {
  factId: string;
  product: OwnerSourceProduct;
  scope: string;
  factClass: OwnerFactClass;
  key: string;
  value: string;
  sourceId: string;
  evidenceLocation: string;
  disposition: OwnerFactDisposition;
  prohibitedExtrapolations: readonly string[];
};

export type OwnerAuthorityConflict = {
  conflictId: string;
  product: OwnerSourceProduct;
  fact: string;
  sourceA: string;
  sourceB: string | null;
  disposition: "OWNER_DECISION_REQUIRED" | "IDENTITY_AMBIGUOUS" | "PRESERVE_BOTH_SCOPES";
  remediationImpact: string;
};

const source = (record: OwnerSourceRecord): OwnerSourceRecord => Object.freeze(record);
export const PROJECTORENCLOSURE_OWNER_SOURCES: readonly OwnerSourceRecord[] = Object.freeze([
  source({ sourceId: "owner-pdf:defender-series-specifications", filename: "Defender Series Specifications.pdf", sha256: "aee2163ced4b96dde173285b0a5444007fa212de27500f9e1d0309435721bce6", byteSize: 1434590, modifiedAt: "2024-10-15T15:19:49.4152509Z", sourceClass: "OWNER_SPECIFICATION", products: ["DEFENDER", "CLIMATE_CONTROLLED"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Defender Series Specifications.pdf" }),
  source({ sourceId: "owner-pdf:defender-feature-sheet", filename: "New Defender Feature Sheet.pdf", sha256: "88838e67fc4a8d29b4812974a604ca17d056c049ada7a236c2b36bed7c139e7f", byteSize: 833820, modifiedAt: "2024-10-15T15:19:33.2491586Z", sourceClass: "OWNER_DOCUMENT", products: ["DEFENDER", "CLIMATE_CONTROLLED"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/New Defender Feature Sheet.pdf" }),
  source({ sourceId: "owner-pdf:defender-ac-manual", filename: "Defender Series Climate Control Enclosure AC Manual (EV).pdf", sha256: "089bf40687c68892eb708b4fcb2af30bc943a78a21c7ceca5ddb87851f720916", byteSize: 2949094, modifiedAt: "2024-10-15T15:19:15.3222033Z", sourceClass: "OWNER_DOCUMENT", products: ["DEFENDER", "CLIMATE_CONTROLLED"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Defender Series Climate Control Enclosure AC Manual (EV).pdf" }),
  source({ sourceId: "owner-pdf:defender-large-plus-signoff", filename: "Large+ Defender Series Enclosure Sign-Off.pdf", sha256: "bf141f0e169d815f32e8b10919a6634a09c2f9bca36b3bbd43a1e5ff094d647d", byteSize: 93630, modifiedAt: "2025-07-10T22:09:15.6068633Z", sourceClass: "OWNER_SIGNOFF", products: ["DEFENDER"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Large+ Defender Series Enclosure Sign-Off.pdf" }),
  source({ sourceId: "owner-pdf:defender-ac-measurements", filename: "Projector Enclosure AC Measurements Sign-Off.pdf", sha256: "6b6d765690f7ecb030efc774c0abdfe275f7128d224514a56989e18fa3a35021", byteSize: 1528435, modifiedAt: "2025-08-26T22:49:28.7682007Z", sourceClass: "OWNER_MEASUREMENT", products: ["DEFENDER", "CLIMATE_CONTROLLED"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Projector Enclosure AC Measurements Sign-Off.pdf" }),
  source({ sourceId: "owner-pdf:defender-ac-measurements-copy", filename: "Projector Enclosure AC Measurements Sign-Off (1).pdf", sha256: "6b6d765690f7ecb030efc774c0abdfe275f7128d224514a56989e18fa3a35021", byteSize: 1528435, modifiedAt: "2025-08-26T22:49:43.3898935Z", sourceClass: "OWNER_MEASUREMENT", products: ["DEFENDER", "CLIMATE_CONTROLLED"], extractionStatus: "DUPLICATE_REGISTERED", duplicateOf: "owner-pdf:defender-ac-measurements", locator: "owner-local:Downloads/Projector Enclosure AC Measurements Sign-Off (1).pdf" }),
  source({ sourceId: "owner-image:defender-product-sheet", filename: "Climate Controlled Projector Enclosure.png", sha256: "290709cef3291763150a1d3daf35dd71c649ff5f9c01aa84a650e2c9e07f7d04", byteSize: 2544218, modifiedAt: "2026-06-03T19:36:35.9272543Z", sourceClass: "OWNER_PHOTOGRAPH", products: ["DEFENDER", "CLIMATE_CONTROLLED"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Climate Controlled Projector Enclosure.png" }),
  source({ sourceId: "owner-pdf:hush-enclosures", filename: "Hush enclosures.pdf", sha256: "287fe1a7024c3ea145638737991ee644c18bbedb5af07e6c2d6e408be0dd38c1", byteSize: 257931, modifiedAt: "2026-06-03T18:52:48.5146403Z", sourceClass: "OWNER_SPECIFICATION", products: ["HUSH"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Hush enclosures.pdf" }),
  source({ sourceId: "owner-image:hush-product-sheet", filename: "Hush Projector Enclosure.png", sha256: "91b9bc544bf7f3e810895ed6cea3bb4d9ca331e558cd82b1e5f05bed4046741b", byteSize: 2209357, modifiedAt: "2026-06-03T19:37:53.2319502Z", sourceClass: "OWNER_PHOTOGRAPH", products: ["HUSH"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Hush Projector Enclosure.png" }),
  source({ sourceId: "owner-pdf:ust-hush-drawing-a", filename: "UST CC Enclosure Sign-Off.pdf", sha256: "e7c7de97c7069e9f58cdfa9a39dd08a48bbf1ebb97ec0efaf99aa1dc2cc6cfab", byteSize: 517865, modifiedAt: "2025-02-25T19:42:07.9540680Z", sourceClass: "OWNER_SIGNOFF", products: ["UST_HUSH"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/UST CC Enclosure Sign-Off.pdf" }),
  source({ sourceId: "owner-pdf:ust-hush-drawing-b", filename: "UST Hush Projector Enclosure Sign-Off.pdf", sha256: "58181d6e79b1af5d9e0a04e218242302a8025c8bccdcdffa6ffe1d3911cf7a09", byteSize: 179498, modifiedAt: "2025-05-19T22:56:30.8007976Z", sourceClass: "OWNER_SIGNOFF", products: ["UST_HUSH"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/UST Hush Projector Enclosure Sign-Off.pdf" }),
  source({ sourceId: "owner-pdf:large-projector-cage-ceiling-mount", filename: "Large Projector Cage Ceiling Mount Sign-Off.pdf", sha256: "4f1c3854fc422212ed3c22faea95da7be8f75e2e2ffe34f27fa2e5dce936064a", byteSize: 422881, modifiedAt: "2024-12-23T20:12:14.5372788Z", sourceClass: "OWNER_SIGNOFF", products: ["PROJECTOR_CAGE"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Large Projector Cage Ceiling Mount Sign-Off.pdf" }),
  source({ sourceId: "owner-image:projector-cage-product-sheet", filename: "Projector Cages.png", sha256: "b0b7784a24e3dfe05ed40ad354faff0b1dfbaa0806476c59ffdd93a66cb1b5eb", byteSize: 2057290, modifiedAt: "2026-06-03T19:34:32.7059468Z", sourceClass: "OWNER_PHOTOGRAPH", products: ["PROJECTOR_CAGE"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Projector Cages.png" }),
  source({ sourceId: "owner-pdf:small-integrator-signoff-2025", filename: "2025 Small Integrator Sign-Off.pdf", sha256: "e56194cc5ba69dad6ef036b18af31c2f41d752eb59f0852c9cbd6d3c4dc5413a", byteSize: 1100004, modifiedAt: "2025-01-31T22:31:22.2761023Z", sourceClass: "OWNER_SIGNOFF", products: ["INTEGRATOR"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/2025 Small Integrator Sign-Off.pdf" }),
  source({ sourceId: "owner-pdf:xs-integrator-incomplete-alternate", filename: "XS Integrator Projector Enclosure Overview & Specifications.pdf", sha256: "6a5d30e02be11006ad1ddd53fea1e22b164be6bd2e7864b6727266297899a549", byteSize: 706577, modifiedAt: "2025-10-14T15:52:04.1375820Z", sourceClass: "OWNER_SPECIFICATION", products: ["HOMELINE_XS"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/XS Integrator Projector Enclosure Overview & Specifications.pdf", notes: "STALE_OR_SUPERSEDED: omits the usable-space specification present in the registered XS source and adds no facts." }),
  source({ sourceId: "owner-pdf:homeline-spec-sheet", filename: "Homeline spec sheet.pdf", sha256: "e866b9a66fd188546561ab6c82ee2721135b16d4fcac3913b5e4b4f73b5153bb", byteSize: 1600794, modifiedAt: "2026-06-03T18:43:01.5314061Z", sourceClass: "OWNER_SPECIFICATION", products: ["HOMELINE_XS"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/Homeline Series/Homeline spec sheet.pdf" }),
  source({ sourceId: "owner-pdf:homeline-marketing-sheet", filename: "homeline-projector-enclosure.pdf", sha256: "4bd7208bbdb49a47e23ca2c4d337d2fd993b70f0f1694b60e83e27437ff15bb0", byteSize: 23832, modifiedAt: "2025-10-14T16:36:14.7633790Z", sourceClass: "OWNER_DOCUMENT", products: ["HOMELINE_XS"], extractionStatus: "EXTRACTED", duplicateOf: null, locator: "owner-local:Downloads/homeline-projector-enclosure.pdf" }),
  source({ sourceId: "owner-archive:xsmall-enclosure-photos", filename: "XSmall Enclosure Photos.zip", sha256: "ec1b3f985cae1a68f010ee5cf994e88b816277552fae787155af6db84c9e2fcd", byteSize: 21968488, modifiedAt: "2025-10-14T16:54:26.4584676Z", sourceClass: "OWNER_ARCHIVE", products: ["HOMELINE_XS"], extractionStatus: "INVENTORIED", duplicateOf: null, locator: "owner-local:Downloads/XSmall Enclosure Photos.zip" }),
]);

const fact = (value: OwnerAuthorityFact): OwnerAuthorityFact => Object.freeze(value);
const noInference = ["no universal compatibility", "no direct-rain guarantee", "no unlisted model applicability"] as const;
export const PROJECTORENCLOSURE_OWNER_FACTS: readonly OwnerAuthorityFact[] = Object.freeze([
  fact({ factId: "hush-cooling", product: "HUSH", scope: "HUSH_FAMILY", factClass: "COOLING_METHOD", key: "cooling_method", value: "thermostatic fan cooling", sourceId: "owner-pdf:hush-enclosures", evidenceLocation: "page:1:product-features", disposition: "NEW_VERIFIED", prohibitedExtrapolations: noInference }),
  fact({ factId: "hush-electrical", product: "HUSH", scope: "HUSH_FAMILY", factClass: "ELECTRICAL", key: "power_requirement", value: "120 V", sourceId: "owner-pdf:hush-enclosures", evidenceLocation: "page:1:specifications", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no current draw inferred", "no international voltage inferred"] }),
  fact({ factId: "hush-sound", product: "HUSH", scope: "HUSH_FAMILY", factClass: "OTHER_VERIFIED_FACT", key: "sound_output", value: "sub 10 dBA", sourceId: "owner-pdf:hush-enclosures", evidenceLocation: "page:1:specifications", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no test method inferred", "no guarantee for installed-room noise"] }),
  fact({ factId: "hush-insulation", product: "HUSH", scope: "HUSH_FAMILY", factClass: "INSULATION", key: "insulation", value: "fully insulated", sourceId: "owner-pdf:hush-enclosures", evidenceLocation: "page:1:description", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no thermal rating inferred"] }),
  fact({ factId: "hush-components", product: "HUSH", scope: "HUSH_FAMILY", factClass: "POWER", key: "internal_power", value: "two internal outlets and two internal breakers", sourceId: "owner-pdf:hush-enclosures", evidenceLocation: "page:1:description", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no amperage inferred"] }),
  fact({ factId: "hush-sizes", product: "HUSH", scope: "HUSH_FAMILY", factClass: "PROJECTOR_FIT", key: "maximum_projector_sizes", value: "Small 14x12x6 in; Medium 18x20x9 in; Medium+ 24x22x10 in; Large 24x32x10 in", sourceId: "owner-pdf:hush-enclosures", evidenceLocation: "page:1:sizes-table", disposition: "NEW_VERIFIED", prohibitedExtrapolations: noInference }),
  fact({ factId: "defender-identity", product: "DEFENDER", scope: "DEFENDER_FAMILY", factClass: "IDENTITY", key: "product_role", value: "climate-controlled insulated closed-loop projector enclosure family", sourceId: "owner-pdf:defender-series-specifications", evidenceLocation: "page:1:description", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no universal environment guarantee", "no model-independent sizing"] }),
  fact({ factId: "defender-models", product: "DEFENDER", scope: "DEFENDER_FAMILY", factClass: "MODEL", key: "models", value: "ENC-CC-SM, ENC-CC-MD, ENC-CC-LG, ENC-CC-LG+, ENC-CC-XL", sourceId: "owner-pdf:defender-series-specifications", evidenceLocation: "page:1:specification-table", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no ENC-AC alias accepted until conflict resolution"] }),
  fact({ factId: "defender-dimensions", product: "DEFENDER", scope: "DEFENDER_MODELS", factClass: "DIMENSIONS", key: "exterior_dimensions_lwh", value: "SM 21.65x22.42x25.57; MD 39.21x27.15x28.83; LG 54.17x35.24x33.44; LG+ 62.64x47.56x41.83; XL 75.25x53.25x46.25 in", sourceId: "owner-pdf:defender-series-specifications", evidenceLocation: "page:1:specification-table", disposition: "NEW_VERIFIED", prohibitedExtrapolations: noInference }),
  fact({ factId: "defender-power", product: "DEFENDER", scope: "DEFENDER_MODELS", factClass: "POWER", key: "power_draw", value: "SM 110V 5A; MD 110V 10A; LG 110V 15A; LG+ 110V 15A; XL 220V 15A; excludes internal outlets", sourceId: "owner-pdf:defender-series-specifications", evidenceLocation: "page:1:specification-table-and-footnote", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no internal outlet load included", "no other voltage inferred"] }),
  fact({ factId: "defender-ac", product: "CLIMATE_CONTROLLED", scope: "DEFENDER_MODELS", factClass: "AC_CLIMATE_CONTROL", key: "ac_and_heating_wattage", value: "AC 500/1500/2500/3500/4500 W by size; heater 400 W for SM through LG+; XL has no heater", sourceId: "owner-pdf:defender-ac-manual", evidenceLocation: "page:2:technical-data", disposition: "CONFIRMS_EXISTING", prohibitedExtrapolations: noInference }),
  fact({ factId: "defender-temperature", product: "CLIMATE_CONTROLLED", scope: "DEFENDER_FAMILY", factClass: "OPERATING_CONDITIONS", key: "working_temperature", value: "-4 F to 131 F", sourceId: "owner-pdf:defender-ac-manual", evidenceLocation: "page:2:technical-data", disposition: "CONFIRMS_EXISTING", prohibitedExtrapolations: ["no projector-specific operating approval", "no guarantee at limits"] }),
  fact({ factId: "defender-ip55", product: "DEFENDER", scope: "DEFENDER_FAMILY", factClass: "ENVIRONMENTAL_LIMITS", key: "ip_rating", value: "IP55 / IP55 Equivalent", sourceId: "owner-pdf:defender-series-specifications", evidenceLocation: "page:1:specification-table", disposition: "CONFLICT", prohibitedExtrapolations: ["do not state IP65", "do not omit Equivalent qualifier where source uses it"] }),
  fact({ factId: "defender-warranty", product: "CLIMATE_CONTROLLED", scope: "DEFENDER_AC_SYSTEM", factClass: "WARRANTY", key: "warranty_period", value: "one year, subject to listed exclusions", sourceId: "owner-pdf:defender-ac-manual", evidenceLocation: "page:5:warranty-terms", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no enclosure-wide warranty inferred", "no omitted exclusions"] }),
  fact({ factId: "ust-hush-identity", product: "UST_HUSH", scope: "UST_HUSH", factClass: "IDENTITY", key: "product_name", value: "UST Hush Projector Enclosure", sourceId: "owner-pdf:ust-hush-drawing-b", evidenceLocation: "page:1:title-block", disposition: "CONFIRMS_EXISTING", prohibitedExtrapolations: ["not climate-controlled authority"] }),
  fact({ factId: "ust-hush-dimensions", product: "UST_HUSH", scope: "UST_HUSH", factClass: "DIMENSIONS", key: "drawing_dimensions", value: "36.62, 41.00, and 21.44 in principal exterior callouts; 30.66, 29.00, 18.75, 8.00, 7.63, and 6.60 in additional drawing callouts", sourceId: "owner-pdf:ust-hush-drawing-a", evidenceLocation: "page:1:dimensional-drawing", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["dimension axes must remain tied to drawing", "no climate-control features inferred"] }),
  fact({ factId: "cage-identity", product: "PROJECTOR_CAGE", scope: "LARGE_CAGE", factClass: "IDENTITY", key: "product_name", value: "Large Projector Cage Ceiling Mount", sourceId: "owner-pdf:large-projector-cage-ceiling-mount", evidenceLocation: "page:1:title-block", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no theft-prevention guarantee", "no dimensions inferred from blank drawing"] }),
  fact({ factId: "integrator-small-model", product: "INTEGRATOR", scope: "SMALL", factClass: "MODEL", key: "model", value: "ENC-FC-SM", sourceId: "owner-pdf:small-integrator-signoff-2025", evidenceLocation: "page:1:title-block", disposition: "CONFIRMS_EXISTING", prohibitedExtrapolations: noInference }),
  fact({ factId: "integrator-small-dimensions", product: "INTEGRATOR", scope: "SMALL", factClass: "DIMENSIONS", key: "exterior_dimensions_whl", value: "28.25 x 14.5 x 31 in", sourceId: "owner-pdf:small-integrator-signoff-2025", evidenceLocation: "page:1:overall-dimensions", disposition: "CONFIRMS_EXISTING", prohibitedExtrapolations: noInference }),
  fact({ factId: "integrator-small-mounting", product: "INTEGRATOR", scope: "SMALL", factClass: "MOUNTING", key: "unistrut", value: "welded top and removable bottom Unistrut, each 1.75 W x 1.625 H x 22.25 L in", sourceId: "owner-pdf:small-integrator-signoff-2025", evidenceLocation: "page:1:drawing-notes", disposition: "CONFIRMS_EXISTING", prohibitedExtrapolations: noInference }),
  fact({ factId: "homeline-fit", product: "HOMELINE_XS", scope: "HOMELINE", factClass: "PROJECTOR_FIT", key: "fit_envelope", value: "right-side/offset lens; under 7.5 in tall, under 16 in long, 20 in wide or less", sourceId: "owner-pdf:homeline-spec-sheet", evidenceLocation: "page:1:description-and-specifications", disposition: "CONFIRMS_EXISTING", prohibitedExtrapolations: ["no universal compatibility"] }),
  fact({ factId: "homeline-components", product: "HOMELINE_XS", scope: "HOMELINE", factClass: "POWER", key: "power_components", value: "wired power cord, one internal outlet, two internal breakers", sourceId: "owner-pdf:homeline-spec-sheet", evidenceLocation: "page:1:description-and-specifications", disposition: "NEW_VERIFIED", prohibitedExtrapolations: ["no voltage inferred from this source"] }),
]);

export const PROJECTORENCLOSURE_OWNER_VISUALS: readonly VisualAuthorityReference[] = Object.freeze([
  { referenceId: "owner-hush-product-sheet", sourceRole: "OWNER_SUPPLIED_PRODUCT_AUTHORITY", classification: "VERIFIED_PRODUCT_RENDER", owner: "ssi", productId: "prod-ssi-hush-projector-enclosures", productFamily: "family-ssi-hush-projector-enclosures", view: "front-three-quarter", installationContext: null, establishesGeometry: true, establishesFeatures: false, environmentOnly: false, generationReferenceAllowed: true, namedProductRepresentationAllowed: true, verificationStatus: "VERIFIED", sourceUrl: null, durableSourceId: "owner-image:Hush Projector Enclosure.png:sha256:91b9bc544bf7f3e810895ed6cea3bb4d9ca331e558cd82b1e5f05bed4046741b", wordpressMediaId: null, lineage: ["owner-pdf:hush-enclosures:page:1", "owner-local:Downloads/Hush Projector Enclosure.png"] },
  { referenceId: "owner-defender-product-sheet", sourceRole: "OWNER_SUPPLIED_PRODUCT_AUTHORITY", classification: "VERIFIED_PRODUCT_RENDER", owner: "ssi", productId: "prod-ssi-defender-series-projector-enclosure", productFamily: "family-ssi-defender-series", view: "front-three-quarter-and-feature-details", installationContext: null, establishesGeometry: true, establishesFeatures: true, environmentOnly: false, generationReferenceAllowed: true, namedProductRepresentationAllowed: true, verificationStatus: "VERIFIED", sourceUrl: null, durableSourceId: "owner-image:Climate Controlled Projector Enclosure.png:sha256:290709cef3291763150a1d3daf35dd71c649ff5f9c01aa84a650e2c9e07f7d04", wordpressMediaId: null, lineage: ["owner-pdf:defender-series-specifications:page:1", "owner-pdf:defender-ac-manual:page:2", "owner-local:Downloads/Climate Controlled Projector Enclosure.png"] },
  { referenceId: "owner-projector-cage-product-sheet", sourceRole: "OWNER_SUPPLIED_PRODUCT_AUTHORITY", classification: "VERIFIED_PRODUCT_RENDER", owner: "ssi", productId: "prod-ssi-projector-cages", productFamily: "family-ssi-projector-cages", view: "ceiling-mounted-cage", installationContext: "indoor ceiling mount", establishesGeometry: true, establishesFeatures: false, environmentOnly: false, generationReferenceAllowed: true, namedProductRepresentationAllowed: true, verificationStatus: "VERIFIED", sourceUrl: null, durableSourceId: "owner-image:Projector Cages.png:sha256:b0b7784a24e3dfe05ed40ad354faff0b1dfbaa0806476c59ffdd93a66cb1b5eb", wordpressMediaId: null, lineage: ["owner-pdf:large-projector-cage-ceiling-mount:page:1", "owner-local:Downloads/Projector Cages.png"] },
  { referenceId: "owner-xs-homeline-open-detail", sourceRole: "OWNER_SUPPLIED_PRODUCT_AUTHORITY", classification: "VERIFIED_PRODUCT_DETAIL_IMAGE", owner: "ssi", productId: "prod-ssi-homeline-projector-enclosure", productFamily: "family-ssi-integrator-series", view: "open-interior-detail", installationContext: null, establishesGeometry: true, establishesFeatures: true, environmentOnly: false, generationReferenceAllowed: true, namedProductRepresentationAllowed: true, verificationStatus: "VERIFIED", sourceUrl: null, durableSourceId: "owner-archive:xsmall-enclosure-photos:member:homeline-1-7.jpg:sha256:06e7f82a7aed0eb90d7bcdcf554534f7605522fb055907646744258d360293bf", wordpressMediaId: null, lineage: ["owner-confirmation:xs-integrator-equals-homeline", "owner-archive:xsmall-enclosure-photos"] },
]);

export const PROJECTORENCLOSURE_OWNER_CONFLICTS: readonly OwnerAuthorityConflict[] = Object.freeze([
  { conflictId: "defender-ip-rating", product: "DEFENDER", fact: "IP rating", sourceA: "owner-pdf:defender-series-specifications:page:1:IP55 Equivalent", sourceB: "owner-image:Climate Controlled Projector Enclosure.png:IP65 Equivalent", disposition: "OWNER_DECISION_REQUIRED", remediationImpact: "Block autonomous IP-rating and weatherproof claims." },
  { conflictId: "defender-model-prefix", product: "DEFENDER", fact: "model prefix", sourceA: "owner-pdf:defender-series-specifications:page:1:ENC-CC", sourceB: "owner-image:Climate Controlled Projector Enclosure.png:ENC-AC", disposition: "OWNER_DECISION_REQUIRED", remediationImpact: "Use source-specific model IDs only until owner resolves naming." },
  { conflictId: "hush-size-table", product: "HUSH", fact: "available model dimensions", sourceA: "owner-pdf:hush-enclosures:page:1", sourceB: "owner-image:Hush Projector Enclosure.png", disposition: "OWNER_DECISION_REQUIRED", remediationImpact: "Block size-table remediation; family-level cooling, electrical, insulation, and sound facts remain usable." },
  { conflictId: "ust-cc-filename-identity", product: "UST_HUSH", fact: "product identity", sourceA: "owner-local:Downloads/UST CC Enclosure Sign-Off.pdf:filename", sourceB: "owner-pdf:ust-hush-drawing-a:page:1:title-block", disposition: "IDENTITY_AMBIGUOUS", remediationImpact: "Do not infer climate-controlled UST authority; both internal title blocks identify UST Hush." },
  { conflictId: "homeline-xs-exterior-dimensions", product: "HOMELINE_XS", fact: "exterior dimensions", sourceA: "owner-pdf:homeline-spec-sheet:page:1:23.66x22.6x10.83", sourceB: "owner-pdf:xs-integrator-overview-specifications:page:1:22.6x19.69x10.83", disposition: "OWNER_DECISION_REQUIRED", remediationImpact: "Block autonomous exterior-dimension claims for the Homeline/XS alias." },
  { conflictId: "homeline-marketing-environment", product: "HOMELINE_XS", fact: "weather sealing and insulation", sourceA: "owner-pdf:homeline-marketing-sheet:page:1", sourceB: "owner-approved-homeline-product-policy:no-weather-or-sealing-inference", disposition: "OWNER_DECISION_REQUIRED", remediationImpact: "Existing conservative product policy remains controlling; marketing claims cannot unlock remediation." },
]);

export const PROJECTORENCLOSURE_FAMILY_AUTHORITY = Object.freeze({
  HUSH: { status: "CONFLICTED_AUTHORITY", established: ["identity", "thermostatic fan cooling", "120 V", "sub 10 dBA", "insulation", "internal outlets and breakers"], missing: ["resolved model dimensions", "test method for sound output", "verified installation limits"] },
  DEFENDER: { status: "CONFLICTED_AUTHORITY", established: ["family identity", "model-specific dimensions", "power", "weights", "door openings", "AC/heating capacity", "working temperature", "one-year AC warranty"], missing: ["resolved IP rating", "resolved model prefix", "approved environmental claim language"] },
  CLIMATE_CONTROLLED: { status: "CONFLICTED_AUTHORITY", established: ["Defender climate-control role", "model-specific AC and heating data", "working temperature"], missing: ["resolved IP rating", "resolved environmental limits", "UST climate-controlled identity"] },
  UST_HUSH: { status: "PARTIAL_PRODUCT_AUTHORITY", established: ["UST Hush identity", "dimensional drawing", "product geometry"], missing: ["model number", "cooling", "electrical", "sound", "installation and fit policy"] },
  PROJECTOR_CAGE: { status: "PARTIAL_PRODUCT_AUTHORITY", established: ["Large Projector Cage ceiling-mount identity", "product geometry visual"], missing: ["model IDs", "dimensions", "construction specification", "locking/security performance", "mount compatibility"] },
  INTEGRATOR: { status: "CONFLICTED_AUTHORITY", established: ["family facts from registered sources", "Small ENC-FC-SM drawing and dimensions", "Small mounting details"], missing: ["resolved cooling-topology wording"] },
  HOMELINE_XS: { status: "CONFLICTED_AUTHORITY", established: ["owner-confirmed alias", "fit envelope", "power components", "exact product photographs"], missing: ["resolved exterior dimensions", "resolved weather/insulation claims"] },
} as const satisfies Record<OwnerSourceProduct, { status: FamilyAuthorityStatus; established: readonly string[]; missing: readonly string[] }>);

export function validateOwnerSourceAuthorityRegistry(): readonly string[] {
  const issues: string[] = [];
  const sourceIds = new Set(PROJECTORENCLOSURE_OWNER_SOURCES.map((item) => item.sourceId));
  const primaryHashes = new Set<string>();
  for (const item of PROJECTORENCLOSURE_OWNER_SOURCES) {
    if (!/^[a-f0-9]{64}$/.test(item.sha256)) issues.push(`INVALID_SHA:${item.sourceId}`);
    if (!item.duplicateOf && primaryHashes.has(item.sha256)) issues.push(`UNDECLARED_DUPLICATE:${item.sourceId}`);
    if (!item.duplicateOf) primaryHashes.add(item.sha256);
    if (item.duplicateOf && !sourceIds.has(item.duplicateOf)) issues.push(`UNKNOWN_DUPLICATE_TARGET:${item.sourceId}`);
  }
  for (const item of PROJECTORENCLOSURE_OWNER_FACTS) {
    if (!sourceIds.has(item.sourceId)) issues.push(`UNKNOWN_FACT_SOURCE:${item.factId}`);
    if (!item.evidenceLocation.trim()) issues.push(`MISSING_EVIDENCE_LOCATION:${item.factId}`);
  }
  return issues;
}