import "server-only";

import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import * as XLSX from "xlsx";
import { normalizeWordPressApiBaseUrl } from "./authenticated-wordpress-read-authority";
import { classifyPublishedLinkResult } from "./published-link-validation";
import { resolveWordPressCredentialReference } from "./wordpress-credential-resolver";
import { saveProjectorEnclosureInventorySnapshot } from "./projectorenclosure-sitewide-inventory-repository";
import { PROJECTORENCLOSURE_INVENTORY_VERSION, buildNicheOpportunities, classifyDisposition, contentSha256, contentTokenOverlap, createSnapshotId, detectClaimFlags, deterministicInventoryId, inferIntent, mapProductAuthority, parseContentSignals, type SitewideInventoryAsset, type SitewideInventorySnapshot, type WordPressCollection } from "./projectorenclosure-sitewide-planner";
import type { SiteConfiguration } from "./types";

type WpObject = { id: number; date_gmt?: string; modified_gmt?: string; slug: string; status: string; parent?: number; link?: string; featured_media?: number; title?: { raw?: string; rendered?: string }; content?: { raw?: string; rendered?: string }; yoast_head_json?: { canonical?: string; robots?: Record<string, string>; title?: string; description?: string } };
type Yoast = { focus: string; title: string; meta: string };
const workbookRelativePath = "resources/seo-authority/projectorenclosure/Projector_Enclosure_Master_Keyword_Universe.xlsx";

function authorization(username: string, password: string): string { return `Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`; }
function xml(value: string): string { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;"); }
function decodeXml(value: string): string { return value.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, "&"); }

async function mapLimit<T, R>(items: readonly T[], limit: number, work: (item: T, index: number) => Promise<R>): Promise<R[]> {
  const output = new Array<R>(items.length); let cursor = 0;
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, async () => { while (cursor < items.length) { const index = cursor++; output[index] = await work(items[index], index); } }));
  return output;
}

async function readWorkbook(): Promise<{ status: "AVAILABLE" | "NOT_FOUND" | "UNREADABLE"; path: string | null; rowCount: number; keywords: Set<string> }> {
  const path = resolve(process.cwd(), workbookRelativePath);
  try {
    const bytes = await readFile(path); const workbook = XLSX.read(bytes, { type: "buffer", dense: true }); const sheet = workbook.Sheets["Master Keywords"];
    if (!sheet) return { status: "UNREADABLE", path, rowCount: 0, keywords: new Set() };
    const rows = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: null }); const headerIndex = rows.findIndex((row) => row[0] === "Master ID" && row[1] === "Keyword"); const keywords = new Set(rows.slice(headerIndex + 1).map((row) => String(row[1] ?? "").trim().toLowerCase()).filter(Boolean));
    return { status: "AVAILABLE", path, rowCount: keywords.size, keywords };
  } catch (error) {
    return { status: (error as NodeJS.ErrnoException).code === "ENOENT" ? "NOT_FOUND" : "UNREADABLE", path: null, rowCount: 0, keywords: new Set() };
  }
}

export async function buildProjectorEnclosureSitewideInventory(site: SiteConfiguration): Promise<SitewideInventorySnapshot> {
  const credential = resolveWordPressCredentialReference(site.integrations.wordpressCredentialReference);
  if (!credential || !site.integrations.wordpressApiBaseUrl || site.siteId !== "site-ssi-projectorenclosure") throw new Error("ProjectorEnclosure read authority unavailable.");
  const apiBase = normalizeWordPressApiBaseUrl(site.integrations.wordpressApiBaseUrl); const origin = new URL(apiBase).origin; const auth = authorization(credential.username, credential.applicationPassword); const headers = { Accept: "application/json", Authorization: auth, "Cache-Control": "no-cache, no-store, max-age=0" }; const timestamp = new Date().toISOString();
  const collections: WordPressCollection[] = ["pages", "posts", "portfolio", "product"];
  const collectionResults: { collection: WordPressCollection; objects: WpObject[]; accessible: boolean }[] = [];
  for (const collection of collections) {
    const objects: WpObject[] = []; let accessible = true;
    for (let page = 1; page <= 100; page += 1) {
      const url = `${apiBase}/${collection}?context=edit&status=any&per_page=100&page=${page}&_fields=id,date_gmt,modified_gmt,slug,status,parent,link,featured_media,title,content,yoast_head_json&_inventory=${crypto.randomUUID()}`;
      const response = await fetch(url, { headers, cache: "no-store", signal: AbortSignal.timeout(30_000) });
      if ((response.status === 400 && page > 1) || response.status === 404) { if (page === 1) accessible = false; break; }
      if (!response.ok) { accessible = false; break; }
      const batch = await response.json() as WpObject[]; objects.push(...batch); if (batch.length < 100) break;
    }
    collectionResults.push({ collection, objects, accessible });
  }
  const raw = collectionResults.flatMap((result) => result.objects.map((object) => ({ collection: result.collection, object })));
  const yoast = await mapLimit(raw, 8, async ({ object }): Promise<Yoast> => {
    const payload = `<?xml version="1.0"?><methodCall><methodName>wp.getPost</methodName><params><param><value><int>0</int></value></param><param><value><string>${xml(credential.username)}</string></value></param><param><value><string>${xml(credential.applicationPassword)}</string></value></param><param><value><int>${object.id}</int></value></param><param><value><array><data><value><string>custom_fields</string></value></data></array></value></param></params></methodCall>`;
    try { const response = await fetch(`${origin}/xmlrpc.php`, { method: "POST", headers: { "Content-Type": "text/xml" }, body: payload, cache: "no-store", signal: AbortSignal.timeout(30_000) }); const body = await response.text(); const blocks = [...body.matchAll(/<struct>([\s\S]*?)<\/struct>/g)].map((match) => match[1]); const field = (key: string) => { const block = blocks.find((value) => value.includes(`<string>${key}</string>`)) ?? ""; return decodeXml(block.match(/<name>value<\/name><value><string>([\s\S]*?)<\/string>/)?.[1] ?? ""); }; return { focus: field("_yoast_wpseo_focuskw"), title: field("_yoast_wpseo_title"), meta: field("_yoast_wpseo_metadesc") }; } catch { return { focus: "", title: "", meta: "" }; }
  });
  const parsed = raw.map(({ collection, object }, index) => { const content = object.content?.raw ?? object.content?.rendered ?? ""; const signals = parseContentSignals(content, origin); return { collection, object, content, signals, yoast: yoast[index] }; });
  const allLinks = [...new Set(parsed.flatMap((item) => [...item.signals.internalLinks, ...item.signals.externalLinks]))];
  const linkEvidence = new Map((await mapLimit(allLinks, 12, async (url) => { try { const response = await fetch(new URL(url, origin), { redirect: "follow", cache: "no-store", signal: AbortSignal.timeout(15_000) }); return [url, { status: response.status, classification: classifyPublishedLinkResult({ requestedUrl: new URL(url, origin).toString(), status: response.status, resolvedUrl: response.url }) }] as const; } catch { return [url, { status: 0, classification: "NETWORK_ERROR" }] as const; } })).map((entry) => entry));
  const publicEvidence = new Map((await mapLimit(parsed.filter((item) => item.object.status === "publish"), 10, async (item) => { const url = item.object.link || item.object.yoast_head_json?.canonical || `${origin}/${item.object.slug}/`; try { const response = await fetch(`${url}${url.includes("?") ? "&" : "?"}_inventory=${crypto.randomUUID()}`, { redirect: "follow", cache: "no-store", signal: AbortSignal.timeout(20_000) }); return [`${item.collection}:${item.object.id}`, response.status] as const; } catch { return [`${item.collection}:${item.object.id}`, 0] as const; } })).map((entry) => entry));
  const redirects = await mapLimit(parsed, 10, async (item) => { const canonical = item.object.yoast_head_json?.canonical || item.object.link || `${origin}/${item.object.slug}/`; try { const endpoint = new URL(`${origin}/wp-json/ssi/v1/redirect`); endpoint.searchParams.set("source", new URL(canonical).pathname); const response = await fetch(endpoint, { headers, cache: "no-store", signal: AbortSignal.timeout(15_000) }); const body = response.ok ? await response.json() as { exists?: boolean; destination?: string } : {}; return { exists: body.exists === true, destination: body.destination ?? null }; } catch { return { exists: false, destination: null }; } });
  const workbook = await readWorkbook();
  let assets: SitewideInventoryAsset[] = parsed.map((item, index) => {
    const object = item.object; const title = object.title?.raw ?? object.title?.rendered ?? ""; const url = object.link || object.yoast_head_json?.canonical || `${origin}/${object.slug}/`; const canonical = object.yoast_head_json?.canonical ?? url; const intent = inferIntent({ sourceId: object.id, title, slug: object.slug, yoastFocus: item.yoast.focus, text: item.signals.text }); const products = mapProductAuthority({ title, slug: object.slug, text: item.signals.text }); const claimFlags = detectClaimFlags(item.signals.text); const brokenLinks = [...item.signals.internalLinks, ...item.signals.externalLinks].filter((link) => { const evidence = linkEvidence.get(link); return !evidence || !["VALID", "BOT_RESTRICTED_OFFICIAL_URL"].includes(evidence.classification); }); const trackedLinks = [...item.signals.internalLinks, ...item.signals.externalLinks].filter((link) => /[?&](?:utm_[^=]+|gclid|fbclid)=/i.test(link)); const mediaQuality = item.signals.mediaUrls.length >= 1 ? "STRONG" : Number(object.featured_media ?? 0) > 0 ? "WEAK" : "MISSING"; const disposition = classifyDisposition({ status: object.status, robots: object.yoast_head_json?.robots ?? {}, wordCount: item.signals.wordCount, claimFlags, brokenLinks, trackedLinks, mediaQuality, ownershipConfidence: intent.confidence, productAuthorityState: products.state, duplicate: false, redirect: redirects[index].exists });
    return { inventoryId: deterministicInventoryId(item.collection, object.id), sourceId: object.id, collection: item.collection, status: object.status, title, slug: object.slug, url, canonical, robots: object.yoast_head_json?.robots ?? {}, yoastFocus: item.yoast.focus, yoastTitle: item.yoast.title || object.yoast_head_json?.title || "", yoastMeta: item.yoast.meta || object.yoast_head_json?.description || "", featuredMediaId: Number(object.featured_media ?? 0), contentHash: contentSha256(item.content), wordCount: item.signals.wordCount, headings: item.signals.headings, internalLinks: item.signals.internalLinks, externalLinks: item.signals.externalLinks, mediaUrls: item.signals.mediaUrls, publishedAt: object.date_gmt ?? null, modifiedAt: object.modified_gmt ?? null, parentId: Number(object.parent ?? 0), publicHttpStatus: publicEvidence.get(`${item.collection}:${object.id}`) ?? null, redirect: redirects[index], apparentIntent: intent.intent, ownershipConfidence: intent.confidence, competingAssetIds: [], productIds: products.productIds, productAuthorityState: products.state, claimFlags, brokenLinks, trackedLinks, mediaQuality, disposition: disposition.disposition, safetyClass: disposition.safetyClass, recommendedActions: disposition.actions, risk: disposition.risk, dependencies: products.state === "PRODUCT_AUTHORITY_MISSING" ? ["product authority"] : [], authorityTimestamp: timestamp };
  });
  for (let left = 0; left < assets.length; left += 1) for (let right = left + 1; right < assets.length; right += 1) { const overlap = contentTokenOverlap(parsed[left].content, parsed[right].content); const normalizeTitle = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); const sameTitle = normalizeTitle(assets[left].title) === normalizeTitle(assets[right].title); if ((sameTitle && overlap >= 0.45) || overlap >= 0.9) { assets[left].competingAssetIds = [...assets[left].competingAssetIds, assets[right].sourceId]; assets[right].competingAssetIds = [...assets[right].competingAssetIds, assets[left].sourceId]; } }
  const mergeDestinations = new Map([[12364, 10338], [12469, 10338], [12748, 10338], [10343, 12646], [12620, 10592]]);
  const canonicalDuplicateOwners = new Set(mergeDestinations.values());
  assets = assets.map((asset) => {
    const unrelated = asset.collection === "portfolio" && /greenworld seo|seo consulting/i.test(asset.title);
    const mergeDestination = mergeDestinations.get(asset.sourceId);
    if (!unrelated && !mergeDestination) return asset;
    const disposition = classifyDisposition({ status: asset.status, robots: asset.robots, wordCount: asset.wordCount, claimFlags: asset.claimFlags, brokenLinks: asset.brokenLinks, trackedLinks: asset.trackedLinks, mediaQuality: asset.mediaQuality, ownershipConfidence: mergeDestination ? "CONFLICTED" : asset.ownershipConfidence, productAuthorityState: asset.productAuthorityState, duplicate: Boolean(mergeDestination), redirect: asset.redirect.exists, unrelated });
    return { ...asset, ownershipConfidence: mergeDestination ? "CONFLICTED" : asset.ownershipConfidence, disposition: disposition.disposition, safetyClass: disposition.safetyClass, risk: disposition.risk, recommendedActions: disposition.actions };
  }).map((asset) => canonicalDuplicateOwners.has(asset.sourceId) && asset.disposition === "MERGE" ? { ...asset, disposition: "ENHANCE" as const, safetyClass: "C" as const, risk: "MEDIUM" as const, recommendedActions: ["validate as consolidation destination"] } : asset);
  const workbookRef = workbook.status === "AVAILABLE" ? `${workbookRelativePath}#Master Keywords` : null; const opportunities = buildNicheOpportunities(assets, workbookRef).map((opportunity) => ({ ...opportunity, workbookLineage: workbook.keywords.has(opportunity.primaryKeyword.toLowerCase()) ? `${workbookRef}:${opportunity.primaryKeyword}` : workbookRef }));
  const snapshotId = createSnapshotId(timestamp, assets); const redirectRecords = assets.filter((asset) => asset.redirect.exists).map((asset) => ({ id: `redirect-${asset.inventoryId}`, source: new URL(asset.url).pathname, destination: asset.redirect.destination ?? "" }));
  const waves: SitewideInventorySnapshot["executionWaves"] = [
    { wave: 0, name: "Critical authority and safety", candidateIds: assets.filter((a) => a.claimFlags.length || a.brokenLinks.length || a.redirect.exists).map((a) => a.inventoryId), mutationTypes: ["claim cleanup", "broken link", "canonical/redirect repair"], qa: ["exact precondition", "public readback", "claim and link scans"], rollback: "exact content/SEO/redirect snapshot", risk: "medium", maximumBatchSize: 10, stopConditions: ["ownership drift", "unknown authority", "public acceptance failure"] },
    { wave: 1, name: "Product and category authorities", candidateIds: assets.filter((a) => a.productAuthorityState === "VERIFIED" && a.disposition === "ENHANCE").map((a) => a.inventoryId), mutationTypes: ["media", "product linkage", "planning content"], qa: ["product facts", "SEO ownership", "media placement"], rollback: "page and media transaction evidence", risk: "medium", maximumBatchSize: 10, stopConditions: ["product mismatch", "claim failure"] },
    { wave: 2, name: "Applications and niches", candidateIds: assets.filter((a) => a.disposition === "ENHANCE" && a.productAuthorityState !== "VERIFIED").map((a) => a.inventoryId), mutationTypes: ["bounded enhancement", "internal links", "CTA"], qa: ["intent", "cannibalization", "desktop/mobile"], rollback: "exact page snapshot", risk: "medium", maximumBatchSize: 8, stopConditions: ["ownership conflict", "product authority gap"] },
    { wave: 3, name: "Consolidation and retirement", candidateIds: assets.filter((a) => ["MERGE", "REDIRECT", "RETIRE"].includes(a.disposition)).map((a) => a.inventoryId), mutationTypes: ["merge", "redirect", "retire"], qa: ["content preservation", "redirect", "SEO", "reference scan", "manual retirement authority"], rollback: "source/destination/redirect snapshot", risk: "high", maximumBatchSize: 5, stopConditions: ["ambiguous owner", "redirect authority failure", "unresolved references"] },
    { wave: 4, name: "New niche creation", candidateIds: opportunities.slice(0, 30).map((a) => a.opportunityId), mutationTypes: ["research", "new page", "media"], qa: ["research lineage", "product authority", "cannibalization"], rollback: "delete draft or restore status", risk: "medium-high", maximumBatchSize: 5, stopConditions: ["missing product authority", "intent collision"] },
    { wave: 5, name: "Geographic expansion", candidateIds: [], mutationTypes: ["geographic generation"], qa: ["foundation stability", "parent authority", "local uniqueness"], rollback: "campaign rollback", risk: "high", maximumBatchSize: 25, stopConditions: ["foundation incomplete", "duplicate ownership"] },
  ];
  const consolidationGraph: SitewideInventorySnapshot["consolidationGraph"] = [
    ...[...mergeDestinations].map(([sourceId, destinationId]) => { const source = assets.find((asset) => asset.sourceId === sourceId)!; const destination = assets.find((asset) => asset.sourceId === destinationId)!; return { sourceId, sourceUrl: source.url, disposition: "MERGE" as const, destinationId, destinationUrl: destination.url, reason: "Strong content overlap with a clearer canonical owner.", preserve: "Unique factual and useful application content after claim review.", discard: "Duplicated boilerplate and unsupported claims.", seoDisposition: "Transfer only unique validated intent; destination retains canonical ownership.", mediaDisposition: "Preserve unique useful media; do not duplicate weak media.", redirectRequired: true, risk: "HIGH", rollbackPrerequisites: ["exact source and destination snapshots", "redirect absence/precondition", "public and SEO readback"] }; }),
    ...assets.filter((asset) => asset.disposition === "RETIRE").map((source) => ({ sourceId: source.sourceId, sourceUrl: source.url, disposition: "RETIRE" as const, destinationId: null, destinationUrl: null, reason: "Unrelated SEO consulting demo portfolio content on ProjectorEnclosure.", preserve: "Nothing unless manual review identifies legitimate provenance.", discard: "Unrelated demo content.", seoDisposition: "Remove from index only after manual confirmation.", mediaDisposition: "Retain media until reference scan and manual review complete.", redirectRequired: false, risk: "HIGH", rollbackPrerequisites: ["exact source snapshot", "navigation/reference scan", "manual authority approval"] })),
    ...assets.filter((asset) => asset.disposition === "REDIRECT").map((source) => { const destination = assets.find((asset) => new URL(asset.url).pathname === source.redirect.destination); return { sourceId: source.sourceId, sourceUrl: source.url, disposition: "REDIRECT" as const, destinationId: destination?.sourceId ?? null, destinationUrl: destination?.url ?? (source.redirect.destination ? `${origin}${source.redirect.destination}` : null), reason: "Certified legacy redirect already exists.", preserve: "Historical redirect evidence.", discard: "No duplicate public content.", seoDisposition: "Canonical authority remains at destination.", mediaDisposition: "No media mutation.", redirectRequired: true, risk: "LOW", rollbackPrerequisites: ["redirect ID/source/destination evidence"] }; }),
  ];
  const snapshot: SitewideInventorySnapshot = { snapshotId, siteId: "site-ssi-projectorenclosure", domain: "projectorenclosure.com", classificationVersion: PROJECTORENCLOSURE_INVENTORY_VERSION, authorityTimestamp: timestamp, mutationCounters: { wordpress: 0, media: 0, redirects: 0, yoast: 0, products: 0 }, workbook: { status: workbook.status, path: workbook.path, rowCount: workbook.rowCount }, assets, opportunities, redirects: redirectRecords, consolidationGraph, otherObjects: collectionResults.filter((result) => !["pages", "posts"].includes(result.collection)).map((result) => ({ collection: result.collection, count: result.objects.length, publicCount: result.objects.filter((object) => object.status === "publish").length, note: result.accessible ? "REST-visible search-relevant custom collection" : "collection inaccessible through authenticated REST" })), executionWaves: waves };
  return saveProjectorEnclosureInventorySnapshot(snapshot);
}