import { createHash, randomUUID } from "node:crypto";

export type PublicVerifierFetchPhase = "CANONICAL_PUBLIC_READ" | "CANONICAL_BODY_READ" | "MEDIA_FETCH" | "INTERNAL_LINK_FETCH" | "SEO_OR_CANONICAL_FETCH" | "PUBLIC_CONVERGENCE_READ" | "WORDPRESS_ROLLBACK_WRITE" | "ROLLBACK_VERIFICATION_READ";
export type StructuredFetchError = { name: string; message: string; stack: string | null; code: string | number | null; errno: string | number | null; syscall: string | null; address: string | null; port: string | number | null; socket: null | { localAddress: string | null; localPort: number | null; remoteAddress: string | null; remotePort: number | null; remoteFamily: string | null; timeout: number | null; bytesWritten: number | null; bytesRead: number | null }; cause: StructuredFetchError | StructuredFetchError[] | null };
export type PublicVerifierFetchEvidence = { eventId: string; attemptId: string; verificationReceiptId: string; phase: PublicVerifierFetchPhase; event: "REQUEST" | "RESPONSE" | "BODY_COMPLETE" | "ERROR" | "VALIDATION"; timestamp: string; url: string; method: string; attemptNumber: number; timeoutMs: number | null; abortState: { before: boolean; after: boolean; reasonName: string | null }; runtimeSha: string; nodeVersion: string; fetchImplementation: string; response: null | { status: number; ok: boolean; finalUrl: string; redirected: boolean; redirectChain: string[]; headers: { contentType: string | null; cacheControl: string | null; server: string | null; age: string | null; via: string | null; xCache: string | null }; cacheClassification: "PRIVATE_NO_STORE" | "NO_STORE" | "CACHEABLE_OR_UNSPECIFIED"; bodyReadComplete: boolean; bodyBytes: number | null; contentHash: string | null }; error: StructuredFetchError | null };
type Recorder = (evidence: PublicVerifierFetchEvidence) => void;
type ErrorLike = { name?: unknown; message?: unknown; stack?: unknown; code?: unknown; errno?: unknown; syscall?: unknown; address?: unknown; port?: unknown; socket?: unknown; cause?: unknown; errors?: unknown };
const scalar = (value: unknown): string | number | null => typeof value === "string" || typeof value === "number" ? value : null;
const text = (value: unknown) => typeof value === "string" ? value : null;
const redactText = (value: string) => value.replace(/(authorization|cookie|password|token|secret|nonce|signature|key)=([^\s&]+)/gi, "$1=[REDACTED]").slice(0, 8_000);
export function redactVerifierUrl(value: string) { const url = new URL(value); url.username = ""; url.password = ""; for (const [name] of url.searchParams) if (/(?:authorization|cookie|password|token|secret|nonce|signature|key)/i.test(name)) url.searchParams.set(name, "[REDACTED]"); return url.toString(); }
export function serializePublicVerifierError(value: unknown, depth = 0): StructuredFetchError { const error = value && typeof value === "object" ? value as ErrorLike : {}; const socket = error.socket && typeof error.socket === "object" ? error.socket as Record<string, unknown> : null; const causes = Array.isArray(error.errors) ? error.errors : null; return { name: text(error.name) ?? (value instanceof Error ? value.name : "UnknownError"), message: redactText(text(error.message) ?? String(value)), stack: text(error.stack) ? redactText(text(error.stack)!) : null, code: scalar(error.code), errno: scalar(error.errno), syscall: text(error.syscall), address: text(error.address), port: scalar(error.port), socket: socket ? { localAddress: text(socket.localAddress), localPort: typeof socket.localPort === "number" ? socket.localPort : null, remoteAddress: text(socket.remoteAddress), remotePort: typeof socket.remotePort === "number" ? socket.remotePort : null, remoteFamily: text(socket.remoteFamily), timeout: typeof socket.timeout === "number" ? socket.timeout : null, bytesWritten: typeof socket.bytesWritten === "number" ? socket.bytesWritten : null, bytesRead: typeof socket.bytesRead === "number" ? socket.bytesRead : null } : null, cause: depth >= 7 ? null : causes ? causes.map((item) => serializePublicVerifierError(item, depth + 1)) : error.cause ? serializePublicVerifierError(error.cause, depth + 1) : null }; }
export const getPublicVerifierRuntimeIdentity = () => { const fetchImplementation = `node-native-fetch:undici-${process.versions.undici ?? "embedded"}`; return { nodeVersion: process.version, fetchImplementation, runtimeSha: createHash("sha256").update(`${process.execPath}|${process.version}|${fetchImplementation}`).digest("hex") }; };
const abortReasonName = (signal: AbortSignal | null) => { const reason = signal?.reason; return reason && typeof reason === "object" && "name" in reason && typeof reason.name === "string" ? reason.name : null; };
const responseEvidence = (response: Response, requestedUrl: string) => { const cacheControl = response.headers.get("cache-control"); const finalUrl = redactVerifierUrl(response.url || requestedUrl); const requestUrl = redactVerifierUrl(requestedUrl); return { status: response.status, ok: response.ok, finalUrl, redirected: response.redirected, redirectChain: finalUrl === requestUrl ? [requestUrl] : [requestUrl, finalUrl], headers: { contentType: response.headers.get("content-type"), cacheControl, server: response.headers.get("server"), age: response.headers.get("age"), via: response.headers.get("via"), xCache: response.headers.get("x-cache") }, cacheClassification: /private/i.test(cacheControl ?? "") && /no-store/i.test(cacheControl ?? "") ? "PRIVATE_NO_STORE" as const : /no-store/i.test(cacheControl ?? "") ? "NO_STORE" as const : "CACHEABLE_OR_UNSPECIFIED" as const, bodyReadComplete: false, bodyBytes: null, contentHash: null }; };
export function createObservedPublicVerifierFetch(input: { record: Recorder; fetcher?: typeof fetch; attemptIdFactory?: () => string }) {
  const fetcher = input.fetcher ?? fetch; const attemptIdFactory = input.attemptIdFactory ?? (() => `public-verifier-fetch-${randomUUID()}`);
  return async function observedFetch(spec: { verificationReceiptId: string; phase: PublicVerifierFetchPhase; url: string | URL; init: RequestInit; attemptNumber: number; timeoutMs: number | null }) {
    const attemptId = attemptIdFactory(); const requestedUrl = redactVerifierUrl(String(spec.url)); const signal = spec.init.signal ?? null; const abortBefore = signal?.aborted ?? false; const base = { attemptId, verificationReceiptId: spec.verificationReceiptId, phase: spec.phase, url: requestedUrl, method: (spec.init.method ?? "GET").toUpperCase(), attemptNumber: spec.attemptNumber, timeoutMs: spec.timeoutMs, ...getPublicVerifierRuntimeIdentity() }; const abortState = () => ({ before: abortBefore, after: signal?.aborted ?? false, reasonName: abortReasonName(signal) }); const append = (event: PublicVerifierFetchEvidence["event"], response: PublicVerifierFetchEvidence["response"], error: StructuredFetchError | null) => input.record({ ...base, eventId: `${attemptId}-${event.toLowerCase()}-${randomUUID()}`, event, timestamp: new Date().toISOString(), abortState: abortState(), response, error });
    append("REQUEST", null, null);
    let response: Response;
    try { response = await fetcher(spec.url, spec.init); append("RESPONSE", responseEvidence(response, String(spec.url)), null); }
    catch (error) { append("ERROR", null, serializePublicVerifierError(error)); throw error; }
    const read = async <T>(phase: PublicVerifierFetchPhase, consume: () => Promise<T>, bytes: (value: T) => Uint8Array) => { try { const value = await consume(); const body = bytes(value); input.record({ ...base, eventId: `${attemptId}-body-complete-${randomUUID()}`, phase, event: "BODY_COMPLETE", timestamp: new Date().toISOString(), abortState: abortState(), response: { ...responseEvidence(response, String(spec.url)), bodyReadComplete: true, bodyBytes: body.byteLength, contentHash: createHash("sha256").update(body).digest("hex") }, error: null }); return value; } catch (error) { input.record({ ...base, eventId: `${attemptId}-body-error-${randomUUID()}`, phase, event: "ERROR", timestamp: new Date().toISOString(), abortState: abortState(), response: responseEvidence(response, String(spec.url)), error: serializePublicVerifierError(error) }); throw error; } };
    return { attemptId, response, text: (phase: PublicVerifierFetchPhase) => read(phase, () => response.text(), (value) => new TextEncoder().encode(value)), arrayBuffer: (phase: PublicVerifierFetchPhase) => read(phase, () => response.arrayBuffer(), (value) => new Uint8Array(value)), recordValidation: (phase: PublicVerifierFetchPhase) => input.record({ ...base, eventId: `${attemptId}-validation-${randomUUID()}`, phase, event: "VALIDATION", timestamp: new Date().toISOString(), abortState: abortState(), response: responseEvidence(response, String(spec.url)), error: null }) };
  };
}