import { load } from "cheerio";

export type PublicHostLinkClass = "NAVIGATIONAL_ANCHOR" | "LOCAL_DOCUMENT_NAVIGATION" | "MEDIA_RESOURCE" | "CANONICAL_OR_SEO_LINK" | "WORDPRESS_DISCOVERY_METADATA" | "PROTOCOL_ENDPOINT" | "API_ENDPOINT" | "NON_HTTP_NAVIGATION" | "EXTERNAL_LINK" | "UNKNOWN";
export type PublicHostLinkValidationPolicy = "VALIDATE_INTERNAL_NAVIGATION" | "EXTERNAL_NAVIGATION" | "SEO_AUTHORITY" | "NOT_APPLICABLE_TO_NAVIGATION" | "FAIL_INVALID_NAVIGATION";
export type PublicHostLinkEvidence = { sourceElementType: string; rel: string[]; href: string; resolvedUrl: string | null; classification: PublicHostLinkClass; validationPolicy: PublicHostLinkValidationPolicy; httpStatus: number | null; result: "PASS" | "FAIL" | "NOT_APPLICABLE" | "PENDING"; reason: string };
const mediaRel = new Set(["stylesheet", "preload", "prefetch", "icon", "apple-touch-icon", "mask-icon", "modulepreload"]);
const discoveryRel = new Set(["alternate", "edituri", "wlwmanifest", "pingback"]);
const nonHttp = /^(?:mailto|tel|sms|javascript|data):/i;
const development = /^(?:localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])$/i;
const preview = /(?:^|[?&])(?:preview|preview_id|preview_nonce)=|\/wp-admin\/|\/wp-login\.php/i;
const endpointClass = (url: URL): PublicHostLinkClass | null => { const path = url.pathname.toLowerCase(); if (path === "/xmlrpc.php") return "PROTOCOL_ENDPOINT"; if (path.includes("/wp-json/oembed/") || path.includes("/oembed/1.0/embed")) return "WORDPRESS_DISCOVERY_METADATA"; if (path.startsWith("/wp-json/")) return "API_ENDPOINT"; return null; };
export function classifyPublicHostLink(input: { sourceElementType: string; rel?: readonly string[]; href: string; documentUrl: string; internalHosts: readonly string[] }): PublicHostLinkEvidence {
  const tag = input.sourceElementType.toLowerCase(); const rel = (input.rel ?? []).map((item) => item.toLowerCase()); const href = input.href.trim(); const pending = (classification: PublicHostLinkClass, validationPolicy: PublicHostLinkValidationPolicy, resolvedUrl: string | null, reason: string): PublicHostLinkEvidence => ({ sourceElementType: tag, rel, href, resolvedUrl, classification, validationPolicy, httpStatus: null, result: validationPolicy === "VALIDATE_INTERNAL_NAVIGATION" ? "PENDING" : validationPolicy === "FAIL_INVALID_NAVIGATION" ? "FAIL" : "NOT_APPLICABLE", reason });
  if (!href) return pending("UNKNOWN", tag === "a" ? "FAIL_INVALID_NAVIGATION" : "NOT_APPLICABLE_TO_NAVIGATION", null, "EMPTY_HREF");
  if (href.startsWith("#")) return pending("LOCAL_DOCUMENT_NAVIGATION", "NOT_APPLICABLE_TO_NAVIGATION", new URL(href, input.documentUrl).toString(), "LOCAL_FRAGMENT");
  if (nonHttp.test(href)) return pending("NON_HTTP_NAVIGATION", "NOT_APPLICABLE_TO_NAVIGATION", href, "NON_HTTP_SCHEME");
  let resolved: URL; try { resolved = new URL(href, input.documentUrl); } catch { return pending("UNKNOWN", tag === "a" ? "FAIL_INVALID_NAVIGATION" : "NOT_APPLICABLE_TO_NAVIGATION", null, "INVALID_URL"); }
  const endpoint = endpointClass(resolved); if (endpoint) return pending(endpoint, "NOT_APPLICABLE_TO_NAVIGATION", resolved.toString(), endpoint === "PROTOCOL_ENDPOINT" ? "PROTOCOL_DISCOVERY_ENDPOINT" : "WORDPRESS_OR_API_DISCOVERY_ENDPOINT");
  if (tag === "link" && rel.includes("canonical")) return pending("CANONICAL_OR_SEO_LINK", "SEO_AUTHORITY", resolved.toString(), "CANONICAL_DECLARATION");
  if (tag === "link" && rel.some((item) => mediaRel.has(item))) return pending("MEDIA_RESOURCE", "NOT_APPLICABLE_TO_NAVIGATION", resolved.toString(), "RESOURCE_LINK");
  if (tag === "link" && rel.some((item) => discoveryRel.has(item))) return pending("WORDPRESS_DISCOVERY_METADATA", "NOT_APPLICABLE_TO_NAVIGATION", resolved.toString(), "DISCOVERY_RELATION");
  if (tag !== "a") return pending("UNKNOWN", "NOT_APPLICABLE_TO_NAVIGATION", resolved.toString(), "NON_NAVIGATION_ELEMENT");
  if (!/^https?:$/.test(resolved.protocol)) return pending("NON_HTTP_NAVIGATION", "NOT_APPLICABLE_TO_NAVIGATION", resolved.toString(), "NON_HTTP_SCHEME");
  if (development.test(resolved.hostname)) return pending("NAVIGATIONAL_ANCHOR", "FAIL_INVALID_NAVIGATION", resolved.toString(), "DEVELOPMENT_TARGET");
  const internal = input.internalHosts.some((host) => resolved.hostname.toLowerCase() === host.toLowerCase()); if (!internal) return pending("EXTERNAL_LINK", "EXTERNAL_NAVIGATION", resolved.toString(), "EXTERNAL_ANCHOR");
  if (preview.test(resolved.toString())) return pending("NAVIGATIONAL_ANCHOR", "FAIL_INVALID_NAVIGATION", resolved.toString(), "PREVIEW_OR_ADMIN_TARGET");
  return pending("NAVIGATIONAL_ANCHOR", "VALIDATE_INTERNAL_NAVIGATION", resolved.toString(), "INTERNAL_ANCHOR_PENDING");
}
export function discoverPublicHostLinks(input: { html: string; documentUrl: string; internalHosts: readonly string[] }) { const $ = load(input.html); return $("[href]").toArray().map((element) => { const node = $(element); return classifyPublicHostLink({ sourceElementType: element.tagName, rel: (node.attr("rel") ?? "").split(/\s+/).filter(Boolean), href: node.attr("href") ?? "", documentUrl: input.documentUrl, internalHosts: input.internalHosts }); }); }
export function applyPublicHostLinkStatus(evidence: PublicHostLinkEvidence, status: number | null, networkError = false): PublicHostLinkEvidence { if (evidence.validationPolicy !== "VALIDATE_INTERNAL_NAVIGATION") return { ...evidence, httpStatus: status, result: evidence.validationPolicy === "FAIL_INVALID_NAVIGATION" ? "FAIL" : "NOT_APPLICABLE", reason: evidence.reason }; const pass = !networkError && status !== null && status >= 200 && status < 400; return { ...evidence, httpStatus: status, result: pass ? "PASS" : "FAIL", reason: networkError ? "NETWORK_ERROR" : status === null ? "NO_HTTP_STATUS" : pass ? "NAVIGATION_HTTP_PASS" : `NAVIGATION_HTTP_${status}` }; }
export function replayPersistedHrefEvidence(input: { responses: readonly { url: string; status: number; ok: boolean }[]; documentUrl: string; internalHosts: readonly string[] }) { const links = input.responses.map((item) => applyPublicHostLinkStatus(classifyPublicHostLink({ sourceElementType: "persisted-v2-href-evidence", href: item.url, documentUrl: input.documentUrl, internalHosts: input.internalHosts }), item.status)); const oembed = links.filter((item) => item.resolvedUrl?.includes("/oembed/1.0/embed")); const xmlrpc = links.filter((item) => item.resolvedUrl && new URL(item.resolvedUrl).pathname.toLowerCase() === "/xmlrpc.php"); const otherFailures = links.filter((item) => item.result === "FAIL"); return { links, exactSourceElementAuthorityAvailable: false, previousFalsePositiveEndpointsClassifiedCorrectly: oembed.every((item) => item.classification === "WORDPRESS_DISCOVERY_METADATA" && item.validationPolicy === "NOT_APPLICABLE_TO_NAVIGATION") && xmlrpc.every((item) => item.classification === "PROTOCOL_ENDPOINT" && item.validationPolicy === "NOT_APPLICABLE_TO_NAVIGATION"), actualNavigationalBrokenLinks: otherFailures.length, otherV2RealLinkFailures: otherFailures.map((item) => item.resolvedUrl), result: oembed.length > 0 && xmlrpc.length > 0 && otherFailures.length === 0 ? "PASS" as const : "FAIL" as const };
}