import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { deepClone, loadPersistedState, savePersistedState } from "./foundation-persistence";

export type SiteVisualAssembly = { assemblyId: string; organizationId: string; siteId: string; buildSessionId: string; pageId: string; pageRevisionId: string; revision: number; status: "READY_FOR_OWNER_REVIEW" | "APPROVED" | "REVISION_REQUESTED"; referenceAssetId: string; referenceClassification: "OWNER_SUPPLIED_REFERENCE"; referencePublished: false; imageCandidateId: string; imageCandidateRevision: number; imageProvenance: "GENERATED_VISUAL" | "OWNER_ASSET"; imageSha256: string; wordpressObjectId: string; wordpressMediaId: string; wordpressMediaUrl: string; wordpressStatus: "draft"; contentHtml: string; contentSha256: string; designSystemVersion: "commercial-stainless-visual-v1"; ownerInstructions: string | null; createdAt: string; createdBy: string; decidedAt: string | null; decidedBy: string | null };
type State = { records: SiteVisualAssembly[] }; const NAMESPACE = "site-visual-assembly-repository"; const seed = (): State => ({ records: [] });
function load() { return loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); }
export function listSiteVisualAssemblies(input: { organizationId: string; siteId: string; buildSessionId: string }) { return deepClone(load().state.records.filter((item) => item.organizationId === input.organizationId && item.siteId === input.siteId && item.buildSessionId === input.buildSessionId)); }
export function saveSiteVisualAssembly(input: Omit<SiteVisualAssembly, "assemblyId" | "revision" | "contentSha256" | "createdAt" | "decidedAt" | "decidedBy">): SiteVisualAssembly { const loaded = load(); const prior = loaded.state.records.filter((item) => item.organizationId === input.organizationId && item.siteId === input.siteId && item.buildSessionId === input.buildSessionId && item.pageId === input.pageId); const existing = prior.find((item) => item.pageRevisionId === input.pageRevisionId && item.imageCandidateId === input.imageCandidateId && item.ownerInstructions === input.ownerInstructions); if (existing) return deepClone(existing); const record: SiteVisualAssembly = { ...input, assemblyId: `site-visual-${randomUUID()}`, revision: (prior.at(-1)?.revision ?? 0) + 1, contentSha256: createHash("sha256").update(input.contentHtml).digest("hex"), createdAt: new Date().toISOString(), decidedAt: null, decidedBy: null }; loaded.state.records.push(record); savePersistedState({ namespace: NAMESPACE, state: loaded.state, expectedRevision: loaded.revision }); return deepClone(record); }
export function decideSiteVisualAssembly(input: { organizationId: string; siteId: string; buildSessionId: string; assemblyId: string; decision: "APPROVE" | "REQUEST_CHANGES"; actor: string }): SiteVisualAssembly { const loaded = load(); const index = loaded.state.records.findIndex((item) => item.organizationId === input.organizationId && item.siteId === input.siteId && item.buildSessionId === input.buildSessionId && item.assemblyId === input.assemblyId); if (index < 0 || loaded.state.records[index].status !== "READY_FOR_OWNER_REVIEW") throw new Error("VISUAL_ASSEMBLY_NOT_REVIEWABLE"); loaded.state.records[index] = { ...loaded.state.records[index], status: input.decision === "APPROVE" ? "APPROVED" : "REVISION_REQUESTED", decidedAt: new Date().toISOString(), decidedBy: input.actor }; savePersistedState({ namespace: NAMESPACE, state: loaded.state, expectedRevision: loaded.revision }); return deepClone(loaded.state.records[index]); }