"use client";

import Link from "next/link";
import { useState } from "react";
import type { SitePublicationExecutionPreflight } from "./site-publication-execution-plan";

export function SitePublicationExecutionWorkflow({ preflight, site }: { preflight: SitePublicationExecutionPreflight; site: { organizationId: string; siteId: string } }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  async function authorizePolicy() {
    setBusy(true); setError(null);
    try {
      const response = await fetch(`/api/sites/${encodeURIComponent(site.siteId)}/site-build`, { method: "POST", headers: { "content-type": "application/json", "x-gcp-roles": "ops_manager", "x-gcp-organization-id": site.organizationId, "x-gcp-site-id": site.siteId }, body: JSON.stringify({ confirm: "AUTHORIZE_PUBLICATION_POLICY" }) });
      const payload = await response.json() as { error?: string };
      if (!response.ok) throw new Error(payload.error ?? "Publication policy authorization failed.");
      location.reload();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Publication policy authorization failed."); setBusy(false); }
  }
  async function execute() {
    setBusy(true); setError(null);
    try {
      const response = await fetch(`/api/sites/${encodeURIComponent(site.siteId)}/site-build`, { method: "POST", headers: { "content-type": "application/json", "x-gcp-roles": "ops_manager", "x-gcp-organization-id": site.organizationId, "x-gcp-site-id": site.siteId }, body: JSON.stringify({ confirm: "EXECUTE_APPROVED_PUBLICATION", executionPlanId: preflight.plan.executionPlanId }) });
      const payload = await response.json() as { workspace?: { next: { route: string } }; error?: string };
      if (!response.ok || !payload.workspace) throw new Error(payload.error ?? "Publication execution failed.");
      location.assign(payload.workspace.next.route);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Publication execution failed."); setBusy(false); }
  }
  const pageOperations = preflight.plan.operations.filter((operation) => operation.kind === "PUBLISH_PAGE");
  return <section className="space-y-6">
    <header className="border border-zinc-800 bg-zinc-950 p-6"><p className="text-xs font-semibold uppercase text-red-400">Publication Execution Review</p><h1 className="mt-2 text-2xl font-semibold text-white">Ready for publication execution</h1><p className="mt-2 text-sm text-zinc-300">Review the exact approved launch operations. Nothing on this page executes automatically.</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6"><div><dt className="text-zinc-500">Pages ready</dt><dd className="text-xl text-white">{preflight.pagePublishCount}</dd></div><div><dt className="text-zinc-500">Designs approved</dt><dd className="text-xl text-white">15</dd></div><div><dt className="text-zinc-500">Media synchronized</dt><dd className="text-xl text-white">15</dd></div><div><dt className="text-zinc-500">Navigation</dt><dd className="text-white">Approved</dd></div><div><dt className="text-zinc-500">Authorization</dt><dd className="text-emerald-300">RECORDED</dd></div><div><dt className="text-zinc-500">Publication</dt><dd className="text-amber-300">DISABLED</dd></div></dl></header>
    <section className="border border-zinc-800 bg-zinc-950"><header className="border-b border-zinc-800 p-5"><h2 className="font-semibold text-white">Exact WordPress page publications</h2><p className="mt-1 text-xs text-zinc-400">Existing objects only. No page creation.</p></header><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase text-zinc-500"><tr><th className="p-3">Operation</th><th className="p-3">Object ID</th><th className="p-3">Current</th><th className="p-3">Intended</th><th className="p-3">Receipt</th></tr></thead><tbody>{pageOperations.map((operation) => <tr key={operation.operationId} className="border-t border-zinc-800"><td className="p-3 text-white">{operation.label}</td><td className="p-3 font-mono text-zinc-300">{operation.targetId}</td><td className="p-3 text-zinc-300">{operation.currentState}</td><td className="p-3 text-emerald-300">{operation.intendedState}</td><td className="p-3 text-zinc-400">{operation.status}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><article className="border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-semibold text-white">Navigation/menu operation</h2><p className="mt-2 text-sm text-zinc-300">Mode: {preflight.navigation.mode.replaceAll("_", " ")}</p><p className="mt-1 text-sm text-zinc-300">{preflight.navigation.topLevelCount} top-level and {preflight.navigation.childCount} child items. Mutation required: {preflight.navigation.mutationRequired ? "Yes" : "No"}.</p><p className="mt-2 text-xs text-zinc-500">The approved navigation is embedded in and verified against every immutable visual assembly. No unrelated menu or theme location is changed.</p></article><article className="border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-semibold text-white">Static front page</h2><p className="mt-2 text-sm text-zinc-300">Current: {preflight.settings.showOnFront ?? "unknown"} / {preflight.settings.pageOnFront ?? "none"}</p><p className="mt-1 text-sm text-zinc-300">Intended: page / WordPress object {preflight.home.wordpressObjectId}</p><p className="mt-1 text-sm text-zinc-300">Mutation required: {preflight.home.assignmentRequired ? "Yes" : "No"}</p></article><article className="border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-semibold text-white">Media and SEO verification</h2><p className="mt-2 text-sm text-zinc-300">Preserve all 15 existing featured-media identities and verify all approved Yoast values after publication. No media upload or SEO write is planned.</p></article><article className="border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-semibold text-white">WordPress settings</h2><p className="mt-2 text-sm text-zinc-300">Permalink structure: {preflight.settings.permalinkStructure ?? "not exposed; preserve unchanged"}</p><p className="mt-1 text-sm text-zinc-300">No unrelated reading, permalink, theme, or menu-location changes are planned.</p></article><article className="border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-semibold text-white">Genesis state transition</h2><p className="mt-2 text-sm text-zinc-300">Current: {preflight.genesis.current}</p><p className="mt-1 text-sm text-zinc-300">After verified launch: {preflight.genesis.intended}</p><p className="mt-1 text-xs text-zinc-500">This occurs last, only after authenticated WordPress verification.</p></article><article className="border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-semibold text-white">Final verification</h2><p className="mt-2 text-sm text-zinc-300">Read back exact IDs, published status, slugs, content, media, SEO, navigation authority, front-page settings, and Genesis state. Completion requires every check to pass.</p></article></section>
    <section className="border border-zinc-800 bg-zinc-950 p-5"><h2 className="font-semibold text-white">Authenticated final preflight</h2><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-3">{Object.entries(preflight.checks).map(([key, value]) => <div key={key} className="border border-zinc-800 p-3"><dt className="text-zinc-500">{key.replaceAll(/([A-Z])/g, " $1")}</dt><dd className={value === true || value === 0 ? "font-semibold text-emerald-300" : "font-semibold text-red-300"}>{typeof value === "boolean" ? value ? "PASS" : "FAIL" : value}</dd></div>)}</dl></section>
    {preflight.blockers.length ? <section className="border-l-4 border-amber-500 bg-amber-950/20 p-5"><p className="text-xs font-semibold uppercase text-amber-300">Execution Blocked</p><h2 className="mt-2 text-xl font-semibold text-white">A required owner prerequisite is unresolved.</h2><ul className="mt-2 list-disc pl-5 text-sm text-amber-100">{preflight.blockers.map((blocker) => <li key={blocker}>{blocker.replaceAll("_", " ")}</li>)}</ul>{preflight.blockers.length === 1 && preflight.blockers[0] === "GENESIS_PUBLICATION_POLICY_TRANSITION_REQUIRED" ? <><p className="mt-3 text-sm text-zinc-300">Authorize this site to move from draft-only policy to publish-after-gates. This changes only the policy; the site remains configuring, disabled, and unpublished.</p><button disabled={busy} onClick={authorizePolicy} className="mt-4 border border-amber-500 px-5 py-3 text-sm font-semibold text-amber-100 disabled:opacity-40">AUTHORIZE PUBLICATION POLICY</button></> : null}</section> : null}
    {preflight.plan.status === "VERIFIED" ? <section className="border-l-4 border-emerald-500 bg-emerald-950/20 p-5"><p className="text-xs font-semibold uppercase text-emerald-300">Publication Complete</p><h2 className="mt-2 text-xl font-semibold text-white">Execution and authenticated verification are complete.</h2><Link href={`/sites/${site.siteId}?organizationId=${encodeURIComponent(site.organizationId)}&siteId=${encodeURIComponent(site.siteId)}`} className="mt-4 inline-block bg-red-600 px-5 py-3 text-sm font-semibold text-white">REVIEW COMPLETED SITE</Link></section> : <section className="border-l-4 border-red-600 bg-red-950/20 p-5"><p className="text-xs font-semibold uppercase text-red-300">Final Explicit Mutation Gate</p><h2 className="mt-2 text-xl font-semibold text-white">Execute the reviewed publication plan</h2><p className="mt-2 text-sm text-zinc-300">Execution is resumable and idempotent. Successful receipts are not repeated; failures remain visible for a reviewed retry.</p><button disabled={busy || !preflight.ready} onClick={execute} className="mt-4 bg-red-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy ? "EXECUTING APPROVED PUBLICATION..." : preflight.plan.status === "PARTIALLY_FAILED" ? "RESUME APPROVED PUBLICATION" : "EXECUTE APPROVED PUBLICATION"}</button>{error ? <p role="alert" className="mt-3 text-red-300">{error}</p> : null}</section>}
  </section>;
}
