"use client";

import Link from "next/link";
import type { SiteBuildWordPressDraftReview } from "./site-build-wordpress-review";
import type { SiteBuildStage } from "./site-build-stage";

export function SiteBuildWordPressDraftReviewWorkspace({ review, site, build }: { review: SiteBuildWordPressDraftReview; site: { organizationId: string; siteId: string; displayName: string }; build: { stage: SiteBuildStage; buildSessionId: string; totalVisualDesigns: number; approvedVisualDesigns: number; navigationItemCount: number } }) {
  const { summary, media, qa } = review;
  const lateStageRank: Partial<Record<SiteBuildStage, number>> = { WORDPRESS_DRAFT_REVIEW: 0, SITE_VISUAL_REVIEW: 1, SITE_QA: 2, NAVIGATION_REVIEW: 3, WORDPRESS_MENU_SYNC: 4, PUBLICATION_READINESS: 4, PUBLICATION_AUTHORIZATION: 5 };
  const currentRank = lateStageRank[build.stage] ?? 0;
  const steps = [{ label: "Page Review", rank: -2 }, { label: "WordPress Content Update", rank: -1 }, { label: "WordPress Draft Review", rank: 0 }, { label: "Site Visual Review", rank: 1 }, { label: "Site QA", rank: 2 }, { label: "Navigation Review", rank: 3 }, { label: "Publication Readiness", rank: 4 }, { label: "Publication Authorization", rank: 5 }].map((step) => ({ ...step, status: step.rank < currentRank ? "COMPLETE" as const : step.rank === currentRank ? "CURRENT" as const : "NEXT" as const }));
  const siteQaCurrent = build.stage === "SITE_QA";
  return <section className="space-y-6"><header className="border border-zinc-800 bg-zinc-950 p-6"><p className="text-xs font-semibold uppercase text-red-400">{siteQaCurrent ? "Site QA" : "WordPress Draft Review"}</p><h1 className="mt-2 text-2xl font-semibold text-white">{site.displayName}</h1><p className="mt-2 text-sm text-zinc-300">Review the exact synchronized WordPress drafts, approved visual assemblies, navigation proposal, and publication safeguards.</p><p className="mt-2 text-xs text-zinc-500">Build session {build.buildSessionId}. WordPress draft links open the authenticated WordPress editor and may require the owner to sign in.</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6"><div><p className="text-zinc-500">Synchronized drafts</p><p className="text-xl font-semibold text-emerald-300">{summary.verifiedDraftCount} / {summary.expectedCount}</p></div><div><p className="text-zinc-500">Approved designs</p><p className="text-xl font-semibold text-emerald-300">{build.approvedVisualDesigns} / {build.totalVisualDesigns}</p></div><div><p className="text-zinc-500">Attached media</p><p className="text-xl font-semibold text-white">{media.imagesAttachedToPages} / {summary.expectedCount}</p></div><div><p className="text-zinc-500">Navigation proposal</p><p className="text-xl font-semibold text-white">{build.navigationItemCount} items</p></div><div><p className="text-zinc-500">Published</p><p className="text-xl font-semibold text-white">{summary.publishedCount}</p></div><div><p className="text-zinc-500">Publication</p><p className="text-xl font-semibold text-amber-300">DISABLED</p></div></div></header>
    <ol className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{steps.map((step) => <li key={step.label} className={`border p-3 ${step.status === "CURRENT" ? "border-red-600 bg-red-950/20" : "border-zinc-800 bg-zinc-950"}`}><p className="text-xs font-semibold text-white">{step.label}</p><p className={`mt-1 text-xs ${step.status === "COMPLETE" ? "text-emerald-300" : step.status === "CURRENT" ? "text-amber-300" : "text-zinc-500"}`}>{step.status}</p></li>)}</ol>
    {media.mediaSyncStillRequired ? <section className="border-l-4 border-amber-500 bg-amber-950/20 p-5"><p className="text-xs font-semibold uppercase text-amber-300">Media Sync Required</p><h2 className="mt-2 text-lg font-semibold text-white">Approved imagery has not been assembled into every WordPress draft.</h2><p className="mt-2 text-sm text-zinc-300">{media.approvedImageCount} approved image requirements exist. {media.imagesAttachedToPages} draft pages currently contain or reference an image, across {media.wordpressMediaObjectCount} featured-media objects. Media upload and attachment remain a separate bounded owner action.</p></section> : null}
    <section className="overflow-x-auto border border-zinc-800 bg-zinc-950"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-zinc-800 text-xs uppercase text-zinc-500"><tr><th className="px-4 py-3">Page</th><th className="px-4 py-3">WordPress object</th><th className="px-4 py-3">Last synchronized revision</th><th className="px-4 py-3">Sync status</th><th className="px-4 py-3">Media</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{review.items.map((item) => <tr key={item.pageRevisionId} className="border-b border-zinc-900 align-top"><td className="px-4 py-4"><p className="font-semibold text-white">{item.pageName}</p><p className="mt-1 font-mono text-xs text-zinc-500">{item.canonicalPath}</p></td><td className="px-4 py-4"><p className="text-zinc-200">Object {item.wordpressObjectId}</p><p className={item.wordpressStatus === "draft" ? "mt-1 text-xs font-semibold text-emerald-300" : "mt-1 text-xs font-semibold text-red-300"}>{item.wordpressStatus?.toUpperCase() ?? "MISSING"}</p><p className="mt-1 text-xs text-zinc-500">/{item.expectedSlug}/</p></td><td className="px-4 py-4"><p className="text-zinc-200">{item.pageRevisionId}</p><p className="mt-1 text-xs text-zinc-500">Synced {item.synchronizedAt ?? "Unknown"}</p></td><td className="px-4 py-4"><p className={item.syncStatus === "VERIFIED" ? "font-semibold text-emerald-300" : "font-semibold text-amber-300"}>{item.syncStatus.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-zinc-500">SEO {item.seoReadback.replaceAll("_", " ")}</p></td><td className="px-4 py-4"><p className={item.imageAttached ? "text-emerald-300" : "text-amber-300"}>{item.imageAttached ? `Attached · ${item.featuredMediaId || "inline"}` : "Not attached"}</p></td><td className="px-4 py-4"><div className="flex flex-col items-start gap-2">{item.wordpressReviewUrl ? <a href={item.wordpressReviewUrl} target="_blank" rel="noreferrer" className="font-semibold text-red-300 underline">VIEW WORDPRESS DRAFT</a> : <span className="text-zinc-500">WordPress review unavailable</span>}<Link href={item.genesisReviewUrl} className="font-semibold text-zinc-300 underline">VIEW GENESIS APPROVED VERSION</Link><details><summary className="cursor-pointer font-semibold text-zinc-300">COMPARE / VERIFY</summary><ul className="mt-2 space-y-1 text-xs text-zinc-500"><li>ID {item.identityMatch ? "matches" : "mismatch"}</li><li>Slug {item.slugMatch ? "matches" : "mismatch"}</li><li>Title {item.titleMatch ? "matches" : "mismatch"}</li><li>Content {item.contentMatch ? "matches" : "mismatch"}</li></ul></details></div></td></tr>)}</tbody></table></section>
    <section className="border border-zinc-800 bg-zinc-950 p-6"><p className="text-xs font-semibold uppercase text-red-400">Site QA</p><h2 className="mt-2 text-xl font-semibold text-white">Draft site integrity</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-zinc-500">Architecture</dt><dd className="text-zinc-200">{qa.architectureComplete ? "Complete" : "Incomplete"}</dd></div><div><dt className="text-zinc-500">Orphan pages</dt><dd className="text-zinc-200">{qa.orphanPageCount}</dd></div><div><dt className="text-zinc-500">Invalid internal links</dt><dd className="text-zinc-200">{qa.invalidInternalLinkCount}</dd></div><div><dt className="text-zinc-500">Missing drafts</dt><dd className="text-zinc-200">{qa.missingDraftCount}</dd></div><div><dt className="text-zinc-500">Duplicate slugs</dt><dd className="text-zinc-200">{qa.duplicateSlugCount}</dd></div><div><dt className="text-zinc-500">Content mismatches</dt><dd className="text-zinc-200">{qa.contentMismatchCount}</dd></div><div><dt className="text-zinc-500">SEO mismatches</dt><dd className="text-zinc-200">{qa.seoMismatchCount}</dd></div><div><dt className="text-zinc-500">Navigation</dt><dd className="text-zinc-200">REVIEW ONLY</dd></div></dl><p className="mt-4 text-sm text-zinc-400">Navigation and menu mutation remain separate owner actions. Publication stays disabled until draft review, media synchronization, site QA, navigation assembly, and publication readiness are complete.</p></section>
  </section>;
}