"use client";

import Link from "next/link";
import { useState } from "react";
import type { CreativeDirectionProposal, SiteIntelligenceWorkspace } from "./site-intelligence";

type Props = {
  workspace: SiteIntelligenceWorkspace;
  busy: boolean;
  onAction(body: Record<string, unknown>): Promise<SiteIntelligenceWorkspace | null>;
};

function CreativeDecisionControls({ busy, placement, onAction }: { busy: boolean; placement: "top" | "bottom"; onAction(body: Record<string, unknown>): Promise<SiteIntelligenceWorkspace | null> }) {
  const decisions = [{ decision: "APPROVED", label: "APPROVE CREATIVE DIRECTION" }, { decision: "REVISION_REQUESTED", label: "REQUEST CHANGES" }, { decision: "REJECTED", label: "REJECT" }] as const;
  return <div aria-label={`${placement} creative review actions`} className={`${placement === "top" ? "mt-4" : "sticky bottom-0 mt-6 border-t border-zinc-800 bg-zinc-950/95 py-4"} flex flex-wrap gap-2`}>{decisions.map(({ decision, label }) => <button key={decision} type="button" disabled={busy} onClick={() => onAction({ action: "DECIDE_CREATIVE", decision, reason: `Owner creative decision: ${decision}.` })} className={decision === "APPROVED" ? "bg-emerald-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40" : "border border-zinc-700 px-4 py-3 text-sm font-semibold text-zinc-200 disabled:opacity-40"}>{label}</button>)}</div>;
}

function CreativeRevisionHistory({ revisions, activeRevision }: { revisions: CreativeDirectionProposal[]; activeRevision: number }) {
  return <div className="mt-4 border border-zinc-800 p-4"><h3 className="text-xs font-semibold uppercase text-zinc-400">Creative Revision History</h3><div className="mt-2 space-y-2">{revisions.map((revision) => { const active = revision.revision === activeRevision; return <div key={revision.revision} className={`flex flex-wrap justify-between gap-2 border p-3 text-xs ${active ? "border-red-700 bg-red-950/20" : "border-zinc-900"}`}><span className={active ? "font-semibold text-red-200" : "text-zinc-400"}>Revision {revision.revision} · {active && revision.status === "PROPOSED" ? "CURRENTLY AWAITING OWNER DECISION" : revision.status}</span><span className="text-zinc-500">{active ? "Active review" : "Historical revision"} · Strategy revision {revision.strategyRevision} · Created {revision.createdAt}</span></div>; })}</div></div>;
}

function CreativeProposalReview({ proposal }: { proposal: CreativeDirectionProposal }) {
  const textSections = [{ label: "Overall Visual Direction", value: proposal.overallDirection }, { label: "Color Direction", value: proposal.colorDirection }, { label: "Typography Direction", value: proposal.typographyDirection }, { label: "Layout Direction", value: proposal.spacingLayoutDirection }, { label: "Photography / Visual Asset Style", value: proposal.photographyStyle }, { label: "Product / Service Presentation", value: proposal.productPresentation }, { label: "Market / Vertical Presentation", value: proposal.verticalPresentation }, { label: "Conversion Direction", value: proposal.ctaTreatment }];
  return <div className="mt-4 space-y-4"><div className="grid gap-3 lg:grid-cols-2">{textSections.map((section) => <section key={section.label} className="border border-zinc-800 p-4"><h3 className="text-xs font-semibold uppercase text-zinc-400">{section.label}</h3><p className="mt-2 text-sm text-zinc-200">{section.value}</p></section>)}</div><section className="border border-zinc-800 p-4"><h3 className="text-xs font-semibold uppercase text-zinc-400">Homepage Blueprint</h3><ol className="mt-2 list-decimal space-y-1 pl-5 text-sm text-zinc-200">{proposal.homepageBlueprint.map((section) => <li key={section}>{section}</li>)}</ol></section><details className="border border-zinc-800 p-4"><summary className="cursor-pointer text-xs font-semibold uppercase text-zinc-400">Creative Guardrails</summary><div className="mt-3 grid gap-3 md:grid-cols-2"><div><h4 className="text-xs font-semibold text-emerald-300">Use</h4><ul className="mt-2 list-disc space-y-1 pl-5 text-xs text-zinc-300">{proposal.visualDos.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h4 className="text-xs font-semibold text-red-300">Avoid</h4><ul className="mt-2 list-disc space-y-1 pl-5 text-xs text-zinc-300">{proposal.visualDonts.map((item) => <li key={item}>{item}</li>)}</ul></div></div></details></div>;
}

export function SiteCreativeDirectionWorkflow({ workspace, busy, onAction }: Props) {
  const strategy = workspace.strategyRevisions.at(-1) ?? null;
  const proposal = workspace.creativeRevisions.at(-1) ?? null;
  const [ownerInstruction, setOwnerInstruction] = useState("");
  const [revisionInstructions, setRevisionInstructions] = useState("");
  const references = workspace.creativeInputs.filter((input) => input.classification === "OWNER_SUPPLIED_REFERENCE" || input.classification === "OWNER_APPROVED_PUBLISHABLE");

  async function generate(action: "GENERATE_CREATIVE_DIRECTION" | "GENERATE_REVISED_CREATIVE_DIRECTION") {
    const updated = await onAction({ action, ownerInstruction, revisionInstructions, reason: action === "GENERATE_CREATIVE_DIRECTION" ? "Owner requested assisted Creative Direction generation." : `Owner requested Creative Direction changes: ${revisionInstructions.trim()}` });
    if (!updated) return;
    requestAnimationFrame(() => {
      const review = document.getElementById("creative-direction");
      review?.focus({ preventScroll: true });
      review?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  }

  if (!proposal) return <section className="border border-zinc-800 bg-zinc-950 p-5"><p className="text-xs font-semibold uppercase text-red-300">Creative Direction</p><h2 className="mt-2 text-xl font-semibold text-white">Genesis will build a visual and structural direction from your approved strategy and creative references.</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div className="border border-zinc-800 p-3"><dt className="text-zinc-500">Approved strategy</dt><dd className="mt-1 font-semibold text-white">Revision {strategy?.status === "APPROVED" ? strategy.revision : "required"}</dd></div><div className="border border-zinc-800 p-3"><dt className="text-zinc-500">Creative references</dt><dd className="mt-1 font-semibold text-white">{references.length} owner {references.length === 1 ? "reference" : "references"}</dd></div></dl>{references.length ? <div className="mt-4 space-y-2">{references.map((reference) => <div key={reference.inputId} className="border border-zinc-800 p-3 text-xs"><strong className="text-zinc-200">{reference.binaryAsset?.originalFileName ?? reference.reference}</strong><span className="ml-2 text-amber-300">Inspiration / reference only · Not publishable</span>{reference.notes ? <p className="mt-1 text-zinc-400">Owner note: {reference.notes}</p> : null}</div>)}</div> : <p className="mt-4 text-sm text-zinc-500">No references are required; Genesis can synthesize from the approved strategy and authority.</p>}<label className="mt-4 block text-sm text-zinc-300">Anything you want Genesis to emphasize or avoid?<textarea value={ownerInstruction} onChange={(event) => setOwnerInstruction(event.target.value)} rows={3} className="mt-2 w-full border border-zinc-700 bg-zinc-900 p-3 text-white" placeholder="Optional: Keep it industrial and premium. Avoid a catalog look." /></label><button type="button" disabled={busy || strategy?.status !== "APPROVED"} onClick={() => generate("GENERATE_CREATIVE_DIRECTION")} className="mt-4 bg-red-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">GENERATE CREATIVE DIRECTION</button></section>;

  if (proposal.status === "APPROVED") return <section className="border border-emerald-800 bg-emerald-950/20 p-5"><p className="text-xs font-semibold uppercase text-emerald-300">Creative Direction approved</p><h2 className="mt-2 text-lg font-semibold text-white">Your market, capability, strategy, and creative decisions are complete.</h2><p className="mt-2 text-sm text-zinc-300">Next, establish product and service authority. Site generation remains disabled until bounded product onboarding is complete.</p><Link href={`/products/new?organizationId=${encodeURIComponent(workspace.organizationId)}&siteId=${encodeURIComponent(workspace.siteId)}&source=manual`} className="mt-4 inline-block bg-emerald-700 px-4 py-3 text-sm font-semibold text-white">CONTINUE TO PRODUCT / SERVICE AUTHORITY</Link><CreativeRevisionHistory revisions={workspace.creativeRevisions} activeRevision={proposal.revision} /></section>;

  if (proposal.status === "REVISION_REQUESTED" || proposal.status === "REJECTED") return <section className="border border-amber-800 bg-amber-950/20 p-5"><p className="text-xs font-semibold uppercase text-amber-300">Creative Direction changes requested</p><h2 className="mt-2 text-lg font-semibold text-white">What should Genesis change?</h2><p className="mt-1 text-sm text-zinc-300">Revision {proposal.revision} remains preserved in history.</p><textarea value={revisionInstructions} onChange={(event) => setRevisionInstructions(event.target.value)} rows={4} className="mt-3 w-full border border-amber-800 bg-zinc-950 p-3 text-white" placeholder="Describe the changes you want Genesis to make." /><button type="button" disabled={busy || !revisionInstructions.trim()} onClick={() => generate("GENERATE_REVISED_CREATIVE_DIRECTION")} className="mt-3 bg-red-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">GENERATE REVISED CREATIVE DIRECTION</button><CreativeRevisionHistory revisions={workspace.creativeRevisions} activeRevision={proposal.revision} /></section>;

  return <section className="border border-zinc-800 bg-zinc-950 p-5"><div className="border border-red-700 bg-red-950/30 p-5"><p className="text-xs font-semibold uppercase text-red-300">Creative Direction ready for review</p><h2 className="mt-2 text-xl font-semibold text-white">Current revision: {proposal.revision}</h2><p className="mt-1 text-sm font-semibold text-amber-200">Status: READY FOR REVIEW</p><p className="mt-3 text-sm text-zinc-300">Generated from approved strategy revision {proposal.strategyRevision}, finalized authority, and owner creative references.</p><CreativeDecisionControls busy={busy} placement="top" onAction={onAction} /></div><CreativeRevisionHistory revisions={workspace.creativeRevisions} activeRevision={proposal.revision} /><CreativeProposalReview proposal={proposal} /><CreativeDecisionControls busy={busy} placement="bottom" onAction={onAction} /></section>;
}