import type { SiteConfiguration } from "./types";

export const FOUNDATION_SITE_FIXTURES: readonly SiteConfiguration[] = [
  {
    siteId: "site-led-display-warehouse-production",
    organizationId: "led-display-warehouse",
    siteName: "LED Display Warehouse",
    displayName: "LEDDisplayWarehouse.com",
    slug: "led-display-warehouse",
    domain: "LEDDisplayWarehouse.com",
    primaryAddress: null,
    canonicalUrl: "https://leddisplaywarehouse.com",
    environment: "production",
    lifecycleState: "active",
    enabled: true,
    healthStatus: "degraded",
    publishingStatus: "not_ready",
    defaultContentType: "article",
    defaultPublicationStatus: "draft",
    defaultAuthorReference: null,
    defaultCategoryReferences: [],
    integrations: {
      wordpressApiBaseUrl: "https://leddisplaywarehouse.com/wp-json/wp/v2",
      wordpressCredentialReference: "LED_COMPANY_CREDENTIAL_REFERENCE",
      workflowReference: "profile-workflow-ledw-default",
    },
    profiles: {
      promptProfileReference: "profile-prompt-commercial-product",
      imageProfileReference: "profile-image-apple-product",
      seoProfileReference: "profile-seo-ledw-default",
      brandProfileReference: "profile-brand-ledw-default",
      analyticsProfileReference: "profile-analytics-ledw-default",
    },
    lastConnectionTest: null,
    lastSuccessfulPublication: null,
    lastHealthCheck: null,
    createdAt: "2026-07-29T00:00:00.000Z",
    updatedAt: "2026-07-29T00:00:00.000Z",
    notes: "Production foundation site. Publishing remains gated until publish-readiness certification passes.",
  },
  {
    siteId: "site-secondary-test-placeholder",
    organizationId: "led-display-warehouse",
    siteName: "Secondary Test Site",
    displayName: "Secondary Test Site",
    slug: "secondary-test-site",
    domain: null,
    primaryAddress: null,
    canonicalUrl: null,
    environment: "test",
    lifecycleState: "draft",
    enabled: false,
    healthStatus: "not_configured",
    publishingStatus: "disabled",
    defaultContentType: "article",
    defaultPublicationStatus: "draft",
    defaultAuthorReference: null,
    defaultCategoryReferences: [],
    integrations: {
      wordpressApiBaseUrl: null,
      wordpressCredentialReference: null,
      workflowReference: null,
    },
    profiles: {
      promptProfileReference: null,
      imageProfileReference: null,
      seoProfileReference: null,
      brandProfileReference: null,
      analyticsProfileReference: null,
    },
    lastConnectionTest: null,
    lastSuccessfulPublication: null,
    lastHealthCheck: null,
    createdAt: "2026-07-29T00:00:00.000Z",
    updatedAt: "2026-07-29T00:00:00.000Z",
    notes: "Placeholder only. Disabled and not publishable by design.",
  },
];
