import { createHash } from "node:crypto";

import type { CreativeDirectionProposal, SiteIntelligenceWorkspace, SiteStrategyProposal } from "./site-intelligence";
import type { SiteBuildPlanPage, SiteBuildPlanProposal } from "./site-build-plan";
import type { SiteProductServiceAuthority, SiteSource } from "./site-product-authority-repository";
import type { SiteConfiguration } from "./types";
import { isCapabilityReviewComplete, selectDistinctCapabilityOpportunities } from "./site-capability-transition";

export const SITE_PAGE_GENERATION_POLICY_VERSION = "fresh-site-page-generation-v2";

export type SitePageImageSource = "OWNER_ASSET" | "APPROVED_PUBLISHABLE_ASSET" | "GENERATED_VISUAL" | "PRODUCT_VISUAL" | "FABRICATION_VISUAL" | "REFERENCE_INSPIRATION_ONLY" | "PLACEHOLDER_REQUIRED";
export type SitePageSection = { sectionId: string; heading: string; level: 2 | 3; body: string[]; presentation: "HERO" | "PROSE" | "GRID" | "STEPS" | "FAQ" | "CTA" };
export type SitePageInternalLink = { linkId: string; href: string; anchorText: string; reason: string; targetPageId: string };
export type SitePageImageRequirement = { slotId: string; placement: string; subject: string; source: SitePageImageSource; publishableAssetId: string | null; status: "READY" | "OWNER_ASSET_NEEDED" | "GENERATED_CANDIDATE_NEEDED"; altTextGuidance: string };
export type SitePageQuality = { ready: boolean; blockers: string[]; warnings: string[]; checks: Record<string, boolean> };
export type SiteGeneratedPageRevision = {
  pageRevisionId: string; pageId: string; revision: number; status: "READY_FOR_OWNER_REVIEW" | "APPROVED" | "REVISION_REQUESTED"; requestedChanges: string | null;
  name: string; slug: string; canonicalPath: string; pageRole: SiteBuildPlanPage["pageType"]; seoTitle: string; metaDescription: string; openGraphTitle: string; openGraphDescription: string; h1: string;
  sections: SitePageSection[]; contentHtml: string; internalLinks: SitePageInternalLink[]; imageRequirements: SitePageImageRequirement[]; authority: SiteBuildPlanPage["authority"]; quality: SitePageQuality;
  contentFingerprint: string; createdAt: string; createdBy: string; decidedAt: string | null; decidedBy: string | null;
};
export type SiteNavigationItem = { label: string; href: string; children: Array<{ label: string; href: string }> };
export type SiteAssemblyProposal = { assemblyId: string; buildSessionId: string; organizationId: string; siteId: string; buildPlanRevision: number; creativeRevision: number; policyVersion: typeof SITE_PAGE_GENERATION_POLICY_VERSION; revision: number; status: "READY_FOR_OWNER_REVIEW" | "APPROVED" | "REVISION_REQUESTED"; pages: SiteGeneratedPageRevision[]; navigation: SiteNavigationItem[]; footerLinks: Array<{ label: string; href: string }>; siteWideInstructions: string | null; createdAt: string; createdBy: string };

const FORBIDDEN_PUBLIC_LANGUAGE = ["owner-confirmed", "approved authority", "approved strategy", "pending validation", "authority used", "evidence gated", "proposed from approved", "genesis"];
const PROTECTED_CLAIMS = /\b(certified|compliant|licensed|nationwide service|guaranteed|industry-leading|award-winning|customers? served|projects? completed)\b/i;
function escape(value: string): string { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;"); }
function pathFor(page: SiteBuildPlanPage): string { return page.slug ? `/${page.slug.replace(/^\/+|\/+$/g, "")}/` : "/"; }
function sentenceList(values: string[]): string { return values.length > 1 ? `${values.slice(0, -1).join(", ")}, and ${values.at(-1)}` : values[0] ?? "commercial stainless solutions"; }
function paragraph(...sentences: string[]): string { return sentences.filter(Boolean).join(" "); }
function section(pageId: string, index: number, heading: string, presentation: SitePageSection["presentation"], ...body: string[]): SitePageSection { return { sectionId: `${pageId}-section-${index}`, heading, level: 2, body, presentation }; }
function render(page: Pick<SiteGeneratedPageRevision, "h1" | "sections" | "internalLinks">): string { const links = page.internalLinks.map((link) => `<li><a href="${escape(link.href)}">${escape(link.anchorText)}</a></li>`).join(""); return [`<h1>${escape(page.h1)}</h1>`, ...page.sections.flatMap((item) => [`<h${item.level}>${escape(item.heading)}</h${item.level}>`, ...item.body.map((body) => `<p>${escape(body)}</p>`)]), links ? `<nav aria-label="Related pages"><ul>${links}</ul></nav>` : ""].filter(Boolean).join("\n"); }

export function evaluateGeneratedPageQuality(input: { page: Omit<SiteGeneratedPageRevision, "quality">; validPaths: Set<string>; duplicateFingerprints: Set<string> }): SitePageQuality {
  const publicText = [input.page.h1, input.page.seoTitle, input.page.metaDescription, ...input.page.sections.flatMap((item) => [item.heading, ...item.body])].join(" ").toLowerCase();
  const checks = {
    noSeedCopy: !/proposed from approved strategy|help .+ buyers understand the approved offerings/i.test(publicText), noGovernanceLanguage: !FORBIDDEN_PUBLIC_LANGUAGE.some((term) => publicText.includes(term)), noProtectedClaims: !PROTECTED_CLAIMS.test(publicText),
    seoComplete: Boolean(input.page.seoTitle.trim() && input.page.metaDescription.trim() && input.page.openGraphTitle.trim() && input.page.openGraphDescription.trim() && input.page.h1.trim()), canonicalPathValid: /^\/(?:[a-z0-9]+(?:-[a-z0-9]+)*\/)*$/.test(input.page.canonicalPath),
    contentSubstantial: input.page.sections.length >= 4 && input.page.contentHtml.length >= 900, linksValid: input.page.internalLinks.every((link) => input.validPaths.has(link.href)), notOrphaned: input.page.canonicalPath === "/" || input.page.internalLinks.length > 0,
    uniqueContent: !input.duplicateFingerprints.has(input.page.contentFingerprint), imageProvenanceBounded: input.page.imageRequirements.every((image) => image.source !== "REFERENCE_INSPIRATION_ONLY" || image.publishableAssetId === null),
  };
  const blockers = Object.entries(checks).filter(([, passed]) => !passed).map(([key]) => key);
  return { ready: blockers.length === 0, blockers, warnings: input.page.imageRequirements.some((item) => item.status !== "READY") ? ["Owner-approved or generated visual assets are still needed for one or more placements."] : [], checks };
}

function pageLinks(page: SiteBuildPlanPage, all: SiteBuildPlanPage[], core: SiteBuildPlanPage | undefined): SitePageInternalLink[] {
  const quote = all.find((item) => item.pageType === "CONTACT"); const capabilities = all.find((item) => item.pageType === "CAPABILITIES"); const about = all.find((item) => item.pageType === "ABOUT"); const offerings = all.filter((item) => item.pageType === "OFFERING"); const markets = all.filter((item) => item.pageType === "MARKET");
  const targets = page.pageType === "HOME" ? [core, capabilities, about, ...offerings, ...markets, quote] : page.pageType === "CATEGORY" ? [...offerings, capabilities, quote] : page.pageType === "OFFERING" ? [core, ...markets.filter((item) => item.authority.some((authority) => page.authority.some((own) => own.kind === authority.kind && own.referenceId === authority.referenceId))).slice(0, 3), quote] : page.pageType === "MARKET" ? [core, ...offerings.slice(0, 3), quote] : page.pageType === "ABOUT" ? [capabilities, quote] : page.pageType === "CAPABILITIES" ? [core, ...offerings, quote] : [core];
  return [...new Map(targets.filter((item): item is SiteBuildPlanPage => Boolean(item && item.pageId !== page.pageId)).map((item) => [item.pageId, item])).values()].map((item, index) => ({ linkId: `${page.pageId}-link-${index}`, href: pathFor(item), anchorText: item.name, reason: `Connect ${page.name} to the related ${item.pageType.toLowerCase()} pathway.`, targetPageId: item.pageId }));
}

function sectionsFor(input: { page: SiteBuildPlanPage; site: SiteConfiguration; strategy: SiteStrategyProposal; offerings: SiteProductServiceAuthority[]; markets: SiteBuildPlanPage[]; core?: SiteBuildPlanPage }): SitePageSection[] {
  const { page, site, strategy } = input; const names = input.offerings.map((item) => item.displayName); const primaryCta = strategy.ctaHierarchy[0] ?? "Request a Quote";
  if (page.pageType === "HOME") return [section(page.pageId, 1, "Commercial stainless solutions built around your project", "HERO", paragraph(`${site.displayName} helps ${strategy.primaryAudience.toLowerCase()} turn project requirements into practical stainless counter, worktable, workstation, and fabrication solutions.`, `Explore ${sentenceList(names)} and move from early planning to a quote-ready conversation.`)), section(page.pageId, 2, "Start with the right stainless solution", "GRID", `Compare the available product and service pathways by application, workflow, footprint, and project need. Each path gives buyers a focused place to organize requirements before requesting a quote.`), section(page.pageId, 3, "Plan for the way your space works", "PROSE", `Commercial stainless projects are shaped by how people prepare, stage, clean, move, store, and serve. Define the work sequence, available space, interfaces, and desired outcome before selecting details.`), section(page.pageId, 4, "Industries and applications", "GRID", `Browse focused guidance for ${sentenceList(input.markets.map((item) => item.name.replace(/ Solutions$/, "")))} environments without forcing every project into the same template.`), section(page.pageId, 5, "A clearer path to a quote", "STEPS", `Share drawings, dimensions, photographs, schedules, and performance requirements that are known. Open questions can be identified for follow-up rather than filled with assumptions.`), section(page.pageId, 6, primaryCta, "CTA", `Bring the project context together and start a practical conversation about the next step.`)];
  if (page.pageType === "CATEGORY") return [section(page.pageId, 1, `${page.name} for commercial environments`, "HERO", `${page.name} brings together the counter, worktable, workstation, and fabrication pathways available for commercial project planning.`), section(page.pageId, 2, "Choose the right product or service path", "GRID", `Explore ${sentenceList(names)} based on the work the surface must support, the surrounding equipment and casework, and the information available for the project.`), section(page.pageId, 3, "Define the project before defining the details", "STEPS", `Document the intended use, overall dimensions, interfaces, openings, supports, edges, access, delivery constraints, and schedule. Project-specific details should be confirmed before final specification.`), section(page.pageId, 4, "Built around real workflows", "PROSE", `A useful commercial surface supports the people, equipment, cleaning routines, and movement patterns around it. Start with those operating needs and use them to guide the design conversation.`), section(page.pageId, 5, "Questions buyers often ask", "FAQ", `What information helps start a quote? Drawings, dimensions, photographs, application details, and schedule context are useful starting points.`, `Can project-specific options be discussed? Yes. Describe the requirement so available approaches and open decisions can be reviewed.`), section(page.pageId, 6, primaryCta, "CTA", `Discuss the counter or fabrication requirement with the information already available.`)];
  if (page.pageType === "OFFERING") return [section(page.pageId, 1, `${page.name} for demanding commercial workflows`, "HERO", `${page.name} can be planned around the work sequence, available footprint, adjacent equipment, and practical needs of the project.`), section(page.pageId, 2, "Where this solution fits", "PROSE", `Use this pathway when the project calls for a focused stainless solution that supports daily commercial activity and can be coordinated with the surrounding environment.`), section(page.pageId, 3, "Information to gather", "STEPS", `Record dimensions, intended use, equipment interfaces, openings, edge conditions, supports, mobility needs, access constraints, and schedule. Mark assumptions clearly so they can be resolved before finalization.`), section(page.pageId, 4, "Coordinate the complete requirement", "GRID", `Consider the relationship between the stainless component and utilities, walls, floors, casework, equipment, cleaning access, traffic flow, and delivery path.`), section(page.pageId, 5, "Project planning FAQ", "FAQ", `Are all projects configured the same way? No. The appropriate details depend on the documented application and constraints.`, `What should be submitted for review? Send available drawings, photographs, dimensions, specifications, and the desired outcome.`), section(page.pageId, 6, primaryCta, "CTA", `Share the project requirement and identify the decisions needed for a useful quote conversation.`)];
  if (page.pageType === "MARKET") { const market = page.name.replace(/ Solutions$/, ""); return [section(page.pageId, 1, `Commercial stainless planning for ${market.toLowerCase()} environments`, "HERO", `${market} projects benefit from stainless solutions organized around workflow, cleaning, durability, equipment coordination, and the people who use the space.`), section(page.pageId, 2, `${market} project priorities`, "PROSE", `Begin with the operating context: what happens in the space, who uses it, what equipment surrounds the work area, and which requirements are already documented.`), section(page.pageId, 3, "Relevant solution pathways", "GRID", `Review ${sentenceList(names)} as distinct starting points. Final suitability and project details should be confirmed against the actual requirement.`), section(page.pageId, 4, "Coordinate stakeholders and interfaces", "STEPS", `Identify the owner, designer, consultant, contractor, equipment team, and other responsible parties as applicable. Record interfaces and unresolved decisions before fabrication planning advances.`), section(page.pageId, 5, "Questions for early planning", "FAQ", `What makes a useful request? Clear application context, available dimensions, drawings, photographs, schedule, and known constraints.`, `Does this page replace project-specific review? No. It helps organize the conversation before details are confirmed.`), section(page.pageId, 6, primaryCta, "CTA", `Bring the ${market.toLowerCase()} requirement into a focused quote and planning conversation.`)]; }
  if (page.pageType === "CAPABILITIES") return [section(page.pageId, 1, "Stainless fabrication capabilities for commercial project needs", "HERO", `Explore how current fabrication and solution pathways can support counters, worktables, workstations, and project-specific stainless requirements.`), section(page.pageId, 2, "From requirement to practical scope", "STEPS", `A productive process starts with the intended application and available project information, then identifies open details before a quote or fabrication decision.`), section(page.pageId, 3, "Products and fabrication pathways", "GRID", `Use ${sentenceList(names)} to navigate to the most relevant starting point.`), section(page.pageId, 4, "Details that shape the work", "PROSE", `Dimensions, interfaces, openings, supports, edges, mobility, finish expectations, access, and schedule can affect the appropriate approach. These details remain project-specific until confirmed.`), section(page.pageId, 5, "Capability FAQ", "FAQ", `Can an unusual requirement be discussed? Yes. Share the available context so feasibility and next questions can be reviewed.`, `Should specifications be assumed from a similar project? No. Material project details should be confirmed for the current requirement.`), section(page.pageId, 6, primaryCta, "CTA", `Discuss the application, available documentation, and desired outcome.`)];
  if (page.pageType === "ABOUT") return [section(page.pageId, 1, `About ${site.displayName}`, "HERO", `${site.displayName} is focused on helping commercial buyers organize stainless counter, worktable, workstation, and fabrication requirements into clear project conversations.`), section(page.pageId, 2, "A practical project-first approach", "PROSE", `The work begins with the application, operating context, and information available. Unknown details are identified for review instead of being treated as settled.`), section(page.pageId, 3, "What to expect", "STEPS", `Share the requirement. Review the available product and fabrication paths. Clarify project-specific decisions. Move toward a quote-ready scope.`), section(page.pageId, 4, "Explore capabilities and solutions", "GRID", `Navigate the site by product, service, industry, or project need to find the most useful starting point.`), section(page.pageId, 5, "Start the conversation", "CTA", `Bring drawings, dimensions, photographs, specifications, and schedule context when available.`)];
  return [section(page.pageId, 1, "Request a quote for your commercial stainless project", "HERO", `Share the project context available today. The goal is to understand the requirement, identify open decisions, and create a useful next step.`), section(page.pageId, 2, "Information that helps", "GRID", `Include contact information, project type, intended application, dimensions, location of use, desired schedule, drawings, photographs, equipment interfaces, and any written requirements that matter.`), section(page.pageId, 3, "What happens next", "STEPS", `The request can be reviewed for scope, relevant solution pathways, missing information, and follow-up questions before details are treated as final.`), section(page.pageId, 4, "Do not wait for perfect documentation", "PROSE", `Early plans often contain open questions. Send what is known and label assumptions so the conversation can focus on the decisions that matter.`), section(page.pageId, 5, "Submit your project", "CTA", `Start with the available requirement and the preferred way to continue the conversation.`)];
}

function applyGenerationInstructions(pageId: string, sections: SitePageSection[], instructions: string | null | undefined): SitePageSection[] {
  if (!instructions?.trim()) return sections;
  const normalized = instructions.toLowerCase(); const result = [...sections];
  if (/quote|contact|conversion|call.to.action/.test(normalized)) { const ctaIndex = result.findIndex((item) => item.presentation === "CTA"); const cta = ctaIndex >= 0 ? result.splice(ctaIndex, 1)[0] : section(pageId, 90, "Discuss your project", "CTA", "Share the available project information and identify the most useful next step."); result.splice(1, 0, { ...cta, body: [...cta.body, "This revision gives the project inquiry path greater prominence for buyers who are ready to continue."] }); }
  else if (/faq|question/.test(normalized)) result.splice(-1, 0, section(pageId, 91, "Additional buyer questions", "FAQ", "What information can be shared early? Send the application, available dimensions, drawings, photographs, schedule, and known constraints.", "How are open details handled? They remain visible for project-specific follow-up rather than being filled with assumptions."));
  else if (/shorter|concise|simplif/.test(normalized) && result.length > 4) result.splice(2, 1);
  else result.splice(-1, 0, section(pageId, 92, "Additional planning guidance", "PROSE", "This revision expands practical buyer guidance around project context, interfaces, available documentation, and the decisions that should be resolved before finalization."));
  return result.map((item, index) => ({ ...item, sectionId: `${pageId}-section-${index + 1}` }));
}

function revisedCommercialHomepage(input: { page: SiteBuildPlanPage; site: SiteConfiguration; strategy: SiteStrategyProposal; core?: SiteBuildPlanPage; offerings: SiteProductServiceAuthority[]; markets: SiteBuildPlanPage[] }): SitePageSection[] {
  const primary = input.core?.name ?? input.site.displayName; const offeringNames = input.offerings.map((item) => item.displayName); const marketNames = input.markets.map((item) => item.name.replace(/ Solutions$/, "")); const cta = input.strategy.ctaHierarchy[0] ?? "Request a Quote";
  return [
    section(input.page.pageId, 1, `${primary} and custom stainless fabrication`, "HERO", `${input.site.displayName} is a commercial stainless fabrication resource for businesses and organizations that need counters, worktables, prep tables, workstations, and project-specific stainless solutions.`, `Connect the application, dimensions, workflow, and available project documents to the right product or fabrication path, then move directly into a quote conversation.`),
    section(input.page.pageId, 2, "Commercial stainless products and fabrication solutions", "GRID", `Explore ${sentenceList(offeringNames)}. Each pathway focuses the conversation on what buyers need to accomplish in the space rather than forcing every requirement into one generic product.`),
    section(input.page.pageId, 3, `${primary}: the central project pathway`, "PROSE", `${primary} is the primary hub for commercial counter requirements, connecting buyers to related countertop, worktable, workstation, and design-build fabrication options.`, `Use it to organize the intended application, footprint, adjacent equipment, interfaces, openings, supports, edges, and other project-specific decisions before final details are established.`),
    section(input.page.pageId, 4, "Solutions for commercial industries", "GRID", `Navigate focused pathways for ${sentenceList(marketNames)} environments. Foodservice guidance includes restaurant buyers within the broader foodservice pathway, avoiding a second page with substantially duplicate intent.`),
    section(input.page.pageId, 5, "A fabrication approach built around the requirement", "STEPS", `Start with the commercial objective and the information already available. Review the relevant counter, product, or fabrication pathway. Identify interfaces and open decisions. Bring the resulting scope into a quote-ready conversation.`),
    section(input.page.pageId, 6, "Fabrication proof and project detail", "PROSE", `This section is structured for attributable fabrication imagery, process detail, and project evidence as suitable material becomes available. Until then, the site does not substitute generic claims, customer names, project counts, or unsupported photography for real proof.`),
    section(input.page.pageId, 7, "Why commercial buyers use this resource", "GRID", `Move quickly from a broad need to the most relevant product or service path. Keep project-specific unknowns visible. Coordinate the information that affects the requirement. Give purchasing, design, operations, and project teams a clearer basis for discussion.`),
    section(input.page.pageId, 8, cta, "CTA", `Share the intended application, available dimensions, drawings, photographs, equipment context, schedule, and known constraints. Start with what is available and identify the next decisions together.`),
  ];
}

export function synthesizeSiteAssembly(input: { site: SiteConfiguration; buildSessionId: string; plan: SiteBuildPlanProposal; intelligence: SiteIntelligenceWorkspace; strategy: SiteStrategyProposal; creative: CreativeDirectionProposal; candidates: SiteProductServiceAuthority[]; sources: SiteSource[]; revision: number; actor: string; instructions?: string | null; now?: string }): SiteAssemblyProposal {
  if (input.plan.status !== "APPROVED" || input.strategy.status !== "APPROVED" || input.creative.status !== "APPROVED") throw new Error("APPROVED_SITE_ASSEMBLY_AUTHORITY_REQUIRED");
  const pages = input.plan.pages.filter((item) => item.launchPhase === "INITIAL"); const paths = new Set(pages.map(pathFor)); const core = pages.find((item) => item.pageType === "CATEGORY"); const markets = pages.filter((item) => item.pageType === "MARKET");
  const approvedCandidates = input.candidates.filter((item) => (item.decision === "APPROVED" || item.decision === "QUALIFIED") && (item.protectedClaimBlockers.length === 0 || item.authorityBasis === "OWNER_ATTESTED_AND_EVIDENCE"));
  const publishable = new Map(input.intelligence.creativeInputs.filter((item) => item.classification === "OWNER_APPROVED_PUBLISHABLE" && item.binaryAsset).map((item) => [item.binaryAsset!.assetId, item]));
  const opportunities = selectDistinctCapabilityOpportunities(input.intelligence.opportunities ?? []); const approvedMarkets = new Set(opportunities.filter((item) => item.ownerDecision === "APPROVED").map((item) => item.opportunityId)); const currentCapabilities = new Set(opportunities.filter(isCapabilityReviewComplete).map((item) => item.opportunityId)); const approvedProducts = new Set(approvedCandidates.map((item) => item.authorityId));
  const fingerprints = new Set<string>(); const intentKeys = new Set<string>(); const generated: SiteGeneratedPageRevision[] = [];
  for (const planPage of pages) {
    const links = pageLinks(planPage, pages, core); const sections = planPage.pageType === "HOME" && input.instructions?.trim() ? revisedCommercialHomepage({ page: planPage, site: input.site, strategy: input.strategy, core, offerings: approvedCandidates, markets }) : applyGenerationInstructions(planPage.pageId, sectionsFor({ page: planPage, site: input.site, strategy: input.strategy, offerings: approvedCandidates, markets, core }), input.instructions); const h1 = sections[0].heading;
    const imageSource: SitePageImageSource = planPage.pageType === "OFFERING" ? "PRODUCT_VISUAL" : planPage.pageType === "CAPABILITIES" ? "FABRICATION_VISUAL" : "GENERATED_VISUAL";
    const imageRequirements: SitePageImageRequirement[] = [{ slotId: `${planPage.pageId}-hero`, placement: "Hero", subject: `${planPage.name} in a credible commercial stainless context`, source: publishable.size ? "APPROVED_PUBLISHABLE_ASSET" : imageSource, publishableAssetId: publishable.keys().next().value ?? null, status: publishable.size ? "READY" : imageSource === "GENERATED_VISUAL" ? "GENERATED_CANDIDATE_NEEDED" : "OWNER_ASSET_NEEDED", altTextGuidance: `Describe the visible ${planPage.name.toLowerCase()} subject without implying a customer, project, certification, or location.` }];
    const canonicalPath = pathFor(planPage); const fabrication = approvedCandidates.some((item) => /fabrication/i.test(item.displayName)) ? "Custom Stainless Fabrication" : "Commercial Stainless Solutions"; const seoTitle = (planPage.pageType === "HOME" ? `${core?.name ?? input.site.displayName} & ${fabrication}` : `${planPage.name} | ${input.site.displayName}`).slice(0, 60); const metaDescription = (planPage.pageType === "HOME" ? `${input.site.displayName} connects commercial buyers with counters, countertops, worktables, workstations, and custom stainless fabrication pathways.` : `${h1}. Explore practical planning guidance and request a quote for your commercial stainless project.`).slice(0, 155);
    const base = { pageRevisionId: `${planPage.pageId}-generation-${input.revision}`, pageId: planPage.pageId, revision: input.revision, status: "READY_FOR_OWNER_REVIEW" as const, requestedChanges: input.instructions?.trim() || null, name: planPage.name, slug: planPage.slug, canonicalPath, pageRole: planPage.pageType, seoTitle, metaDescription, openGraphTitle: seoTitle, openGraphDescription: metaDescription, h1, sections, contentHtml: "", internalLinks: links, imageRequirements, authority: planPage.authority, contentFingerprint: "", createdAt: input.now ?? new Date().toISOString(), createdBy: input.actor, decidedAt: null, decidedBy: null };
    base.contentHtml = render(base); base.contentFingerprint = createHash("sha256").update(base.contentHtml).digest("hex"); const quality = evaluateGeneratedPageQuality({ page: base, validPaths: paths, duplicateFingerprints: fingerprints });
    const authorityValid = planPage.authority.every((item) => item.kind === "PRODUCT_SERVICE" ? approvedProducts.has(item.referenceId) : item.kind === "MARKET" ? approvedMarkets.has(item.referenceId) : item.kind === "CAPABILITY" ? currentCapabilities.has(item.referenceId) : true); const intentKey = planPage.name.toLowerCase().replace(/\b(commercial|solutions?|products?|services?)\b/g, "").replace(/[^a-z0-9]+/g, ""); const duplicateIntent = intentKeys.has(intentKey);
    quality.checks.approvedAuthorityOnly = authorityValid; quality.checks.distinctSearchIntent = !duplicateIntent; if (!authorityValid) quality.blockers.push("approvedAuthorityOnly"); if (duplicateIntent) quality.blockers.push("distinctSearchIntent"); quality.ready = quality.blockers.length === 0; fingerprints.add(base.contentFingerprint); intentKeys.add(intentKey); generated.push({ ...base, quality, status: quality.ready ? "READY_FOR_OWNER_REVIEW" : "REVISION_REQUESTED" });
  }
  const inbound = new Map(generated.map((item) => [item.pageId, 0])); for (const generatedPage of generated) for (const link of generatedPage.internalLinks) inbound.set(link.targetPageId, (inbound.get(link.targetPageId) ?? 0) + 1);
  for (const generatedPage of generated) if (generatedPage.canonicalPath !== "/" && (inbound.get(generatedPage.pageId) ?? 0) === 0) { generatedPage.quality.ready = false; generatedPage.quality.blockers.push("orphanPage"); generatedPage.quality.checks.notOrphaned = false; generatedPage.status = "REVISION_REQUESTED"; }
  const offerings = pages.filter((item) => item.pageType === "OFFERING").map((item) => ({ label: item.name, href: pathFor(item) })); const industries = markets.map((item) => ({ label: item.name.replace(/ Solutions$/, ""), href: pathFor(item) }));
  const navigation: SiteNavigationItem[] = [{ label: core?.name ?? input.site.displayName, href: core ? pathFor(core) : "/", children: [] }, { label: "Products & Solutions", href: core ? pathFor(core) : "/", children: offerings }, { label: "Industries", href: industries[0]?.href ?? "/", children: industries }, ...pages.filter((item) => ["CAPABILITIES", "ABOUT", "CONTACT"].includes(item.pageType)).map((item) => ({ label: item.name, href: pathFor(item), children: [] }))];
  return { assemblyId: `${input.buildSessionId}-assembly-${input.revision}`, buildSessionId: input.buildSessionId, organizationId: input.site.organizationId, siteId: input.site.siteId, buildPlanRevision: input.plan.revision, creativeRevision: input.creative.revision, policyVersion: SITE_PAGE_GENERATION_POLICY_VERSION, revision: input.revision, status: generated.every((item) => item.quality.ready) ? "READY_FOR_OWNER_REVIEW" : "REVISION_REQUESTED", pages: generated, navigation, footerLinks: pages.filter((item) => ["ABOUT", "CONTACT", "CAPABILITIES"].includes(item.pageType)).map((item) => ({ label: item.name, href: pathFor(item) })), siteWideInstructions: input.instructions?.trim() || null, createdAt: input.now ?? new Date().toISOString(), createdBy: input.actor };
}