import { NextRequest, NextResponse } from "next/server";

import { authorizeRequest, hasOrganizationScope, isRecordInScope, resolveRequestScope } from "@/modules/foundation/api-auth";
import { certifyCommercialStainlessDesignBuildCandidate, inspectCommercialStainlessDesignBuild, listCommercialStainlessDesignBuildStageRecords, restageCommercialStainlessDesignBuild, stageCommercialStainlessDesignBuild, summarizeCommercialStainlessDesignBuildStageRecord, type CommercialStainlessDesignBuildViewportEvidence } from "@/modules/foundation/commercial-stainless-design-build-staging";
import { getSiteById } from "@/modules/foundation/site-repository";

type Context = { params: Promise<{ siteId: string }> };
async function scoped(request: NextRequest, context: Context) { const scope = resolveRequestScope(request); const { siteId } = await context.params; const site = getSiteById(siteId); return hasOrganizationScope(scope) && site && isRecordInScope({ recordOrganizationId: site.organizationId, recordSiteId: site.siteId, scope }) ? site : null; }
const records = () => listCommercialStainlessDesignBuildStageRecords().map(summarizeCommercialStainlessDesignBuildStageRecord);
export async function GET(request: NextRequest, context: Context) { const auth = authorizeRequest(request, "sites:read"); if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status }); const site = await scoped(request, context); if (!site) return NextResponse.json({ error: "Site not found" }, { status: 404 }); try { return NextResponse.json({ preflight: await inspectCommercialStainlessDesignBuild(site), records: records(), mutationPerformed: false, publicationMutation: false }); } catch (cause) { return NextResponse.json({ error: cause instanceof Error ? cause.message : "DESIGN_BUILD_INSPECTION_FAILED", records: records(), publicationMutation: false }, { status: 409 }); } }
export async function POST(request: NextRequest, context: Context) { const auth = authorizeRequest(request, "sites:manage_integrations"); if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status }); const site = await scoped(request, context); if (!site) return NextResponse.json({ error: "Site not found" }, { status: 404 }); const body = await request.json().catch(()=>null) as {confirm?:string;viewports?:CommercialStainlessDesignBuildViewportEvidence[]}|null;if(!body||!["STAGE_COMMERCIAL_STAINLESS_DESIGN_BUILD_MODERNIZATION_V1","RESTAGE_COMMERCIAL_STAINLESS_DESIGN_BUILD_MODERNIZATION_V1","CERTIFY_COMMERCIAL_STAINLESS_DESIGN_BUILD_NATIVE_EQUIVALENT_V1"].includes(body.confirm??""))return NextResponse.json({error:"Exact Design-Build staging or certification confirmation is required."},{status:400});try{if(body.confirm==="CERTIFY_COMMERCIAL_STAINLESS_DESIGN_BUILD_NATIVE_EQUIVALENT_V1")return NextResponse.json({record:summarizeCommercialStainlessDesignBuildStageRecord(certifyCommercialStainlessDesignBuildCandidate(body.viewports??[])),wordpressMutation:false,publicationMutation:false});const record=body.confirm==="RESTAGE_COMMERCIAL_STAINLESS_DESIGN_BUILD_MODERNIZATION_V1"?await restageCommercialStainlessDesignBuild(site):await stageCommercialStainlessDesignBuild(site);return NextResponse.json({record:summarizeCommercialStainlessDesignBuildStageRecord(record),wordpressMutation:true,publicationMutation:false});}catch(cause){return NextResponse.json({error:cause instanceof Error?cause.message:"DESIGN_BUILD_STAGING_FAILED",records:records(),publicationMutation:false},{status:409});}}
