jest.mock("server-only",()=>({}));
import { evaluateThemeIntegrationReady } from "../dallas-public-theme-integration";
import { readFileSync } from "node:fs";import { join } from "node:path";
const viewports=["DESKTOP_1440","DESKTOP_1024","TABLET_768","MOBILE_375"] as const;const roles=["PRODUCT_AUTHORITY","CONTEXTUAL_IN_USE","APPLICATION_EXPERIENCE","LOCAL_CONTEXTUAL_ATMOSPHERE"];
const captures=viewports.map(viewport=>({viewport,horizontalOverflow:0,themeIntegration:{visibleH1Count:1,visibleH1Texts:["Protected projection, planned for North Texas."],duplicateThemeTitleVisible:false,duplicateThemeFeaturedMediaVisible:false,globalHeaderPresent:true,globalFooterPresent:true,overflowElements:[]},mediaRolesRendered:roles}));
describe("Dallas public theme integration",()=>{
  test("passes only the separated theme-integrated render with one Genesis H1 and zero overflow",()=>{expect(evaluateThemeIntegrationReady(captures)).toEqual({state:"PASS",failures:[]})});
  test("detects the prior duplicate Cerato title and featured media",()=>{const broken=captures.map(item=>({...item,themeIntegration:{...item.themeIntegration,visibleH1Count:2,visibleH1Texts:["Fan Cooled Projector Enclosures in Dallas","Protected projection, planned for North Texas."],duplicateThemeTitleVisible:true,duplicateThemeFeaturedMediaVisible:true}}));expect(evaluateThemeIntegrationReady(broken)).toMatchObject({state:"FAIL",failures:expect.arrayContaining(["DESKTOP_1440_H1_COUNT","DESKTOP_1440_THEME_TITLE","DESKTOP_1440_THEME_FEATURED_MEDIA"])})});
  test("reproduces and rejects the exact 1024 overflow without masking",()=>{const broken=captures.map(item=>item.viewport==="DESKTOP_1024"?{...item,horizontalOverflow:107}:item);expect(evaluateThemeIntegrationReady(broken)).toEqual({state:"FAIL",failures:["DESKTOP_1024_OVERFLOW"]})});
  test("rejects removing or replacing the approved Genesis H1",()=>{const broken=captures.map(item=>({...item,themeIntegration:{...item.themeIntegration,visibleH1Texts:["Wrong H1"]}}));expect(evaluateThemeIntegrationReady(broken).failures).toContain("DESKTOP_1440_GENESIS_H1")});
  test("rejects missing header, footer, or semantic media",()=>{const broken=captures.map(item=>({...item,themeIntegration:{...item.themeIntegration,globalHeaderPresent:false,globalFooterPresent:false},mediaRolesRendered:roles.slice(1)}));expect(evaluateThemeIntegrationReady(broken)).toMatchObject({state:"FAIL",failures:expect.arrayContaining(["DESKTOP_1440_HEADER","DESKTOP_1440_FOOTER","DESKTOP_1440_MEDIA_ROLES"])})});
  test("keeps repair draft-only, fixed-target, and free of overflow masking",()=>{const service=readFileSync(join(process.cwd(),"src/modules/glw/dallas-public-theme-integration-service.ts"),"utf8");const snapshot=readFileSync(join(process.cwd(),"src/app/api/glw/pages/[jobId]/theme-integrated-snapshot/route.ts"),"utf8");expect(service).toContain('template: DALLAS_THEME_TEMPLATE');expect(service).toContain('hide_title: "yes"');expect(service).not.toMatch(/status\s*:\s*["']publish/);expect(snapshot).not.toMatch(/overflow-x\s*:\s*hidden/i);expect(snapshot).toContain('fan-cooled-projector-enclosures/');});
});