jest.mock("server-only",()=>({}));
import { mkdtempSync,rmSync } from "node:fs";import { tmpdir } from "node:os";import { join } from "node:path";
import { evaluateDallasV3Drift,freezeDallasV3Identity,renderDallasWordPressV3,type DallasWordPressBeforeState } from "../dallas-rich-composition-apply";
const identity={organizationId:"ssi",siteId:"site-ssi-projectorenclosure",pageId:"target-dallas",jobId:"2ca74016-252b-4587-bf3c-ec9b7eb839c9",pageRevisionIdentity:"job:2ca74016-252b-4587-bf3c-ec9b7eb839c9:revision"};
const links=["fan-cooled","projection-mapping","outdoor-planning","project-review","quote","nws","culture","public-art-link","convention-link"].map((linkId)=>({linkId,url:`https://${linkId.includes("nws")?"weather.gov":"example.com"}/${linkId}`,anchorIntent:linkId,reason:"Approved reason."}));
const media=["PRODUCT_AUTHORITY","CONTEXTUAL_IN_USE","APPLICATION_EXPERIENCE","LOCAL_CONTEXTUAL_ATMOSPHERE"].map((role)=>({role,altText:`Safe ${role} visual`,sha256:"a".repeat(64)}));
const local={bundleId:"local-v2",context:{identity,contextId:"context",facts:[{kind:"CLIMATE_ENVIRONMENT",statement:"Sourced fact."}]},links:{graphId:"links",links},theme:{profileId:"theme"},applications:{authorityId:"applications"},composition:{planId:"plan-v2",validationState:"READY_FOR_OWNER_REVIEW"},media};
const market={bundleId:"market-match-dallas-north-texas-v1",intelligence:{intelligenceId:"market-r1"},pageStrategy:{pageId:"target-dallas",primaryApplication:"PROJECTION_MAPPING",supportingApplications:["COMMERCIAL_AV","EVENT_VENUE"],crossSellCatalogItemIds:[],rejectedAdjacencies:[{applicationId:"SPORTS_STADIUM"}],mediaRoles:media.map(item=>item.role)},opportunities:[{confidence:"HIGH",applicationId:"PROJECTION_MAPPING",whyProduct:"Approved product fit."},{confidence:"HIGH",applicationId:"COMMERCIAL_AV",whyProduct:"Approved product fit."},{confidence:"MEDIUM",applicationId:"EVENT_VENUE",whyProduct:"Approved product fit."}]};
const urls={PRODUCT_AUTHORITY:"https://example.com/product.webp",CONTEXTUAL_IN_USE:"https://example.com/in-use.jpg",APPLICATION_EXPERIENCE:"https://example.com/application.jpg",LOCAL_CONTEXTUAL_ATMOSPHERE:"https://example.com/atmosphere.jpg"};
describe("Dallas rich composition apply",()=>{
  test("binds owner approval identity to exact V3 authorities",()=>{expect(freezeDallasV3Identity({local:local as never,market:market as never,previewManifestHash:"b".repeat(64)})).toMatchObject({wordpressObjectId:"13084",localBundleId:"local-v2",marketBundleId:"market-match-dallas-north-texas-v1",approvedV3PreviewHash:"b".repeat(64)});});
  test("rejects stale page and altered market strategy",()=>{expect(()=>freezeDallasV3Identity({local:{...local,context:{...local.context,identity:{...identity,jobId:"wrong"}}} as never,market:market as never,previewManifestHash:"b".repeat(64)})).toThrow("DALLAS_V3_IDENTITY_INVALID");expect(()=>freezeDallasV3Identity({local:local as never,market:{...market,pageStrategy:{...market.pageStrategy,primaryApplication:"SPORTS_STADIUM"}} as never,previewManifestHash:"b".repeat(64)})).toThrow("DALLAS_V3_MARKET_STRATEGY_MISMATCH");});
  test("renders one H1, four roles, approved links, and no dev or documentary claims",()=>{const html=renderDallasWordPressV3({local:local as never,market:market as never,mediaUrls:urls});expect(html.match(/<h1\b/g)).toHaveLength(1);for(const role of media.map(item=>item.role))expect(html).toContain(`data-media-role="${role}"`);expect(html).toContain("Not a real Dallas venue or SSI project");expect(html).not.toMatch(/localhost|:3003|\/glw\//);});
  test("allows exact/minor drift and blocks material or critical drift",()=>{const html=renderDallasWordPressV3({local:local as never,market:market as never,mediaUrls:urls});const hrefs=[...html.matchAll(/href="([^"]+)/g)].map(match=>match[1]);const roles=media.map(item=>item.role);expect(evaluateDallasV3Drift({expectedHtml:html,actualHtml:html,expectedLinks:hrefs,actualLinks:hrefs,expectedRoles:roles,actualRoles:roles}).classification).toBe("NONE");expect(evaluateDallasV3Drift({expectedHtml:html,actualHtml:`${html}\n`,expectedLinks:hrefs,actualLinks:hrefs,expectedRoles:roles,actualRoles:roles}).classification).toBe("MINOR");expect(evaluateDallasV3Drift({expectedHtml:html,actualHtml:html.replace("Request project review","Continue"),expectedLinks:hrefs,actualLinks:hrefs,expectedRoles:roles,actualRoles:roles}).classification).toBe("MATERIAL");expect(evaluateDallasV3Drift({expectedHtml:html,actualHtml:`${html}<script></script>`,expectedLinks:hrefs,actualLinks:hrefs,expectedRoles:roles,actualRoles:roles}).classification).toBe("CRITICAL");});
  test("persists append-only exact approval and rollback idempotently",async()=>{const original=process.env.GCP_FOUNDATION_PERSISTENCE_DIR;const root=mkdtempSync(join(tmpdir(),"dallas-apply-"));process.env.GCP_FOUNDATION_PERSISTENCE_DIR=root;jest.resetModules();const repository=await import("../dallas-rich-composition-apply-repository");const exact=freezeDallasV3Identity({local:local as never,market:market as never,previewManifestHash:"b".repeat(64)});const before={wordpressObjectId:"13084",status:"draft",title:"Title",slug:"dallas",canonicalPath:"path",parent:13083,template:"default",content:"before",contentHash:"c".repeat(64),excerpt:"",featuredMediaId:10757,seo:null,seoHash:"d".repeat(64),operativeBodyAuthority:"WORDPRESS_POST_CONTENT",shadowAuthority:"NONE",templateAuthority:"WORDPRESS_THEME",links:[],mediaReferences:[],capturedAt:"2026-09-13T00:00:00.000Z"} as DallasWordPressBeforeState;const first=repository.persistDallasApprovalAndRollback({identity:exact,before,now:"2026-09-13T00:00:00.000Z"});const second=repository.persistDallasApprovalAndRollback({identity:exact,before,now:"2026-09-13T01:00:00.000Z"});expect(second.decision.decisionId).toBe(first.decision.decisionId);expect(repository.getDallasApplyState()).toMatchObject({decisions:[{decision:"APPROVED",publicationAuthorized:false}],rollbacks:[{state:"AVAILABLE",before:{content:"before"}}]});if(original===undefined)delete process.env.GCP_FOUNDATION_PERSISTENCE_DIR;else process.env.GCP_FOUNDATION_PERSISTENCE_DIR=original;rmSync(root,{recursive:true,force:true});});
});