import type { SitePageMediaAssignment, SitePageMediaRole } from "@/modules/foundation/site-page-media-assignment";
import { evaluateGlwRichReferenceReadiness, GLW_RICH_REFERENCE_COMPOSITION_CONTRACT, GLW_RICH_REFERENCE_COMPOSITION_VERSION } from "../rich-reference-composition";

const revision = "job:reference:revision";
function artifact(body: string) { return { title: "Outdoor Digital Sphere in Indiana", contentHtml: body, slug: "outdoor-digital-sphere/indiana", excerpt: null, seoTitle: "Outdoor Digital Sphere Indiana", metaDescription: "Planning guide", focusKeyphrase: "outdoor digital sphere indiana" }; }
function assignment(role: SitePageMediaRole, type: "APPROVED_EXISTING" | "GENERATED" = "APPROVED_EXISTING", authorityReference = "wordpress-media:1"): SitePageMediaAssignment {
  const asset = type === "APPROVED_EXISTING"
    ? { type, authorityReference, productId: role === "PRODUCT_AUTHORITY" ? "prod-outdoor-digital-sphere" : null, wordpressMediaId: 1, url: "https://example.com/media.jpg", sha256: "a".repeat(64) } as const
    : { type, provider: "provider", model: "model", generationJobId: "image-job", effectivePrompt: "Grounded contextual scene", referenceInputs: [{ referenceId: "product", role: "PRODUCT_TRUTH" as const, sha256: "b".repeat(64) }], outputSha256: "c".repeat(64) } as const;
  return { assignmentId: `assignment-${role}`, organizationId: "org", siteId: "site", buildSessionId: "session", pageId: "page", pageRevisionId: revision, slotId: role, role, asset, metadata: { altText: `${role} visual`, caption: null, title: role, description: "Governed media" }, approval: { candidateId: `candidate-${role}`, approvedBy: "owner", approvedAt: "2030-01-01T00:00:00Z" }, wordpressReceipt: { mediaId: 1, url: "https://example.com/media.jpg", attachedToObjectId: "10", altTextVerified: true, placementVerified: true, verifiedAt: "2030-01-01T00:00:00Z" }, createdAt: "2030-01-01T00:00:00Z" };
}
const plan = { contract: "site-page-localized-composition-plan-v2", validationState: "READY_FOR_OWNER_REVIEW", wordpressMutationAuthorized: false } as never;
const visual = { contract: "rendered-visual-certification-v1", overallState: "PASS", layoutClass: "FULL_WIDTH_MARKETING_PAGE" } as never;
const roles = ["HERO", "PRODUCT_IDENTITY", "LOCALIZED_INTRODUCTION", "APPLICATIONS", "PRODUCT_OR_EVALUATION", "PLANNING_GUIDANCE", "VISUAL_APPLICATION", "CTA"];
function richBody(options: { comparison?: string; mechanical?: boolean } = {}) {
  return `<main data-composition-contract="${GLW_RICH_REFERENCE_COMPOSITION_VERSION}" data-media-provenance="governed-assignments">${roles.map((role) => `<section data-reference-section="${role}"${role === "HERO" ? ' data-composition-role="hero" data-media-authority="LOCAL_CONTEXTUAL_ATMOSPHERE"' : role === "VISUAL_APPLICATION" ? ' data-composition-role="visual-application" data-media-authority="APPLICATION_EXPERIENCE"' : ""}>${role === "HERO" ? '<img src="https://example.com/hero.jpg" alt="Conceptual Indiana event atmosphere"><h1>Outdoor Digital Sphere in Indiana</h1><a href="/outdoor-digital-sphere/">Outdoor Digital Sphere</a>' : `<h2>${role}</h2><p>${options.mechanical && role === "APPLICATIONS" ? "One possible concept a project team could consider is an interactive experience concept." : role === "LOCALIZED_INTRODUCTION" ? "Indiana project teams can use this authority-neutral planning guide." : role === "CTA" ? "Contact the team to confirm project requirements." : "What should the project team evaluate?"}</p>`}${role === "PRODUCT_OR_EVALUATION" ? options.comparison ?? "" : ""}</section>`).join("")}</main>`;
}
const allMedia = [assignment("PRODUCT_AUTHORITY"), assignment("CONTEXTUAL_IN_USE", "GENERATED"), assignment("APPLICATION_EXPERIENCE", "GENERATED"), assignment("LOCAL_CONTEXTUAL_ATMOSPHERE", "GENERATED")];
function evaluate(input: Partial<Parameters<typeof evaluateGlwRichReferenceReadiness>[0]> = {}) { return evaluateGlwRichReferenceReadiness({ artifact: artifact(richBody()), compositionPlan: plan, mediaAssignments: allMedia, pageRevisionId: revision, approvedProductMediaAvailable: true, comparisonAuthority: { mode: "EVALUATION_FRAMEWORK", authorizedCellTexts: [] }, visualCertification: visual, ...input }); }

describe("GLW rich reference composition bridge", () => {
  test("reuses existing composition, media, and visual certification contracts", () => { expect(GLW_RICH_REFERENCE_COMPOSITION_CONTRACT).toMatchObject({ version: GLW_RICH_REFERENCE_COMPOSITION_VERSION, reusedContracts: { compositionPlan: "site-page-localized-composition-plan-v2", mediaAssignment: "site-page-media-assignment-v1", visualCertification: "rendered-visual-certification-v1" }, articleHtmlIsSemanticInputOnly: true, silentArticleFallbackAllowed: false }); });
  test("blocks article-only candidate", () => expect(evaluate({ artifact: artifact("<h1>Outdoor Digital Sphere in Indiana</h1><p>Article.</p>") })).toMatchObject({ state: "REFERENCE_COMPOSITION_BLOCKED", articleHtmlFinalPresentationAuthority: false }));
  test("blocks missing product media when product representation is required", () => expect(evaluate({ mediaAssignments: allMedia.filter((item) => item.role !== "PRODUCT_AUTHORITY") })).toMatchObject({ ready: false, blockers: expect.arrayContaining(["APPROVED_PRODUCT_AUTHORITY_IMAGE_REQUIRED"]) }));
  test("allows a contextual hero when governed atmosphere does not represent the product", () => expect(evaluate()).toMatchObject({ mediaRoles: { LOCAL_CONTEXTUAL_ATMOSPHERE: true }, sectionRoles: { HERO: true } }));
  test("blocks unverified image as product representation", () => expect(evaluate({ mediaAssignments: [assignment("PRODUCT_AUTHORITY", "APPROVED_EXISTING", "unverified:file"), ...allMedia.slice(1)], approvedProductMediaAvailable: true })).toMatchObject({ ready: false, blockers: expect.arrayContaining(["PRODUCT_AUTHORITY_MEDIA_UNVERIFIED"]) }));
  test("content-reference PDF cannot satisfy product media", () => expect(evaluate({ mediaAssignments: allMedia.filter((item) => item.role !== "PRODUCT_AUTHORITY") })).toMatchObject({ mediaRoles: { PRODUCT_AUTHORITY: false }, ready: false }));
  test("approved product media satisfies the product role", () => expect(evaluate()).toMatchObject({ mediaRoles: { PRODUCT_AUTHORITY: true } }));
  test("blocks unsupported factual comparison", () => expect(evaluate({ artifact: artifact(richBody({ comparison: "<table><tr><td>360° panoramic display</td></tr></table>" })), comparisonAuthority: { mode: "FACTUAL_COMPARISON", authorizedCellTexts: [] } })).toMatchObject({ comparison: { state: "BLOCKED" }, ready: false }));
  test("passes authority-backed comparison cells", () => expect(evaluate({ artifact: artifact(richBody({ comparison: "<table><tr><td>Verified fact</td></tr></table>" })), comparisonAuthority: { mode: "FACTUAL_COMPARISON", authorizedCellTexts: ["Verified fact"] } })).toMatchObject({ comparison: { state: "PASS" } }));
  test("passes authority-neutral evaluation framework", () => expect(evaluate({ artifact: artifact(richBody({ comparison: "<table><tr><th>Question</th></tr><tr><td>What should buyers compare?</td></tr></table>" })) })).toMatchObject({ comparison: { state: "PASS", mode: "EVALUATION_FRAMEWORK" } }));
  test("blocks mechanical canonicalization prose", () => expect(evaluate({ artifact: artifact(richBody({ mechanical: true })) })).toMatchObject({ ready: false, blockers: expect.arrayContaining(["CANONICALIZATION_COPY_QUALITY"]) }));
  test("allows natural authority-safe conceptual prose", () => expect(evaluate()).toMatchObject({ copyQuality: { ok: true } }));
  test("complete composition passes", () => expect(evaluate()).toMatchObject({ ready: true, state: "READY_FOR_OWNER_REVIEW", existingCompositionReused: true }));
  test("missing required role blocks", () => expect(evaluate({ artifact: artifact(richBody().replace(' data-reference-section="CTA"', "")) })).toMatchObject({ ready: false, blockers: expect.arrayContaining(["SECTION_CTA_REQUIRED"]) }));
});
