import { readFileSync } from "node:fs";
import { join } from "node:path";
import { normalizeGenesisRenderAuthority, selectAuthoritativeContrastEvidence } from "../../foundation/background-aware-text-contrast";

const service = readFileSync(join(process.cwd(), "src/modules/glw/san-antonio-final-publication-service.ts"), "utf8");
const repository = readFileSync(join(process.cwd(), "src/modules/glw/san-antonio-final-publication-repository.ts"), "utf8");
const route = readFileSync(join(process.cwd(), "src/app/api/glw/pages/[jobId]/san-antonio-final-publication/route.ts"), "utf8");
test("requires exact owner authority and consumes it once", () => { expect(route).toContain("SAN_ANTONIO_OWNER_APPROVAL"); expect(route).toContain("SAN_ANTONIO_STAGING_TARGET_ID"); expect(route).toContain("SAN_ANTONIO_FINAL_PUBLICATION_HASH"); expect(repository).toContain("CURRENT_NATIVE_WORDPRESS_PREVIEW_VISUALLY_APPROVED"); expect(repository).toContain("SAN_ANTONIO_PUBLICATION_AUTHORITY_INVALID_OR_CONSUMED"); expect(service).toContain("consumeSanAntonioPublicationAuthority"); expect(route).not.toContain("RUN_DRAFT_BATCH"); });
test("publishes only object 13103 and rolls back on any post-publication failure", () => { expect(service).toContain('wordpressObjectId: "13103"'); expect(service).toContain("restoreDraft(receiptId, reason, reconciled, publicUrl)"); expect(service).toContain('body: JSON.stringify({ status: "draft" })'); expect(service).not.toMatch(/generateGenesisFeaturedImage|execute_workflow|dispatchGlw/i); });
test("certifies the actual public host with convergence and four viewports", () => { expect(service).toContain('publicRenderAuthority: "ACTUAL_PUBLIC_HOST_RENDER"'); expect(service).toContain("genesis_public_read"); expect(service).toContain("DESKTOP_1440"); expect(service).toContain("DESKTOP_1024"); expect(service).toContain("TABLET_768"); expect(service).toContain("MOBILE_375"); expect(service).toContain("GENESIS_DURABLE_HEADING_CONTRAST_CSS"); expect(normalizeGenesisRenderAuthority("ACTUAL_PUBLIC_HOST_RENDER")).toBe("ACTUAL_PUBLIC_HOST_RENDER"); expect(selectAuthoritativeContrastEvidence([{ authority: "ACTUAL_NATIVE_HOST_RENDER" as const, state: "PASS" as const }, { authority: "ACTUAL_PUBLIC_HOST_RENDER" as const, state: "PASS" as const }]).authority).toBe("ACTUAL_PUBLIC_HOST_RENDER"); });
test("preserves authority, media, localization, claims, and exact target history", () => { for (const value of ["copyHashBefore", "mediaUrlsBefore", "seoHashBefore", "productGridBefore", "featuredMediaBefore", "UNAUTHORIZED_VALID_DISPATCH", "otherTargetSnapshot", "unsupportedClaims: 0", "contentReconstructed: false"]) expect(service).toContain(value); });
test("exposes read-only observability proof without publication authority", () => { expect(route).toContain("runSanAntonioVerifierObservabilityProof"); expect(route).toContain("wordpressMutationPerformed: false"); expect(service).toContain('recordType: "VERIFIER_OBSERVABILITY_PROOF"'); expect(service).toContain('status: "draft"'); expect(service).toContain("ERR_TEST_ONLY_FETCH"); });
test("binds V2 retry to new operation, proof, commit, and current runtime", () => { for (const value of ["SAN_ANTONIO_PUBLICATION_RETRY_V2_OPERATION", "SAN_ANTONIO_VERIFIER_OBSERVABILITY_COMMIT", "SAN_ANTONIO_VERIFIER_OBSERVABILITY_PROOF", "createSanAntonioPublicationRetryV2Authority", "getPublicVerifierRuntimeIdentity", "expectedOperation", "expectedRuntimeSha"]) expect(`${repository}${service}${route}`).toContain(value); expect(repository).toContain("san-antonio-publication-retry-v2-authority-"); expect(service).toContain("verificationReceiptId: receiptId"); });