import { NextRequest, NextResponse } from "next/server";
import { authorizeRequest, hasOrganizationScope, isRecordInScope, resolveRequestScope } from "@/modules/foundation/api-auth";
import { getSiteById } from "@/modules/foundation/site-repository";
import { storeSiteIntelligenceAsset } from "@/modules/foundation/site-intelligence-asset-store";
import { addUploadedSource } from "@/modules/foundation/site-product-authority-repository";
import type { SiteSourceRole } from "@/modules/foundation/site-product-authority-repository";

type Context = { params: Promise<{ siteId: string }> };
const ROLES = new Set<SiteSourceRole>(["BUSINESS_FACTS", "PRODUCT_SERVICE_AUTHORITY", "TECHNICAL_SPECIFICATION", "CREATIVE_REFERENCE", "OTHER_REFERENCE"]);
export async function POST(request: NextRequest, context: Context) { const auth = authorizeRequest(request, "products:create"); if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status }); const scope = resolveRequestScope(request); const { siteId } = await context.params; const site = getSiteById(siteId); if (!hasOrganizationScope(scope) || !site || !isRecordInScope({ recordOrganizationId: site.organizationId, recordSiteId: site.siteId, scope })) return NextResponse.json({ error: "Site not found" }, { status: 404 }); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File) || file.size === 0 || file.size > 25 * 1024 * 1024) return NextResponse.json({ error: "Upload one file up to 25 MB." }, { status: 400 }); const sourceRole = String(form.get("sourceRole") ?? "OTHER_REFERENCE") as SiteSourceRole; if (!ROLES.has(sourceRole)) return NextResponse.json({ error: "SOURCE_ROLE_INVALID" }, { status: 400 }); try { const asset = storeSiteIntelligenceAsset({ organizationId: site.organizationId, siteId: site.siteId, originalFileName: file.name, mediaType: file.type || "application/octet-stream", bytes: new Uint8Array(await file.arrayBuffer()), actor: "site-owner", classification: "OWNER_SUPPLIED_REFERENCE", note: String(form.get("label") ?? "") || null }); const source = addUploadedSource({ organizationId: site.organizationId, siteId: site.siteId, assetId: asset.assetId, originalFileName: asset.originalFileName, sha256: asset.sha256, mediaType: asset.mediaType, sourceRole, label: String(form.get("label") ?? ""), actor: "site-owner" }); return NextResponse.json({ source }, { status: 201 }); } catch (cause) { return NextResponse.json({ error: cause instanceof Error ? cause.message : "SOURCE_UPLOAD_FAILED" }, { status: 422 }); } }