import { NextRequest, NextResponse } from "next/server";

import { authorizeRequest, resolveRequestScope } from "@/modules/foundation/api-auth";
import { getDallasPublicationState } from "@/modules/glw/dallas-reference-page-publication-repository";
import { buildDallasPublicationPreflight, publishDallasReferencePage, rollbackFailedDallasReferenceCertification } from "@/modules/glw/dallas-reference-page-publication-service";

export const dynamic = "force-dynamic";
export const maxDuration = 300;
const JOB_ID = "2ca74016-252b-4587-bf3c-ec9b7eb839c9";
function access(request: NextRequest, jobId: string, update = false) { const auth = authorizeRequest(request, update ? "sites:update" : "sites:read"); const scope = resolveRequestScope(request); return { auth, valid: auth.ok && scope.organizationId === "ssi" && scope.siteId === "site-ssi-projectorenclosure" && jobId === JOB_ID && (!update || auth.roles.includes("platform_admin")) }; }

export async function GET(request: NextRequest, context: { params: Promise<{ jobId: string }> }) { const { jobId } = await context.params; const allowed = access(request, jobId); if (!allowed.valid) return NextResponse.json({ error: allowed.auth.error ?? "Exact Dallas scope required." }, { status: allowed.auth.ok ? 403 : allowed.auth.status }); const state = getDallasPublicationState(); const activeReference = state.referenceCertifications.find((certification) => !state.referenceRevocations.some((revocation) => revocation.certificationId === certification.certificationId)); if (activeReference) return NextResponse.json({ state, activeReference, publicationPerformed: false, campaignMutationPerformed: false, dispatchPerformed: false }); try { const preflight = await buildDallasPublicationPreflight(); return NextResponse.json({ readiness: preflight.readiness, identity: preflight.identity, expectedPublicUrl: preflight.expectedPublicUrl, target: preflight.target, historicalState: state, publicationPerformed: false, campaignMutationPerformed: false, dispatchPerformed: false }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "DALLAS_PUBLICATION_PREFLIGHT_FAILED", publicationPerformed: false, campaignMutationPerformed: false, dispatchPerformed: false }, { status: 409 }); } }

export async function POST(request: NextRequest, context: { params: Promise<{ jobId: string }> }) { const { jobId } = await context.params; const allowed = access(request, jobId, true); if (!allowed.valid) return NextResponse.json({ error: "Platform-admin exact Dallas scope required." }, { status: 403 }); const body = await request.json().catch(() => null) as { operation?: string } | null; if (!body || Object.keys(body).length !== 1 || !["REPUBLISH_OWNER_APPROVED_DALLAS_AFTER_THEME_REPAIR", "PUBLISH_OWNER_APPROVED_DALLAS_REFERENCE_PAGE", "ROLLBACK_FAILED_DALLAS_REFERENCE_CERTIFICATION"].includes(body.operation ?? "")) return NextResponse.json({ error: "Exact Dallas publication operation required." }, { status: 400 }); try { if (body.operation === "ROLLBACK_FAILED_DALLAS_REFERENCE_CERTIFICATION") { const result = await rollbackFailedDallasReferenceCertification(); return NextResponse.json({ ...result, wordpressMutationPerformed: !result.reused, campaignMutationPerformed: !result.reused, dispatchPerformed: false, otherPageMutationPerformed: false }, { status: result.reused ? 200 : 201 }); } const result = await publishDallasReferencePage(); return NextResponse.json({ ...result, wordpressMutationPerformed: !result.reused, campaignMutationPerformed: !result.reused, dispatchPerformed: false, otherPageMutationPerformed: false }, { status: result.reused ? 200 : 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "DALLAS_REFERENCE_PUBLICATION_FAILED", wordpressMutationPerformed: false, campaignMutationPerformed: false, dispatchPerformed: false, otherPageMutationPerformed: false }, { status: 422 }); } }