import { NextRequest, NextResponse } from "next/server";

import { authorizeRequest, hasOrganizationScope, isRecordInScope, resolveRequestScope } from "@/modules/foundation/api-auth";
import { certifyCommercialStainlessWave2Page, COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_IMPLEMENTATION_SHA, COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_ORDER, listCommercialStainlessWave2PublicationReceipts, publishCommercialStainlessWave2Page, summarizeCommercialStainlessWave2PublicationReceipt, type Wave2VisualCertification } from "@/modules/foundation/commercial-stainless-wave2-publication";
import { getSiteById } from "@/modules/foundation/site-repository";

type Context = { params: Promise<{ siteId: string }> };
async function scoped(request: NextRequest, context: Context) { const scope = resolveRequestScope(request); const { siteId } = await context.params; const site = getSiteById(siteId); return hasOrganizationScope(scope) && site && isRecordInScope({ recordOrganizationId: site.organizationId, recordSiteId: site.siteId, scope }) ? site : null; }
const receipts = () => listCommercialStainlessWave2PublicationReceipts().map(summarizeCommercialStainlessWave2PublicationReceipt);
export async function GET(request: NextRequest, context: Context) { const auth = authorizeRequest(request, "sites:read"); if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status }); const site = await scoped(request, context); if (!site) return NextResponse.json({ error: "Site not found" }, { status: 404 }); return NextResponse.json({ operation: "COMMERCIAL_STAINLESS_WAVE2_OBJECT12_RETRY_AND_RESUME_V2", previousAuthorityReused: false, implementationSha: COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_IMPLEMENTATION_SHA, publicationOrder: COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_ORDER, receipts: receipts(), mutationPerformed: false }); }
export async function POST(request: NextRequest, context: Context) { const auth = authorizeRequest(request, "sites:manage_integrations"); if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status }); const site = await scoped(request, context); if (!site) return NextResponse.json({ error: "Site not found" }, { status: 404 }); const body = await request.json().catch(() => null) as null | { confirm?: string; implementationSha?: string; wordpressObjectId?: number; receiptId?: string; visual?: Wave2VisualCertification }; if (!body || body.implementationSha !== COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_IMPLEMENTATION_SHA || !COMMERCIAL_STAINLESS_WAVE2_PUBLICATION_ORDER.includes(Number(body.wordpressObjectId) as never)) return NextResponse.json({ error: "Exact Wave 2 V2 implementation and object authority required." }, { status: 403 }); try { if (body.confirm === "RECONCILE_EXACT_COMMERCIAL_STAINLESS_WAVE2_V2_NEXT_OBJECT") { const receipt = await publishCommercialStainlessWave2Page(site, Number(body.wordpressObjectId)); return NextResponse.json({ receipt: summarizeCommercialStainlessWave2PublicationReceipt(receipt), publicationAttempted: true, publicationWriteRequired: false, publicationWriteExecuted: false, wordpressContentMutation: false }); } if (body.confirm === "CERTIFY_EXACT_COMMERCIAL_STAINLESS_WAVE2_V2_ACTUAL_PUBLIC_RENDER" && body.visual && body.receiptId) { const receipt = await certifyCommercialStainlessWave2Page(site, Number(body.wordpressObjectId), body.visual, body.receiptId); return NextResponse.json({ receipt: summarizeCommercialStainlessWave2PublicationReceipt(receipt), mutationPerformed: false }); } return NextResponse.json({ error: "Exact V2 reconciliation or actual-host certification confirmation required." }, { status: 400 }); } catch (cause) { return NextResponse.json({ error: cause instanceof Error ? cause.message : "WAVE2_V2_PUBLICATION_FAILED", receipts: receipts(), sequentialStopTriggered: true }, { status: 409 }); } }
