import { NextRequest, NextResponse } from "next/server";
import { authorizeRequest, resolveRequestPrincipal, resolveRequestScope } from "@/modules/foundation/api-auth";
import { authorizeSanAntonioFinalPublication, authorizeSanAntonioPublicationRetryV2, publishSanAntonioFinal, runSanAntonioVerifierObservabilityProof } from "@/modules/glw/san-antonio-final-publication-service";
import { SAN_ANTONIO_FINAL_PUBLICATION_HASH, SAN_ANTONIO_FINAL_PUBLICATION_OPERATION, SAN_ANTONIO_OWNER_APPROVAL, SAN_ANTONIO_PUBLICATION_RETRY_V2_OPERATION, SAN_ANTONIO_VERIFIER_OBSERVABILITY_COMMIT, SAN_ANTONIO_VERIFIER_OBSERVABILITY_PROOF } from "@/modules/glw/san-antonio-final-publication-repository";
import { SAN_ANTONIO_APPROVED_ARTIFACT_SHA, SAN_ANTONIO_STAGING_CAMPAIGN_ID, SAN_ANTONIO_STAGING_JOB_ID, SAN_ANTONIO_STAGING_TARGET_ID } from "@/modules/glw/san-antonio-wordpress-staging-authority";

export const dynamic = "force-dynamic";
export const maxDuration = 300;
const exact = (body: Record<string, unknown>) => body.operation === SAN_ANTONIO_FINAL_PUBLICATION_OPERATION && body.organization === "ssi" && body.site === "site-ssi-projectorenclosure" && body.campaign === SAN_ANTONIO_STAGING_CAMPAIGN_ID && body.target === SAN_ANTONIO_STAGING_TARGET_ID && body.wordpressObjectId === "13103" && body.canonicalPath === "/fan-cooled-projector-enclosures/texas/san-antonio/" && body.storedHash === SAN_ANTONIO_FINAL_PUBLICATION_HASH && body.artifactSha === SAN_ANTONIO_APPROVED_ARTIFACT_SHA && body.ownerApproval === SAN_ANTONIO_OWNER_APPROVAL;
const exactRetryV2 = (body: Record<string, unknown>) => body.operation === SAN_ANTONIO_PUBLICATION_RETRY_V2_OPERATION && body.organization === "ssi" && body.site === "site-ssi-projectorenclosure" && body.campaign === SAN_ANTONIO_STAGING_CAMPAIGN_ID && body.target === SAN_ANTONIO_STAGING_TARGET_ID && body.wordpressObjectId === "13103" && body.canonicalPath === "/fan-cooled-projector-enclosures/texas/san-antonio/" && body.storedHash === SAN_ANTONIO_FINAL_PUBLICATION_HASH && body.artifactSha === SAN_ANTONIO_APPROVED_ARTIFACT_SHA && body.ownerApproval === SAN_ANTONIO_OWNER_APPROVAL && body.verifierObservabilityCommit === SAN_ANTONIO_VERIFIER_OBSERVABILITY_COMMIT && body.verifierObservabilityProofReceipt === SAN_ANTONIO_VERIFIER_OBSERVABILITY_PROOF;
export async function GET(request: NextRequest, context: { params: Promise<{ jobId: string }> }) { const { jobId } = await context.params; const auth = authorizeRequest(request, "sites:read"); const scope = resolveRequestScope(request); if (!auth.ok || jobId !== SAN_ANTONIO_STAGING_JOB_ID || scope.organizationId !== "ssi" || scope.siteId !== "site-ssi-projectorenclosure") return NextResponse.json({ error: "Exact read-only San Antonio verifier scope required." }, { status: 403 }); try { const proof = await runSanAntonioVerifierObservabilityProof(); return NextResponse.json({ proof, wordpressMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false, workflowExecuted: false }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "SAN_ANTONIO_OBSERVABILITY_PROOF_FAILED", wordpressMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false, workflowExecuted: false }, { status: 422 }); } }
export async function POST(request: NextRequest, context: { params: Promise<{ jobId: string }> }) { const { jobId } = await context.params; const auth = authorizeRequest(request, "sites:update"); const scope = resolveRequestScope(request); const principal = resolveRequestPrincipal(request); if (!auth.ok || !auth.roles.includes("platform_admin") || !principal || jobId !== SAN_ANTONIO_STAGING_JOB_ID || scope.organizationId !== "ssi" || scope.siteId !== "site-ssi-projectorenclosure") return NextResponse.json({ error: "Exact principal-bound San Antonio publication authority required." }, { status: 403 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; const retryV2 = Boolean(body && exactRetryV2(body)); const allowedKeys = ["action", "authorityId", "operation", "organization", "site", "campaign", "target", "wordpressObjectId", "canonicalPath", "storedHash", "artifactSha", "ownerApproval", "verifierObservabilityCommit", "verifierObservabilityProofReceipt"]; if (!body || (!exact(body) && !retryV2) || !["AUTHORIZE", "PUBLISH"].includes(String(body.action)) || Object.keys(body).some((key) => !allowedKeys.includes(key))) return NextResponse.json({ error: "Exact owner-approved San Antonio publication identity required." }, { status: 400 }); try { if (body.action === "AUTHORIZE") { if (body.authorityId) throw new Error("SAN_ANTONIO_PUBLICATION_AUTHORIZATION_BODY_INVALID"); const authority = retryV2 ? await authorizeSanAntonioPublicationRetryV2({ principal }) : await authorizeSanAntonioFinalPublication({ principal }); return NextResponse.json({ authority, publicationPerformed: false, dispatchPerformed: false, workflowExecuted: false }, { status: 201 }); } if (typeof body.authorityId !== "string" || !body.authorityId) throw new Error("SAN_ANTONIO_PUBLICATION_AUTHORITY_REQUIRED"); const result = await publishSanAntonioFinal({ authorityId: body.authorityId, principal, expectedOperation: retryV2 ? SAN_ANTONIO_PUBLICATION_RETRY_V2_OPERATION : SAN_ANTONIO_FINAL_PUBLICATION_OPERATION }); return NextResponse.json({ ...result, publicationPerformed: !result.reused, dispatchPerformed: false, workflowExecuted: false }, { status: result.reused ? 200 : 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "SAN_ANTONIO_FINAL_PUBLICATION_FAILED", publicationPerformed: false, dispatchPerformed: false, workflowExecuted: false }, { status: 422 }); } }