<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Genesis.GLW.RuntimeSupervisor</AssemblyName>
    <RootNamespace>Genesis.GLW.RuntimeSupervisor</RootNamespace>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>false</StripSymbols>
    <IlcGenerateStackTraceData>true</IlcGenerateStackTraceData>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Genesis.GLW.RuntimeSupervisor.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
