graph LR
  GovernanceArtifact --> AuthoritySource
  GovernanceArtifact --> ConstitutionReference
  GovernanceArtifact --> RelatedStandards
  GovernanceArtifact --> RelatedProcedures
  GovernanceArtifact --> ImplementationConsumers
  GovernanceArtifact --> CertificationConsumers
  GovernanceArtifact --> AuditConsumers
  GovernanceArtifact --> EvidenceConsumers
