import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { buildManifest, sha256File } from "./glw-immutable-release.mjs";
import { createNodeInstallerAdapters, currentProductionPreflightFailures, installPreparedRelease, validatePreparedStage, verifyTree } from "./glw-immutable-installer.mjs";
import { CERTIFIED_PREDECESSOR, hasExactProtectedLauncherAuthority, inspectPromotionState, inspectSidecarHealth, normalizeProcessAuthorityRecords, resolveCertifiedPredecessorLauncher, waitForExpectedRuntime } from "./glw-immutable-installer-windows.mjs";

const sourceSha = "a".repeat(40); const treeId = "b".repeat(40); const buildId = "build-1";
function fixture() {
  const root = mkdtempSync(join(tmpdir(), "glw-installer-")); const stage = join(root, "stage"); const release = join(stage, "release"); const finals = join(root, "finals"); const manifests = join(root, "manifests");
  const finalReleasePath = join(finals, `${sourceSha}__${buildId}__test`); const finalManifestPath = join(manifests, `GLW-Research-Security-${sourceSha}-${buildId}.json`); const manifestPath = join(stage, "GLW-Research-Security-Immutable-Release-Manifest.json"); const launcherPath = join(stage, "Start-GenesisGlw.ps1.candidate"); const environmentPath = join(root, "production.env"); const installedLauncher = join(root, "Start-GenesisGlw.ps1"); const baselinePath = join(root, "baseline.json");
  mkdirSync(release, { recursive: true }); mkdirSync(join(release, "nested")); mkdirSync(join(release, ".next", "server"), { recursive: true }); writeFileSync(join(release, "package.json"), "{}"); writeFileSync(join(release, "package-lock.json"), "{}"); writeFileSync(join(release, "nested", "app.js"), "ready"); writeFileSync(join(release, ".next", "server", "app-paths-manifest.json"), JSON.stringify({ "/api/glw/health/route": "health.js", "/api/glw/version/route": "version.js", "/api/glw/capabilities/route": "capabilities.js", "/api/glw/campaign-launch/route": "campaign-launch.js", "/glw/campaign-launchpad/page": "launchpad.js" })); writeFileSync(environmentPath, "NODE_ENV=production\n"); writeFileSync(baselinePath, "baseline\n"); writeFileSync(installedLauncher, `$ReleasePath = "C:\\old-release"\n$EnvironmentPath = "${environmentPath}"\n$ExpectedSourceSha = "${"d".repeat(40)}"\n$ExpectedBuildId = "old-build"\n$ExpectedEnvironmentSha256 = "${sha256File(environmentPath)}"\n`);
  const typecheckCertification = { policy: "EXACT_DIAGNOSTIC_AND_SOURCE_BLOB_FAIL_ON_DRIFT", baselineFingerprint: "c".repeat(64), diagnosticCount: 7 };
  const manifest = buildManifest({ releaseRoot: release, sourceSha, treeId, buildId, sourcePath: join(stage, "source"), finalReleasePath, typecheckCertification, generatedAtUtc: "2030-01-01T00:00:00.000Z" }); writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  const launcher = `$ReleasePath = "${finalReleasePath}"\n$EnvironmentPath = "${environmentPath}"\n$ManifestPath = "${finalManifestPath}"\n$ExpectedSourceSha = "${sourceSha}"\n$ExpectedTreeId = "${treeId}"\n$ExpectedBuildId = "${buildId}"\n$ExpectedManifestSha256 = "${sha256File(manifestPath)}"\n$ExpectedEnvironmentSha256 = "${sha256File(environmentPath)}"\n$ExpectedPackageJsonSha256 = "${sha256File(join(release, "package.json"))}"\n$ExpectedPackageLockSha256 = "${sha256File(join(release, "package-lock.json"))}"\n[Environment]::SetEnvironmentVariable("GIT_COMMIT", $ExpectedSourceSha, "Process")\n[Environment]::SetEnvironmentVariable("NODE_ENV", "production", "Process")\n`; writeFileSync(launcherPath, launcher);
  const plan = { schemaVersion: "genesis.glw.immutable-release-plan/v1", productionMutationAuthorized: false, sourceSha, treeId, buildId, stageRoot: stage, stagedReleasePath: release, finalReleasePath, stagedManifestPath: manifestPath, finalManifestPath, stagedLauncherPath: launcherPath, hashes: { manifestSha256: sha256File(manifestPath), launcherSha256: sha256File(launcherPath), environmentSha256: sha256File(environmentPath), typecheckBaselineSha256: sha256File(baselinePath) }, typecheckCertification, objectCounts: manifest.summary }; writeFileSync(join(stage, "release-plan.json"), `${JSON.stringify(plan, null, 2)}\n`);
  return { root, stage, release, finals, manifests, finalReleasePath, finalManifestPath, manifestPath, launcherPath, environmentPath, installedLauncher, baselinePath, manifest, plan, cleanup: () => rmSync(root, { recursive: true, force: true }) };
}
function production(overrides = {}) { return { healthy: true, health: "HEALTHY/READY/LIVE", port: 3001, expectedGenesisRuntime: true, promotionEnabled: false, promotionState: "DISABLED", sourceSha: "d".repeat(40), buildId: "old-build", releasePath: "C:\\old-release", pid: 111, launcherPid: 100, sidecarPid: 222, sidecarHealthy: true, persistence: { campaignHash: "C", targetHash: "T", executionHash: "E", campaignCount: 6, targetCount: 97, executionCount: 119, ownershipCollisionCount: 0, unreconciledCount: 0 }, ...overrides }; }
function adapters(f, overrides = {}) {
  const calls = []; const security = { owner: "BUILTIN\\Administrators", sddl: "O:BAG:SYD:PAI(A;;0x1200a9;;;SY)(A;;0x1200a9;;;BA)" };
  const base = createNodeInstallerAdapters({ isElevatedAdministrator: () => true, isPromotionEnvironmentSafe: () => true, now: () => "2030-01-01T00:00:00.000Z", transactionId: () => "tx-1", inspectProduction: async () => production(), captureLauncherSecurity: () => security, grantTemporaryLauncherWrite: () => calls.push("grant"), replaceLauncher: (source, target) => { calls.push("replace"); writeFileSync(target, readFileSync(source)); }, restoreLauncherSecurity: () => calls.push("restore"), verifyLauncherSecurity: () => calls.push("verify-acl"), stopRuntimeOnce: async () => calls.push("stop"), startProtectedLauncherOnce: async () => { calls.push("start"); return 999; }, verifyInstalledRuntime: async (prepared) => ({ ...production(), sourceSha: prepared.plan.sourceSha, buildId: prepared.plan.buildId, releasePath: prepared.paths.finalReleasePath }) });
  return { value: { ...base, ...overrides }, calls, security };
}
function installInput(f, adapter) { return { stage: f.stage, environmentPath: f.environmentPath, launcherPath: f.installedLauncher, evidenceRoot: join(f.root, "evidence"), rollbackRoot: join(f.root, "rollback"), releaseRoot: f.finals, manifestRoot: f.manifests, typecheckBaselinePath: f.baselinePath, adapters: adapter }; }
function response(status, body = null, headers = {}) { return { status, ok: status >= 200 && status < 300, redirected: false, headers: { get: (name) => headers[name.toLowerCase()] ?? null }, json: async () => { if (body instanceof Error) throw body; return body; } }; }

for (const [name, mutate, expected] of [
  ["altered release plan", (f) => { const p = JSON.parse(readFileSync(join(f.stage, "release-plan.json"))); p.sourceSha = "e".repeat(40); writeFileSync(join(f.stage, "release-plan.json"), JSON.stringify(p)); }, /Manifest source SHA/u],
  ["altered manifest", (f) => writeFileSync(f.manifestPath, "{}"), /Manifest hash/u],
  ["altered launcher", (f) => writeFileSync(f.launcherPath, "changed"), /Launcher hash/u],
  ["environment hash mismatch", (f) => writeFileSync(f.environmentPath, "changed"), /Environment hash/u],
  ["missing file", (f) => rmSync(join(f.release, "nested", "app.js")), /verification failed/u],
  ["extra file", (f) => writeFileSync(join(f.release, "extra"), "x"), /verification failed/u],
  ["file hash mismatch", (f) => writeFileSync(join(f.release, "nested", "app.js"), "changed"), /verification failed/u],
]) test(`${name} fails before production mutation`, () => { const f = fixture(); try { mutate(f); assert.throws(() => validatePreparedStage(f.stage, f.environmentPath, { releaseRoot: f.finals, manifestRoot: f.manifests, typecheckBaselinePath: f.baselinePath }), expected); } finally { f.cleanup(); } });

test("valid prepared stage passes complete verification", () => { const f = fixture(); try { const result = validatePreparedStage(f.stage, f.environmentPath, { releaseRoot: f.finals, manifestRoot: f.manifests, typecheckBaselinePath: f.baselinePath }); assert.deepEqual(result.tree, { objectCount: 7, directoryCount: 3, regularFileCount: 4, reparsePointCount: 0 }); } finally { f.cleanup(); } });
test("missing packaged production route fails before production inspection", () => { const f = fixture(); try { const path = join(f.release, ".next", "server", "app-paths-manifest.json"); const routes = JSON.parse(readFileSync(path)); delete routes["/api/glw/health/route"]; writeFileSync(path, JSON.stringify(routes)); const manifest = buildManifest({ releaseRoot: f.release, sourceSha, treeId, buildId, sourcePath: join(f.stage, "source"), finalReleasePath: f.finalReleasePath, typecheckCertification: f.plan.typecheckCertification, generatedAtUtc: "2030-01-01T00:00:00.000Z" }); writeFileSync(f.manifestPath, `${JSON.stringify(manifest, null, 2)}\n`); const plan = JSON.parse(readFileSync(join(f.stage, "release-plan.json"))); plan.hashes.manifestSha256 = sha256File(f.manifestPath); plan.objectCounts = manifest.summary; writeFileSync(join(f.stage, "release-plan.json"), JSON.stringify(plan)); assert.throws(() => validatePreparedStage(f.stage, f.environmentPath, { releaseRoot: f.finals, manifestRoot: f.manifests, typecheckBaselinePath: f.baselinePath }), /PACKAGED_RUNTIME_CONTRACT_MISSING.*health/u); } finally { f.cleanup(); } });
test("source identity and baseline authority are mandatory when configured", () => { const f = fixture(); try { assert.throws(() => validatePreparedStage(f.stage, f.environmentPath, { releaseRoot: f.finals, manifestRoot: f.manifests }), /baseline path/u); assert.throws(() => validatePreparedStage(f.stage, f.environmentPath, { releaseRoot: f.finals, manifestRoot: f.manifests, typecheckBaselinePath: f.baselinePath, sourceIdentityResolver: () => ({ commit: sourceSha, tree: "c".repeat(40) }) }), /Source tree/u); assert.doesNotThrow(() => validatePreparedStage(f.stage, f.environmentPath, { releaseRoot: f.finals, manifestRoot: f.manifests, typecheckBaselinePath: f.baselinePath, sourceIdentityResolver: () => ({ commit: sourceSha, tree: treeId }) })); } finally { f.cleanup(); } });
test("reparse point fails closed", { skip: process.platform !== "win32" }, () => { const f = fixture(); try { symlinkSync(join(f.release, "nested"), join(f.release, "link"), "junction"); assert.throws(() => verifyTree(f.release, f.manifest), /Forbidden release object/u); } finally { f.cleanup(); } });
test("insufficient elevation fails before inspection", async () => { const f = fixture(); try { let inspected = false; const a = adapters(f, { isElevatedAdministrator: () => false, inspectProduction: async () => { inspected = true; } }); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /Administrator/u); assert.equal(inspected, false); } finally { f.cleanup(); } });
test("inherited promotion enablement fails before stage or production inspection", async () => { const f = fixture(); try { let inspected = false; const a = adapters(f, { isPromotionEnvironmentSafe: () => false, inspectProduction: async () => { inspected = true; } }); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /promotion environment/u); assert.equal(inspected, false); } finally { f.cleanup(); } });
test("unexpected listener or enabled promotion fails before materialization", async () => { for (const current of [production({ expectedGenesisRuntime: false }), production({ promotionEnabled: true })]) { const f = fixture(); try { const a = adapters(f, { inspectProduction: async () => current }); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /preflight/iu); assert.equal(a.calls.length, 0); } finally { f.cleanup(); } } });
test("production drift at the mutation boundary fails before materialization", async () => { const f = fixture(); try { let reads = 0; const a = adapters(f, { inspectProduction: async () => reads++ === 0 ? production() : production({ sidecarPid: 333 }) }); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /mutation boundary/u); assert.equal(a.value.pathExists(f.finalReleasePath), false); assert.equal(a.calls.length, 0); } finally { f.cleanup(); } });
test("conflicting final release fails closed", async () => { const f = fixture(); try { mkdirSync(f.finalReleasePath, { recursive: true }); const a = adapters(f); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /Conflicting/u); assert.equal(a.calls.length, 0); } finally { f.cleanup(); } });
test("current protected launcher drift fails before materialization", async () => { const f = fixture(); try { writeFileSync(f.installedLauncher, readFileSync(f.installedLauncher, "utf8").replace("old-build", "wrong-build")); const a = adapters(f); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /Current launcher build ID/u); assert.equal(a.value.pathExists(f.finalReleasePath), false); assert.equal(a.calls.length, 0); } finally { f.cleanup(); } });
test("valid install materializes, switches once, verifies, and records evidence", async () => { const f = fixture(); try { const a = adapters(f); const result = await installPreparedRelease(installInput(f, a.value)); assert.equal(result.state, "INSTALLED"); assert.deepEqual(a.calls, ["grant", "replace", "restore", "verify-acl", "stop", "start"]); const evidence = JSON.parse(readFileSync(result.evidencePath)); assert.equal(evidence.result, "PASS"); assert.equal(evidence.secretsRecorded, false); } finally { f.cleanup(); } });
test("partial release copy failure is cleaned before launcher mutation", async () => { const f = fixture(); try { const a = adapters(f, { copyTree: (_source, target) => { mkdirSync(target, { recursive: true }); writeFileSync(join(target, "partial"), "x"); throw new Error("copy failed"); } }); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /rollback=PASS/u); assert.equal(a.value.pathExists(f.finalReleasePath), false); assert.equal(a.calls.length, 0); } finally { f.cleanup(); } });
test("already installed healthy runtime is idempotent", async () => { const f = fixture(); try { const a = adapters(f, { inspectProduction: async () => production({ sourceSha, buildId, releasePath: f.finalReleasePath }) }); a.value.copyTree(f.release, f.finalReleasePath); mkdirSync(f.manifests, { recursive: true }); a.value.copyFile(f.manifestPath, f.finalManifestPath); a.value.writeBytes(f.installedLauncher, readFileSync(f.launcherPath)); const result = await installPreparedRelease(installInput(f, a.value)); assert.equal(result.state, "ALREADY_INSTALLED_AND_RUNNING"); assert.deepEqual(a.calls, ["verify-acl"]); } finally { f.cleanup(); } });
test("corrupt already-installed release fails closed without recycle", async () => { const f = fixture(); try { const a = adapters(f, { inspectProduction: async () => production({ sourceSha, buildId, releasePath: f.finalReleasePath }) }); a.value.copyTree(f.release, f.finalReleasePath); writeFileSync(join(f.finalReleasePath, "nested", "app.js"), "corrupt"); mkdirSync(f.manifests, { recursive: true }); a.value.copyFile(f.manifestPath, f.finalManifestPath); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /verification failed/u); assert.equal(a.calls.length, 0); } finally { f.cleanup(); } });
test("launcher ACL authority rejects broadened or inherited rights", () => { const exact = { owner: "BUILTIN\\Administrators", inheritanceProtected: true, rules: [{ identity: "NT AUTHORITY\\SYSTEM", type: "Allow", rights: "ReadAndExecute, Synchronize", inherited: false }, { identity: "BUILTIN\\Administrators", type: "Allow", rights: "ReadAndExecute, Synchronize", inherited: false }] }; assert.equal(hasExactProtectedLauncherAuthority(exact), true); assert.equal(hasExactProtectedLauncherAuthority({ ...exact, rules: [{ ...exact.rules[0], rights: "FullControl" }, exact.rules[1]] }), false); assert.equal(hasExactProtectedLauncherAuthority({ ...exact, rules: [{ ...exact.rules[0], inherited: true }, exact.rules[1]] }), false); });
test("certified predecessor route absence is safe only before install", async () => { const fetchImpl = async () => response(404); const safe = await inspectPromotionState({ ...CERTIFIED_PREDECESSOR, phase: "PRE_INSTALL", fetchImpl }); assert.deepEqual(safe, { enabled: false, state: "LEGACY_ROUTE_ABSENT_SAFE" }); await assert.rejects(inspectPromotionState({ ...CERTIFIED_PREDECESSOR, phase: "POST_INSTALL", fetchImpl }), /absent/u); await assert.rejects(inspectPromotionState({ sourceSha: "e".repeat(40), buildId: CERTIFIED_PREDECESSOR.buildId, phase: "PRE_INSTALL", fetchImpl }), /unauthorized runtime/u); });
test("promotion endpoint accepts valid disabled state and rejects enabled predecessor state at preflight", async () => { const disabled = await inspectPromotionState({ ...CERTIFIED_PREDECESSOR, phase: "PRE_INSTALL", fetchImpl: async () => response(200, { mutationPerformed: false, promotion: { state: "DISABLED" } }) }); assert.deepEqual(disabled, { enabled: false, state: "DISABLED" }); const enabled = await inspectPromotionState({ ...CERTIFIED_PREDECESSOR, phase: "PRE_INSTALL", fetchImpl: async () => response(200, { mutationPerformed: false, promotion: { state: "ENABLED_CERTIFIED_RELEASE" } }) }); assert.deepEqual(currentProductionPreflightFailures(production({ sourceSha: CERTIFIED_PREDECESSOR.sourceSha, buildId: CERTIFIED_PREDECESSOR.buildId, promotionEnabled: enabled.enabled, promotionState: enabled.state })), ["promotionState=ENABLED_CERTIFIED_RELEASE"]); });
test("promotion endpoint fails closed for auth, server, redirects, and malformed responses", async () => { for (const status of [401, 403, 500]) await assert.rejects(inspectPromotionState({ ...CERTIFIED_PREDECESSOR, phase: "PRE_INSTALL", fetchImpl: async () => response(status) }), /Promotion GET/u); await assert.rejects(inspectPromotionState({ ...CERTIFIED_PREDECESSOR, phase: "PRE_INSTALL", fetchImpl: async () => ({ ...response(404), redirected: true }) }), /absent/u); await assert.rejects(inspectPromotionState({ ...CERTIFIED_PREDECESSOR, phase: "PRE_INSTALL", fetchImpl: async () => response(200, new Error("bad json")) }), /malformed JSON/u); await assert.rejects(inspectPromotionState({ ...CERTIFIED_PREDECESSOR, phase: "PRE_INSTALL", fetchImpl: async () => response(200, { promotion: { state: "DISABLED" } }) }), /read-only/u); });
test("post-install promotion requires an existing valid disabled route", async () => { const disabled = await inspectPromotionState({ sourceSha, buildId, phase: "POST_INSTALL", fetchImpl: async () => response(200, { mutationPerformed: false, promotion: { state: "DISABLED" } }) }); assert.equal(disabled.enabled, false); await assert.rejects(inspectPromotionState({ sourceSha, buildId, phase: "POST_INSTALL", fetchImpl: async () => response(404) }), /absent/u); const enabled = await inspectPromotionState({ sourceSha, buildId, phase: "POST_INSTALL", fetchImpl: async () => response(200, { mutationPerformed: false, promotion: { state: "ENABLED_CERTIFIED_RELEASE" } }) }); assert.deepEqual(currentProductionPreflightFailures(production({ sourceSha, buildId, promotionEnabled: enabled.enabled, promotionState: enabled.state })), ["promotionState=ENABLED_CERTIFIED_RELEASE"]); });
test("sidecar health requires exact HTTP 200 without redirect", async () => { assert.equal(await inspectSidecarHealth(async () => response(200)), true); for (const status of [401, 403, 500]) assert.equal(await inspectSidecarHealth(async () => response(status)), false); assert.equal(await inspectSidecarHealth(async () => ({ ...response(200), redirected: true })), false); assert.equal(await inspectSidecarHealth(async () => response(302, null, { location: "/login" })), false); });
test("runtime polling tolerates missing 3001 until the correct runtime becomes healthy", async () => { const observations = [new Error("Required production listeners are missing."), new Error("Required production listeners are missing."), production({ sourceSha, buildId, releasePath: "C:\\new-release" })]; let clock = 0; const result = await waitForExpectedRuntime({ inspect: async () => { const value = observations.shift(); if (value instanceof Error) throw value; return value; }, expectedSourceSha: sourceSha, expectedBuildId: buildId, expectedReleasePath: "C:\\new-release", timeoutMs: 100, intervalMs: 10, now: () => clock, sleep: async (milliseconds) => { clock += milliseconds; } }); assert.equal(result.sourceSha, sourceSha); assert.equal(clock, 20); });
test("runtime polling rejects wrong identity and reports bounded timeout observations", async () => { let clock = 0; await assert.rejects(waitForExpectedRuntime({ inspect: async () => production({ sourceSha: "e".repeat(40), buildId: "wrong", releasePath: "C:\\wrong" }), expectedSourceSha: sourceSha, expectedBuildId: buildId, expectedReleasePath: "C:\\new-release", timeoutMs: 30, intervalMs: 10, now: () => clock, sleep: async (milliseconds) => { clock += milliseconds; } }), /timed out after 30ms and 3 observations.*sourceSha=/u); });
test("runtime polling tolerates normal rollback startup delay", async () => { const old = production(); let attempts = 0; let clock = 0; const result = await waitForExpectedRuntime({ inspect: async () => { attempts += 1; if (attempts < 4) throw new Error("Required production listeners are missing."); return old; }, expectedSourceSha: old.sourceSha, expectedBuildId: old.buildId, expectedReleasePath: old.releasePath, timeoutMs: 100, intervalMs: 10, now: () => clock, sleep: async (milliseconds) => { clock += milliseconds; } }); assert.equal(result.buildId, "old-build"); assert.equal(attempts, 4); });
test("process authority normalization accepts one or many listener records", () => { const one = { port: 3001, pid: 1 }; const many = [one, { port: 3002, pid: 2 }]; assert.deepEqual(normalizeProcessAuthorityRecords(one), [one]); assert.deepEqual(normalizeProcessAuthorityRecords(many), many); assert.deepEqual(normalizeProcessAuthorityRecords(null), []); });
test("certified predecessor recognizes task and manual protected-launcher recovery ancestry only", () => { const common = { exactPredecessor: true, releasePath: "C:\\old-release", predecessorReleasePath: "C:\\old-release", schedulePid: 10 }; assert.deepEqual(resolveCertifiedPredecessorLauncher({ ...common, ancestors: [{ ProcessId: 20, ParentProcessId: 10, Name: "powershell.exe" }] }), { pid: 20, authority: "TASK_SCHEDULER" }); assert.deepEqual(resolveCertifiedPredecessorLauncher({ ...common, ancestors: [{ ProcessId: 21, ParentProcessId: 999, Name: "powershell.exe" }] }), { pid: 21, authority: "PROTECTED_LAUNCHER_RECOVERY" }); assert.equal(resolveCertifiedPredecessorLauncher({ ...common, exactPredecessor: false, ancestors: [{ ProcessId: 21, ParentProcessId: 999, Name: "powershell.exe" }] }), null); assert.equal(resolveCertifiedPredecessorLauncher({ ...common, releasePath: "C:\\other", ancestors: [{ ProcessId: 21, ParentProcessId: 999, Name: "powershell.exe" }] }), null); });
test("preflight diagnostics identify every failed invariant", () => { const failures = currentProductionPreflightFailures(production({ healthy: false, port: 9, expectedGenesisRuntime: false, releasePath: null, launcherPid: null, promotionEnabled: true, promotionState: "ENABLED_CERTIFIED_RELEASE", persistence: { ownershipCollisionCount: 2, unreconciledCount: 3 }, sidecarHealthy: false })); assert.deepEqual(failures, ["healthy=false", "port=9", "expectedGenesisRuntime=false", "releasePath=null", "launcherPid=null", "promotionState=ENABLED_CERTIFIED_RELEASE", "ownershipCollisionCount=2", "unreconciledCount=3", "sidecarHealthy=false"]); });
for (const [name, override] of [
  ["launcher replacement failure", { replaceLauncher: () => { throw new Error("replace failed"); } }],
  ["health failure", { verifyInstalledRuntime: async () => ({ ...production(), healthy: false }) }],
  ["runtime SHA mismatch", { verifyInstalledRuntime: async () => ({ ...production(), sourceSha: "e".repeat(40), buildId, releasePath: "C:\\wrong" }) }],
  ["build ID mismatch", { verifyInstalledRuntime: async (p) => ({ ...production(), sourceSha: p.plan.sourceSha, buildId: "wrong", releasePath: p.paths.finalReleasePath }) }],
  ["persistence hash drift", { verifyInstalledRuntime: async (p) => ({ ...production(), sourceSha: p.plan.sourceSha, buildId: p.plan.buildId, releasePath: p.paths.finalReleasePath, persistence: { ...production().persistence, campaignHash: "DRIFT" } }) }],
  ["execution hash drift", { verifyInstalledRuntime: async (p) => ({ ...production(), sourceSha: p.plan.sourceSha, buildId: p.plan.buildId, releasePath: p.paths.finalReleasePath, persistence: { ...production().persistence, executionHash: "DRIFT" } }) }],
  ["sidecar change", { verifyInstalledRuntime: async (p) => ({ ...production(), sourceSha: p.plan.sourceSha, buildId: p.plan.buildId, releasePath: p.paths.finalReleasePath, sidecarPid: 333 }) }],
  ["promotion unexpectedly enabled", { verifyInstalledRuntime: async (p) => ({ ...production(), sourceSha: p.plan.sourceSha, buildId: p.plan.buildId, releasePath: p.paths.finalReleasePath, promotionEnabled: true }) }],
]) test(`${name} triggers fail-closed rollback`, async () => { const f = fixture(); try { const a = adapters(f, override); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /rollback=PASS/u); assert.equal(a.value.pathExists(f.finalReleasePath), false); } finally { f.cleanup(); } });
test("failed installation writes secret-free evidence", async () => { const f = fixture(); try { const evidenceRoot = join(f.root, "evidence"); const a = adapters(f, { verifyInstalledRuntime: async () => ({ ...production(), healthy: false }) }); await assert.rejects(installPreparedRelease({ ...installInput(f, a.value), evidenceRoot }), /rollback=PASS/u); const evidence = JSON.parse(readFileSync(join(evidenceRoot, "install-tx-1-failed.json"))); assert.equal(evidence.result, "FAIL"); assert.equal(evidence.secretsRecorded, false); assert.equal(evidence.rollback.succeeded, true); } finally { f.cleanup(); } });
test("post-stop rollback stops the failed new runtime before restoring the old launcher", async () => { const f = fixture(); try { let verification = 0; const a = adapters(f, { verifyInstalledRuntime: async (prepared) => verification++ === 0 ? ({ ...production(), sourceSha: prepared.plan.sourceSha, buildId: prepared.plan.buildId, releasePath: prepared.paths.finalReleasePath, healthy: false }) : production() }); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /rollback=PASS/u); assert.deepEqual(a.calls, ["grant", "replace", "restore", "verify-acl", "stop", "start", "stop", "grant", "restore", "verify-acl", "start"]); } finally { f.cleanup(); } });
for (const [name, override] of [
  ["launcher DACL mismatch", { verifyLauncherSecurity: () => { throw new Error("ACL mismatch"); } }],
  ["ACL restoration failure", { restoreLauncherSecurity: () => { throw new Error("restore failed"); } }],
  ["runtime start failure", { startProtectedLauncherOnce: async () => { throw new Error("start failed"); } }],
]) test(`${name} reports rollback failure when the rollback authority also fails`, async () => { const f = fixture(); try { const a = adapters(f, override); await assert.rejects(installPreparedRelease(installInput(f, a.value)), /rollback=FAILED/u); } finally { f.cleanup(); } });
test("rollback failure is reported", async () => { const f = fixture(); try { let replacement = 0; const a = adapters(f, { replaceLauncher: (source, target) => { replacement += 1; if (replacement === 1) writeFileSync(target, readFileSync(source)); }, verifyLauncherSecurity: () => { throw new Error("ACL verification failed"); }, restoreLauncherSecurity: () => { if (replacement > 1) throw new Error("rollback ACL failed"); } }); const error = await installPreparedRelease(installInput(f, a.value)).then(() => null, (value) => value); assert.match(error.message, /rollback=FAILED/u); assert.equal(error.rollback.succeeded, false); } finally { f.cleanup(); } });
