import { createDecipheriv, createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import nextEnv from "@next/env";
const { loadEnvConfig } = nextEnv; loadEnvConfig(process.cwd(), true);
const root=process.env.GCP_FOUNDATION_PERSISTENCE_DIR?.trim();if(!root)throw new Error("PERSISTENCE_REQUIRED");
type R=Record<string,unknown>;const obj=(v:unknown)=>v&&typeof v==="object"&&!Array.isArray(v)?v as R:null;const text=(v:unknown):string=>typeof v==="string"?v.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim():(obj(v)?text(obj(v)!.raw)||text(obj(v)!.rendered):"");
function siteIn(v:unknown):R|null{if(Array.isArray(v)){for(const x of v){const f=siteIn(x);if(f)return f}return null}const r=obj(v);if(!r)return null;if(r.siteId==="site-led-display-warehouse-production"&&obj(r.integrations)?.wordpressApiBaseUrl)return r;for(const x of Object.values(r)){const f=siteIn(x);if(f)return f}return null}
let site:R|null=null;for(const n of readdirSync(root).filter(n=>n.endsWith(".json"))){try{site=siteIn(JSON.parse(readFileSync(join(root,n),"utf8")))}catch{}if(site)break}if(!site)throw new Error("SITE_NOT_FOUND");const integrations=obj(site.integrations)!;const store=JSON.parse(readFileSync(join(root,"wordpress-credential-store.json"),"utf8"));const rec=(obj(store.data)?.credentials as R[]).find(r=>r.reference===integrations.wordpressCredentialReference)!;const key=Buffer.from(process.env.GENESIS_CREDENTIAL_MASTER_KEY?.trim()??"","base64"),d=createDecipheriv("aes-256-gcm",key,Buffer.from(String(rec.iv),"base64"));d.setAuthTag(Buffer.from(String(rec.authTag),"base64"));const cred=JSON.parse(Buffer.concat([d.update(Buffer.from(String(rec.ciphertext),"base64")),d.final()]).toString("utf8"));const base=String(integrations.wordpressApiBaseUrl).replace(/\/$/,""),authorization=`Basic ${Buffer.from(`${cred.username}:${cred.applicationPassword}`).toString("base64")}`;
const terms=["Outdoor Digital Sphere","Outdoor LED Sphere","Digital Sphere","LED Sphere","Sphere","outdoor-digital-sphere","outdoor-led-sphere"];const results=new Map<number,R>();const failures:string[]=[];for(const term of terms){try{const response=await fetch(`${base}/media?${new URLSearchParams({search:term,context:"edit",per_page:"100",_fields:"id,date,slug,status,link,title,caption,description,alt_text,media_type,mime_type,media_details,source_url,post"})}`,{headers:{Authorization:authorization,Accept:"application/json"},signal:AbortSignal.timeout(30_000),cache:"no-store"});if(!response.ok){failures.push(`${term}:HTTP_${response.status}`);continue}for(const item of await response.json() as R[])results.set(Number(item.id),item)}catch{failures.push(`${term}:NETWORK`)}}
const candidates=[...results.values()].map(item=>{const title=text(item.title),caption=text(item.caption),description=text(item.description),altText=text(item.alt_text),slug=text(item.slug),haystack=`${title} ${caption} ${description} ${altText} ${slug.replaceAll("-"," ")}`;const exact=/\boutdoor (?:digital|led) sphere\b/i.test(haystack),indoor=/\bindoor digital sphere\b/i.test(haystack);const details=obj(item.media_details);return{mediaId:Number(item.id),source:"WORDPRESS_MEDIA",url:text(item.source_url),type:text(item.mime_type)||text(item.media_type),dimensions:details?{width:Number(details.width)||null,height:Number(details.height)||null}:null,title,slug,altText,caption,description,status:text(item.status),attachedTo:Number(item.post)||null,provenance:"WORDPRESS_METADATA_ONLY_NO_GENESIS_PRODUCT_BINDING",productIdentityMatch:exact&&!indoor?"PLAUSIBLE_UNVERIFIED":indoor?"INDOOR_PRODUCT_CONFLICT":"WEAK_TERM_MATCH",authorityClass:exact&&!indoor?"UNVERIFIED":"UNRELATED",approvedForProductRepresentation:false,approvedForContextualUse:false,approvedForApplicationUse:false,approvedForLocalAtmosphere:false,disposition:exact&&!indoor?"OWNER_PRODUCT_MEDIA_AUTHORITY_REQUIRED":"DO_NOT_USE"}}).filter(c=>c.productIdentityMatch!=="WEAK_TERM_MATCH").sort((a,b)=>a.mediaId-b.mediaId);
const localFiles=["product-repository.json","site-product-authority-repository.json","site-page-image-candidate-repository.json","site-page-media-assignment-v1.json","owner-supplied-media-ingestion.json","glw-campaign-reference-repository.json","glw-campaign-reference-image-candidate-v1.json","integration-profile-repository.json"];const localInventory=localFiles.map(name=>{const raw=readFileSync(join(root,name),"utf8");return{name,exactProductId:raw.includes("prod-outdoor-digital-sphere"),exactProductName:raw.includes("Outdoor Digital Sphere"),productImageRole:raw.includes("product_image"),productAuthorityRole:raw.includes("PRODUCT_AUTHORITY")}});const fingerprint=createHash("sha256").update(JSON.stringify({candidates,failures,localInventory})).digest("hex");console.log(JSON.stringify({complete:failures.length===0,fingerprint,candidates,failures,localInventory},null,2));
