import type { ThemeIntegrationEvidence } from "@/modules/foundation/governed-render-capture-browser";

export const DALLAS_THEME_INTEGRATION_CONTRACT = "dallas-public-theme-integration-repair-v1" as const;
export const DALLAS_THEME_TEMPLATE = "elementor_header_footer" as const;
export const DALLAS_APPROVED_BODY_HASH = "77df4b25869341cadbce741bf0932e6abe7f97728b1e9207e66a5306f8c9200b" as const;
export const DALLAS_APPROVED_SEO_HASH = "01adf755d77249323a55cb652671cda7f6e38431feda5d1e1267c00fbdad2f71" as const;
export type DallasThemeRepairReceipt = { receiptId: string; contract: typeof DALLAS_THEME_INTEGRATION_CONTRACT; wordpressObjectId: "13084"; status: "draft"; beforeTemplate: "default"; afterTemplate: typeof DALLAS_THEME_TEMPLATE; beforePageSettings: unknown; afterPageSettings: { hide_title: "yes" }; bodyHashBefore: typeof DALLAS_APPROVED_BODY_HASH; bodyHashAfter: typeof DALLAS_APPROVED_BODY_HASH; seoHashBefore: typeof DALLAS_APPROVED_SEO_HASH; seoHashAfter: typeof DALLAS_APPROVED_SEO_HASH; featuredMediaBefore: 10757; featuredMediaAfter: 10757; rollbackState: "AVAILABLE"; mutationVerifiedAt: string; publicationPerformed: false; campaignMutationPerformed: false; dispatchPerformed: false };
export type DallasThemeCapture = { captureId: string; viewport: "DESKTOP_1440" | "DESKTOP_1024" | "TABLET_768" | "MOBILE_375"; width: number; height: number; documentWidth: number; documentHeight: number; horizontalOverflow: number; themeIntegration: ThemeIntegrationEvidence; mediaRolesRendered: readonly string[]; sectionCount: number; artifact: { reference: string; sha256: string; bytes: number; width: number; height: number }; capturedAt: string };
export type DallasThemeCertification = { certificationId: string; receiptId: string; renderClass: "THEME_INTEGRATED_RENDER"; captureAuthority: "SIGNED_INTERNAL_EQUIVALENT_USING_LIVE_ELEMENTOR_HEADER_FOOTER_SHELL"; captures: readonly DallasThemeCapture[]; findings: readonly { code: string; state: "PASS" | "FAIL"; summary: string }[]; themeIntegrationReady: boolean; overallState: "PASS" | "FAIL"; drift: "NONE" | "MINOR" | "MATERIAL" | "CRITICAL"; driftReasons: readonly string[]; createdAt: string; publicationPerformed: false };
export function evaluateThemeIntegrationReady(captures: readonly Pick<DallasThemeCapture,"viewport"|"horizontalOverflow"|"themeIntegration"|"mediaRolesRendered">[]){const failures:string[]=[];for(const capture of captures){if(capture.horizontalOverflow!==0)failures.push(`${capture.viewport}_OVERFLOW`);if(capture.themeIntegration.visibleH1Count!==1)failures.push(`${capture.viewport}_H1_COUNT`);if(capture.themeIntegration.visibleH1Texts[0]!=="Protected projection, planned for North Texas.")failures.push(`${capture.viewport}_GENESIS_H1`);if(capture.themeIntegration.duplicateThemeTitleVisible)failures.push(`${capture.viewport}_THEME_TITLE`);if(capture.themeIntegration.duplicateThemeFeaturedMediaVisible)failures.push(`${capture.viewport}_THEME_FEATURED_MEDIA`);if(!capture.themeIntegration.globalHeaderPresent)failures.push(`${capture.viewport}_HEADER`);if(!capture.themeIntegration.globalFooterPresent)failures.push(`${capture.viewport}_FOOTER`);if(capture.mediaRolesRendered.length!==4)failures.push(`${capture.viewport}_MEDIA_ROLES`)}return {state:failures.length?"FAIL" as const:"PASS" as const,failures}}