import "server-only";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { normalizeWordPressApiBaseUrl } from "@/modules/foundation/authenticated-wordpress-read-authority";
import { resolvePersistenceRoot } from "@/modules/foundation/foundation-persistence";
import { getLocalPageThemingBundle, readLocalPageThemingMedia } from "@/modules/foundation/local-context-page-theming-repository";
import { getMarketProductMatchBundle } from "@/modules/foundation/local-market-product-match-repository";
import { getProductById } from "@/modules/foundation/product-repository";
import { getSiteById } from "@/modules/foundation/site-repository";
import { resolveWordPressCredentialReference } from "@/modules/foundation/wordpress-credential-resolver";
import { writeGenesisWordPressDraft } from "@/modules/foundation/wordpress-draft-writer";
import { DALLAS_LOCALIZED_PREVIEW_V2_BUNDLE_ID } from "./dallas-localized-preview-v2-service";
import { DALLAS_MARKET_MATCH_BUNDLE_ID } from "./dallas-market-product-match-service";
import { inspectDallasWordPressAuthority } from "./dallas-wordpress-authority-inspector";
import { evaluateDallasV3Drift, freezeDallasV3Identity, renderDallasWordPressV3, type DallasApplyReceipt, type DallasWordPressBeforeState } from "./dallas-rich-composition-apply";
import { appendDallasApplyAudit, getDallasApplyState, markDallasRollbackUsed, persistDallasApprovalAndRollback, saveDallasApplyReceipt } from "./dallas-rich-composition-apply-repository";

const JOB_ID="2ca74016-252b-4587-bf3c-ec9b7eb839c9";const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
function auth(username:string,password:string){return `Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`}
async function uploadMedia(input:{apiBaseUrl:string;authorization:string;bytes:Buffer;fileName:string;mimeType:string;title:string;altText:string;description:string}){const upload=await fetch(`${input.apiBaseUrl}/media`,{method:"POST",headers:{Accept:"application/json",Authorization:input.authorization,"Content-Disposition":`attachment; filename="${input.fileName}"`,"Content-Type":input.mimeType},body:new Uint8Array(input.bytes),cache:"no-store",signal:AbortSignal.timeout(30_000)});if(!upload.ok)throw new Error(`DALLAS_MEDIA_UPLOAD_FAILED:${upload.status}`);const created=await upload.json() as {id?:number;source_url?:string};if(!created.id||!created.source_url)throw new Error("DALLAS_MEDIA_UPLOAD_IDENTITY_INVALID");const metadata=await fetch(`${input.apiBaseUrl}/media/${created.id}`,{method:"POST",headers:{Accept:"application/json",Authorization:input.authorization,"Content-Type":"application/json"},body:JSON.stringify({title:input.title,alt_text:input.altText,description:input.description,caption:"Conceptual Genesis visualization; not documentary evidence of a Dallas installation, customer, office, or completed SSI project."}),cache:"no-store",signal:AbortSignal.timeout(30_000)});if(!metadata.ok)throw new Error(`DALLAS_MEDIA_METADATA_FAILED:${metadata.status}`);const verified=await metadata.json() as {id?:number;source_url?:string;alt_text?:string};if(verified.id!==created.id||verified.source_url!==created.source_url||verified.alt_text!==input.altText)throw new Error("DALLAS_MEDIA_METADATA_MISMATCH");return {mediaId:created.id,url:created.source_url}}
async function deleteMedia(apiBaseUrl:string,authorization:string,mediaId:number){try{await fetch(`${apiBaseUrl}/media/${mediaId}?force=true`,{method:"DELETE",headers:{Accept:"application/json",Authorization:authorization},cache:"no-store",signal:AbortSignal.timeout(30_000)})}catch{}}
async function verifyLinks(urls:readonly string[]){const results=[] as {url:string;status:number;state:"DIRECT_200"|"REDIRECT"|"BROKEN"|"UNAVAILABLE"}[];for(const url of [...new Set(urls)]){try{const response=await fetch(url,{method:"GET",redirect:"follow",cache:"no-store",signal:AbortSignal.timeout(30_000)});results.push({url,status:response.status,state:response.ok?(response.url===url?"DIRECT_200":"REDIRECT"):"BROKEN"})}catch{results.push({url,status:0,state:"UNAVAILABLE"})}}return results}

export async function applyApprovedDallasV3(input:{actor:string}){
  const prior=getDallasApplyState().receipts.at(-1);if(prior)return {receipt:prior,reused:true,drift:null};const local=getLocalPageThemingBundle({organizationId:"ssi",siteId:"site-ssi-projectorenclosure",jobId:JOB_ID,bundleId:DALLAS_LOCALIZED_PREVIEW_V2_BUNDLE_ID});const market=getMarketProductMatchBundle({organizationId:"ssi",bundleId:DALLAS_MARKET_MATCH_BUNDLE_ID});if(!local||!market)throw new Error("DALLAS_V3_AUTHORITY_MISSING");
  const root=resolvePersistenceRoot();const previewManifestPath=join(root,"market-product-match-preview-artifacts","dallas-v3","manifest.json");const previewBytes=readFileSync(previewManifestPath);const manifest=JSON.parse(previewBytes.toString("utf8")) as {identity?:{pageRevisionIdentity?:string;localizedV2BundleId?:string;marketBundleId?:string};captures?:{artifact:string;sha256:string}[]};for(const capture of manifest.captures??[]){const bytes=readFileSync(join(root,"market-product-match-preview-artifacts","dallas-v3",capture.artifact));if(sha(bytes)!==capture.sha256)throw new Error("DALLAS_V3_VISUAL_EVIDENCE_STALE")}if(manifest.identity?.pageRevisionIdentity!==local.context.identity.pageRevisionIdentity||manifest.identity?.localizedV2BundleId!==local.bundleId||manifest.identity?.marketBundleId!==market.bundleId)throw new Error("DALLAS_V3_PREVIEW_IDENTITY_STALE");const frozen=freezeDallasV3Identity({local,market,previewManifestHash:sha(previewBytes)});
  const before=await inspectDallasWordPressAuthority();if(before.authorityMap.operativeBody!=="WORDPRESS_POST_CONTENT"||before.authorityMap.shadowAuthority!=="NONE"||before.identity.parent!==13083||before.identity.title!=="Fan Cooled Projector Enclosures in Dallas"||before.body.contentHash!=="1dbcfbce270979dbb67d4e7ee3daee98289de34e224d2801c281d7df5dcd6c2c"||before.featuredMediaId!==10757)throw new Error("DALLAS_BEFORE_AUTHORITY_MISMATCH");const beforeState:DallasWordPressBeforeState={wordpressObjectId:"13084",status:"draft",title:before.identity.title,slug:before.identity.slug,canonicalPath:"fan-cooled-projector-enclosures/texas/dallas",parent:before.identity.parent,template:before.identity.template,content:before.body.raw,contentHash:before.body.contentHash,excerpt:before.body.excerpt,featuredMediaId:before.featuredMediaId,seo:before.seo.stored,seoHash:before.seo.hash,operativeBodyAuthority:"WORDPRESS_POST_CONTENT",shadowAuthority:"NONE",templateAuthority:"WORDPRESS_THEME",links:before.body.links,mediaReferences:before.body.mediaReferences,capturedAt:before.inspectedAt};const timestamp=new Date().toISOString();const approval=persistDallasApprovalAndRollback({identity:frozen,before:beforeState,now:timestamp});
  const product=getProductById("prod-ssi-fan-cooled-projector-enclosures");const productMedia=local.media.find(item=>item.role==="PRODUCT_AUTHORITY");if(!product||product.media.primaryImageReference!=="wordpress-media:10757"||!productMedia||productMedia.sha256!=="685495793be84b3a9d1a7e902087d63ae7a636e2042e6c0d592f5ba83e767078")throw new Error("DALLAS_PRODUCT_AUTHORITY_STALE");const productResponse=await fetch(productMedia.url,{cache:"no-store",signal:AbortSignal.timeout(30_000)});if(!productResponse.ok||sha(Buffer.from(await productResponse.arrayBuffer()))!==productMedia.sha256)throw new Error("DALLAS_PRODUCT_MEDIA_STALE");const linkResults=await verifyLinks(local.links.links.map(item=>item.url));if(linkResults.some(item=>item.state==="BROKEN"||item.state==="UNAVAILABLE"))throw new Error("DALLAS_V3_LINK_VALIDATION_FAILED");
  const site=getSiteById("site-ssi-projectorenclosure");if(!site||!site.integrations.wordpressApiBaseUrl)throw new Error("DALLAS_SITE_AUTHORITY_REQUIRED");const credential=resolveWordPressCredentialReference(site.integrations.wordpressCredentialReference);if(!credential)throw new Error("DALLAS_WORDPRESS_CREDENTIAL_REQUIRED");const apiBaseUrl=normalizeWordPressApiBaseUrl(site.integrations.wordpressApiBaseUrl);const authorization=auth(credential.username,credential.applicationPassword);const uploaded: {role:"CONTEXTUAL_IN_USE"|"APPLICATION_EXPERIENCE"|"LOCAL_CONTEXTUAL_ATMOSPHERE";mediaId:number;url:string;sha256:string;claimClass:string}[]=[];let bodyMutated=false;appendDallasApplyAudit("APPLY_STARTED",{decisionId:approval.decision.decisionId,wordpressObjectId:13084,actor:input.actor},timestamp);
  try{for(const role of ["CONTEXTUAL_IN_USE","APPLICATION_EXPERIENCE","LOCAL_CONTEXTUAL_ATMOSPHERE"] as const){const stored=readLocalPageThemingMedia({organizationId:"ssi",siteId:"site-ssi-projectorenclosure",jobId:JOB_ID,mediaId:local.media.find(item=>item.role===role)!.mediaId});if(!stored)throw new Error(`DALLAS_V3_MEDIA_BYTES_MISSING:${role}`);const item=stored.item;const created=await uploadMedia({apiBaseUrl,authorization,bytes:stored.bytes,fileName:`dallas-${role.toLowerCase().replaceAll("_","-")}-${item.sha256.slice(0,12)}.jpg`,mimeType:item.mimeType,title:item.altText,altText:item.altText,description:`${item.claimClass.replaceAll("_"," ")} for the owner-approved Dallas V3 composition. Not documentary evidence.`});uploaded.push({role,mediaId:created.mediaId,url:created.url,sha256:item.sha256,claimClass:item.claimClass});appendDallasApplyAudit("MEDIA_UPLOADED",{role,mediaId:created.mediaId,sha256:item.sha256},new Date().toISOString())}
    const urls={PRODUCT_AUTHORITY:productMedia.url,CONTEXTUAL_IN_USE:uploaded.find(item=>item.role==="CONTEXTUAL_IN_USE")!.url,APPLICATION_EXPERIENCE:uploaded.find(item=>item.role==="APPLICATION_EXPERIENCE")!.url,LOCAL_CONTEXTUAL_ATMOSPHERE:uploaded.find(item=>item.role==="LOCAL_CONTEXTUAL_ATMOSPHERE")!.url};const html=renderDallasWordPressV3({local,market,mediaUrls:urls});if((html.match(/<h1\b/gi)??[]).length!==1||/(?:localhost|127\.0\.0\.1|:3003|\/glw\/)/i.test(html))throw new Error("DALLAS_V3_CONTENT_SAFETY_FAILED");const result=await writeGenesisWordPressDraft({operation:"UPDATE",site,wordpressObjectId:"13084",artifact:{title:beforeState.title,slug:beforeState.canonicalPath,excerpt:beforeState.excerpt,contentHtml:html,parentId:beforeState.parent}});if(!result.ok)throw new Error(`DALLAS_WORDPRESS_WRITE_FAILED:${result.state}`);bodyMutated=true;appendDallasApplyAudit("WORDPRESS_MUTATED",{wordpressObjectId:13084,expectedHash:sha(html)},new Date().toISOString());const after=await inspectDallasWordPressAuthority();if(after.identity.status!=="draft"||after.identity.parent!==beforeState.parent||after.identity.title!==beforeState.title||after.body.contentHash!==sha(html)||after.featuredMediaId!==10757||after.seo.hash!==beforeState.seoHash||after.body.h1Count!==1)throw new Error("DALLAS_WORDPRESS_READBACK_MISMATCH");const actualRoles=[...after.body.raw.matchAll(/data-media-role=["']([^"']+)/g)].map(match=>match[1]);const actualLinks=[...after.body.raw.matchAll(/href=["']([^"']+)/g)].map(match=>match[1]);const expectedLinks=local.links.links.map(item=>item.url);const drift=evaluateDallasV3Drift({expectedHtml:html,actualHtml:after.body.raw,expectedLinks,actualLinks,expectedRoles:market.pageStrategy.mediaRoles,actualRoles});if(drift.classification==="MATERIAL"||drift.classification==="CRITICAL")throw new Error(`DALLAS_V3_DRIFT_${drift.classification}`);appendDallasApplyAudit("READBACK_VERIFIED",{afterHash:after.body.contentHash,status:after.identity.status,seoPreserved:after.seo.hash===beforeState.seoHash},new Date().toISOString());appendDallasApplyAudit("DRIFT_EVALUATED",{classification:drift.classification},new Date().toISOString());const receipt:DallasApplyReceipt={receiptId:`dallas-v3-apply-${frozen.approvedV3PreviewHash.slice(0,20)}`,contract:"dallas-rich-composition-apply-v1",schemaVersion:1,decisionId:approval.decision.decisionId,exactIdentity:frozen,beforeHash:beforeState.contentHash,afterHash:after.body.contentHash,wordpressObjectId:"13084",wordpressStatus:"draft",uploadedMedia:uploaded,productMediaId:10757,mutationVerifiedAt:new Date().toISOString(),publicationPerformed:false,campaignMutationPerformed:false,dispatchPerformed:false};return {receipt:saveDallasApplyReceipt(receipt),reused:false,drift,linkResults,rollback:approval.rollback}
  }catch(error){if(bodyMutated){appendDallasApplyAudit("ROLLBACK_STARTED",{rollbackArtifactId:approval.rollback.rollbackArtifactId},new Date().toISOString());const restored=await writeGenesisWordPressDraft({operation:"UPDATE",site,wordpressObjectId:"13084",artifact:{title:beforeState.title,slug:beforeState.canonicalPath,excerpt:beforeState.excerpt,contentHtml:beforeState.content,parentId:beforeState.parent}});const verified=await inspectDallasWordPressAuthority();if(!restored.ok||verified.body.contentHash!==beforeState.contentHash||verified.identity.status!=="draft")throw new Error("DALLAS_ROLLBACK_VERIFICATION_FAILED");markDallasRollbackUsed(approval.rollback.rollbackArtifactId,new Date().toISOString());appendDallasApplyAudit("ROLLBACK_VERIFIED",{rollbackArtifactId:approval.rollback.rollbackArtifactId},new Date().toISOString())}for(const item of uploaded)await deleteMedia(apiBaseUrl,authorization,item.mediaId);throw error}
}