import "server-only";
import { randomUUID } from "node:crypto";
import { deepClone, loadPersistedState, savePersistedState } from "@/modules/foundation/foundation-persistence";
import type { DallasActualVisualCertification, DallasApplyAuditEvent, DallasApplyReceipt, DallasPreviewWordPressComparison, DallasRollbackArtifact, DallasV3FrozenIdentity, DallasV3OwnerDecision } from "./dallas-rich-composition-apply";
const NAMESPACE="dallas-rich-composition-apply-v1"; type State={decisions:DallasV3OwnerDecision[];rollbacks:DallasRollbackArtifact[];receipts:DallasApplyReceipt[];audit:DallasApplyAuditEvent[];visualCertifications?:DallasActualVisualCertification[];comparisons?:DallasPreviewWordPressComparison[]}; const load=()=>{const loaded=loadPersistedState<State>({namespace:NAMESPACE,seedFactory:()=>({decisions:[],rollbacks:[],receipts:[],audit:[],visualCertifications:[],comparisons:[]})});return {...loaded,state:{...loaded.state,visualCertifications:loaded.state.visualCertifications??[],comparisons:loaded.state.comparisons??[]}}};
export function getDallasApplyState(){return deepClone(load().state)}
export function persistDallasApprovalAndRollback(input:{identity:DallasV3FrozenIdentity;before:DallasRollbackArtifact["before"];now:string}){const loaded=load();const prior=loaded.state.decisions.find(item=>item.exactIdentity.approvedV3PreviewHash===input.identity.approvedV3PreviewHash);if(prior)return {decision:deepClone(prior),rollback:deepClone(loaded.state.rollbacks.find(item=>item.rollbackArtifactId===`rollback-${prior.decisionId}`)!)};const decision:DallasV3OwnerDecision={decisionId:`dallas-v3-decision-${randomUUID()}`,decision:"APPROVED",exactIdentity:structuredClone(input.identity),ownerStatement:"yes its great",decidedBy:"owner",decidedAt:input.now,publicationAuthorized:false};const rollback:DallasRollbackArtifact={rollbackArtifactId:`rollback-${decision.decisionId}`,before:deepClone(input.before),state:"AVAILABLE",createdAt:input.now,usedAt:null};loaded.state.decisions.push(decision);loaded.state.rollbacks.push(rollback);loaded.state.audit.push({eventId:`audit-${randomUUID()}`,action:"OWNER_APPROVED",at:input.now,detail:{decisionId:decision.decisionId,previewHash:input.identity.approvedV3PreviewHash}},{eventId:`audit-${randomUUID()}`,action:"BEFORE_CAPTURED",at:input.now,detail:{rollbackArtifactId:rollback.rollbackArtifactId,beforeHash:input.before.contentHash}});savePersistedState({namespace:NAMESPACE,state:loaded.state,expectedRevision:loaded.revision});return {decision:deepClone(decision),rollback:deepClone(rollback)}}
export function appendDallasApplyAudit(action:DallasApplyAuditEvent["action"],detail:DallasApplyAuditEvent["detail"],at=new Date().toISOString()){const loaded=load();const event={eventId:`audit-${randomUUID()}`,action,at,detail};loaded.state.audit.push(event);savePersistedState({namespace:NAMESPACE,state:loaded.state,expectedRevision:loaded.revision});return deepClone(event)}
export function saveDallasApplyReceipt(receipt:DallasApplyReceipt){const loaded=load();const existing=loaded.state.receipts.find(item=>item.receiptId===receipt.receiptId);if(existing)return deepClone(existing);loaded.state.receipts.push(deepClone(receipt));savePersistedState({namespace:NAMESPACE,state:loaded.state,expectedRevision:loaded.revision});return deepClone(receipt)}
export function markDallasRollbackUsed(rollbackArtifactId:string,at:string){const loaded=load();const item=loaded.state.rollbacks.find(candidate=>candidate.rollbackArtifactId===rollbackArtifactId);if(!item)throw new Error("DALLAS_ROLLBACK_NOT_FOUND");item.state="USED_VERIFIED";item.usedAt=at;savePersistedState({namespace:NAMESPACE,state:loaded.state,expectedRevision:loaded.revision});return deepClone(item)}
export function saveDallasActualVisualCertification(certification:DallasActualVisualCertification){const loaded=load();const existing=loaded.state.visualCertifications.find(item=>item.certificationId===certification.certificationId);if(existing)return deepClone(existing);loaded.state.visualCertifications.push(deepClone(certification));savePersistedState({namespace:NAMESPACE,state:loaded.state,expectedRevision:loaded.revision});return deepClone(certification)}
export function saveDallasPreviewWordPressComparison(comparison:DallasPreviewWordPressComparison){const loaded=load();const existing=loaded.state.comparisons.find(item=>item.comparisonId===comparison.comparisonId);if(existing)return deepClone(existing);loaded.state.comparisons.push(deepClone(comparison));savePersistedState({namespace:NAMESPACE,state:loaded.state,expectedRevision:loaded.revision});return deepClone(comparison)}