import "server-only";

import { deriveLocalThemeProfile, LOCAL_CONTEXT_CONTRACT, LOCAL_LINK_GRAPH_CONTRACT, APPLICATION_AUTHORITY_CONTRACT, LOCALIZED_COMPOSITION_PLAN_CONTRACT, validateLocalContext, validateLocalLinkGraph, validateApplicationAuthority, validateLocalizedMedia, type LocalResearchEvidence, type LocalizedMediaPlanItem, type SitePageLocalContext, type SitePageLocalLinkGraph, type SitePageApplicationAuthority } from "@/modules/foundation/local-context-page-theming";
import { getLocalPageThemingBundle, saveLocalPageThemingBundle, saveLocalPageThemingMedia, type LocalPageThemingBundle } from "@/modules/foundation/local-context-page-theming-repository";
import { getProductById } from "@/modules/foundation/product-repository";
import { listSitePageMediaAssignments } from "@/modules/foundation/site-page-media-assignment";
import { getSiteById } from "@/modules/foundation/site-repository";
import { listGlwCampaigns } from "./campaign-repository";
import { listAllGlwCampaignTargets } from "./campaign-target-repository";
import { generateGenesisFeaturedImage } from "./generated-image-service";
import { glwPageExecutionRepository } from "./page-execution-repository";
import { generateGenesisFeaturedImageWithCampaignReferences } from "./reference-aware-image-service";

const JOB_ID = "2ca74016-252b-4587-bf3c-ec9b7eb839c9";
const BUNDLE_ID = `local-theming-dallas-${JOB_ID}-v2`;
const PRODUCT_ID = "prod-ssi-fan-cooled-projector-enclosures";
const SOURCES = [
  ["product", "https://projectorenclosure.com/fan-cooled-projector-enclosures/", "Fan Cooled Projector Enclosures", "ProjectorEnclosure / Screen Solutions International", "OWNER_AUTHORITY", "The canonical product page identifies fan-cooled enclosures for indoor, covered outdoor, mild-environment commercial AV, and explicitly includes projection mapping setups."],
  ["catalog", "https://projectorenclosure.com/projector-enclosures/", "Projector Enclosure Lineup", "ProjectorEnclosure / Screen Solutions International", "OFFICIAL_BRAND", "The official enclosure catalog distinguishes product categories by environment and directs buyers to project-specific review."],
  ["outdoor", "https://projectorenclosure.com/ip65-projector-enclosures-for-outdoor-applications/", "Outdoor Projector Enclosures", "ProjectorEnclosure / Screen Solutions International", "OFFICIAL_BRAND", "The official outdoor-enclosure resource is the appropriate path for exposed or demanding outdoor requirements."],
  ["contact", "https://projectorenclosure.com/contact-us-projection-enclosure/", "Project Review and Contact", "ProjectorEnclosure / Screen Solutions International", "OFFICIAL_BRAND", "The official contact path supports product fit, installation-detail, and configuration review."],
  ["ssi", "https://projectorenclosure.com/about-ssi/", "About Screen Solutions International", "Screen Solutions International", "OWNER_AUTHORITY", "The official brand page identifies the relationship between ProjectorEnclosure and Screen Solutions International."],
  ["climate", "https://www.weather.gov/fwd/dfw_records_normals", "DFW Normals, Means, and Extremes", "National Weather Service Fort Worth/Dallas", "GOVERNMENT", "Official DFW climate normals document hot summers, precipitation, thunderstorms, wind, and seasonal temperature variation relevant to site-condition review."],
  ["venues", "https://dallasculture.org/cultural-venues/", "Dallas Cultural Venues", "City of Dallas Office of Arts and Culture", "GOVERNMENT", "The City documents a varied network of performance halls, galleries, museums, historic buildings, open-air event spaces, and cultural facilities."],
  ["public-art", "https://dallasculture.org/publicart/", "Dallas Public Art", "City of Dallas Office of Arts and Culture", "GOVERNMENT", "The City documents public art across civic spaces and a planning process concerned with location, durability, maintenance, safety, and community context."],
  ["convention", "https://www.dallasconventioncenter.com/about/about-us", "Kay Bailey Hutchison Convention Center Dallas", "Kay Bailey Hutchison Convention Center Dallas", "OFFICIAL_VENUE", "The official venue describes substantial flexible exhibit, ballroom, meeting, convention, concert, and event environments in downtown Dallas."],
] as const;

async function verifiedEvidence(fetcher: typeof fetch, createdAt: string): Promise<LocalResearchEvidence[]> {
  return Promise.all(SOURCES.map(async ([evidenceId, url, title, publisher, sourceClass, observedClaim]) => { const response = await fetcher(url, { method: "GET", redirect: "follow", cache: "no-store", signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error(`LOCAL_RESEARCH_SOURCE_UNAVAILABLE:${evidenceId}:${response.status}`); return { evidenceId, url, title, publisher, sourceClass, retrievedAt: createdAt, verifiedAt: createdAt, httpStatus: response.status, observedClaim }; }));
}

export async function createDallasLocalizedPreviewV2(input: { actor: string; fetcher?: typeof fetch; now?: string }): Promise<LocalPageThemingBundle> {
  const existing = getLocalPageThemingBundle({ organizationId: "ssi", siteId: "site-ssi-projectorenclosure", jobId: JOB_ID, bundleId: BUNDLE_ID }); if (existing) return existing;
  const job = await glwPageExecutionRepository.getById(JOB_ID); const target = listAllGlwCampaignTargets().find((item) => item.jobId === JOB_ID); const campaign = target ? listGlwCampaigns().find((item) => item.campaignId === target.campaignId) : null; const site = getSiteById("site-ssi-projectorenclosure"); const product = getProductById(PRODUCT_ID);
  if (!job || !target || !campaign || !site || !product || job.organizationId !== "ssi" || job.siteId !== site.siteId || job.productId !== PRODUCT_ID || target.status !== "draft_ready" || job.wordpressObjectId !== "13084" || job.wordpressStatus !== "draft" || campaign.publicationPolicy !== "draft_only") throw new Error("DALLAS_LOCALIZED_PREVIEW_IDENTITY_INVALID");
  const pageRevisionIdentity = `job:${job.jobId}:${job.updatedAt}`; const productAssignment = listSitePageMediaAssignments({ organizationId: job.organizationId, siteId: job.siteId, buildSessionId: `glw-job:${job.jobId}`, pageRevisionId: pageRevisionIdentity }).find((item) => item.role === "PRODUCT_AUTHORITY" && item.asset.type === "APPROVED_EXISTING" && item.asset.productId === PRODUCT_ID);
  if (!productAssignment || productAssignment.asset.type !== "APPROVED_EXISTING" || productAssignment.asset.wordpressMediaId !== 10757 || productAssignment.asset.sha256 !== "685495793be84b3a9d1a7e902087d63ae7a636e2042e6c0d592f5ba83e767078") throw new Error("DALLAS_PRODUCT_AUTHORITY_REQUIRED");
  const productAsset = productAssignment.asset;
  const createdAt = input.now ?? new Date().toISOString(); const evidence = await verifiedEvidence(input.fetcher ?? fetch, createdAt); const identity = { organizationId: job.organizationId, siteId: job.siteId, pageId: target.targetId, jobId: job.jobId, pageRevisionIdentity };
  const context: SitePageLocalContext = validateLocalContext({ contract: LOCAL_CONTEXT_CONTRACT, schemaVersion: 1, contextId: `local-context-dallas-${job.jobId}-r1`, identity, geography: { city: "Dallas", state: "Texas", region: "North Texas", countryCode: "US" }, researchRevision: 1, evidence, facts: [
    { factId: "north-texas-environment", kind: "CLIMATE_ENVIRONMENT", statement: "North Texas project planning should account for strong summer heat, precipitation, thunderstorms, wind, and seasonal variation; enclosure selection must follow the exact site exposure and product documentation.", evidenceIds: ["climate", "product", "outdoor"] },
    { factId: "dallas-built-environment", kind: "BUILT_ENVIRONMENT", statement: "Dallas presents a mix of contemporary performance architecture, historic theaters, museums, civic spaces, open-air event settings, and large flexible convention environments.", evidenceIds: ["venues", "convention"] },
    { factId: "dallas-venue-types", kind: "VENUE_ENVIRONMENT", statement: "Relevant planning contexts include galleries, performance halls, museums, campuses, convention spaces, public spaces, and outdoor event areas.", evidenceIds: ["venues", "public-art", "convention", "product"] },
    { factId: "dallas-visual-context", kind: "VISUAL_CONTEXT", statement: "A Level 2 Dallas expression may use broad North Texas sky, warm daylight, contemporary glass and steel, masonry, civic arts architecture, and generous event-space scale without depicting a recognizable property or landmark.", evidenceIds: ["venues", "public-art", "convention", "climate"] },
    { factId: "projection-mapping-opportunity", kind: "APPLICATION_OPPORTUNITY", statement: "Projection mapping is an explicitly documented fan-cooled enclosure application; Dallas cultural, public-art, event, and convention environments provide regional planning context, not evidence of an SSI installation.", evidenceIds: ["product", "venues", "public-art", "convention"] },
  ], prohibitedInferences: ["SSI has a Dallas office", "ProjectorEnclosure is headquartered in Texas", "a depicted Dallas venue is an SSI customer", "a generated scene is an actual Dallas installation", "SSI performed a depicted local project"], createdAt }, pageRevisionIdentity);
  const links: SitePageLocalLinkGraph = validateLocalLinkGraph({ contract: LOCAL_LINK_GRAPH_CONTRACT, schemaVersion: 1, graphId: `local-links-dallas-${job.jobId}-r1`, identity, researchRevision: 1, links: [
    ["fan-cooled", SOURCES[0][1], "product", "INTERNAL_PRODUCT", "Review fan-cooled enclosure details", "Canonical product and fit context."], ["projection-mapping", SOURCES[0][1], "product", "INTERNAL_APPLICATION", "Explore projection-mapping fit", "The canonical product page explicitly includes projection mapping setups."], ["outdoor-planning", SOURCES[2][1], "outdoor", "INTERNAL_CAPABILITY", "Compare outdoor protection requirements", "Directs exposed environments to the appropriate enclosure class."], ["project-review", SOURCES[3][1], "contact", "INTERNAL_SUPPORT", "Request project review", "Supports projector, lens, site-condition, and configuration review."], ["quote", SOURCES[3][1], "contact", "INTERNAL_CONVERSION", "Discuss your Dallas-area project", "Provides the governed conversion destination without implying local presence."], ["nws", SOURCES[5][1], "climate", "REGIONAL_REFERENCE", "Review official DFW climate normals", "Helps buyers evaluate environmental assumptions against official regional data."], ["culture", SOURCES[6][1], "venues", "LOCAL_INSTITUTION", "Understand Dallas venue environments", "Orients planners to the region's documented range of cultural and performance spaces."], ["public-art-link", SOURCES[7][1], "public-art", "LOCAL_AUTHORITY", "Review Dallas public-art planning context", "Provides official context for location, durability, maintenance, safety, and community considerations."], ["convention-link", SOURCES[8][1], "convention", "LOCAL_INSTITUTION", "See the scale of Dallas event environments", "Orients buyers to a documented large-format event and convention context."],
  ].map(([linkId, url, evidenceId, role, anchorIntent, reason]) => ({ linkId, url, destinationIdentity: role.startsWith("INTERNAL") ? `url:${url}` : null, role: role as SitePageLocalLinkGraph["links"][number]["role"], anchorIntent, reason, evidenceIds: [evidenceId], validation: { state: "VERIFIED", httpStatus: 200, checkedAt: createdAt } })), createdAt }, context);
  const applications: SitePageApplicationAuthority = validateApplicationAuthority({ contract: APPLICATION_AUTHORITY_CONTRACT, schemaVersion: 1, authorityId: `applications-dallas-${job.jobId}-r1`, identity, productId: PRODUCT_ID, researchRevision: 1, applications: [
    { applicationId: "PROJECTION_MAPPING", label: "Projection Mapping", compatibility: "SUPPORTED", relationship: "The canonical fan-cooled enclosure page explicitly identifies projection mapping setups as an application, subject to projector, site-condition, and enclosure-configuration review.", evidenceIds: ["product"], internalDestinationUrl: SOURCES[0][1] },
    { applicationId: "COMMERCIAL_AV", label: "Commercial AV", compatibility: "SUPPORTED", relationship: "The product authority supports indoor, covered outdoor, and mild-environment commercial AV installations.", evidenceIds: ["product"], internalDestinationUrl: SOURCES[0][1] },
    { applicationId: "EVENT_VENUE", label: "Event Venues", compatibility: "SUPPORTED", relationship: "The product authority includes commercial installations and the regional evidence documents flexible performance and event environments; exact fit remains project-specific.", evidenceIds: ["product", "venues", "convention"], internalDestinationUrl: SOURCES[0][1] },
    { applicationId: "MUSEUM_ATTRACTION", label: "Museums and Attractions", compatibility: "REVIEW_REQUIRED", relationship: "Official sources establish museum and exhibit contexts, but product fit requires project review.", evidenceIds: ["venues", "product"], internalDestinationUrl: SOURCES[0][1] },
  ], createdAt }, context);
  const theme = deriveLocalThemeProfile({ profileId: `local-theme-dallas-${job.jobId}-r1`, context, applications, brandAuthorityReference: product.brandReference ?? site.profiles.brandProfileReference ?? "profile-brand-projectorenclosure-default", localizationLevel: 2, expression: { heroAtmosphere: "Contemporary North Texas commercial venue at blue hour, broad sky and warm architectural light, without a recognizable property or landmark.", environmentalCharacter: ["large civic and event-space scale", "contemporary glass and steel", "masonry and warm architectural light", "broad North Texas sky"], materialCues: ["powder-coated metal", "glass", "limestone-toned masonry", "architectural concrete"], accentGuidance: "Preserve ProjectorEnclosure red, charcoal, white, and amber hierarchy; local context may affect atmosphere, never the logo or core brand.", visualDensity: "Confident industrial editorial composition with generous visual bands and restrained technical detail.", terminology: ["Dallas", "North Texas", "site conditions", "project review", "covered environment"], compositionEmphasis: ["approved enclosure", "credible in-use context", "projection mapping experience", "regional planning resources"] }, antiClicheTerms: ["cowboy hats", "boots", "longhorns", "Texas flag motif", "desert", "western font", "oil derrick", "ranch imagery", "red-white-blue theme"], createdAt });
  const prompts = {
    inUse: "Create a conceptual, photorealistic commercial AV scene in a covered modern event pavilion with subtle North Texas character: broad sky beyond the structure, warm masonry, glass and steel. Use the supplied approved projector-enclosure reference to show one physically plausible fan-cooled metal enclosure mounted with realistic clearance and a projector lens aligned through its opening. The enclosure is the visible subject. This is not a real Dallas location or installation. No recognizable landmark, people, logos, signage, flags, western imagery, customer identity, text, impossible geometry, exposed rain, or unsupported product features.",
    application: "Create a photorealistic application visualization of large-scale architectural projection mapping on a generic contemporary civic-event facade at blue hour. The environment should feel plausibly North Texas through broad sky, warm limestone-toned masonry, glass and steel, but must not depict or imitate a recognizable Dallas landmark, venue, customer, or actual installation. Show the projection experience as the primary visual and a small technically plausible protected projection position in the foreground using the supplied approved enclosure as form reference. No logos, signage, readable text, crowds, flags, western motifs, performance specifications, or documentary framing.",
    atmosphere: "Create a restrained atmospheric photograph for a commercial AV website: a generic North Texas arts-and-events district at blue hour with broad sky, warm architectural lighting, contemporary glass and steel, limestone-toned masonry, an open civic plaza, and generous negative space. No recognizable Dallas landmark, no people, no projector or enclosure, no logos, signage, flags, cowboy or ranch imagery, readable text, customer identity, or claim of an actual project. This is an atmospheric regional visualization, not documentary evidence.",
  };
  const [inUseResult, applicationResult, atmosphereResult] = await Promise.all([generateGenesisFeaturedImageWithCampaignReferences({ prompt: prompts.inUse, siteName: site.displayName, productTopic: product.displayName, campaignId: campaign.campaignId }), generateGenesisFeaturedImageWithCampaignReferences({ prompt: prompts.application, siteName: site.displayName, productTopic: "projection mapping enabled by protected projection systems", campaignId: campaign.campaignId }), generateGenesisFeaturedImage({ prompt: prompts.atmosphere, siteName: site.displayName, productTopic: "North Texas commercial AV planning atmosphere" })]);
  if (!inUseResult.ok || !applicationResult.ok || !atmosphereResult.ok) throw new Error(`DALLAS_LOCALIZED_MEDIA_GENERATION_FAILED:${[inUseResult, applicationResult, atmosphereResult].filter((item) => !item.ok).map((item) => item.ok ? "" : item.state).join(",")}`);
  const generated = [{ mediaId: "dallas-contextual-in-use-v2", role: "CONTEXTUAL_IN_USE", claimClass: "CONCEPTUAL_CONTEXTUAL", applicationId: "COMMERCIAL_AV", prompt: prompts.inUse, altText: "Concept visualization of a fan-cooled projector enclosure in a covered commercial AV environment", image: inUseResult.image }, { mediaId: "dallas-projection-mapping-v2", role: "APPLICATION_EXPERIENCE", claimClass: "APPLICATION_VISUALIZATION", applicationId: "PROJECTION_MAPPING", prompt: prompts.application, altText: "Application visualization of architectural projection mapping in a North Texas-inspired civic event setting", image: applicationResult.image }, { mediaId: "dallas-atmosphere-v2", role: "LOCAL_CONTEXTUAL_ATMOSPHERE", claimClass: "ATMOSPHERIC", applicationId: null, prompt: prompts.atmosphere, altText: "Atmospheric visualization of a contemporary North Texas arts and event district at blue hour", image: atmosphereResult.image }] as const;
  const generatedMedia = generated.map((item): LocalizedMediaPlanItem => { const stored = saveLocalPageThemingMedia({ bundleId: BUNDLE_ID, mediaId: item.mediaId, mimeType: item.image.mimeType, bytes: item.image.bytes }); return validateLocalizedMedia({ mediaId: item.mediaId, role: item.role, claimClass: item.claimClass, source: "GENERATED_CANDIDATE", productTruthReference: item.role === "LOCAL_CONTEXTUAL_ATMOSPHERE" ? null : productAsset.authorityReference, applicationId: item.applicationId, localContextId: context.contextId, generationPrompt: item.prompt, sha256: stored.sha256, url: `/api/glw/pages/${job.jobId}/localized-preview-v2/media/${item.mediaId}?organizationId=${job.organizationId}&siteId=${job.siteId}`, mimeType: item.image.mimeType, altText: item.altText, ownerReviewState: "PENDING" }, { context, applications }); });
  const productMedia: LocalizedMediaPlanItem = validateLocalizedMedia({ mediaId: "dallas-product-authority-v2", role: "PRODUCT_AUTHORITY", claimClass: "DOCUMENTARY", source: "APPROVED_EXISTING", productTruthReference: productAsset.authorityReference, applicationId: null, localContextId: null, generationPrompt: null, sha256: productAsset.sha256, url: productAsset.url, mimeType: "image/webp", altText: productAssignment.metadata.altText, ownerReviewState: "APPROVED" }, { context, applications });
  const media = [productMedia, ...generatedMedia]; const composition = { contract: LOCALIZED_COMPOSITION_PLAN_CONTRACT, schemaVersion: 2 as const, planId: `composition-plan-dallas-${job.jobId}-v2`, identity, priorPlanId: `composition-plan-${job.jobId}-${job.updatedAt}`, profile: "LOCATION_SERVICE" as const, localContextId: context.contextId, localLinkGraphId: links.graphId, applicationAuthorityId: applications.authorityId, localThemeProfileId: theme.profileId, mediaIds: media.map((item) => item.mediaId), validationState: "READY_FOR_OWNER_REVIEW" as const, blockers: [], wordpressMutationAuthorized: false as const, createdAt };
  return saveLocalPageThemingBundle({ bundleId: BUNDLE_ID, context, links, applications, theme, media, composition, createdAt });
}

export const DALLAS_LOCALIZED_PREVIEW_V2_BUNDLE_ID = BUNDLE_ID;