import "server-only";

import { getLocalPageThemingBundle } from "@/modules/foundation/local-context-page-theming-repository";
import { createCampaignDiscoveryRecommendations, createCrossSellGraph, createMarketProductOpportunity, createPageStrategyRecommendation, createSiteOpportunityBlueprint, mapMarketSignalsToApplications, validateMarketIntelligence, MARKET_INTELLIGENCE_CONTRACT, CROSS_SELL_GRAPH_CONTRACT, type CatalogAuthorityItem, type MarketEvidence, type OpportunityScoreComponent, type RecommendedUse, type SiteMarketIntelligence } from "@/modules/foundation/local-market-product-match";
import { getMarketProductMatchBundle, saveMarketProductMatchBundle, type MarketProductMatchBundle } from "@/modules/foundation/local-market-product-match-repository";
import { listProducts } from "@/modules/foundation/product-repository";

export const DALLAS_MARKET_MATCH_BUNDLE_ID = "market-match-dallas-north-texas-v1";
const JOB_ID = "2ca74016-252b-4587-bf3c-ec9b7eb839c9";
const MARKET_ID = "market-dallas-north-texas";
const FAN_PRODUCT = "prod-ssi-fan-cooled-projector-enclosures";
const HOMELINE_PRODUCT = "prod-ssi-homeline-projector-enclosure";
const MARKET_SOURCES = [
  ["dallas-economic-development", "https://www.dallasecodev.org/", "City of Dallas Office of Economic Development", "GOVERNMENT", "The City documents corporate relocation, commercial development, college-graduate, and North Texas event-related business activity."],
  ["dallas-business-development", "https://www.dallasecodev.org/354/Business-Development", "City of Dallas Office of Economic Development", "GOVERNMENT", "The City supports companies locating or expanding operations and documents business-development and site-selection programs."],
  ["dallas-real-estate", "https://www.dallasecodev.org/352/Redevelopment", "City of Dallas Office of Economic Development", "GOVERNMENT", "The City documents commercial, industrial, mixed-use, and other development and redevelopment activity."],
  ["uta", "https://www.uta.edu/about/fast-facts", "The University of Texas at Arlington", "OFFICIAL_INSTITUTION", "UTA documents 42,710 students in Fall 2025, more than 100 campus buildings, NCAA Division I athletics, research facilities, galleries, and a planetarium."],
] as const;

const addDays = (iso: string, days: number) => new Date(Date.parse(iso) + days * 86_400_000).toISOString();
async function marketEvidence(fetcher: typeof fetch, local: NonNullable<ReturnType<typeof getLocalPageThemingBundle>>, createdAt: string): Promise<MarketEvidence[]> {
  const inherited = local.context.evidence.map((item): MarketEvidence => ({ evidenceId: `local:${item.evidenceId}`, url: item.url, publisher: item.publisher, sourceClass: item.sourceClass === "OFFICIAL_BRAND" ? "OWNER_AUTHORITY" : item.sourceClass, observedClaim: item.observedClaim, retrievedAt: item.retrievedAt, validThrough: addDays(item.verifiedAt, item.sourceClass === "OFFICIAL_VENUE" ? 180 : 365), httpStatus: item.httpStatus }));
  const added = await Promise.all(MARKET_SOURCES.map(async ([evidenceId, url, publisher, sourceClass, observedClaim]): Promise<MarketEvidence> => { const response = await fetcher(url, { method: "GET", cache: "no-store", redirect: "follow", signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error(`MARKET_SOURCE_UNAVAILABLE:${evidenceId}:${response.status}`); return { evidenceId, url, publisher, sourceClass, observedClaim, retrievedAt: createdAt, validThrough: addDays(createdAt, evidenceId === "dallas-economic-development" ? 180 : 365), httpStatus: response.status }; }));
  return [...inherited, ...added];
}

const score = (values: Partial<Record<OpportunityScoreComponent["dimension"], OpportunityScoreComponent["value"]>>, evidenceIds: readonly string[]): OpportunityScoreComponent[] => (["MARKET_EVIDENCE_STRENGTH", "VERTICAL_FIT", "APPLICATION_FIT", "PRODUCT_FIT", "LOCAL_CONDITION_FIT", "COMMERCIAL_INTENT", "CATALOG_AUTHORITY_CONFIDENCE"] as const).map((dimension) => ({ dimension, value: values[dimension] ?? "HIGH", rationale: `${dimension.replaceAll("_", " ")} is ${values[dimension] ?? "HIGH"} based on the cited market, application, and catalog authority.`, evidenceIds }));

export async function createDallasMarketProductMatchV1(input: { fetcher?: typeof fetch; now?: string } = {}): Promise<MarketProductMatchBundle> {
  const existing = getMarketProductMatchBundle({ organizationId: "ssi", bundleId: DALLAS_MARKET_MATCH_BUNDLE_ID }); if (existing) return existing;
  const local = getLocalPageThemingBundle({ organizationId: "ssi", siteId: "site-ssi-projectorenclosure", jobId: JOB_ID }); if (!local || local.composition.validationState !== "READY_FOR_OWNER_REVIEW") throw new Error("DALLAS_LOCAL_CONTEXT_AUTHORITY_REQUIRED");
  const createdAt = input.now ?? new Date().toISOString(); const evidence = await marketEvidence(input.fetcher ?? fetch, local, createdAt); const market = { marketId: MARKET_ID, geography: { city: "Dallas", state: "Texas", region: "Dallas-Fort Worth / North Texas", countryCode: "US" }, scope: "Dallas-Fort Worth commercial, institutional, cultural, event, and outdoor projection environments" };
  const signals: SiteMarketIntelligence["signals"] = [
    { signalId: "venue-ecosystem", signalClass: "VENUE_ECOSYSTEM", statement: "Official Dallas sources document a broad set of cultural, performance, museum, open-air, and convention venues.", buyerVerticals: ["venue operators", "AV integrators", "facility planners"], evidenceIds: ["local:venues", "local:convention"], evidenceStrength: "STRONG", freshness: "CURRENT" },
    { signalId: "events-experiential", signalClass: "EVENTS_EXPERIENTIAL", statement: "Official sources document public art, performance settings, exhibitions, conventions, concerts, and event environments where visual experiences are relevant planning contexts.", buyerVerticals: ["event producers", "cultural institutions", "AV integrators"], evidenceIds: ["local:public-art", "local:venues", "local:convention"], evidenceStrength: "STRONG", freshness: "CURRENT" },
    { signalId: "education-ecosystem", signalClass: "EDUCATION_ECOSYSTEM", statement: "UTA documents a large North Texas campus with research, gallery, planetarium, athletics, and instructional environments.", buyerVerticals: ["universities", "campus facilities", "education AV"], evidenceIds: ["uta"], evidenceStrength: "STRONG", freshness: "CURRENT" },
    { signalId: "museum-attraction", signalClass: "MUSEUM_ATTRACTION_ECOSYSTEM", statement: "City sources document museums, galleries, historic facilities, public art, and visitor-facing cultural environments.", buyerVerticals: ["museums", "attractions", "cultural institutions"], evidenceIds: ["local:venues", "local:public-art"], evidenceStrength: "STRONG", freshness: "CURRENT" },
    { signalId: "sports-ecosystem", signalClass: "SPORTS_ECOSYSTEM", statement: "Official sources document NCAA Division I athletics and current North Texas sports-event business activity, but do not establish specific enclosure demand.", buyerVerticals: ["sports venues", "campus athletics"], evidenceIds: ["uta", "dallas-economic-development"], evidenceStrength: "MODERATE", freshness: "CURRENT" },
    { signalId: "climate-exposure", signalClass: "CLIMATE_EXPOSURE", statement: "Official DFW normals document heat, precipitation, thunderstorms, wind, and seasonal variation relevant to environmental review.", buyerVerticals: ["facility planners", "AV integrators"], evidenceIds: ["local:climate"], evidenceStrength: "STRONG", freshness: "CURRENT" },
    { signalId: "outdoor-environment", signalClass: "OUTDOOR_ENVIRONMENT", statement: "Official regional and venue sources establish outdoor and open-air contexts, while product authority requires exact exposure review.", buyerVerticals: ["event venues", "public-space planners"], evidenceIds: ["local:climate", "local:venues", "local:outdoor"], evidenceStrength: "MODERATE", freshness: "CURRENT" },
    { signalId: "corporate-development", signalClass: "CORPORATE_DEVELOPMENT", statement: "City economic-development sources document companies locating and expanding operations in Dallas.", buyerVerticals: ["corporate facilities", "commercial developers"], evidenceIds: ["dallas-economic-development", "dallas-business-development"], evidenceStrength: "MODERATE", freshness: "CURRENT" },
    { signalId: "building-activity", signalClass: "BUILDING_ACTIVITY", statement: "City sources document active commercial, industrial, mixed-use, and civic development programs.", buyerVerticals: ["developers", "architects", "facility planners"], evidenceIds: ["dallas-real-estate", "dallas-economic-development"], evidenceStrength: "MODERATE", freshness: "CURRENT" },
    { signalId: "convention-tourism", signalClass: "CONVENTION_TOURISM", statement: "The official convention center documents substantial exhibit, ballroom, meeting, convention, concert, and event capacity.", buyerVerticals: ["convention operators", "event producers", "hospitality AV"], evidenceIds: ["local:convention"], evidenceStrength: "STRONG", freshness: "CURRENT" },
  ];
  const intelligence = validateMarketIntelligence({ contract: MARKET_INTELLIGENCE_CONTRACT, schemaVersion: 1, intelligenceId: `market-intelligence-${MARKET_ID}-r1`, organizationId: "ssi", market, researchRevision: 1, evidence, signals, competitiveIntensity: "NOT_EVALUATED", createdAt, provenance: `Governed synthesis of ${local.context.contextId} plus current official Dallas economic-development and UTA evidence.` }, createdAt);
  const rules = [{ applicationId: "PROJECTION_MAPPING", requiredSignalClasses: ["VENUE_ECOSYSTEM", "EVENTS_EXPERIENTIAL"], rationale: "Venue and experiential evidence must both be present." }, { applicationId: "COMMERCIAL_AV", requiredSignalClasses: ["VENUE_ECOSYSTEM", "CORPORATE_DEVELOPMENT"], rationale: "Venue and corporate environment signals support commercial AV planning." }, { applicationId: "EVENT_VENUE", requiredSignalClasses: ["VENUE_ECOSYSTEM", "CONVENTION_TOURISM"], rationale: "Documented event and convention environments support venue evaluation." }, { applicationId: "EDUCATION_CAMPUS", requiredSignalClasses: ["EDUCATION_ECOSYSTEM"], rationale: "Official campus evidence supports education application analysis." }, { applicationId: "MUSEUM_ATTRACTION", requiredSignalClasses: ["MUSEUM_ATTRACTION_ECOSYSTEM"], rationale: "Official museum and cultural evidence supports application analysis." }, { applicationId: "SPORTS_STADIUM", requiredSignalClasses: ["SPORTS_ECOSYSTEM"], rationale: "Sports ecosystem evidence supports evaluation, not product fit by itself." }, { applicationId: "OUTDOOR_PROJECTION", requiredSignalClasses: ["OUTDOOR_ENVIRONMENT", "CLIMATE_EXPOSURE"], rationale: "Outdoor context and climate evidence are both required." }, { applicationId: "IMMERSIVE_MEDIA", requiredSignalClasses: ["MUSEUM_ATTRACTION_ECOSYSTEM", "EVENTS_EXPERIENTIAL"], rationale: "Museum and experiential signals support immersive-media evaluation." }, { applicationId: "EXPERIENTIAL_AV", requiredSignalClasses: ["EVENTS_EXPERIENTIAL"], rationale: "Experiential venue evidence supports evaluation." }, { applicationId: "DVLED", requiredSignalClasses: ["VENUE_ECOSYSTEM"], rationale: "Venue evidence permits evaluation but does not establish catalog authority." }, { applicationId: "TRANSPARENT_DISPLAY", requiredSignalClasses: ["CORPORATE_DEVELOPMENT"], rationale: "Corporate environments permit evaluation but do not establish catalog authority." }, { applicationId: "INTERACTIVE_TECHNOLOGY", requiredSignalClasses: ["EDUCATION_ECOSYSTEM", "CORPORATE_DEVELOPMENT"], rationale: "Education and corporate signals permit evaluation but do not establish catalog authority." }] as const;
  const applicationMappings = mapMarketSignalsToApplications({ intelligence, rules, now: createdAt }); const products = listProducts().filter((item) => item.organizationId === "ssi" && item.catalogStatus === "ready"); const localSupported = local.applications.applications.filter((item) => item.compatibility === "SUPPORTED").map((item) => item.applicationId);
  const catalog: CatalogAuthorityItem[] = products.map((product) => ({ catalogItemId: product.productId, organizationId: product.organizationId, siteId: product.primarySiteId, name: product.displayName, kind: "PRODUCT", authorityState: product.enabled && Boolean(product.authorityProvenance?.authorityReference) ? "APPROVED" : "UNAPPROVED", authorityReference: product.authorityProvenance?.authorityReference ?? null, supportedApplications: product.productId === FAN_PRODUCT ? localSupported : product.productId === HOMELINE_PRODUCT ? ["PROJECTION_MAPPING", "OUTDOOR_PROJECTION"] : [], buyerVerticals: product.productId === HOMELINE_PRODUCT ? ["residential buyers"] : product.productId === FAN_PRODUCT ? ["AV integrators", "facility planners", "event producers", "corporate facilities"] : [] }));
  const fan = catalog.find((item) => item.catalogItemId === FAN_PRODUCT) ?? null; const mapping = (applicationId: string) => applicationMappings.find((item) => item.applicationId === applicationId)!;
  const opportunity = (spec: { id: string; applicationId: string; buyer: string; catalogItem: CatalogAuthorityItem | null; signalIds: string[]; evidenceIds: string[]; uses: RecommendedUse[]; values?: Partial<Record<OpportunityScoreComponent["dimension"], OpportunityScoreComponent["value"]>>; whyProduct: string; risks: string[] }) => createMarketProductOpportunity({ opportunityId: spec.id, organizationId: "ssi", market, buyerVertical: spec.buyer, signalIds: spec.signalIds, applicationId: spec.applicationId, catalogItemId: spec.catalogItem?.catalogItemId ?? null, catalogAuthorityReference: spec.catalogItem?.authorityReference ?? null, whyMarket: `Dallas evidence supports ${spec.applicationId.replaceAll("_", " ").toLowerCase()} evaluation through ${spec.signalIds.join(" and ")}.`, whyBuyer: `${spec.buyer} are the bounded buyer group associated with the cited signals.`, whyApplication: mapping(spec.applicationId).rationale, whyProduct: spec.whyProduct, scoreComponents: score(spec.values ?? {}, spec.evidenceIds), recommendedUsage: spec.uses, crossSellAdjacencyIds: spec.catalogItem?.catalogItemId === FAN_PRODUCT ? ["fan-to-homeline-projection"] : [], evidenceIds: spec.evidenceIds, risks: spec.risks, createdAt, intelligence, application: mapping(spec.applicationId), catalogItem: spec.catalogItem, now: createdAt });
  const opportunities = [
    opportunity({ id: "dallas-projection-mapping", applicationId: "PROJECTION_MAPPING", buyer: "AV integrators", catalogItem: fan, signalIds: ["venue-ecosystem", "events-experiential"], evidenceIds: ["local:product", "local:venues", "local:public-art", "local:convention"], uses: ["PAGE_PRIMARY", "CAMPAIGN_CANDIDATE", "SITE_PRIMARY"], values: { LOCAL_CONDITION_FIT: "MEDIUM" }, whyProduct: "Approved fan-cooled product authority explicitly includes projection mapping setups, subject to project-specific fit review.", risks: ["No Dallas installation or customer proof exists.", "Exposed environments may require another enclosure class."] }),
    opportunity({ id: "dallas-commercial-av", applicationId: "COMMERCIAL_AV", buyer: "corporate facilities", catalogItem: fan, signalIds: ["venue-ecosystem", "corporate-development"], evidenceIds: ["local:product", "local:venues", "dallas-business-development"], uses: ["PAGE_SUPPORTING", "CAMPAIGN_CANDIDATE", "SITE_PRIMARY"], values: { LOCAL_CONDITION_FIT: "MEDIUM" }, whyProduct: "Approved product authority supports indoor, covered outdoor, and mild-environment commercial AV installations.", risks: ["Market presence does not prove a specific project requirement."] }),
    opportunity({ id: "dallas-event-venue", applicationId: "EVENT_VENUE", buyer: "event producers", catalogItem: fan, signalIds: ["venue-ecosystem", "convention-tourism"], evidenceIds: ["local:product", "local:venues", "local:convention"], uses: ["PAGE_SUPPORTING", "SITE_SECONDARY"], values: { COMMERCIAL_INTENT: "LOW", LOCAL_CONDITION_FIT: "MEDIUM" }, whyProduct: "The approved application authority connects fan-cooled enclosures to event-venue planning under bounded site conditions.", risks: ["Venue ecosystem evidence is not a customer or demand-volume claim."] }),
    opportunity({ id: "dallas-education-campus", applicationId: "EDUCATION_CAMPUS", buyer: "campus facilities", catalogItem: null, signalIds: ["education-ecosystem"], evidenceIds: ["uta", "local:product"], uses: ["PAGE_SUPPORTING"], whyProduct: "No approved product/application compatibility record is available in the current application authority.", risks: ["Do not convert campus presence into demand."] }),
    opportunity({ id: "dallas-museum-attraction", applicationId: "MUSEUM_ATTRACTION", buyer: "museums", catalogItem: null, signalIds: ["museum-attraction"], evidenceIds: ["local:venues", "local:public-art"], uses: ["PAGE_SUPPORTING"], whyProduct: "Museum compatibility remains review-required in current application authority.", risks: ["No specific institution may be represented as a customer."] }),
    opportunity({ id: "dallas-sports-stadium", applicationId: "SPORTS_STADIUM", buyer: "sports venues", catalogItem: null, signalIds: ["sports-ecosystem"], evidenceIds: ["uta", "dallas-economic-development"], uses: ["CROSS_SELL"], whyProduct: "No approved sports/stadium compatibility exists for the current product authority.", risks: ["Sports activity alone is not product demand."] }),
    opportunity({ id: "dallas-outdoor-projection", applicationId: "OUTDOOR_PROJECTION", buyer: "event venues", catalogItem: null, signalIds: ["outdoor-environment", "climate-exposure"], evidenceIds: ["local:climate", "local:outdoor", "local:venues"], uses: ["CROSS_SELL"], whyProduct: "The approved commercial fan-cooled product is bounded to covered or mild environments; no approved commercial outdoor catalog match is available.", risks: ["Do not use fan-cooled authority for exposed conditions."] }),
    ...(["IMMERSIVE_MEDIA", "EXPERIENTIAL_AV", "DVLED", "TRANSPARENT_DISPLAY", "INTERACTIVE_TECHNOLOGY"] as const).map((applicationId) => opportunity({ id: `dallas-${applicationId.toLowerCase().replaceAll("_", "-")}`, applicationId, buyer: applicationId === "INTERACTIVE_TECHNOLOGY" ? "education and corporate buyers" : "experience designers", catalogItem: null, signalIds: mapping(applicationId).signalIds as string[], evidenceIds: mapping(applicationId).signalIds.flatMap((id) => signals.find((signal) => signal.signalId === id)?.evidenceIds ?? []), uses: ["CROSS_SELL"], whyProduct: "The current approved SSI catalog does not establish a compatible product for this application.", risks: ["Public brand marketing is not a substitute for approved catalog authority."] })),
  ];
  const crossSellGraph = createCrossSellGraph({ contract: CROSS_SELL_GRAPH_CONTRACT, schemaVersion: 1, graphId: `cross-sell-${MARKET_ID}-r1`, organizationId: "ssi", marketId: MARKET_ID, edges: [{ adjacencyId: "fan-to-homeline-projection", fromCatalogItemId: FAN_PRODUCT, toCatalogItemId: HOMELINE_PRODUCT, applicationId: "PROJECTION_MAPPING", reasonType: "SAME_APPLICATION", reason: "Both approved enclosure records cite projection-mapping contexts, but Homeline is limited to a separate residential buyer intent and is not selected for the Dallas commercial page.", authorityReferences: [fan?.authorityReference ?? "", catalog.find((item) => item.catalogItemId === HOMELINE_PRODUCT)?.authorityReference ?? ""].filter(Boolean), confidence: "LOW" }], createdAt }, catalog);
  const campaignDiscovery = createCampaignDiscoveryRecommendations(opportunities); const pageStrategy = createPageStrategyRecommendation({ pageId: local.context.identity.pageId, primaryApplication: "PROJECTION_MAPPING", supportingApplications: ["COMMERCIAL_AV", "EVENT_VENUE"], crossSellCatalogItemIds: [], rejectedAdjacencies: opportunities.filter((item) => item.confidence === "INSUFFICIENT_EVIDENCE").map((item) => ({ applicationId: item.applicationId, reason: item.whyConfidence })), internalLinkIds: ["fan-cooled", "projection-mapping", "outdoor-planning", "project-review", "quote"], localAuthorityLinkIds: ["nws", "culture", "public-art-link", "convention-link"], mediaRoles: ["PRODUCT_AUTHORITY", "CONTEXTUAL_IN_USE", "APPLICATION_EXPERIENCE", "LOCAL_CONTEXTUAL_ATMOSPHERE"], ctaIntent: "Request project-specific enclosure review.", compositionAuthorityPreserved: true, mutationAuthorized: false });
  const siteBlueprint = createSiteOpportunityBlueprint({ blueprintId: `site-blueprint-${MARKET_ID}-r1`, organizationId: "ssi", market, catalogScope: catalog.map((item) => item.catalogItemId), priorityProducts: opportunities.filter((item) => item.confidence === "HIGH" && item.catalogItemId).map((item) => item.catalogItemId!), priorityVerticals: ["AV integrators", "corporate facilities", "event producers"], applications: ["PROJECTION_MAPPING", "COMMERCIAL_AV", "EVENT_VENUE"], pageArchitecture: ["product families", "applications", "market context", "project planning", "contact / quote"], internalLinkRecommendations: [{ from: "market context", to: "fan-cooled product", reason: "Connect regional planning context to approved product truth." }, { from: "projection mapping", to: "project review", reason: "Move a qualified application into fit review." }], conversionStrategy: ["Request projector model, lens, exposure, mounting, airflow, and service constraints."], mediaStrategy: ["Keep product, in-use, application experience, and local atmosphere roles distinct."], themeContextStrategy: ["Use Level 2 North Texas expression under ProjectorEnclosure brand authority."], evidence, evidenceIds: ["local:product", "local:venues", "local:climate", "dallas-business-development"], confidence: "HIGH", freshness: "CURRENT", createdAt });
  const commercialEvidence: MarketEvidence = { evidenceId: "commercial-stainless-site", url: "https://commercialstainlesscounters.com/", publisher: "Commercial Stainless Counters", sourceClass: "OWNER_AUTHORITY", observedClaim: "The approved site presents commercial counters, worktables, countertops, mobile workstations, design-build fabrication, six industry pathways, and a requirements-led quote path.", retrievedAt: createdAt, validThrough: addDays(createdAt, 365), httpStatus: 200 };
  const commercialBlueprint = createSiteOpportunityBlueprint({ blueprintId: "site-blueprint-commercial-stainless-read-only-v1", organizationId: "rj-metal", market: { marketId: "market-commercial-stainless-current-scope", geography: { city: null, state: "Unspecified", region: "United States", countryCode: "US" }, scope: "Commercial buyers represented by the approved live site" }, catalogScope: ["commercial-stainless-counters", "commercial-worktables-and-prep-tables", "design-build-fabrication", "mobile-and-modular-stainless-workstations", "stainless-countertop"], priorityProducts: ["commercial-stainless-counters", "design-build-fabrication"], priorityVerticals: ["education", "foodservice", "healthcare", "hospitality", "industrial", "labs"], applications: ["COMMERCIAL_WORKSURFACES", "CUSTOM_FABRICATION"], pageArchitecture: ["products and solutions", "capabilities", "industries and applications", "commercial project planning", "request a quote"], internalLinkRecommendations: [{ from: "industry pathway", to: "relevant product solution", reason: "Connect buyer context to the appropriate approved solution." }, { from: "product solution", to: "request a quote", reason: "Move known dimensions, drawings, interfaces, and constraints into review." }], conversionStrategy: ["Request application, dimensions, drawings, photographs, equipment interfaces, schedule, and constraints."], mediaStrategy: ["Use approved fabrication and product evidence; do not imply undocumented facilities or projects."], themeContextStrategy: ["Preserve the approved Commercial Stainless brand and composition direction."], evidence: [commercialEvidence], evidenceIds: [commercialEvidence.evidenceId], confidence: "MEDIUM", freshness: "CURRENT", createdAt });
  return saveMarketProductMatchBundle({ bundleId: DALLAS_MARKET_MATCH_BUNDLE_ID, intelligence, catalog, applicationMappings, opportunities, crossSellGraph, campaignDiscovery, pageStrategy, siteBlueprint, proofBlueprints: [commercialBlueprint], createdAt });
}