import type { LocalThemeVisualCertification } from "@/modules/foundation/local-theme-visual-certification";
import type { HoustonReferencePreview } from "./houston-reference-preview";
import { GlwMarketInformedReferencePreview } from "./GlwMarketInformedReferencePreview";

const label = (value: string) => value.replaceAll("_", " ");

export function GlwHoustonReferencePreviewReview({ preview, certification }: { preview: HoustonReferencePreview; certification: LocalThemeVisualCertification | null }) {
  const { bundle, market, narrative, comparison } = preview;
  const high = market.opportunities.filter((item) => item.confidence === "HIGH");
  const medium = market.opportunities.filter((item) => item.confidence === "MEDIUM");
  const insufficient = market.opportunities.filter((item) => item.confidence === "INSUFFICIENT_EVIDENCE");
  return <div className="space-y-6">
    <header className="border border-emerald-800 bg-emerald-950/20 p-6"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-300">Houston Reference Candidate</p><h1 className="mt-3 text-3xl font-black text-white">Houston market-informed preview for owner review</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-zinc-300">Fresh Houston and Southeast Texas evidence informs this preview. Dallas supplies process discipline only; no Dallas local source, theme, generated image, or market conclusion is reused.</p><div className="mt-5 flex flex-wrap gap-2"><span className="border border-emerald-700 px-3 py-2 text-xs font-bold text-emerald-200">PREVIEW ONLY</span><span className="border border-amber-700 px-3 py-2 text-xs font-bold text-amber-200">OWNER REVIEW REQUIRED</span><span className="border border-zinc-700 px-3 py-2 text-xs font-bold text-zinc-300">NO APPLY OR PUBLISH CONTROL</span></div></header>
    <section className="grid gap-px bg-zinc-800 sm:grid-cols-2 lg:grid-cols-4"><article className="bg-zinc-950 p-4"><p className="text-xs uppercase text-zinc-500">Primary application</p><p className="mt-2 font-bold text-white">{label(market.pageStrategy.primaryApplication ?? "NONE")}</p></article><article className="bg-zinc-950 p-4"><p className="text-xs uppercase text-zinc-500">Supporting</p><p className="mt-2 text-sm text-white">{market.pageStrategy.supportingApplications.map(label).join(" · ")}</p></article><article className="bg-zinc-950 p-4"><p className="text-xs uppercase text-zinc-500">Localization</p><p className="mt-2 font-bold text-white">LEVEL {bundle.theme.localizationLevel}</p></article><article className="bg-zinc-950 p-4"><p className="text-xs uppercase text-zinc-500">Visual certification</p><p className={`mt-2 font-bold ${certification?.state === "READY_FOR_OWNER_REVIEW" ? "text-emerald-300" : "text-amber-300"}`}>{certification?.state.replaceAll("_", " ") ?? "CAPTURE PENDING"}</p></article></section>
    <section className="border border-zinc-800 bg-zinc-900/45 p-5"><h2 className="text-xl font-bold text-white">Research and environmental truth</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{bundle.context.facts.map((fact) => <article key={fact.factId} className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs font-bold uppercase text-emerald-300">{label(fact.kind)}</p><p className="mt-2 text-sm leading-6 text-zinc-300">{fact.statement}</p><p className="mt-2 text-xs text-zinc-600">Evidence: {fact.evidenceIds.join(" · ")}</p></article>)}</div><p className="mt-4 text-xs text-zinc-500">{bundle.context.evidence.length} current sources · {market.intelligence.signals.length} independently derived Houston market signals</p></section>
    <section className="border border-zinc-800 bg-zinc-900/45 p-5"><h2 className="text-xl font-bold text-white">Opportunity and product suitability</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><article className="border border-emerald-900 bg-zinc-950 p-4"><p className="text-xs font-bold text-emerald-300">HIGH</p><p className="mt-2 text-sm text-white">{high.map((item) => label(item.applicationId)).join(" · ") || "None"}</p></article><article className="border border-amber-900 bg-zinc-950 p-4"><p className="text-xs font-bold text-amber-300">MEDIUM</p><p className="mt-2 text-sm text-white">{medium.map((item) => label(item.applicationId)).join(" · ") || "None"}</p></article><article className="border border-zinc-700 bg-zinc-950 p-4"><p className="text-xs font-bold text-zinc-400">INSUFFICIENT EVIDENCE</p><p className="mt-2 text-sm text-zinc-300">{insufficient.map((item) => label(item.applicationId)).join(" · ")}</p></article></div><div className="mt-4 border border-amber-700 bg-amber-950/20 p-4"><p className="font-bold text-amber-200">{narrative.suitabilityHeading}</p><p className="mt-2 text-sm leading-6 text-amber-100/80">{narrative.suitabilityBody}</p><p className="mt-2 text-xs text-amber-300">Climate-controlled guidance is a verified resource recommendation, not an invented catalog SKU.</p></div></section>
    <section className="border border-zinc-800 bg-zinc-900/45 p-5"><h2 className="text-xl font-bold text-white">Why Houston is different from Dallas</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs uppercase text-zinc-500"><tr><th className="p-3">Evidence dimension</th><th className="p-3">Dallas reference</th><th className="p-3">Houston proposed</th></tr></thead><tbody className="divide-y divide-zinc-800"><tr><td className="p-3 text-zinc-400">Primary application</td><td className="p-3 text-white">{label(comparison.dallasPrimaryApplication)}</td><td className="p-3 text-emerald-300">{label(comparison.houstonPrimaryApplication)}</td></tr><tr><td className="p-3 text-zinc-400">Environmental emphasis</td><td className="p-3 text-white">North Texas seasonal planning</td><td className="p-3 text-emerald-300">Heat, humidity, rainfall, storm exposure, suitability boundary</td></tr><tr><td className="p-3 text-zinc-400">Built environment</td><td className="p-3 text-white">Civic arts and event district</td><td className="p-3 text-emerald-300">Convention, hospitality, cultural, and Ship Channel scale</td></tr><tr><td className="p-3 text-zinc-400">Evidence separation</td><td className="p-3 text-white">Certified process reference</td><td className="p-3 text-emerald-300">Fresh sources, links, theme, and generated media</td></tr></tbody></table></div><p className="mt-4 text-xs text-zinc-500">Primary {comparison.primaryApplicationDifferent ? "DIFFERENT" : "SAME"} · Theme {comparison.themeDifferent ? "DIFFERENT" : "SAME"} · Market evidence {comparison.marketEvidenceDifferent ? "DIFFERENT" : "SAME"} · Media {comparison.mediaDifferent ? "DIFFERENT" : "SAME"} · Links {comparison.linkGraphDifferent ? "DIFFERENT" : "SAME"}</p></section>
    {certification ? <section className="border border-zinc-800 bg-zinc-900/45 p-5"><h2 className="text-xl font-bold text-white">Preview visual findings</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{certification.captures.map((capture) => <article key={capture.captureId} className="border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs font-bold text-emerald-300">{label(capture.viewport)}</p><p className="mt-2 text-sm text-white">Overflow {capture.horizontalOverflow}px</p><p className="mt-1 text-xs text-zinc-500">Media {capture.media.filter((item) => item.rendered).length}/4 · Sections {capture.sections.length}</p></article>)}</div><div className="mt-4 divide-y divide-zinc-800">{certification.findings.map((finding) => <div key={finding.code} className="flex justify-between gap-4 py-3 text-sm"><span className="text-zinc-300">{label(finding.code)}</span><span className={finding.state === "PASS" ? "text-emerald-300" : finding.state === "FAIL" ? "text-red-300" : "text-amber-300"}>{finding.state}</span></div>)}</div></section> : null}
    <section className="border border-zinc-700 bg-zinc-950 p-2"><GlwMarketInformedReferencePreview bundle={bundle} market={market} narrative={narrative} /></section>
  </div>;
}
