import React from "react";
import Image from "next/image";
import type { LocalPageThemingBundle } from "@/modules/foundation/local-context-page-theming-repository";
import type { MarketProductMatchBundle } from "@/modules/foundation/local-market-product-match-repository";

const role = (bundle: LocalPageThemingBundle, value: LocalPageThemingBundle["media"][number]["role"]) => bundle.media.find((item) => item.role === value)!;
const linksByRole = (bundle: LocalPageThemingBundle, roles: readonly string[]) => bundle.links.links.filter((link) => roles.includes(link.role));

export function GlwLocalizedRichCompositionPreview({ bundle, compact = false, market = null, sourceHtml = null }: { bundle: LocalPageThemingBundle; compact?: boolean; market?: MarketProductMatchBundle | null; sourceHtml?: string | null }) {
  const product = role(bundle, "PRODUCT_AUTHORITY"); const inUse = role(bundle, "CONTEXTUAL_IN_USE"); const application = role(bundle, "APPLICATION_EXPERIENCE"); const atmosphere = role(bundle, "LOCAL_CONTEXTUAL_ATMOSPHERE");
  const primary = bundle.links.links.find((link) => link.role === "INTERNAL_CONVERSION")!; const productLink = bundle.links.links.find((link) => link.role === "INTERNAL_PRODUCT")!; const applicationLink = bundle.links.links.find((link) => link.role === "INTERNAL_APPLICATION")!;
  const { city, state, region } = bundle.context.geography;
  const primaryApplication = bundle.applications.applications.find((item) => item.applicationId === application.applicationId) ?? bundle.applications.applications.find((item) => item.compatibility === "SUPPORTED")!;
  const contextSummary = bundle.context.facts.slice(0, 3).map((fact) => fact.statement).join(" ");
  const heroStyle = { backgroundImage: `linear-gradient(90deg,rgba(17,22,23,.96) 0%,rgba(17,22,23,.78) 48%,rgba(17,22,23,.28) 100%),url("${atmosphere.url.replaceAll('"', "%22")}")` };
  return <article className="overflow-hidden bg-[#f3f1eb] text-[#172022]" data-genesis-primary-content data-preview-authority="NON_MUTATING" data-composition-profile="LOCATION_SERVICE" data-localization-level={bundle.theme.localizationLevel}>
    <div className="flex min-h-12 items-center justify-between gap-4 bg-[#b3261e] px-5 py-3 text-[11px] font-black uppercase text-white sm:px-8"><span>{market ? "Proposed Market-Informed Composition V3" : "Proposed Localized Rich Composition V2"}</span><span>Preview - Not Applied to WordPress</span></div>
    <header className="flex min-h-16 items-center justify-between border-b border-black/10 bg-white px-5 sm:px-8 lg:px-[6vw]"><a href="#top" className="text-sm font-black uppercase tracking-[0.16em] text-[#172022]">ProjectorEnclosure <span className="text-[#b3261e]">/ SSI</span></a><nav className="hidden items-center gap-6 text-xs font-bold text-[#4e5959] md:flex"><a href="#product">Enclosure</a><a href="#applications">Applications</a><a href="#planning">{region} planning</a><a href={primary.url}>Project review</a></nav></header>
    <section id="top" className={`flex flex-col justify-end bg-[#172022] bg-cover bg-center px-5 py-14 text-white sm:px-8 ${compact ? "min-h-[430px]" : "min-h-[680px] lg:px-[8vw]"}`} style={heroStyle} data-genesis-hero data-media-role="LOCAL_CONTEXTUAL_ATMOSPHERE">
      <div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#f2b84b]">ProjectorEnclosure × {city}, {state}</p><h1 className="mt-5 text-4xl font-black leading-[1.02] sm:text-6xl lg:text-7xl">Protected projection, planned for {city}.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/82 sm:text-lg">Fan-cooled projector enclosures for indoor, covered outdoor, and mild-environment commercial AV projects, with product and site-condition review for the exact installation.</p><div className="mt-8 flex flex-wrap gap-3"><a href={primary.url} className="bg-[#f2b84b] px-5 py-3 text-sm font-black text-[#172022]">Discuss your project</a><a href={productLink.url} className="border border-white/60 px-5 py-3 text-sm font-bold text-white">Review the enclosure</a></div></div>
      <p className="mt-8 max-w-2xl text-[11px] font-semibold uppercase text-white/55">Atmospheric visualization · Regional familiarity, not a {city} facility or SSI installation</p>
    </section>
    <section id="product" className={`grid items-center gap-10 bg-white px-5 py-14 sm:px-8 ${compact ? "lg:grid-cols-2" : "lg:grid-cols-[minmax(0,1.1fr)_minmax(0,.9fr)] lg:gap-0 lg:px-0 lg:py-0"}`} data-media-role="PRODUCT_AUTHORITY" data-product-authority-balance="PROMINENT_MEDIA">
      <figure className={`border border-[#d5d2ca] bg-[#eceeeb] ${compact ? "" : "lg:border-y-0 lg:border-l-0"}`} data-product-authority-figure><Image unoptimized src={product.url} alt={product.altText} width={2560} height={1152} className="aspect-[20/9] h-auto w-full object-contain" data-product-authority-image /><figcaption className="mt-3 flex flex-wrap justify-between gap-2 px-4 pb-4 text-[11px] font-bold uppercase text-[#687170] lg:px-5"><span>Approved product media</span><span>WordPress media 10757</span></figcaption></figure>
      <div className={compact ? "" : "lg:px-[5vw] lg:py-16"}><p className="text-xs font-black uppercase tracking-[0.18em] text-[#b3261e]">The Product</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">Fan-cooled protection for the projector at the center of the experience.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-[#4d5858]">The approved enclosure authority supports built-in fan cooling, durable metal construction, and removable or hinged service access. Final selection still depends on projector, lens, mounting, airflow, and site conditions.</p><a href={productLink.url} className="mt-7 inline-flex border-b-2 border-[#b3261e] pb-1 text-sm font-black text-[#7f1d18]">Review canonical product details</a></div>
    </section>
    <section className={`grid items-stretch bg-[#172022] text-white ${compact ? "lg:grid-cols-2" : "lg:grid-cols-2"}`} data-media-role="CONTEXTUAL_IN_USE">
      <Image unoptimized src={inUse.url} alt={inUse.altText} width={1536} height={1024} className="h-full min-h-[360px] w-full object-cover" />
      <div className={`flex flex-col justify-center px-5 py-14 sm:px-8 ${compact ? "" : "lg:px-[7vw] lg:py-24"}`}><p className="text-xs font-black uppercase tracking-[0.18em] text-[#f2b84b]">Product in Context</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">A credible covered commercial AV environment.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/72">This concept uses the approved product image as a form reference and shows a plausible mounted enclosure with service clearance. It does not represent a real {city} property, customer, or completed SSI installation.</p><div className="mt-7 border-l-2 border-[#f2b84b] pl-4 text-xs uppercase text-white/55"><p>{inUse.claimClass.replaceAll("_", " ")}</p><p className="mt-1">Owner review {inUse.ownerReviewState}</p></div></div>
    </section>
    <section id="applications" className="relative bg-[#0e1415] text-white" data-media-role="APPLICATION_EXPERIENCE"><Image unoptimized src={application.url} alt={application.altText} width={1536} height={1024} className={`${compact ? "min-h-[440px]" : "min-h-[680px]"} w-full object-cover opacity-70`} /><div className="absolute inset-0 flex items-end bg-gradient-to-t from-[#0e1415] via-[#0e1415]/30 to-transparent px-5 py-12 sm:px-8 lg:px-[8vw] lg:py-20"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#f2b84b]">What Protected Projection Can Enable</p><h2 className="mt-4 text-4xl font-black leading-tight sm:text-6xl">{primaryApplication.label} with the enclosure planned as part of the system.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-white/80">{primaryApplication.relationship} A successful system still requires project-specific review of the projector, environment, exposure, airflow, mounting, and service needs.</p><a href={applicationLink.url} className="mt-7 inline-flex bg-white px-5 py-3 text-sm font-black text-[#172022]">Explore {primaryApplication.label.toLowerCase()} fit</a><p className="mt-5 text-[11px] font-semibold uppercase text-white/50">Application visualization · Not a real {city} venue or SSI project</p></div></div></section>
    <section id="planning" className={`bg-[#f3f1eb] px-5 py-14 sm:px-8 ${compact ? "" : "lg:px-[8vw] lg:py-24"}`}><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#b3261e]">{region} Planning Context</p><div className="mt-5 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><h2 className="text-3xl font-black leading-tight sm:text-5xl">Regional conditions belong in the project conversation.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-[#4d5858]">{contextSummary} These facts shape questions for planning; they do not establish product fit by themselves.</p></div><div className="grid gap-3 sm:grid-cols-2">{bundle.context.facts.slice(0, 4).map((fact) => <article key={fact.factId} className="border-t-2 border-[#b3261e] bg-white p-4"><p className="text-[11px] font-black uppercase text-[#697271]">{fact.kind.replaceAll("_", " ")}</p><p className="mt-3 text-sm leading-6 text-[#313b3b]">{fact.statement}</p></article>)}</div></div></div></section>
    {sourceHtml ? <section id="detailed-guide" className={`bg-white px-5 py-14 sm:px-8 ${compact ? "" : "lg:px-[8vw] lg:py-24"}`} data-source-artifact="CONTENT_READY"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#b3261e]">Detailed Planning Guide</p><div data-prose-content style={{ maxWidth: "76ch" }} className="mt-7 [&_a]:font-bold [&_a]:text-[#8d211b] [&_dd]:mb-4 [&_dt]:font-black [&_h2]:mb-4 [&_h2]:mt-12 [&_h2]:text-3xl [&_h2]:font-black [&_h2]:leading-tight [&_h3]:mb-3 [&_h3]:mt-8 [&_h3]:text-xl [&_h3]:font-black [&_li]:mb-2 [&_p]:mb-5 [&_p]:text-base [&_p]:leading-7 [&_table]:my-8 [&_table]:w-full [&_table]:table-fixed [&_td]:break-words [&_td]:border [&_td]:border-[#d5d2ca] [&_td]:p-3 [&_th]:break-words [&_th]:border [&_th]:border-[#d5d2ca] [&_th]:bg-[#f3f1eb] [&_th]:p-3 max-md:[&_table]:text-xs" dangerouslySetInnerHTML={{ __html: sourceHtml }} /></div></section> : null}
    {market ? <section className={`bg-[#172022] px-5 py-14 text-white sm:px-8 ${compact ? "" : "lg:px-[8vw] lg:py-20"}`} data-market-informed="true"><div className="mx-auto max-w-[1180px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#f2b84b]">V3 Market-Informed Additions</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">Lead with the applications the evidence can actually support.</h2><p className="mt-5 text-sm leading-6 text-white/65">Market evidence informs emphasis. It does not become a customer, demand-volume, or market-leadership claim.</p></div><div className="grid gap-3 sm:grid-cols-3">{market.opportunities.filter((item) => item.confidence === "HIGH" || item.confidence === "MEDIUM").map((item) => <article key={item.opportunityId} className="border border-white/15 bg-white/5 p-4"><p className="text-[11px] font-black uppercase text-[#f2b84b]">{item.confidence}</p><h3 className="mt-3 text-lg font-black">{item.applicationId.replaceAll("_", " ")}</h3><p className="mt-2 text-sm leading-6 text-white/65">{item.whyProduct}</p></article>)}</div></div><div className="mt-8 border-t border-white/15 pt-5 text-xs text-white/55"><span className="font-bold text-white">Not selected for this page:</span> {market.pageStrategy.rejectedAdjacencies.map((item) => item.applicationId.replaceAll("_", " ")).join(" · ")}</div></div></section> : null}
    <section className={`bg-white px-5 py-14 sm:px-8 ${compact ? "" : "lg:px-[8vw] lg:py-24"}`}><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#b3261e]">Useful Pathways</p><h2 className="mt-4 max-w-3xl text-3xl font-black leading-tight sm:text-5xl">Move from regional context to a reviewed system.</h2><div className="mt-8 grid gap-px bg-[#d5d2ca] md:grid-cols-2 xl:grid-cols-3">{linksByRole(bundle, ["INTERNAL_CAPABILITY", "INTERNAL_SUPPORT", "INTERNAL_CONVERSION"]).map((link) => <a key={link.linkId} href={link.url} className="bg-[#f8f7f3] p-5 hover:bg-white"><p className="text-[11px] font-black uppercase text-[#b3261e]">{link.role.replaceAll("_", " ")}</p><h3 className="mt-3 text-lg font-black">{link.anchorIntent}</h3><p className="mt-2 text-sm leading-6 text-[#596262]">{link.reason}</p></a>)}</div></div></section>
    <section className={`bg-[#e4e0d6] px-5 py-14 sm:px-8 ${compact ? "" : "lg:px-[8vw] lg:py-20"}`}><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#7f1d18]">{city} / {region} Project Planning Resources</p><div className="mt-6 grid gap-4 lg:grid-cols-3">{linksByRole(bundle, ["LOCAL_AUTHORITY", "LOCAL_INSTITUTION", "REGIONAL_REFERENCE"]).map((link) => <a key={link.linkId} href={link.url} target="_blank" rel="noreferrer" className="border border-[#c7c2b7] bg-[#f3f1eb] p-5 hover:border-[#7f1d18]"><p className="text-[11px] font-black uppercase text-[#697271]">{link.role.replaceAll("_", " ")}</p><h3 className="mt-3 text-lg font-black">{link.anchorIntent}</h3><p className="mt-2 text-sm leading-6 text-[#596262]">{link.reason}</p></a>)}</div></div></section>
    <section className={`bg-[#b3261e] px-5 py-14 text-white sm:px-8 ${compact ? "" : "lg:px-[8vw] lg:py-20"}`}><div className="mx-auto flex max-w-[1180px] flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-white/65">Project-specific review</p><h2 className="mt-4 max-w-3xl text-3xl font-black leading-tight sm:text-5xl">Bring the projector, lens, environment, and mounting plan.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-white/75">SSI can help review the appropriate enclosure category and available documentation for the exact project requirements.</p></div><a href={primary.url} className="inline-flex min-h-12 items-center justify-center bg-white px-6 py-3 text-sm font-black text-[#7f1d18]">Request project review</a></div></section>
    <footer className="bg-[#111718] px-5 py-8 text-xs text-white/60 sm:px-8 lg:px-[6vw]"><div className="flex flex-col justify-between gap-3 sm:flex-row"><p>ProjectorEnclosure / Screen Solutions International</p><p>Preview only · No WordPress update, publication, campaign transition, or dispatch</p></div></footer>
  </article>;
}