import Image from "next/image";

import type { LocalPageThemingBundle } from "@/modules/foundation/local-context-page-theming-repository";
import type { MarketProductMatchBundle } from "@/modules/foundation/local-market-product-match-repository";
import type { HoustonPreviewNarrative } from "./houston-reference-preview";

const mediaByRole = (bundle: LocalPageThemingBundle, role: LocalPageThemingBundle["media"][number]["role"]) => bundle.media.find((item) => item.role === role)!;
const linksByRole = (bundle: LocalPageThemingBundle, roles: readonly string[]) => bundle.links.links.filter((link) => roles.includes(link.role));

export function GlwMarketInformedReferencePreview({ bundle, market, narrative }: { bundle: LocalPageThemingBundle; market: MarketProductMatchBundle; narrative: HoustonPreviewNarrative }) {
  const product = mediaByRole(bundle, "PRODUCT_AUTHORITY");
  const inUse = mediaByRole(bundle, "CONTEXTUAL_IN_USE");
  const application = mediaByRole(bundle, "APPLICATION_EXPERIENCE");
  const atmosphere = mediaByRole(bundle, "LOCAL_CONTEXTUAL_ATMOSPHERE");
  const conversion = bundle.links.links.find((link) => link.role === "INTERNAL_CONVERSION")!;
  const productLink = bundle.links.links.find((link) => link.role === "INTERNAL_PRODUCT")!;
  const capability = bundle.links.links.find((link) => link.linkId === "climate-controlled")!;
  const selected = market.opportunities.filter((item) => item.confidence === "HIGH" || item.confidence === "MEDIUM");
  return <article className="overflow-hidden bg-[#eef1ee] text-[#14201f]" data-genesis-primary-content data-preview-authority="PREVIEW_ONLY" data-composition-profile="LOCATION_SERVICE" data-localization-level={bundle.theme.localizationLevel}>
    <div className="flex min-h-12 items-center justify-between gap-4 bg-[#b4251d] px-5 py-3 text-[11px] font-black uppercase text-white sm:px-8"><span>Houston Proposed Localized Market-Informed Composition</span><span>Preview - Not Applied to WordPress</span></div>
    <header className="flex min-h-16 items-center justify-between border-b border-black/10 bg-white px-5 sm:px-8 lg:px-[6vw]"><a href="#top" className="text-sm font-black uppercase tracking-[0.16em]">ProjectorEnclosure <span className="text-[#b4251d]">/ SSI</span></a><nav className="hidden items-center gap-6 text-xs font-bold text-[#465453] md:flex"><a href="#product">Enclosure</a><a href="#application">Commercial AV</a><a href="#planning">Houston planning</a><a href={conversion.url}>Project review</a></nav></header>
    <section id="top" className="relative flex min-h-[680px] items-end overflow-hidden bg-[#152321] px-5 py-16 text-white sm:px-8 lg:px-[8vw]" data-genesis-hero data-media-role="LOCAL_CONTEXTUAL_ATMOSPHERE">
      <Image unoptimized priority src={atmosphere.url} alt={atmosphere.altText} fill sizes="100vw" className="object-cover" />
      <div className="absolute inset-0 bg-[#10211dcc]" />
      <div className="relative max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#7dc7ad]">{narrative.eyebrow}</p><h1 className="mt-5 text-4xl font-black leading-[1.04] sm:text-6xl lg:text-7xl">{narrative.heroHeading}</h1><p className="mt-6 max-w-3xl text-base leading-7 text-white/85 sm:text-lg">{narrative.heroBody}</p><div className="mt-8 flex flex-wrap gap-3"><a href={conversion.url} className="bg-[#f1b84b] px-5 py-3 text-sm font-black text-[#14201f]">Discuss your project</a><a href={productLink.url} className="border border-white/65 px-5 py-3 text-sm font-bold text-white">Review the enclosure</a></div><p className="mt-8 text-[11px] font-semibold uppercase text-white/60">Atmospheric visualization · Houston familiarity without local-presence claims</p></div>
    </section>
    <section id="product" className="grid items-center gap-10 bg-white px-5 py-16 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:px-[8vw] lg:py-24" data-media-role="PRODUCT_AUTHORITY"><figure className="border border-[#ccd3cf] bg-[#edf0ed] p-4"><Image unoptimized loading="eager" src={product.url} alt={product.altText} width={2560} height={1152} className="aspect-[20/9] h-auto w-full object-contain" /><figcaption className="mt-3 flex justify-between gap-2 text-[11px] font-bold uppercase text-[#66716f]"><span>Approved product authority</span><span>WordPress media 10757</span></figcaption></figure><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#b4251d]">The product</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">{narrative.productHeading}</h2><p className="mt-5 text-base leading-7 text-[#4b5856]">{narrative.productBody}</p><a href={productLink.url} className="mt-7 inline-flex border-b-2 border-[#b4251d] pb-1 text-sm font-black text-[#861c16]">Review canonical product details</a></div></section>
    <section className="grid bg-[#152321] text-white lg:grid-cols-2" data-media-role="CONTEXTUAL_IN_USE"><Image unoptimized loading="eager" src={inUse.url} alt={inUse.altText} width={1536} height={1024} className="h-full min-h-[420px] w-full object-cover" /><div className="flex flex-col justify-center px-5 py-16 sm:px-8 lg:px-[7vw] lg:py-24"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#7dc7ad]">Product in context</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">{narrative.inUseHeading}</h2><p className="mt-5 text-base leading-7 text-white/75">{narrative.inUseBody}</p><p className="mt-7 border-l-2 border-[#7dc7ad] pl-4 text-xs uppercase text-white/55">{inUse.claimClass.replaceAll("_", " ")} · Product grounded · Owner review pending</p></div></section>
    <section id="application" className="relative min-h-[680px] overflow-hidden bg-[#0d1716] text-white" data-media-role="APPLICATION_EXPERIENCE"><Image unoptimized loading="eager" src={application.url} alt={application.altText} fill sizes="100vw" className="object-cover opacity-65" /><div className="absolute inset-0 bg-[#0d171699]" /><div className="relative flex min-h-[680px] items-end px-5 py-16 sm:px-8 lg:px-[8vw] lg:py-24"><div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#f1b84b]">Evidence-selected application</p><h2 className="mt-4 text-4xl font-black leading-tight sm:text-6xl">{narrative.applicationHeading}</h2><p className="mt-5 max-w-3xl text-base leading-7 text-white/82">{narrative.applicationBody}</p><p className="mt-6 text-[11px] font-semibold uppercase text-white/55">Application visualization · Not a Houston venue, customer, or installation</p></div></div></section>
    <section id="planning" className="bg-[#dfe9e3] px-5 py-16 sm:px-8 lg:px-[8vw] lg:py-24"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#17614c]">Houston environmental context</p><div className="mt-5 grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><h2 className="text-3xl font-black leading-tight sm:text-5xl">{narrative.planningHeading}</h2><p className="mt-5 text-base leading-7 text-[#465451]">{narrative.planningBody}</p></div><div className="grid gap-3 sm:grid-cols-2">{bundle.context.facts.slice(0, 4).map((fact) => <article key={fact.factId} className="border-t-2 border-[#17614c] bg-white p-4"><p className="text-[11px] font-black uppercase text-[#62706d]">{fact.kind.replaceAll("_", " ")}</p><p className="mt-3 text-sm leading-6">{fact.statement}</p></article>)}</div></div></div></section>
    <section className="bg-[#f1b84b] px-5 py-12 sm:px-8 lg:px-[8vw]"><div className="mx-auto flex max-w-[1180px] flex-col justify-between gap-6 lg:flex-row lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#6d4b08]">Product suitability boundary</p><h2 className="mt-3 text-3xl font-black">{narrative.suitabilityHeading}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#463608]">{narrative.suitabilityBody}</p></div><a href={capability.url} className="shrink-0 bg-[#14201f] px-5 py-3 text-sm font-black text-white">Compare climate-controlled protection</a></div></section>
    <section className="bg-[#152321] px-5 py-16 text-white sm:px-8 lg:px-[8vw] lg:py-20" data-market-informed="true"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#7dc7ad]">Houston market-product match</p><div className="mt-6 grid gap-4 md:grid-cols-3">{selected.map((item) => <article key={item.opportunityId} className="border border-white/15 p-5"><p className="text-[11px] font-black text-[#f1b84b]">{item.confidence}</p><h3 className="mt-3 text-xl font-black">{item.applicationId.replaceAll("_", " ")}</h3><p className="mt-3 text-sm leading-6 text-white/65">{item.whyProduct}</p></article>)}</div><p className="mt-6 text-xs text-white/55">Primary: {market.pageStrategy.primaryApplication?.replaceAll("_", " ")} · Supporting: {market.pageStrategy.supportingApplications.join(" · ").replaceAll("_", " ")} · No market signal is treated as customer proof.</p></div></section>
    <section className="bg-white px-5 py-16 sm:px-8 lg:px-[8vw] lg:py-24"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#b4251d]">Useful pathways</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">Move from Houston context to the right enclosure review.</h2><div className="mt-8 grid gap-px bg-[#ccd3cf] md:grid-cols-2 xl:grid-cols-3">{linksByRole(bundle, ["INTERNAL_CAPABILITY", "INTERNAL_SUPPORT", "INTERNAL_CONVERSION"]).map((link) => <a key={link.linkId} href={link.url} className="bg-[#f5f6f3] p-5"><p className="text-[11px] font-black uppercase text-[#b4251d]">{link.role.replaceAll("_", " ")}</p><h3 className="mt-3 text-lg font-black">{link.anchorIntent}</h3><p className="mt-2 text-sm leading-6 text-[#596562]">{link.reason}</p></a>)}</div></div></section>
    <section className="bg-[#d8ded9] px-5 py-16 sm:px-8 lg:px-[8vw] lg:py-20"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#17614c]">{narrative.resourceHeading}</p><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{linksByRole(bundle, ["LOCAL_AUTHORITY", "LOCAL_INSTITUTION", "REGIONAL_REFERENCE"]).map((link) => <a key={link.linkId} href={link.url} target="_blank" rel="noreferrer" className="border border-[#b8c2bc] bg-[#eef1ee] p-5"><p className="text-[11px] font-black uppercase text-[#62706d]">{link.role.replaceAll("_", " ")}</p><h3 className="mt-3 text-lg font-black">{link.anchorIntent}</h3><p className="mt-2 text-sm leading-6 text-[#596562]">{link.reason}</p></a>)}</div></div></section>
    <section className="bg-[#b4251d] px-5 py-16 text-white sm:px-8 lg:px-[8vw] lg:py-20"><div className="mx-auto flex max-w-[1180px] flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-white/65">Project-specific review</p><h2 className="mt-4 max-w-3xl text-3xl font-black sm:text-5xl">Bring the projector, lens, environment, duty cycle, and exposure plan.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-white/78">SSI can help determine whether fan-cooled, climate-controlled, IP-rated, or another enclosure direction fits the actual Houston-area project.</p></div><a href={conversion.url} className="inline-flex min-h-12 items-center justify-center bg-white px-6 py-3 text-sm font-black text-[#861c16]">Request project review</a></div></section>
    <footer className="bg-[#101817] px-5 py-8 text-xs text-white/60 sm:px-8 lg:px-[6vw]"><div className="flex flex-col justify-between gap-3 sm:flex-row"><p>ProjectorEnclosure / Screen Solutions International</p><p>Preview only · No WordPress content, campaign transition, dispatch, or publication</p></div></footer>
  </article>;
}
