import "server-only";

import { createHash, randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { captureGovernedRenderedPage } from "@/modules/foundation/governed-render-capture-browser";
import { resolvePersistenceRoot } from "@/modules/foundation/foundation-persistence";
import { publishGenesisWordPressDraft } from "@/modules/foundation/wordpress-publish-writer";
import { getLocalPageThemingBundle } from "@/modules/foundation/local-context-page-theming-repository";
import { reconcileGlwCampaignTargetPublishedWithoutDispatch, reconcileGlwCampaignTargetQueuedAfterDirectPublicationFailure, listGlwCampaignTargets } from "./campaign-target-repository";
import { getDallasPublicationState } from "./dallas-reference-page-publication-repository";
import { getHoustonDraftState } from "./houston-approved-preview-draft-repository";
import { inspectHoustonWordPressAuthority, listHoustonWordPressObjects } from "./houston-approved-preview-draft-service";
import { HOUSTON_H1 } from "./houston-approved-preview-draft";
import { HOUSTON_BUNDLE_ID, HOUSTON_PRODUCT_MEDIA_HASH, HOUSTON_PRODUCT_MEDIA_ID, HOUSTON_PRODUCT_MEDIA_URL, HOUSTON_TARGET_ID } from "./houston-reference-preview";
import { consumeHoustonPublicationIntent, getHoustonPublicationState, persistHoustonPublicationApprovalAndIntent, saveHoustonPublicationRecord } from "./houston-reference-page-publication-repository";
import { evaluateHoustonDraftPublicDrift, evaluateHoustonPublicationReadiness, evaluateHoustonPublicEvidence, freezeHoustonPublicationIdentity, normalizeHoustonSemanticText, resolveHoustonPublicSeoContract, HOUSTON_APPROVED_BODY_HASH, HOUSTON_APPROVED_SEO_HASH, HOUSTON_CAMPAIGN_ID, HOUSTON_MEDIA_ROLES, HOUSTON_PUBLICATION_COMMIT, HOUSTON_PUBLIC_URL, HOUSTON_PUBLIC_VERIFIER_VERSION, HOUSTON_WORDPRESS_OBJECT_ID, type HoustonFirstPublicProbe, type HoustonProbeHttpClassification, type HoustonPublicationFailure, type HoustonPublicationTiming, type HoustonPublicCapture, type HoustonPublicLinkResult, type HoustonPublicVerification, type HoustonPublicVisualCertification, type HoustonWordPressPublicationReceipt } from "./houston-reference-page-publication";

const VIEWPORTS = [{ viewport: "DESKTOP_1440" as const, width: 1440, height: 1024, viewportClass: "DESKTOP" as const }, { viewport: "DESKTOP_1024" as const, width: 1024, height: 900, viewportClass: "DESKTOP" as const }, { viewport: "TABLET_768" as const, width: 768, height: 1024, viewportClass: "DESKTOP" as const }, { viewport: "MOBILE_375" as const, width: 375, height: 812, viewportClass: "MOBILE" as const }];
const digest = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex");
const text = (html: string, pattern: RegExp) => pattern.exec(html)?.[1]?.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim() ?? "";
const normalize = (value: string) => { const url = new URL(value); url.hash = ""; return url.toString(); };
const safeUrl = (value: string) => { const url = new URL(value); url.username = ""; url.password = ""; url.search = ""; url.hash = ""; return url.toString(); };
const allowedPublicHost = (value: string) => { try { return /^(?:www\.)?projectorenclosure\.com$/i.test(new URL(value).hostname); } catch { return false; } };
const timing = (intentId: string, phase: HoustonPublicationTiming["phase"], at: string) => saveHoustonPublicationRecord("publicationTimings", { timingId: `${intentId}-${phase.toLowerCase()}-${at}`, publicationIntentId: intentId, phase, at }, `TIMING_${phase}`, at);
const responseHeaders = (headers?: Headers) => ({ contentType: headers?.get("content-type") ?? null, cacheControl: headers?.get("cache-control") ?? null, server: headers?.get("server") ?? null, age: headers?.get("age") ?? null, via: headers?.get("via") ?? null, xCache: headers?.get("x-cache") ?? null });

function classifyNetworkError(error: unknown): HoustonFirstPublicProbe["networkErrorClass"] { const message = error instanceof Error ? `${error.name}:${error.message}` : String(error); if (/timeout|abort/i.test(message)) return "TIMEOUT"; if (/ENOTFOUND|EAI_AGAIN|dns/i.test(message)) return "DNS"; if (/certificate|TLS|SSL/i.test(message)) return "TLS"; return "OTHER"; }
function classifyHttp(status: number | null, redirectEscape: boolean, network: HoustonFirstPublicProbe["networkErrorClass"]): HoustonProbeHttpClassification { if (redirectEscape) return "REDIRECT_ESCAPE"; if (network) return network; if (status === 200) return "HTTP_200"; if (status === 403) return "HTTP_403"; if (status === 404) return "HTTP_404"; if (status !== null && status >= 300 && status < 400) return "HTTP_3XX"; if (status !== null && status >= 500) return "HTTP_5XX"; return "OTHER"; }

export async function collectHoustonFirstPublicProbe(input: { publicationIntentId: string; publicationReceiptId: string; fetcher?: typeof fetch }): Promise<{ probe: HoustonFirstPublicProbe; html: string }> {
  const fetcher = input.fetcher ?? fetch; const startedAt = new Date().toISOString(); let current: string = HOUSTON_PUBLIC_URL; const redirects: { status: number; location: string; resolvedDestination: string }[] = []; let response: Response | null = null; let html = ""; let networkErrorClass: HoustonFirstPublicProbe["networkErrorClass"] = null; let redirectEscape = false;
  try { for (let count = 0; count <= 3; count += 1) { response = null; response = await fetcher(current, { method: "GET", redirect: "manual", cache: "no-store", signal: AbortSignal.timeout(30_000), headers: { "Cache-Control": "no-cache, no-store", Pragma: "no-cache" } }); if (![301, 302, 303, 307, 308].includes(response.status)) break; const location = response.headers.get("location"); if (!location) break; const resolved = new URL(location, current).toString(); redirects.push({ status: response.status, location: safeUrl(resolved), resolvedDestination: safeUrl(resolved) }); if (!allowedPublicHost(resolved)) { redirectEscape = true; current = resolved; break; } current = resolved; } if (response && !redirectEscape) html = await response.text(); } catch (error) { networkErrorClass = classifyNetworkError(error); }
  const contentType = response?.headers.get("content-type") ?? null; const isHtml = Boolean(contentType?.toLowerCase().includes("text/html") || /^\s*</.test(html)); const titleMatch = /<title[^>]*>([\s\S]*?)<\/title>/i.exec(html); const metaMatch = /<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i.exec(html); const openGraphMatch = /<meta[^>]+property=["']og:description["'][^>]+content=["']([^"']*)/i.exec(html); const canonicalMatch = /<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)/i.exec(html) ?? /<link[^>]+href=["']([^"']+)["'][^>]+rel=["']canonical["']/i.exec(html); const robotsMatch = /<meta[^>]+name=["']robots["'][^>]+content=["']([^"']*)/i.exec(html); const h1Texts = [...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map((match) => match[1].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim()); const roles = [...html.matchAll(/data-media-role=["']([^"']+)/gi)].map((match) => match[1]); const approvedMarker = html.includes('data-market-primary="COMMERCIAL_AV"'); const devLeak = html ? /(?:localhost|127\.0\.0\.1|:(?:3001|3002|3003)\b|\/glw\/)/i.test(html) : null; const previewLeak = html ? /houston-reference-preview|theme-integrated-snapshot|composition-preview/i.test(html) : null; const robots = robotsMatch?.[1]?.trim() ?? null; const completedAt = new Date().toISOString();
  const probe: HoustonFirstPublicProbe = { probeId: `houston-first-probe-${input.publicationReceiptId}`, publicationIntentId: input.publicationIntentId, publicationReceiptId: input.publicationReceiptId, wordpressObjectId: HOUSTON_WORDPRESS_OBJECT_ID, requestedUrl: HOUSTON_PUBLIC_URL, startedAt, completedAt, httpStatus: response?.status ?? null, httpClassification: classifyHttp(response?.status ?? null, redirectEscape, networkErrorClass), finalUrl: response ? safeUrl(current) : null, redirectChain: redirects, responseHeaders: responseHeaders(response?.headers), contentType, contentHash: html ? digest(html) : null, title: titleMatch ? text(html, /<title[^>]*>([\s\S]*?)<\/title>/i) : null, metaDescription: metaMatch ? metaMatch[1].replace(/\s+/g, " ").trim() : null, metaDescriptionPresent: isHtml ? Boolean(metaMatch) : null, openGraphDescription: openGraphMatch?.[1]?.replace(/\s+/g, " ").trim() ?? null, canonical: canonicalMatch?.[1] ? safeUrl(canonicalMatch[1]) : null, robots, indexability: !isHtml ? "NOT_EVALUATED" : /noindex/i.test(robots ?? "") ? "NOINDEX" : "INDEXABLE", visibleH1Count: isHtml ? h1Texts.length : null, visibleH1Texts: h1Texts, normalizedH1Texts: h1Texts.map(normalizeHoustonSemanticText), expectedH1Raw: HOUSTON_H1, expectedH1Normalized: normalizeHoustonSemanticText(HOUSTON_H1), bodyMarkerClassification: !response || !html ? "UNAVAILABLE" : !isHtml ? "NOT_HTML" : approvedMarker ? "APPROVED_CONTENT" : "CONTENT_MISMATCH", approvedContentMarkerPresent: isHtml ? approvedMarker : null, semanticMediaRoles: [...new Set(roles)], devLeak, previewLeak, networkErrorClass, verifierVersion: HOUSTON_PUBLIC_VERIFIER_VERSION };
  return { probe, html };
}

async function verifyLinks(urls: readonly string[]) { const results: HoustonPublicLinkResult[] = []; for (const value of [...new Set(urls)]) { const source = new URL(value, HOUSTON_PUBLIC_URL); const internal = /^(?:www\.)?projectorenclosure\.com$/i.test(source.hostname); try { const response = await fetch(source, { redirect: "follow", cache: "no-store", signal: AbortSignal.timeout(30_000) }); results.push({ url: source.toString(), classification: internal ? response.ok ? normalize(response.url) === normalize(source.toString()) ? "INTERNAL_DIRECT" : "INTERNAL_REDIRECT" : "INTERNAL_BROKEN" : response.ok ? "EXTERNAL_VERIFIED" : "EXTERNAL_ACCEPTABLE", status: response.status, finalUrl: response.url }); } catch { results.push({ url: source.toString(), classification: internal ? "INTERNAL_BROKEN" : "EXTERNAL_ACCEPTABLE", status: 0, finalUrl: null }); } } return results; }
async function verifyMedia(expected: readonly { role: string; url: string }[]) { const results = []; for (const item of expected) { const response = await fetch(item.url, { cache: "no-store", signal: AbortSignal.timeout(30_000) }); const bytes = new Uint8Array(await response.arrayBuffer()); if (!response.ok || !bytes.length) throw new Error(`HOUSTON_PUBLIC_MEDIA_UNAVAILABLE:${item.role}`); results.push({ role: item.role, url: item.url, status: response.status }); } return results; }
function storeCapture(receiptId: string, capture: HoustonPublicCapture["viewport"], bytes: Uint8Array, width: number, height: number) { const reference = `houston-reference-page-artifacts/${receiptId}/${capture.toLowerCase()}.png`; const path = join(resolvePersistenceRoot(), ...reference.split("/")); const sha256 = digest(bytes); mkdirSync(dirname(path), { recursive: true }); if (existsSync(path) && digest(readFileSync(path)) !== sha256) throw new Error("HOUSTON_PUBLIC_CAPTURE_COLLISION"); if (!existsSync(path)) writeFileSync(path, bytes); return { reference, sha256, bytes: bytes.length, width, height }; }
export function readHoustonPublicCapture(reference: string) { if (!reference.startsWith("houston-reference-page-artifacts/") || reference.includes("..")) throw new Error("HOUSTON_PUBLIC_CAPTURE_REFERENCE_INVALID"); return readFileSync(join(resolvePersistenceRoot(), ...reference.split("/"))); }

export async function buildHoustonPublicationPreflight() {
  const state = getHoustonDraftState(); const receipt = state.receipts.at(-1); const draftApproval = receipt ? state.approvals.find((item) => item.decisionId === receipt.decisionId) : null; const certification = receipt ? state.certifications.find((item) => item.receiptId === receipt.receiptId) : null; const comparison = receipt ? state.comparisons.find((item) => item.receiptId === receipt.receiptId) : null;
  if (!receipt || !draftApproval || !certification || !comparison) throw new Error("HOUSTON_PUBLICATION_SOURCE_AUTHORITY_MISSING");
  const current = await inspectHoustonWordPressAuthority(HOUSTON_WORDPRESS_OBJECT_ID, "draft"); const settings = current.meta._elementor_page_settings as { hide_title?: string } | undefined;
  const identity = freezeHoustonPublicationIdentity({ receipt, approvalIdentity: draftApproval.exactIdentity, certification, comparison, readback: { wordpressObjectId: current.identity.wordpressObjectId, status: current.identity.status, parent: current.identity.parent, title: current.identity.title, slug: current.identity.slug, bodyHash: current.body.hash, seoHash: current.seo.hash, featuredMediaId: current.featuredMediaId, template: current.identity.template, hideTitle: settings?.hide_title, roles: current.body.roles }, repositoryCommit: HOUSTON_PUBLICATION_COMMIT });
  const campaignTargets = listGlwCampaignTargets(HOUSTON_CAMPAIGN_ID);
  const target = campaignTargets.find((item) => item.targetId === HOUSTON_TARGET_ID);
  if (!target) throw new Error("HOUSTON_PUBLICATION_TARGET_MISSING");
  if (target.status !== "queued") throw new Error(`HOUSTON_PUBLICATION_TARGET_STATUS_STALE:${target.status}`);
  if (target.jobId) throw new Error("HOUSTON_PUBLICATION_TARGET_JOB_STALE");
  if (target.wordpressObjectId) throw new Error(`HOUSTON_PUBLICATION_TARGET_WORDPRESS_STALE:${target.wordpressObjectId}`);
  if (target.leaseId) throw new Error("HOUSTON_PUBLICATION_TARGET_LEASE_STALE");
  const local = getLocalPageThemingBundle({ organizationId: "ssi", siteId: "site-ssi-projectorenclosure", jobId: null, bundleId: HOUSTON_BUNDLE_ID }); if (!local) throw new Error("HOUSTON_LOCAL_AUTHORITY_MISSING");
  const objects = await listHoustonWordPressObjects(); if (objects.length !== 1 || String(objects[0].id) !== HOUSTON_WORDPRESS_OBJECT_ID || objects[0].status !== "draft") throw new Error("HOUSTON_WORDPRESS_OBJECT_COUNT_MISMATCH");
  const links = await verifyLinks(current.body.links); const expectedMedia = [{ role: "PRODUCT_AUTHORITY", url: HOUSTON_PRODUCT_MEDIA_URL }, ...receipt.uploadedMedia.map((item) => ({ role: item.role, url: item.url }))]; const media = await verifyMedia(expectedMedia);
  const readiness = evaluateHoustonPublicationReadiness({ html: current.body.raw, identity, linksValid: !links.some((item) => item.classification === "INTERNAL_BROKEN"), mediaValid: media.length === 4, themeReady: certification.themeIntegrationReady && certification.overallState === "PASS" && certification.captures.every((item) => item.horizontalOverflow === 0), ownerApproved: true }); if (readiness.failures.length) throw new Error(`HOUSTON_PUBLICATION_READINESS_FAILED:${readiness.failures.join(",")}`);
  const product = await fetch(HOUSTON_PRODUCT_MEDIA_URL, { cache: "no-store", signal: AbortSignal.timeout(30_000) }); if (!product.ok || digest(new Uint8Array(await product.arrayBuffer())) !== HOUSTON_PRODUCT_MEDIA_HASH) throw new Error("HOUSTON_PRODUCT_MEDIA_STALE");
  if (getDallasPublicationState().referenceCertifications.length < 1) throw new Error("DALLAS_REFERENCE_CERTIFICATION_MISSING");
  return { state, receipt, draftApproval, certification, comparison, current, identity, target, campaignSafety: { targets: campaignTargets.map((item) => ({ targetId: item.targetId, citySlug: item.citySlug, status: item.status, jobId: item.jobId, wordpressObjectId: item.wordpressObjectId, leaseId: item.leaseId ?? null, dispatchDate: item.dispatchDate ?? null })), dailyAllowanceConsumed: campaignTargets.filter((item) => item.dispatchDate === new Date().toISOString().slice(0, 10)).length }, local, links, expectedMedia, readiness };
}

async function verifyPublic(preflight: Awaited<ReturnType<typeof buildHoustonPublicationPreflight>>, publicationReceiptId: string) {
  const intentId = getHoustonPublicationState().intents.at(-1)?.intentId; if (!intentId) throw new Error("HOUSTON_PUBLICATION_INTENT_NOT_FOUND");
  const collected = await collectHoustonFirstPublicProbe({ publicationIntentId: intentId, publicationReceiptId }); timing(intentId, "FIRST_PROBE_STARTED", collected.probe.startedAt); timing(intentId, "FIRST_PROBE_COMPLETED", collected.probe.completedAt); saveHoustonPublicationRecord("firstProbes", collected.probe, "FIRST_PUBLIC_PROBE_PERSISTED", collected.probe.completedAt);
  const links = collected.probe.approvedContentMarkerPresent ? await verifyLinks(preflight.current.body.links) : []; let mediaLoaded: { role: string; url: string; status: number }[] = []; let mediaValid: boolean | undefined; try { mediaLoaded = collected.probe.approvedContentMarkerPresent ? await verifyMedia(preflight.expectedMedia) : []; mediaValid = collected.probe.approvedContentMarkerPresent ? mediaLoaded.length === 4 : undefined; } catch { mediaValid = false; }
  const claimSafe = collected.html ? !/(?:our|the) Houston (?:office|staff|team|customer|installation)|installed at|completed (?:in|at) Houston|minutes? from|nearby/i.test(collected.html) : undefined; const result = evaluateHoustonPublicEvidence({ probe: collected.probe, seoContract: resolveHoustonPublicSeoContract(), linksValid: collected.probe.approvedContentMarkerPresent ? !links.some((item) => item.classification === "INTERNAL_BROKEN") : undefined, mediaValid, claimSafe }); timing(intentId, "VERIFICATION_DECIDED", result.decisionAt); saveHoustonPublicationRecord("verifierResults", result, "PUBLIC_VERIFIER_RESULT_PERSISTED", result.decisionAt);
  if (result.overallState !== "PASS") { const failure: HoustonPublicationFailure = { failureId: `houston-publication-failure-${randomUUID()}`, reason: "HOUSTON_PUBLIC_VERIFICATION_FAILED", probeId: collected.probe.probeId, verifierResultId: result.verifierResultId, failedChecks: result.failedChecks, primaryFailureClassification: result.primaryFailureClassification ?? "VERIFICATION_BLOCKED", rollbackRequired: true, failedAt: result.decisionAt }; saveHoustonPublicationRecord("failures", failure, "PUBLIC_VERIFICATION_FAILED", failure.failedAt); throw new Error(`HOUSTON_PUBLIC_VERIFICATION_FAILED:${result.failedChecks.join(",") || "EVIDENCE_BLOCKED"}`); }
  const verification: HoustonPublicVerification = { verificationId: `houston-public-verification-${publicationReceiptId}`, publicationReceiptId, probeId: collected.probe.probeId, verifierResultId: result.verifierResultId, requestedUrl: collected.probe.requestedUrl, finalUrl: collected.probe.finalUrl!, httpStatus: collected.probe.httpStatus!, https: collected.probe.finalUrl!.startsWith("https://"), canonical: collected.probe.canonical!, title: collected.probe.title!, metaDescription: collected.probe.metaDescription ?? "", indexability: collected.probe.indexability as "INDEXABLE" | "NOINDEX", h1Count: collected.probe.visibleH1Count!, remainingH1: collected.probe.visibleH1Texts[0] ?? "", semanticMediaRoles: collected.probe.semanticMediaRoles, mediaLoaded, links, bodyHash: HOUSTON_APPROVED_BODY_HASH, seoHash: HOUSTON_APPROVED_SEO_HASH, featuredMediaId: HOUSTON_PRODUCT_MEDIA_ID, claimSafe: claimSafe!, devLeak: collected.probe.devLeak!, previewLeak: collected.probe.previewLeak!, verifiedAt: result.decisionAt };
  return { verification, html: collected.html };
}

async function capturePublic(preflight: Awaited<ReturnType<typeof buildHoustonPublicationPreflight>>, publicationReceiptId: string, html: string): Promise<HoustonPublicVisualCertification> { const assignments = preflight.expectedMedia.map((item, index) => ({ assignmentId: `wordpress-media:${index ? preflight.receipt.uploadedMedia[index - 1].mediaId : HOUSTON_PRODUCT_MEDIA_ID}`, semanticRole: item.role as typeof HOUSTON_MEDIA_ROLES[number], mediaId: String(index ? preflight.receipt.uploadedMedia[index - 1].mediaId : HOUSTON_PRODUCT_MEDIA_ID), sourceUrl: item.url, contextId: index ? preflight.receipt.uploadedMedia[index - 1].claimClass : "DOCUMENTARY" })); const captures: HoustonPublicCapture[] = []; for (const viewport of VIEWPORTS) { const result = await captureGovernedRenderedPage({ targetUrl: HOUSTON_PUBLIC_URL, allowedOrigins: ["https://projectorenclosure.com", "https://fonts.googleapis.com", "https://fonts.gstatic.com"], viewportClass: viewport.viewportClass, viewport: { width: viewport.width, height: viewport.height }, captureId: `houston-public-${publicationReceiptId}-${viewport.viewport.toLowerCase()}`, mediaAssignments: assignments }); captures.push({ captureId: result.evidence.captureId, viewport: viewport.viewport, width: viewport.width, height: viewport.height, documentWidth: result.evidence.documentWidth, documentHeight: result.evidence.documentHeight, horizontalOverflow: result.evidence.horizontalOverflow, mediaRolesRendered: result.evidence.media.filter((item) => item.rendered).map((item) => item.semanticRole), themeIntegration: result.themeIntegration, artifact: storeCapture(publicationReceiptId, viewport.viewport, result.bytes, result.imageWidth, result.imageHeight), capturedAt: result.evidence.capturedAt }); }
  const all = (predicate: (capture: HoustonPublicCapture) => boolean) => captures.every(predicate); const normalizedH1 = (value: string | undefined) => value?.replace(/[’‘]/g, "'").replace(/\s+/g, " ").trim(); const findings: HoustonPublicVisualCertification["findings"] = [{ code: "HEADER_FONT", state: all((item) => item.themeIntegration.globalHeaderPresent && item.themeIntegration.fontAuthorityExpected && item.themeIntegration.headerActionsContained && item.themeIntegration.quoteCtaContained) ? "PASS" : "FAIL", summary: "Authoritative header, font, actions, and quote CTA are contained." }, { code: "THEME_INTEGRATION", state: all((item) => item.themeIntegration.visibleH1Count === 1 && normalizedH1(item.themeIntegration.visibleH1Texts[0]) === HOUSTON_H1 && !item.themeIntegration.duplicateThemeTitleVisible && !item.themeIntegration.duplicateThemeFeaturedMediaVisible) ? "PASS" : "FAIL", summary: "One approved Houston H1 renders without duplicate title or featured media." }, { code: "SEMANTIC_MEDIA", state: all((item) => HOUSTON_MEDIA_ROLES.every((role) => item.mediaRolesRendered.includes(role))) ? "PASS" : "FAIL", summary: "All four semantic media roles render publicly." }, { code: "RESPONSIVE", state: all((item) => item.horizontalOverflow === 0) ? "PASS" : "FAIL", summary: "All public viewports have zero horizontal overflow." }, { code: "CONTENT_STRATEGY", state: /COMMERCIAL_AV|Commercial AV/i.test(html) && /EVENT VENUE/i.test(html) && /PROJECTION MAPPING/i.test(html) && /climate-controlled/i.test(html) && /humidity/i.test(html) ? "PASS" : "FAIL", summary: "Houston strategy and climate suitability remain visible." }, { code: "FOOTER", state: all((item) => item.themeIntegration.globalFooterPresent) ? "PASS" : "FAIL", summary: "Public footer renders at every viewport." }]; const overallState = findings.some((item) => item.state === "FAIL") ? "FAIL" : "PASS"; if (overallState === "FAIL") throw new Error(`HOUSTON_PUBLIC_VISUAL_CERTIFICATION_FAILED:${findings.filter((item) => item.state === "FAIL").map((item) => item.code).join(",")}`); return { certificationId: `houston-public-visual-${publicationReceiptId}`, publicationReceiptId, publicUrl: HOUSTON_PUBLIC_URL, renderAuthority: "PUBLIC_RENDER", captures, findings, overallState, createdAt: new Date().toISOString() }; }

async function restoreDraft(preflight: Awaited<ReturnType<typeof buildHoustonPublicationPreflight>>, failureId: string) { const intentId = getHoustonPublicationState().intents.at(-1)?.intentId; if (!intentId) throw new Error("HOUSTON_ROLLBACK_INTENT_REQUIRED"); const startedAt = new Date().toISOString(); timing(intentId, "ROLLBACK_STARTED", startedAt); const siteModule = await import("@/modules/foundation/site-repository"); const credentialModule = await import("@/modules/foundation/wordpress-credential-resolver"); const site = siteModule.getSiteById("site-ssi-projectorenclosure"); const credential = site ? credentialModule.resolveWordPressCredentialReference(site.integrations.wordpressCredentialReference) : null; if (!site?.integrations.wordpressApiBaseUrl || !credential) throw new Error("HOUSTON_ROLLBACK_AUTHORITY_MISSING"); const base = site.integrations.wordpressApiBaseUrl.replace(/\/$/, ""); const response = await fetch(`${base}/pages/${HOUSTON_WORDPRESS_OBJECT_ID}`, { method: "POST", headers: { Authorization: `Basic ${Buffer.from(`${credential.username}:${credential.applicationPassword}`).toString("base64")}`, "Content-Type": "application/json" }, body: JSON.stringify({ status: "draft" }), cache: "no-store", signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error("HOUSTON_ROLLBACK_FAILED"); const restored = await inspectHoustonWordPressAuthority(HOUSTON_WORDPRESS_OBJECT_ID, "draft"); if (restored.body.hash !== HOUSTON_APPROVED_BODY_HASH || restored.seo.hash !== HOUSTON_APPROVED_SEO_HASH) throw new Error("HOUSTON_ROLLBACK_READBACK_FAILED"); const completedAt = new Date().toISOString(); timing(intentId, "ROLLBACK_COMPLETED", completedAt); saveHoustonPublicationRecord("rollbacks", { rollbackId: `houston-rollback-${failureId}`, publicationIntentId: intentId, failureId, startedAt, completedAt, wordpressRestoredToDraft: true, bodyHash: HOUSTON_APPROVED_BODY_HASH, seoHash: HOUSTON_APPROVED_SEO_HASH }, "PUBLICATION_ROLLED_BACK", completedAt); void preflight; }

export async function publishHoustonReferencePage() { const persisted = getHoustonPublicationState(); const existing = persisted.referenceCertifications.at(-1); if (existing) return { state: persisted, reference: existing, reused: true }; const preflight = await buildHoustonPublicationPreflight(); const records = persistHoustonPublicationApprovalAndIntent(preflight.identity, new Date().toISOString()); let published = false; let reconciled = false; let attemptStartedAt: string | null = null; try { const site = (await import("@/modules/foundation/site-repository")).getSiteById("site-ssi-projectorenclosure"); if (!site) throw new Error("HOUSTON_SITE_AUTHORITY_MISSING"); const publishStartedAt = new Date().toISOString(); attemptStartedAt = publishStartedAt; timing(records.intent.intentId, "PUBLISH_STARTED", publishStartedAt); const result = await publishGenesisWordPressDraft({ site, wordpressObjectId: HOUSTON_WORDPRESS_OBJECT_ID }); if (!result.ok) throw new Error(`HOUSTON_WORDPRESS_PUBLICATION_FAILED:${result.state}`); const publishConfirmedAt = new Date().toISOString(); timing(records.intent.intentId, "PUBLISH_CONFIRMED", publishConfirmedAt); published = true; const after = await inspectHoustonWordPressAuthority(HOUSTON_WORDPRESS_OBJECT_ID, "publish"); const settings = after.meta._elementor_page_settings as { hide_title?: string } | undefined; if (after.body.hash !== HOUSTON_APPROVED_BODY_HASH || after.seo.hash !== HOUSTON_APPROVED_SEO_HASH || after.identity.parent !== 13083 || after.identity.template !== "elementor_header_footer" || settings?.hide_title !== "yes" || after.featuredMediaId !== HOUSTON_PRODUCT_MEDIA_ID || after.body.h1Count !== 1 || !HOUSTON_MEDIA_ROLES.every((role) => after.body.roles.includes(role))) throw new Error("HOUSTON_POST_PUBLISH_READBACK_MISMATCH");
  const publicationReceipt: HoustonWordPressPublicationReceipt = { publicationReceiptId: `houston-publication-${records.intent.intentId}`, intentId: records.intent.intentId, approvalId: records.approval.approvalId, wordpressObjectId: HOUSTON_WORDPRESS_OBJECT_ID, beforeStatus: "draft", afterStatus: "publish", bodyHash: HOUSTON_APPROVED_BODY_HASH, seoHash: HOUSTON_APPROVED_SEO_HASH, publicUrl: HOUSTON_PUBLIC_URL, wordpressPermalink: result.wordpressUrl, mutationPerformed: result.publicationPerformed, publishStartedAt, publishConfirmedAt }; saveHoustonPublicationRecord("publicationReceipts", publicationReceipt, "WORDPRESS_PUBLISHED", publicationReceipt.publishConfirmedAt);
    const { verification, html } = await verifyPublic(preflight, publicationReceipt.publicationReceiptId); saveHoustonPublicationRecord("publicVerifications", verification, "PUBLIC_VERIFIED", verification.verifiedAt); const visual = await capturePublic(preflight, publicationReceipt.publicationReceiptId, html); saveHoustonPublicationRecord("visualCertifications", visual, "PUBLIC_VISUAL_CERTIFIED", visual.createdAt); const drift = evaluateHoustonDraftPublicDrift({ approvedBodyHash: HOUSTON_APPROVED_BODY_HASH, postPublishBodyHash: after.body.hash, expectedRoles: HOUSTON_MEDIA_ROLES, publicRoles: verification.semanticMediaRoles, expectedLinks: preflight.current.body.links, publicLinks: verification.links.map((item) => item.url), publicHtml: html }); if (["MATERIAL", "CRITICAL"].includes(drift.classification)) throw new Error(`HOUSTON_PUBLIC_DRIFT_${drift.classification}`); const comparison = { comparisonId: `houston-draft-public-${publicationReceipt.publicationReceiptId}`, publicationReceiptId: publicationReceipt.publicationReceiptId, draftCertificationId: preflight.certification.certificationId, publicCertificationId: visual.certificationId, classification: drift.classification, reasons: drift.reasons, createdAt: new Date().toISOString() }; saveHoustonPublicationRecord("comparisons", comparison, "PUBLIC_DRIFT_EVALUATED", comparison.createdAt);
    const target = reconcileGlwCampaignTargetPublishedWithoutDispatch({ campaignId: HOUSTON_CAMPAIGN_ID, stateCode: "TX", citySlug: "houston", targetId: HOUSTON_TARGET_ID, wordpressObjectId: HOUSTON_WORDPRESS_OBJECT_ID }); reconciled = true; const reconciliation = { reconciliationReceiptId: `houston-reconciliation-${publicationReceipt.publicationReceiptId}`, publicationReceiptId: publicationReceipt.publicationReceiptId, campaignId: HOUSTON_CAMPAIGN_ID, targetId: HOUSTON_TARGET_ID, beforeState: "queued" as const, afterState: target.status as "published", dispatchPerformed: false as const, leaseCreated: false as const, newJobCreated: false as const, newExecutionCreated: false as const, newDispatchDateCreated: false as const, reconciledAt: new Date().toISOString() }; saveHoustonPublicationRecord("reconciliations", reconciliation, "CAMPAIGN_RECONCILED", reconciliation.reconciledAt);
    const reference = { certificationId: `genesis-reference-page-houston-${publicationReceipt.publicationReceiptId}`, contract: "GENESIS_REFERENCE_PAGE_V1" as const, state: "CERTIFIED" as const, identity: preflight.identity, publicUrl: HOUSTON_PUBLIC_URL, publicationReceiptId: publicationReceipt.publicationReceiptId, publicVerificationId: verification.verificationId, publicVisualCertificationId: visual.certificationId, ownerApprovalId: records.approval.approvalId, reconciliationReceiptId: reconciliation.reconciliationReceiptId, reusableRules: ["Market intelligence may select different primary applications by city.", "Environmental conditions may change product-suitability guidance.", "Local theme and context may vary without weakening product authority.", "Semantic media may vary while product authority remains stable.", "Local link graphs may vary independently.", "Theme-integrated draft certification prevents duplicate-H1 and overflow failures.", "Reusable governance does not require identical composition or content.", "Preview, theme-integrated draft, and public render require separate certification."], houstonSpecificExpressions: ["Commercial AV is Houston's primary application.", "Event venues and projection mapping are supporting Houston applications.", "Houston and Southeast Texas climate context shapes suitability guidance.", "Houston imagery, links, palette, and composition are local expressions."], createdAt: new Date().toISOString() }; saveHoustonPublicationRecord("referenceCertifications", reference, "REFERENCE_CERTIFIED", reference.createdAt); consumeHoustonPublicationIntent(records.intent.intentId); return { state: getHoustonPublicationState(), reference, reused: false };
  } catch (error) { if (reconciled) reconcileGlwCampaignTargetQueuedAfterDirectPublicationFailure({ campaignId: HOUSTON_CAMPAIGN_ID, stateCode: "TX", citySlug: "houston", targetId: HOUSTON_TARGET_ID, wordpressObjectId: HOUSTON_WORDPRESS_OBJECT_ID }); if (published) { const state = getHoustonPublicationState(); let failure = state.failures.filter((item) => !attemptStartedAt || item.failedAt >= attemptStartedAt).at(-1); if (!failure || failure.probeId === undefined) { const failedAt = new Date().toISOString(); failure = saveHoustonPublicationRecord("failures", { failureId: `houston-publication-failure-${randomUUID()}`, reason: error instanceof Error ? error.message : "UNKNOWN", probeId: null, verifierResultId: null, failedChecks: [], primaryFailureClassification: "IMMEDIATE_ROLLBACK_REQUIRED", rollbackRequired: true, failedAt }, "PUBLICATION_FAILURE_RECORDED", failedAt) as HoustonPublicationFailure; } await restoreDraft(preflight, failure.failureId); } throw error; } }