import { createHash } from "node:crypto";

import type { ThemeIntegrationEvidence } from "@/modules/foundation/governed-render-capture-browser";
import type { HoustonApprovedPreviewIdentity, HoustonDraftReceipt } from "./houston-approved-preview-draft";
import { HOUSTON_H1, HOUSTON_SEO, HOUSTON_THEME_TEMPLATE, HOUSTON_TITLE } from "./houston-approved-preview-draft";
import { HOUSTON_CANONICAL_PATH, HOUSTON_PRODUCT_MEDIA_ID, HOUSTON_TARGET_ID } from "./houston-reference-preview";

export const HOUSTON_PUBLICATION_CONTRACT = "houston-reference-page-certify-and-publish-v1" as const;
export const HOUSTON_PUBLIC_VERIFIER_VERSION = "houston-public-verifier-v2" as const;
export const HOUSTON_WORDPRESS_OBJECT_ID = "13093" as const;
export const HOUSTON_APPROVED_BODY_HASH = "1a1664c3847fd74c72ba590b50a6556e8162baf3e328870c05d03bcb87b25c3d" as const;
export const HOUSTON_APPROVED_SEO_HASH = "ad63840abd6120bd9ace1fd1fd35056ddd94b7f1d4bc1ea3786b120c40831e1c" as const;
export const HOUSTON_PUBLIC_URL = `https://projectorenclosure.com/${HOUSTON_CANONICAL_PATH}/` as const;
export const HOUSTON_CAMPAIGN_ID = "campaign-ssi-site-ssi-projectorenclosure-fan-cooled-projector-enclosures-texas-cities" as const;
export const HOUSTON_PUBLICATION_COMMIT = "2cc2072175fcb20a71e87a1ff6014e92ae5a0ec8" as const;
export const HOUSTON_VERIFIER_REPAIR_COMMIT = "e7cca00e8d102ce974d73b3aff325495419f8674" as const;
export const HOUSTON_V1_APPROVAL_ID = "houston-publication-approval-a0cacaed-7227-4b2c-bc09-22bd38fe845f" as const;
export const HOUSTON_V1_INTENT_ID = "houston-publication-intent-652a7c73-b841-4dfd-9943-5d9df0e09e12" as const;
export const HOUSTON_V1_RECEIPT_ID = "houston-publication-houston-publication-intent-652a7c73-b841-4dfd-9943-5d9df0e09e12" as const;
export const HOUSTON_V1_FAILURE_REASON = "HOUSTON_PUBLIC_VERIFICATION_FAILED" as const;
export const HOUSTON_H1_NORMALIZATION_REPAIR_COMMIT = "701e9fcfb8670bead66b629ad40298a9189c74ce" as const;
export const HOUSTON_V2_APPROVAL_ID = "houston-publication-retry-v2-approval-10028bfd-a50f-428d-9ce4-6952963332aa" as const;
export const HOUSTON_V2_INTENT_ID = "houston-publication-retry-v2-intent-a6270098-0caa-4f72-8c58-71c560b57b8c" as const;
export const HOUSTON_V2_RECEIPT_ID = "houston-publication-houston-publication-retry-v2-intent-a6270098-0caa-4f72-8c58-71c560b57b8c" as const;
export const HOUSTON_V2_FAILURE_ID = "houston-publication-failure-d2b8c51d-30ed-453e-9ce5-ac81609ae429" as const;
export const HOUSTON_V2_ROLLBACK_ID = "houston-rollback-houston-publication-failure-d2b8c51d-30ed-453e-9ce5-ac81609ae429" as const;
export const HOUSTON_MEDIA_ROLES = ["PRODUCT_AUTHORITY", "CONTEXTUAL_IN_USE", "APPLICATION_EXPERIENCE", "LOCAL_CONTEXTUAL_ATMOSPHERE"] as const;
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
export const normalizeHoustonSemanticText = (value: string) => value.replace(/&amp;/gi, "&").replace(/&#0*(?:39|8216|8217);|&apos;|&#x0*(?:27|2018|2019);/gi, "'").replace(/[’‘]/g, "'").replace(/\s+/g, " ").trim();
const normalizeUrl = (value: string) => { try { const url = new URL(value); url.hash = ""; return url.toString(); } catch { return "INVALID"; } };

export type HoustonPublicationIdentity = { organizationId: "ssi"; siteId: "site-ssi-projectorenclosure"; campaignId: typeof HOUSTON_CAMPAIGN_ID; targetId: typeof HOUSTON_TARGET_ID; wordpressObjectId: typeof HOUSTON_WORDPRESS_OBJECT_ID; parentId: 13083; title: typeof HOUSTON_TITLE; slug: "houston"; canonicalPath: typeof HOUSTON_CANONICAL_PATH; bodyHash: typeof HOUSTON_APPROVED_BODY_HASH; seoHash: typeof HOUSTON_APPROVED_SEO_HASH; featuredMediaId: typeof HOUSTON_PRODUCT_MEDIA_ID; template: typeof HOUSTON_THEME_TEMPLATE; hideTitle: "yes"; repositoryCommit: typeof HOUSTON_PUBLICATION_COMMIT; draftReceiptId: string; draftApprovalId: string; approvedPreviewIdentity: HoustonApprovedPreviewIdentity; themeCertificationId: string; themeCertificationHash: string; previewDraftComparisonId: string; previewDraftDrift: "NONE" | "MINOR"; semanticMediaHash: string; semanticMediaRoles: readonly string[] };
export type HoustonPublicationReadiness = { CONTENT_READY: boolean; SEO_READY: boolean; MEDIA_READY: boolean; LINKS_READY: boolean; CLAIM_SAFE: boolean; RESPONSIVE_READY: boolean; THEME_INTEGRATION_READY: boolean; OWNER_APPROVED: boolean; PUBLICATION_READY: boolean; failures: readonly string[] };
export type HoustonRetryAuthority = { attempt: "V2"; priorApprovalId: typeof HOUSTON_V1_APPROVAL_ID; priorIntentId: typeof HOUSTON_V1_INTENT_ID; priorPublicationReceiptId: typeof HOUSTON_V1_RECEIPT_ID; priorFailureId: string; priorFailureReason: typeof HOUSTON_V1_FAILURE_REASON; priorRollbackVerified: true; previousDraftApprovalId: string; verifierRepairCommit: typeof HOUSTON_VERIFIER_REPAIR_COMMIT; seoContractVersion: "projectorenclosure-public-seo-v1"; publicVerifierVersion: typeof HOUSTON_PUBLIC_VERIFIER_VERSION };
export type HoustonRetryV3Authority = { attempt: "V3"; priorApprovalId: typeof HOUSTON_V2_APPROVAL_ID; priorIntentId: typeof HOUSTON_V2_INTENT_ID; priorPublicationReceiptId: typeof HOUSTON_V2_RECEIPT_ID; priorFailureId: typeof HOUSTON_V2_FAILURE_ID; priorRollbackId: typeof HOUSTON_V2_ROLLBACK_ID; priorFailedCheck: "H1"; priorRollbackVerified: true; previousDraftApprovalId: string; h1NormalizationRepairCommit: typeof HOUSTON_H1_NORMALIZATION_REPAIR_COMMIT; seoContractVersion: "projectorenclosure-public-seo-v1"; publicVerifierVersion: typeof HOUSTON_PUBLIC_VERIFIER_VERSION };
export type HoustonPublicationApproval = { approvalId: string; decision: "APPROVED_FOR_PUBLICATION"; ownerStatement: "approved"; source: "OWNER_ACTUAL_WORDPRESS_DRAFT_REVIEW"; identity: HoustonPublicationIdentity; approvedAt: string; retryAuthority?: never } | { approvalId: string; decision: "APPROVED_FOR_PUBLICATION_RETRY_V2"; ownerStatement: "approved"; source: "OWNER_VERIFIER_REPAIR_RETRY_AUTHORIZATION"; identity: HoustonPublicationIdentity; retryAuthority: HoustonRetryAuthority; approvedAt: string } | { approvalId: string; decision: "APPROVED_FOR_PUBLICATION_RETRY_V3"; ownerStatement: "approved"; source: "OWNER_H1_NORMALIZATION_RETRY_AUTHORIZATION"; identity: HoustonPublicationIdentity; retryAuthority: HoustonRetryV3Authority; approvedAt: string };
export type HoustonPublicationIntent = { intentId: string; contract: typeof HOUSTON_PUBLICATION_CONTRACT; attempt: "V1" | "V2" | "V3"; approvalId: string; identity: HoustonPublicationIdentity; expectedPublicUrl: typeof HOUSTON_PUBLIC_URL; seoContractVersion: "projectorenclosure-public-seo-v1"; publicVerifierVersion: typeof HOUSTON_PUBLIC_VERIFIER_VERSION; rollbackAuthority: { wordpressObjectId: typeof HOUSTON_WORDPRESS_OBJECT_ID; restoreStatus: "draft"; bodyHash: typeof HOUSTON_APPROVED_BODY_HASH; seoHash: typeof HOUSTON_APPROVED_SEO_HASH }; state: "READY" | "CONSUMED"; createdAt: string };
export type HoustonWordPressPublicationReceipt = { publicationReceiptId: string; intentId: string; approvalId: string; wordpressObjectId: typeof HOUSTON_WORDPRESS_OBJECT_ID; beforeStatus: "draft"; afterStatus: "publish"; bodyHash: typeof HOUSTON_APPROVED_BODY_HASH; seoHash: typeof HOUSTON_APPROVED_SEO_HASH; publicUrl: typeof HOUSTON_PUBLIC_URL; wordpressPermalink: string | null; mutationPerformed: boolean; publishStartedAt: string; publishConfirmedAt: string };
export type HoustonPublicLinkResult = { url: string; classification: "INTERNAL_DIRECT" | "INTERNAL_REDIRECT" | "INTERNAL_BROKEN" | "EXTERNAL_VERIFIED" | "EXTERNAL_ACCEPTABLE"; status: number; finalUrl: string | null };
export type PublicSeoTextExpectation = "EXPECTED_NONEMPTY_EXACT" | "EXPECTED_NONEMPTY_NORMALIZED" | "EXPECTED_EMPTY" | "OPTIONAL" | "NOT_EVALUATED";
export type HoustonPublicSeoContract = { contractVersion: "projectorenclosure-public-seo-v1"; title: { state: Exclude<PublicSeoTextExpectation, "EXPECTED_EMPTY">; expectedValues: readonly string[] }; metaDescription: { state: PublicSeoTextExpectation; expectedValue: string | null }; canonical: string; indexability: "INDEXABLE" };
export type HoustonVerifierCheckState = "PASS" | "FAIL" | "NOT_EVALUATED";
export type HoustonVerifierCheckCode = "HTTP" | "FINAL_URL" | "CANONICAL" | "TITLE" | "META" | "ROBOTS" | "H1" | "CONTENT_IDENTITY" | "SEMANTIC_MEDIA" | "LINKS" | "DEV_LEAK" | "PREVIEW_LEAK" | "CLAIM_SAFETY" | "THEME_INTEGRATION" | "RESPONSIVE" | "VISUAL";
export type HoustonVerifierCheck = { code: HoustonVerifierCheckCode; state: HoustonVerifierCheckState; expected: string; actual: string | null };
export type HoustonVerificationFailureClass = "IMMEDIATE_ROLLBACK_REQUIRED" | "VERIFICATION_BLOCKED" | "SEO_FAILURE";
export type HoustonProbeHttpClassification = "HTTP_200" | "HTTP_3XX" | "HTTP_404" | "HTTP_403" | "HTTP_5XX" | "TIMEOUT" | "DNS" | "TLS" | "REDIRECT_ESCAPE" | "OTHER";
export type HoustonSafeResponseHeaders = { contentType: string | null; cacheControl: string | null; server: string | null; age: string | null; via: string | null; xCache: string | null };
export type HoustonRedirectEvidence = { status: number; location: string; resolvedDestination: string };
export type HoustonFirstPublicProbe = { probeId: string; publicationIntentId: string; publicationReceiptId: string; wordpressObjectId: typeof HOUSTON_WORDPRESS_OBJECT_ID; requestedUrl: string; startedAt: string; completedAt: string; httpStatus: number | null; httpClassification: HoustonProbeHttpClassification; finalUrl: string | null; redirectChain: readonly HoustonRedirectEvidence[]; responseHeaders: HoustonSafeResponseHeaders; contentType: string | null; contentHash: string | null; title: string | null; metaDescription: string | null; metaDescriptionPresent: boolean | null; openGraphDescription: string | null; canonical: string | null; robots: string | null; indexability: "INDEXABLE" | "NOINDEX" | "NOT_EVALUATED"; visibleH1Count: number | null; visibleH1Texts: readonly string[]; normalizedH1Texts: readonly string[]; expectedH1Raw: typeof HOUSTON_H1; expectedH1Normalized: string; bodyMarkerClassification: "APPROVED_CONTENT" | "CONTENT_MISMATCH" | "NOT_HTML" | "UNAVAILABLE"; approvedContentMarkerPresent: boolean | null; semanticMediaRoles: readonly string[]; devLeak: boolean | null; previewLeak: boolean | null; networkErrorClass: "TIMEOUT" | "DNS" | "TLS" | "OTHER" | null; verifierVersion: typeof HOUSTON_PUBLIC_VERIFIER_VERSION };
export type HoustonPublicVerifierResult = { verifierResultId: string; probeId: string; publicationIntentId: string; publicationReceiptId: string; seoContract: HoustonPublicSeoContract; checks: readonly HoustonVerifierCheck[]; failedChecks: readonly HoustonVerifierCheckCode[]; primaryFailureClassification: HoustonVerificationFailureClass | null; secondaryFailures: readonly HoustonVerifierCheckCode[]; overallState: "PASS" | "FAIL" | "BLOCKED"; decisionAt: string; verifierVersion: typeof HOUSTON_PUBLIC_VERIFIER_VERSION };
export type HoustonPublicationTiming = { timingId: string; publicationIntentId: string; phase: "PUBLISH_STARTED" | "PUBLISH_CONFIRMED" | "FIRST_PROBE_STARTED" | "FIRST_PROBE_COMPLETED" | "VERIFICATION_DECIDED" | "ROLLBACK_STARTED" | "ROLLBACK_COMPLETED"; at: string };
export type HoustonPublicationRollback = { rollbackId: string; publicationIntentId: string; failureId: string; startedAt: string; completedAt: string; wordpressRestoredToDraft: true; bodyHash: typeof HOUSTON_APPROVED_BODY_HASH; seoHash: typeof HOUSTON_APPROVED_SEO_HASH };
export type HoustonPublicationFailure = { failureId: string; reason: string; probeId: string | null; verifierResultId: string | null; failedChecks: readonly HoustonVerifierCheckCode[]; primaryFailureClassification: HoustonVerificationFailureClass; rollbackRequired: boolean; failedAt: string };
export type HoustonPublicVerification = { verificationId: string; publicationReceiptId: string; probeId: string; verifierResultId: string; requestedUrl: string; finalUrl: string; httpStatus: number; https: boolean; canonical: string; title: string; metaDescription: string; indexability: "INDEXABLE" | "NOINDEX"; h1Count: number; remainingH1: string; semanticMediaRoles: readonly string[]; mediaLoaded: readonly { role: string; url: string; status: number }[]; links: readonly HoustonPublicLinkResult[]; bodyHash: string; seoHash: string; featuredMediaId: number; claimSafe: boolean; devLeak: boolean; previewLeak: boolean; verifiedAt: string };
export type HoustonPublicCapture = { captureId: string; viewport: "DESKTOP_1440" | "DESKTOP_1024" | "TABLET_768" | "MOBILE_375"; width: number; height: number; documentWidth: number; documentHeight: number; horizontalOverflow: number; mediaRolesRendered: readonly string[]; themeIntegration: ThemeIntegrationEvidence; artifact: { reference: string; sha256: string; bytes: number; width: number; height: number }; capturedAt: string };
export type HoustonPublicVisualCertification = { certificationId: string; publicationReceiptId: string; publicUrl: typeof HOUSTON_PUBLIC_URL; renderAuthority: "PUBLIC_RENDER"; captures: readonly HoustonPublicCapture[]; findings: readonly { code: string; state: "PASS" | "FAIL"; summary: string }[]; overallState: "PASS" | "FAIL"; createdAt: string };
export type HoustonDraftPublicComparison = { comparisonId: string; publicationReceiptId: string; draftCertificationId: string; publicCertificationId: string; classification: "NONE" | "MINOR" | "MATERIAL" | "CRITICAL"; reasons: readonly string[]; createdAt: string };
export type HoustonCampaignReconciliationReceipt = { reconciliationReceiptId: string; publicationReceiptId: string; campaignId: typeof HOUSTON_CAMPAIGN_ID; targetId: typeof HOUSTON_TARGET_ID; beforeState: "queued"; afterState: "published"; dispatchPerformed: false; leaseCreated: false; newJobCreated: false; newExecutionCreated: false; newDispatchDateCreated: false; reconciledAt: string };
export type HoustonReferencePageCertification = { certificationId: string; contract: "GENESIS_REFERENCE_PAGE_V1"; state: "CERTIFIED"; identity: HoustonPublicationIdentity; publicUrl: typeof HOUSTON_PUBLIC_URL; publicationReceiptId: string; publicVerificationId: string; publicVisualCertificationId: string; ownerApprovalId: string; reconciliationReceiptId: string; reusableRules: readonly string[]; houstonSpecificExpressions: readonly string[]; createdAt: string };

export function freezeHoustonRetryAuthority(input: { priorApprovalId: string; priorIntentId: string; priorPublicationReceiptId: string; priorFailureId: string; priorFailureReason: string; priorRollbackVerified: boolean; previousDraftApprovalId: string; verifierRepairCommit: string; seoContractVersion: string; publicVerifierVersion: string }): HoustonRetryAuthority {
  if (input.priorApprovalId !== HOUSTON_V1_APPROVAL_ID || input.priorIntentId !== HOUSTON_V1_INTENT_ID || input.priorPublicationReceiptId !== HOUSTON_V1_RECEIPT_ID || !input.priorFailureId || input.priorFailureReason !== HOUSTON_V1_FAILURE_REASON || !input.priorRollbackVerified || !input.previousDraftApprovalId || input.verifierRepairCommit !== HOUSTON_VERIFIER_REPAIR_COMMIT || input.seoContractVersion !== "projectorenclosure-public-seo-v1" || input.publicVerifierVersion !== HOUSTON_PUBLIC_VERIFIER_VERSION) throw new Error("HOUSTON_V2_RETRY_AUTHORITY_STALE");
  return { attempt: "V2", priorApprovalId: HOUSTON_V1_APPROVAL_ID, priorIntentId: HOUSTON_V1_INTENT_ID, priorPublicationReceiptId: HOUSTON_V1_RECEIPT_ID, priorFailureId: input.priorFailureId, priorFailureReason: HOUSTON_V1_FAILURE_REASON, priorRollbackVerified: true, previousDraftApprovalId: input.previousDraftApprovalId, verifierRepairCommit: HOUSTON_VERIFIER_REPAIR_COMMIT, seoContractVersion: "projectorenclosure-public-seo-v1", publicVerifierVersion: HOUSTON_PUBLIC_VERIFIER_VERSION };
}

export function freezeHoustonRetryV3Authority(input: { priorApprovalId: string; priorIntentId: string; priorPublicationReceiptId: string; priorFailureId: string; priorRollbackId: string; priorFailedChecks: readonly string[]; priorRollbackVerified: boolean; previousDraftApprovalId: string; h1NormalizationRepairCommit: string; seoContractVersion: string; publicVerifierVersion: string }): HoustonRetryV3Authority {
  if (input.priorApprovalId !== HOUSTON_V2_APPROVAL_ID || input.priorIntentId !== HOUSTON_V2_INTENT_ID || input.priorPublicationReceiptId !== HOUSTON_V2_RECEIPT_ID || input.priorFailureId !== HOUSTON_V2_FAILURE_ID || input.priorRollbackId !== HOUSTON_V2_ROLLBACK_ID || JSON.stringify(input.priorFailedChecks) !== JSON.stringify(["H1"]) || !input.priorRollbackVerified || !input.previousDraftApprovalId || input.h1NormalizationRepairCommit !== HOUSTON_H1_NORMALIZATION_REPAIR_COMMIT || input.seoContractVersion !== "projectorenclosure-public-seo-v1" || input.publicVerifierVersion !== HOUSTON_PUBLIC_VERIFIER_VERSION) throw new Error("HOUSTON_V3_RETRY_AUTHORITY_STALE");
  return { attempt: "V3", priorApprovalId: HOUSTON_V2_APPROVAL_ID, priorIntentId: HOUSTON_V2_INTENT_ID, priorPublicationReceiptId: HOUSTON_V2_RECEIPT_ID, priorFailureId: HOUSTON_V2_FAILURE_ID, priorRollbackId: HOUSTON_V2_ROLLBACK_ID, priorFailedCheck: "H1", priorRollbackVerified: true, previousDraftApprovalId: input.previousDraftApprovalId, h1NormalizationRepairCommit: HOUSTON_H1_NORMALIZATION_REPAIR_COMMIT, seoContractVersion: "projectorenclosure-public-seo-v1", publicVerifierVersion: HOUSTON_PUBLIC_VERIFIER_VERSION };
}

export function resolveHoustonPublicSeoContract(): HoustonPublicSeoContract { return { contractVersion: "projectorenclosure-public-seo-v1", title: { state: "EXPECTED_NONEMPTY_NORMALIZED", expectedValues: [HOUSTON_SEO.seoTitle] }, metaDescription: { state: "EXPECTED_NONEMPTY_NORMALIZED", expectedValue: HOUSTON_SEO.metaDescription }, canonical: HOUSTON_PUBLIC_URL, indexability: "INDEXABLE" }; }
export function resolveDallasCertifiedSeoContract(input: { publicTitle: string; publicCanonical: string }): HoustonPublicSeoContract { return { contractVersion: "projectorenclosure-public-seo-v1", title: { state: "EXPECTED_NONEMPTY_NORMALIZED", expectedValues: [input.publicTitle] }, metaDescription: { state: "OPTIONAL", expectedValue: null }, canonical: input.publicCanonical, indexability: "INDEXABLE" }; }

function evaluateTextExpectation(expectation: { state: PublicSeoTextExpectation; expectedValue: string | null }, actual: string | null | undefined): HoustonVerifierCheckState { if (expectation.state === "NOT_EVALUATED" || actual === undefined) return "NOT_EVALUATED"; if (expectation.state === "OPTIONAL") return "PASS"; if (expectation.state === "EXPECTED_EMPTY") return normalizeHoustonSemanticText(actual ?? "") === "" ? "PASS" : "FAIL"; if (!actual) return "FAIL"; if (expectation.state === "EXPECTED_NONEMPTY_EXACT") return actual === expectation.expectedValue ? "PASS" : "FAIL"; return normalizeHoustonSemanticText(actual) === normalizeHoustonSemanticText(expectation.expectedValue ?? "") ? "PASS" : "FAIL"; }

export function evaluatePublicSeoContract(input: { contract: HoustonPublicSeoContract; actual: { title?: string | null; metaDescription?: string | null; canonical?: string | null; indexability?: "INDEXABLE" | "NOINDEX" | "NOT_EVALUATED" } }): HoustonVerifierCheck[] {
  const titleState: HoustonVerifierCheckState = input.actual.title === undefined || input.actual.title === null ? "NOT_EVALUATED" : input.contract.title.state === "OPTIONAL" ? "PASS" : input.contract.title.expectedValues.some((expected) => normalizeHoustonSemanticText(expected) === normalizeHoustonSemanticText(input.actual.title ?? "")) ? "PASS" : "FAIL";
  return [
    { code: "CANONICAL", state: input.actual.canonical === undefined || input.actual.canonical === null ? "NOT_EVALUATED" : normalizeUrl(input.actual.canonical) === normalizeUrl(input.contract.canonical) ? "PASS" : "FAIL", expected: input.contract.canonical, actual: input.actual.canonical ?? null },
    { code: "TITLE", state: titleState, expected: input.contract.title.expectedValues.join(" OR "), actual: input.actual.title ?? null },
    { code: "META", state: evaluateTextExpectation(input.contract.metaDescription, input.actual.metaDescription), expected: `${input.contract.metaDescription.state}:${input.contract.metaDescription.expectedValue ?? ""}`, actual: input.actual.metaDescription ?? null },
    { code: "ROBOTS", state: input.actual.indexability === undefined || input.actual.indexability === "NOT_EVALUATED" ? "NOT_EVALUATED" : input.actual.indexability === input.contract.indexability ? "PASS" : "FAIL", expected: input.contract.indexability, actual: input.actual.indexability ?? null },
  ];
}

export function evaluateHoustonPublicEvidence(input: { probe: HoustonFirstPublicProbe; seoContract: HoustonPublicSeoContract; linksValid?: boolean; mediaValid?: boolean; claimSafe?: boolean }): HoustonPublicVerifierResult {
  const seoChecks = evaluatePublicSeoContract({ contract: input.seoContract, actual: { title: input.probe.title, metaDescription: input.probe.metaDescription === null && input.probe.metaDescriptionPresent === null ? undefined : input.probe.metaDescription, canonical: input.probe.canonical, indexability: input.probe.indexability } });
  const checks: HoustonVerifierCheck[] = [
    { code: "HTTP", state: input.probe.httpStatus === null ? "NOT_EVALUATED" : input.probe.httpStatus === 200 ? "PASS" : "FAIL", expected: "HTTP 200", actual: input.probe.httpStatus === null ? null : String(input.probe.httpStatus) },
    { code: "FINAL_URL", state: input.probe.finalUrl === null ? "NOT_EVALUATED" : normalizeUrl(input.probe.finalUrl) === normalizeUrl(input.probe.requestedUrl) ? "PASS" : "FAIL", expected: input.probe.requestedUrl, actual: input.probe.finalUrl },
    ...seoChecks,
    { code: "H1", state: input.probe.visibleH1Count === null ? "NOT_EVALUATED" : input.probe.visibleH1Count === 1 && input.probe.normalizedH1Texts[0] === input.probe.expectedH1Normalized ? "PASS" : "FAIL", expected: `1:${input.probe.expectedH1Normalized}`, actual: input.probe.visibleH1Count === null ? null : `${input.probe.visibleH1Count}:${input.probe.normalizedH1Texts.join("|")}` },
    { code: "CONTENT_IDENTITY", state: input.probe.approvedContentMarkerPresent === null ? "NOT_EVALUATED" : input.probe.approvedContentMarkerPresent ? "PASS" : "FAIL", expected: "data-market-primary=COMMERCIAL_AV", actual: input.probe.bodyMarkerClassification },
    { code: "SEMANTIC_MEDIA", state: input.mediaValid === undefined ? "NOT_EVALUATED" : input.mediaValid && HOUSTON_MEDIA_ROLES.every((role) => input.probe.semanticMediaRoles.includes(role)) ? "PASS" : "FAIL", expected: HOUSTON_MEDIA_ROLES.join(","), actual: input.probe.semanticMediaRoles.join(",") },
    { code: "LINKS", state: input.linksValid === undefined ? "NOT_EVALUATED" : input.linksValid ? "PASS" : "FAIL", expected: "NO_BROKEN_INTERNAL_LINKS", actual: input.linksValid === undefined ? null : input.linksValid ? "VALID" : "INVALID" },
    { code: "DEV_LEAK", state: input.probe.devLeak === null ? "NOT_EVALUATED" : input.probe.devLeak ? "FAIL" : "PASS", expected: "false", actual: input.probe.devLeak === null ? null : String(input.probe.devLeak) },
    { code: "PREVIEW_LEAK", state: input.probe.previewLeak === null ? "NOT_EVALUATED" : input.probe.previewLeak ? "FAIL" : "PASS", expected: "false", actual: input.probe.previewLeak === null ? null : String(input.probe.previewLeak) },
    { code: "CLAIM_SAFETY", state: input.claimSafe === undefined ? "NOT_EVALUATED" : input.claimSafe ? "PASS" : "FAIL", expected: "SAFE", actual: input.claimSafe === undefined ? null : input.claimSafe ? "SAFE" : "UNSAFE" },
    ...(["THEME_INTEGRATION", "RESPONSIVE", "VISUAL"] as const).map((code) => ({ code, state: "NOT_EVALUATED" as const, expected: "LATER_PUBLIC_RENDER_STAGE", actual: null })),
  ];
  const requiredCodes: HoustonVerifierCheckCode[] = ["HTTP", "FINAL_URL", "CANONICAL", "TITLE", "META", "ROBOTS", "H1", "CONTENT_IDENTITY", "SEMANTIC_MEDIA", "LINKS", "DEV_LEAK", "PREVIEW_LEAK", "CLAIM_SAFETY"];
  const failedChecks = checks.filter((check) => check.state === "FAIL").map((check) => check.code); const missing = checks.filter((check) => requiredCodes.includes(check.code) && check.state === "NOT_EVALUATED").map((check) => check.code); const seoFailures = failedChecks.filter((code) => ["TITLE", "META", "ROBOTS"].includes(code));
  const primaryFailureClassification: HoustonVerificationFailureClass | null = missing.length ? "VERIFICATION_BLOCKED" : failedChecks.length === seoFailures.length && failedChecks.length > 0 ? "SEO_FAILURE" : failedChecks.length ? "IMMEDIATE_ROLLBACK_REQUIRED" : null;
  return { verifierResultId: `houston-verifier-result-${input.probe.probeId}`, probeId: input.probe.probeId, publicationIntentId: input.probe.publicationIntentId, publicationReceiptId: input.probe.publicationReceiptId, seoContract: input.seoContract, checks, failedChecks, primaryFailureClassification, secondaryFailures: failedChecks.slice(1), overallState: missing.length ? "BLOCKED" : failedChecks.length ? "FAIL" : "PASS", decisionAt: new Date().toISOString(), verifierVersion: HOUSTON_PUBLIC_VERIFIER_VERSION };
}

export function freezeHoustonPublicationIdentity(input: { receipt: HoustonDraftReceipt; approvalIdentity: HoustonApprovedPreviewIdentity; certification: { certificationId: string; receiptId: string; themeIntegrationReady: boolean; overallState: string; captures: readonly { horizontalOverflow: number; themeIntegration: { visibleH1Count: number; duplicateThemeTitleVisible: boolean; duplicateThemeFeaturedMediaVisible: boolean } }[] }; comparison: { comparisonId: string; receiptId: string; draftVisualCertificationId: string; drift: string }; readback: { wordpressObjectId: string; status: string; parent: number; title: string; slug: string; bodyHash: string; seoHash: string; featuredMediaId: number; template: string; hideTitle: string | undefined; roles: readonly string[] }; repositoryCommit: string }): HoustonPublicationIdentity {
  const roles = [...new Set(input.readback.roles)].sort();
  if (input.repositoryCommit !== HOUSTON_PUBLICATION_COMMIT || input.receipt.wordpressObjectId !== HOUSTON_WORDPRESS_OBJECT_ID || input.receipt.bodyHash !== HOUSTON_APPROVED_BODY_HASH || input.receipt.seoHash !== HOUSTON_APPROVED_SEO_HASH || input.readback.wordpressObjectId !== HOUSTON_WORDPRESS_OBJECT_ID || input.readback.status !== "draft" || input.readback.parent !== 13083 || input.readback.title !== HOUSTON_TITLE || input.readback.slug !== "houston" || input.readback.bodyHash !== HOUSTON_APPROVED_BODY_HASH || input.readback.seoHash !== HOUSTON_APPROVED_SEO_HASH || input.readback.featuredMediaId !== HOUSTON_PRODUCT_MEDIA_ID || input.readback.template !== HOUSTON_THEME_TEMPLATE || input.readback.hideTitle !== "yes" || JSON.stringify(roles) !== JSON.stringify([...HOUSTON_MEDIA_ROLES].sort()) || input.certification.receiptId !== input.receipt.receiptId || !input.certification.themeIntegrationReady || input.certification.overallState !== "PASS" || input.certification.captures.length !== 4 || input.certification.captures.some((capture) => capture.horizontalOverflow !== 0 || capture.themeIntegration.visibleH1Count !== 1 || capture.themeIntegration.duplicateThemeTitleVisible || capture.themeIntegration.duplicateThemeFeaturedMediaVisible) || input.comparison.receiptId !== input.receipt.receiptId || input.comparison.draftVisualCertificationId !== input.certification.certificationId || !["NONE", "MINOR"].includes(input.comparison.drift)) throw new Error("HOUSTON_PUBLICATION_APPROVAL_IDENTITY_STALE");
  return { organizationId: "ssi", siteId: "site-ssi-projectorenclosure", campaignId: HOUSTON_CAMPAIGN_ID, targetId: HOUSTON_TARGET_ID, wordpressObjectId: HOUSTON_WORDPRESS_OBJECT_ID, parentId: 13083, title: HOUSTON_TITLE, slug: "houston", canonicalPath: HOUSTON_CANONICAL_PATH, bodyHash: HOUSTON_APPROVED_BODY_HASH, seoHash: HOUSTON_APPROVED_SEO_HASH, featuredMediaId: HOUSTON_PRODUCT_MEDIA_ID, template: HOUSTON_THEME_TEMPLATE, hideTitle: "yes", repositoryCommit: HOUSTON_PUBLICATION_COMMIT, draftReceiptId: input.receipt.receiptId, draftApprovalId: input.receipt.decisionId, approvedPreviewIdentity: input.approvalIdentity, themeCertificationId: input.certification.certificationId, themeCertificationHash: hash(input.certification), previewDraftComparisonId: input.comparison.comparisonId, previewDraftDrift: input.comparison.drift as "NONE" | "MINOR", semanticMediaHash: hash(input.receipt.uploadedMedia), semanticMediaRoles: HOUSTON_MEDIA_ROLES };
}

export function evaluateHoustonPublicationReadiness(input: { html: string; identity: HoustonPublicationIdentity; linksValid: boolean; mediaValid: boolean; themeReady: boolean; ownerApproved: boolean }): HoustonPublicationReadiness {
  const devLeak = /(?:localhost|127\.0\.0\.1|:(?:3001|3002|3003)\b|\/glw\/|preview)/i.test(input.html); const claimUnsafe = /(?:our|the) Houston (?:office|staff|team|customer|installation)|installed at|completed (?:in|at) Houston|minutes? from|nearby/i.test(input.html);
  const gates = { CONTENT_READY: input.identity.bodyHash === HOUSTON_APPROVED_BODY_HASH && (input.html.match(/<h1\b/gi) ?? []).length === 1 && !devLeak, SEO_READY: input.identity.seoHash === HOUSTON_APPROVED_SEO_HASH, MEDIA_READY: input.mediaValid && input.identity.semanticMediaRoles.length === 4, LINKS_READY: input.linksValid && !devLeak, CLAIM_SAFE: !claimUnsafe, RESPONSIVE_READY: input.themeReady, THEME_INTEGRATION_READY: input.themeReady, OWNER_APPROVED: input.ownerApproved };
  const publicationReady = Object.values(gates).every(Boolean); return { ...gates, PUBLICATION_READY: publicationReady, failures: [...Object.entries(gates).filter(([, pass]) => !pass).map(([name]) => name), ...(publicationReady ? [] : ["PUBLICATION_READY"])] };
}

export function evaluateHoustonDraftPublicDrift(input: { approvedBodyHash: string; postPublishBodyHash: string; expectedRoles: readonly string[]; publicRoles: readonly string[]; expectedLinks: readonly string[]; publicLinks: readonly string[]; publicHtml: string }) { const rolesMatch = input.expectedRoles.every((role) => input.publicRoles.includes(role)); const linksMatch = input.expectedLinks.every((link) => input.publicLinks.includes(link)); const strategy = /COMMERCIAL_AV|Commercial AV/i.test(input.publicHtml) && /EVENT VENUE/i.test(input.publicHtml) && /PROJECTION MAPPING/i.test(input.publicHtml); const suitability = /climate-controlled/i.test(input.publicHtml) && /humidity/i.test(input.publicHtml) && /covered/i.test(input.publicHtml); if (input.approvedBodyHash !== input.postPublishBodyHash || !rolesMatch) return { classification: "CRITICAL" as const, reasons: [input.approvedBodyHash !== input.postPublishBodyHash ? "APPROVED_BODY_CHANGED" : "SEMANTIC_MEDIA_CHANGED"] }; const reasons = [...(linksMatch ? [] : ["LINK_GRAPH_CHANGED"]), ...(strategy ? [] : ["APPLICATION_STRATEGY_CHANGED"]), ...(suitability ? [] : ["CLIMATE_SUITABILITY_CHANGED"])]; return reasons.length ? { classification: "MATERIAL" as const, reasons } : { classification: "MINOR" as const, reasons: ["NORMAL_PUBLIC_WORDPRESS_THEME_CHROME"] }; }