import "server-only";

import { randomUUID } from "node:crypto";
import { deepClone, loadPersistedState, savePersistedState } from "@/modules/foundation/foundation-persistence";
import type { HoustonCampaignReconciliationReceipt, HoustonDraftPublicComparison, HoustonFirstPublicProbe, HoustonPublicationApproval, HoustonPublicationFailure, HoustonPublicationIdentity, HoustonPublicationIntent, HoustonPublicationRollback, HoustonPublicationTiming, HoustonPublicVerification, HoustonPublicVerifierResult, HoustonPublicVisualCertification, HoustonReferencePageCertification, HoustonWordPressPublicationReceipt } from "./houston-reference-page-publication";
import { HOUSTON_APPROVED_BODY_HASH, HOUSTON_APPROVED_SEO_HASH, HOUSTON_PUBLICATION_CONTRACT, HOUSTON_PUBLIC_URL, HOUSTON_WORDPRESS_OBJECT_ID } from "./houston-reference-page-publication";

const NAMESPACE = "houston-reference-page-publication-v1";
type Audit = { eventId: string; action: string; detail: Record<string, string | number | boolean | null>; at: string };
type State = { approvals: HoustonPublicationApproval[]; intents: HoustonPublicationIntent[]; publicationReceipts: HoustonWordPressPublicationReceipt[]; firstProbes: HoustonFirstPublicProbe[]; verifierResults: HoustonPublicVerifierResult[]; publicationTimings: HoustonPublicationTiming[]; publicVerifications: HoustonPublicVerification[]; visualCertifications: HoustonPublicVisualCertification[]; comparisons: HoustonDraftPublicComparison[]; reconciliations: HoustonCampaignReconciliationReceipt[]; referenceCertifications: HoustonReferencePageCertification[]; failures: HoustonPublicationFailure[]; rollbacks: HoustonPublicationRollback[]; audit: Audit[] };
const seed = (): State => ({ approvals: [], intents: [], publicationReceipts: [], firstProbes: [], verifierResults: [], publicationTimings: [], publicVerifications: [], visualCertifications: [], comparisons: [], reconciliations: [], referenceCertifications: [], failures: [], rollbacks: [], audit: [] });
const load = () => { const loaded = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); return { ...loaded, state: { ...seed(), ...loaded.state, firstProbes: loaded.state.firstProbes ?? [], verifierResults: loaded.state.verifierResults ?? [], publicationTimings: loaded.state.publicationTimings ?? [], rollbacks: loaded.state.rollbacks ?? [] } }; }; const save = (loaded: ReturnType<typeof load>) => savePersistedState({ namespace: NAMESPACE, state: loaded.state, expectedRevision: loaded.revision });
const audit = (state: State, action: string, detail: Audit["detail"], at: string) => state.audit.push({ eventId: `audit-${randomUUID()}`, action, detail, at });
export const getHoustonPublicationState = () => deepClone(load().state);
export function persistHoustonPublicationApprovalAndIntent(identity: HoustonPublicationIdentity, now: string) { const loaded = load(); const existing = loaded.state.approvals.find((item) => item.identity.themeCertificationHash === identity.themeCertificationHash && item.identity.repositoryCommit === identity.repositoryCommit); const existingIntent = existing ? loaded.state.intents.find((item) => item.approvalId === existing.approvalId) : null; const alreadyAttempted = existingIntent ? loaded.state.publicationReceipts.some((item) => item.intentId === existingIntent.intentId) : false; if (existing && existingIntent && !alreadyAttempted) return { approval: deepClone(existing), intent: deepClone(existingIntent) }; const approval: HoustonPublicationApproval = { approvalId: `houston-publication-approval-${randomUUID()}`, decision: "APPROVED_FOR_PUBLICATION", ownerStatement: "approved", source: "OWNER_ACTUAL_WORDPRESS_DRAFT_REVIEW", identity: deepClone(identity), approvedAt: now }; const intent: HoustonPublicationIntent = { intentId: `houston-publication-intent-${randomUUID()}`, contract: HOUSTON_PUBLICATION_CONTRACT, approvalId: approval.approvalId, identity: deepClone(identity), expectedPublicUrl: HOUSTON_PUBLIC_URL, rollbackAuthority: { wordpressObjectId: HOUSTON_WORDPRESS_OBJECT_ID, restoreStatus: "draft", bodyHash: HOUSTON_APPROVED_BODY_HASH, seoHash: HOUSTON_APPROVED_SEO_HASH }, state: "READY", createdAt: now }; loaded.state.approvals.push(approval); loaded.state.intents.push(intent); audit(loaded.state, "OWNER_PUBLICATION_APPROVED", { approvalId: approval.approvalId, wordpressObjectId: HOUSTON_WORDPRESS_OBJECT_ID }, now); audit(loaded.state, "PUBLICATION_INTENT_CREATED", { intentId: intent.intentId, publicUrl: HOUSTON_PUBLIC_URL }, now); save(loaded); return { approval: deepClone(approval), intent: deepClone(intent) }; }
export function saveHoustonPublicationRecord<K extends "publicationReceipts" | "firstProbes" | "verifierResults" | "publicationTimings" | "publicVerifications" | "visualCertifications" | "comparisons" | "reconciliations" | "referenceCertifications" | "failures" | "rollbacks">(key: K, record: State[K][number], action: string, at: string) { const loaded = load(); const records = loaded.state[key] as unknown as Record<string, unknown>[]; const id = Object.entries(record as Record<string, unknown>).find(([name]) => name.endsWith("Id"))?.[1]; const existing = records.find((item) => Object.values(item).includes(id)); if (existing) return deepClone(existing) as State[K][number]; records.push(deepClone(record) as Record<string, unknown>); audit(loaded.state, action, { recordId: String(id) }, at); save(loaded); return deepClone(record); }
export function consumeHoustonPublicationIntent(intentId: string) { const loaded = load(); const intent = loaded.state.intents.find((item) => item.intentId === intentId); if (!intent) throw new Error("HOUSTON_PUBLICATION_INTENT_NOT_FOUND"); intent.state = "CONSUMED"; save(loaded); return deepClone(intent); }