import "server-only";

import { createHash, randomUUID } from "node:crypto";
import { deepClone, FoundationPersistenceConflictError, loadPersistedState, savePersistedState } from "@/modules/foundation/foundation-persistence";

export const SAN_ANTONIO_STAGING_OPERATION = "WORDPRESS_STAGING" as const;
export const SAN_ANTONIO_APPROVED_COMPOSITION_COMMIT = "69481665113d9a39dc206075e9496ff262b59e67" as const;
export const SAN_ANTONIO_APPROVED_ARTIFACT_SHA = "0255fda847e2962dc0ae10afcd86a646a5d89aef303331286babf2dae49078d2" as const;
export const SAN_ANTONIO_STAGING_TARGET_ID = "target-campaign-ssi-site-ssi-projectorenclosure-fan-cooled-projector-enclosures-texas-cities-tx-san-antonio" as const;
export const SAN_ANTONIO_STAGING_CAMPAIGN_ID = "campaign-ssi-site-ssi-projectorenclosure-fan-cooled-projector-enclosures-texas-cities" as const;
export const SAN_ANTONIO_STAGING_JOB_ID = "f518ffb7-9216-4866-a93c-7f4793e74038" as const;

type Principal = { principalId: string; sessionId: string };
export type SanAntonioStagingPreflightReceipt = { preflightReceiptId: string; operation: typeof SAN_ANTONIO_STAGING_OPERATION; organizationId: "ssi"; siteId: "site-ssi-projectorenclosure"; campaignId: typeof SAN_ANTONIO_STAGING_CAMPAIGN_ID; targetId: typeof SAN_ANTONIO_STAGING_TARGET_ID; jobId: typeof SAN_ANTONIO_STAGING_JOB_ID; artifactSha: typeof SAN_ANTONIO_APPROVED_ARTIFACT_SHA; approvedCompositionCommit: typeof SAN_ANTONIO_APPROVED_COMPOSITION_COMMIT; targetFingerprint: string; existingObjectPreflight: "NO_EXISTING_OBJECT" | "EXISTING_EXPECTED_OBJECT"; principal: Principal; createdAt: string; expiresAt: string };
export type SanAntonioStagingGrant = { grantId: string; preflightReceiptId: string; operation: typeof SAN_ANTONIO_STAGING_OPERATION; targetFingerprint: string; principal: Principal; createdAt: string; expiresAt: string; consumedAt: string | null; consumedByReceiptId: string | null };
export type SanAntonioStagingReceipt = { receiptId: string; preflightReceiptId: string; grantId: string; operation: typeof SAN_ANTONIO_STAGING_OPERATION; organizationId: "ssi"; siteId: "site-ssi-projectorenclosure"; campaignId: typeof SAN_ANTONIO_STAGING_CAMPAIGN_ID; targetId: typeof SAN_ANTONIO_STAGING_TARGET_ID; jobId: typeof SAN_ANTONIO_STAGING_JOB_ID; artifactSha: typeof SAN_ANTONIO_APPROVED_ARTIFACT_SHA; approvedCompositionCommit: typeof SAN_ANTONIO_APPROVED_COMPOSITION_COMMIT; principal: Principal; wordpressObjectId: string; wordpressStatus: "draft"; wordpressUrl: string; wordpressAuthority: "POST_CONTENT"; storedCompositionHash: string; uploadedMedia: readonly { role: string; mediaId: number; url: string; sha256: string; claimClass: string }[]; targetLifecycleBefore: "content_ready"; targetLifecycleAfter: "draft_ready"; jobLifecycleBefore: "CONTENT_READY"; jobLifecycleAfter: "COMPLETE"; incidentClassification: "UNAUTHORIZED_VALID_DISPATCH"; incidentSeverity: "HIGH"; createdAt: string; publicationPerformed: false; dispatchPerformed: false; workflowExecuted: false; regenerationPerformed: false };
export type SanAntonioStoredAuthorityCertification = { certificationId: string; receiptId: string; wordpressObjectId: string; wordpressStatus: "draft"; wordpressAuthority: "POST_CONTENT"; multiAuthorityDetected: false; storedCompositionHash: string; h1Count: 1; productAuthorityMediaId: 10757; mediaResolved: 4; brokenMedia: 0; localizationContaminationGate: "PASS"; forbiddenReferenceLocationsFound: 0; applicationAuthorityPreserved: true; unsupportedClaims: 0; seoIdentityValid: true; canonicalIntentValid: true; draftIndexabilitySafe: true; brokenInternalLinks: 0; devLinks: 0; genesisCompositionCertified: true; wordpressStoredAuthorityCertified: true; nativeWordPressDraftRenderCertified: false; nativeWordPressPreviewLimitation: string; certifiedAt: string };

type State = { preflights: SanAntonioStagingPreflightReceipt[]; grants: Omit<SanAntonioStagingGrant, "consumedAt" | "consumedByReceiptId">[]; consumptions: { grantId: string; receiptId: string; consumedAt: string }[]; receipts: SanAntonioStagingReceipt[]; outcomes: { receiptId: string; state: "WORDPRESS_VERIFIED" | "LIFECYCLE_RECONCILED" | "FAILED" | "ROLLED_BACK"; at: string; reason: string | null }[]; certifications: SanAntonioStoredAuthorityCertification[] };
const NAMESPACE = "glw-san-antonio-wordpress-staging-v1";
const seed = (): State => ({ preflights: [], grants: [], consumptions: [], receipts: [], outcomes: [], certifications: [] });
const normalizePrincipal = (value: Principal) => { const principalId = value.principalId.trim(); const sessionId = value.sessionId.trim(); if (!principalId || !sessionId) throw new Error("SAN_ANTONIO_STAGING_PRINCIPAL_REQUIRED"); return { principalId, sessionId }; };
const samePrincipal = (left: Principal, right: Principal) => left.principalId === right.principalId && left.sessionId === right.sessionId;
const save = <T>(mutate: (state: State) => { state: State; value: T }): T => { for (let attempt = 0; attempt < 8; attempt += 1) { const loaded = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); const result = mutate(deepClone(loaded.state)); try { savePersistedState({ namespace: NAMESPACE, state: result.state, expectedRevision: loaded.revision }); return result.value; } catch (error) { if (!(error instanceof FoundationPersistenceConflictError) || attempt === 7) throw error; } } throw new Error("SAN_ANTONIO_STAGING_CAS_EXHAUSTED"); };
export const createSanAntonioStagingFingerprint = (value: object) => createHash("sha256").update(JSON.stringify(value)).digest("hex");

export function saveSanAntonioStagingPreflight(input: Omit<SanAntonioStagingPreflightReceipt, "preflightReceiptId" | "createdAt" | "expiresAt" | "principal"> & { principal: Principal; now?: Date }) {
  const now = input.now ?? new Date(); const principal = normalizePrincipal(input.principal); const receipt: SanAntonioStagingPreflightReceipt = { ...input, principal, preflightReceiptId: `san-antonio-staging-preflight-${randomUUID()}`, createdAt: now.toISOString(), expiresAt: new Date(now.getTime() + 10 * 60 * 1000).toISOString() };
  return save((state) => ({ state: { ...state, preflights: [...state.preflights, receipt] }, value: deepClone(receipt) }));
}

export function createSanAntonioStagingGrant(input: { preflightReceiptId: string; principal: Principal; now?: Date }) {
  const now = input.now ?? new Date(); const principal = normalizePrincipal(input.principal); const state = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }).state; const preflight = state.preflights.find((item) => item.preflightReceiptId === input.preflightReceiptId); const latest = [...state.preflights].reverse().find((item) => item.targetId === SAN_ANTONIO_STAGING_TARGET_ID);
  if (!preflight || latest?.preflightReceiptId !== preflight.preflightReceiptId || new Date(preflight.expiresAt) <= now || !samePrincipal(preflight.principal, principal)) throw new Error("SAN_ANTONIO_STAGING_PREFLIGHT_INVALID");
  const grant = { grantId: `san-antonio-staging-grant-${randomUUID()}`, preflightReceiptId: preflight.preflightReceiptId, operation: SAN_ANTONIO_STAGING_OPERATION, targetFingerprint: preflight.targetFingerprint, principal, createdAt: now.toISOString(), expiresAt: new Date(now.getTime() + 5 * 60 * 1000).toISOString() };
  save((current) => ({ state: { ...current, grants: [...current.grants, grant] }, value: grant })); return { ...grant, consumedAt: null, consumedByReceiptId: null } satisfies SanAntonioStagingGrant;
}

export function consumeSanAntonioStagingGrant(input: { preflightReceiptId: string; grantId: string; targetFingerprint: string; principal: Principal; receiptId: string; now?: Date }) {
  const now = input.now ?? new Date(); const principal = normalizePrincipal(input.principal);
  return save((state) => { const preflight = state.preflights.find((item) => item.preflightReceiptId === input.preflightReceiptId); const grant = state.grants.find((item) => item.grantId === input.grantId); if (!preflight || !grant || grant.preflightReceiptId !== preflight.preflightReceiptId || state.consumptions.some((item) => item.grantId === grant.grantId) || new Date(grant.expiresAt) <= now || preflight.targetFingerprint !== input.targetFingerprint || grant.targetFingerprint !== input.targetFingerprint || !samePrincipal(preflight.principal, principal) || !samePrincipal(grant.principal, principal)) throw new Error("SAN_ANTONIO_STAGING_GRANT_INVALID_OR_CONSUMED"); const consumedAt = now.toISOString(); return { state: { ...state, consumptions: [...state.consumptions, { grantId: grant.grantId, receiptId: input.receiptId, consumedAt }] }, value: { ...grant, consumedAt, consumedByReceiptId: input.receiptId } }; });
}

export function saveSanAntonioStagingReceipt(receipt: SanAntonioStagingReceipt) { return save((state) => { if (state.receipts.length) throw new Error("SAN_ANTONIO_STAGING_ALREADY_RECORDED"); return { state: { ...state, receipts: [...state.receipts, receipt] }, value: deepClone(receipt) }; }); }
export function appendSanAntonioStagingOutcome(input: { receiptId: string; state: State["outcomes"][number]["state"]; reason?: string | null }) { const outcome = { receiptId: input.receiptId, state: input.state, at: new Date().toISOString(), reason: input.reason ?? null }; return save((state) => ({ state: { ...state, outcomes: [...(state.outcomes ?? []), outcome] }, value: deepClone(outcome) })); }
export function saveSanAntonioStoredAuthorityCertification(certification: SanAntonioStoredAuthorityCertification) { return save((state) => { const existing = (state.certifications ?? []).find((item) => item.certificationId === certification.certificationId); if (existing) return { state, value: deepClone(existing) }; return { state: { ...state, certifications: [...(state.certifications ?? []), certification] }, value: deepClone(certification) }; }); }
export function getSanAntonioStagingState() { const state = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }).state; return { preflights: deepClone(state.preflights), grants: state.grants.map((grant) => { const use = state.consumptions.find((item) => item.grantId === grant.grantId); return { ...deepClone(grant), consumedAt: use?.consumedAt ?? null, consumedByReceiptId: use?.receiptId ?? null }; }), consumptions: deepClone(state.consumptions), receipts: deepClone(state.receipts), outcomes: deepClone(state.outcomes ?? []), certifications: deepClone(state.certifications ?? []) }; }