import "server-only";

import { createHash, randomUUID } from "node:crypto";
import { deepClone, FoundationPersistenceConflictError, loadPersistedState, savePersistedState } from "@/modules/foundation/foundation-persistence";
import { applyPublicHostLinkStatus, discoverPublicHostLinks } from "@/modules/foundation/public-host-link-classification";
import { getSiteById } from "@/modules/foundation/site-repository";
import { writeGenesisWordPressDraft } from "@/modules/foundation/wordpress-draft-writer";
import { glwPageExecutionRepository } from "./page-execution-repository";
import { applySanAntonioBrokenNavigationRemediation, removeSanAntonioBrokenNavigationRemediation, SAN_ANTONIO_BROKEN_NAVIGATION_BEFORE_HASH, SAN_ANTONIO_BROKEN_NAVIGATION_REMEDIATION_OPERATION, SAN_ANTONIO_LINK_REMEDIATIONS } from "./san-antonio-broken-navigation-remediation";
import { SAN_ANTONIO_APPROVED_ARTIFACT_SHA, SAN_ANTONIO_APPROVED_COMPOSITION_COMMIT } from "./san-antonio-wordpress-staging-authority";
import { inspectSanAntonioWordPressDraft } from "./san-antonio-wordpress-staging-service";

const NAMESPACE = "glw-san-antonio-broken-navigation-remediation-v1"; const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const SEO = { focusKeyphrase: "fan cooled projector enclosures San Antonio", seoTitle: "Fan Cooled Projector Enclosures San Antonio Texas", metaDescription: "Discover fan cooled projector enclosures San Antonio Texas for commercial AV protection. Learn about airflow, selection, and maintenance. Request planning assistance." };
const textHash = (value: string) => hash(value.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim()); const sections = (value: string) => [...value.matchAll(/<section\b[^>]*>/gi)].map((item) => item[0]); const grid = (value: string) => value.match(/\.saw-product\{[^}]*grid-template-columns:([^;}]+)/)?.[1]?.trim() ?? null; const contrast = (value: string) => hash([...value.matchAll(/data-genesis-(?:background|heading)[^=]*="[^"]+"|GENESIS_(?:BACKGROUND_AWARE_TEXT_CONTRAST|DURABLE_HEADING_CONTRAST)_V1|\[data-genesis-background-luminance[^}]+\}/g)].map((item) => item[0]).join("|"));
type Principal = { principalId: string; sessionId: string }; type State = { receipts: Record<string, unknown>[] }; const seed = (): State => ({ receipts: [] });
function save(receipt: Record<string, unknown>) { for (let attempt = 0; attempt < 8; attempt += 1) { const loaded = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); try { savePersistedState({ namespace: NAMESPACE, state: { receipts: [...loaded.state.receipts, receipt] }, expectedRevision: loaded.revision }); return deepClone(receipt); } catch (error) { if (!(error instanceof FoundationPersistenceConflictError) || attempt === 7) throw error; } } throw new Error("SAN_ANTONIO_LINK_REMEDIATION_CAS_EXHAUSTED"); }
export const getSanAntonioBrokenNavigationRemediationState = () => deepClone(loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }).state);
async function validateNavigation(html: string) { const discovered = discoverPublicHostLinks({ html, documentUrl: "https://projectorenclosure.com/fan-cooled-projector-enclosures/texas/san-antonio/", internalHosts: ["projectorenclosure.com", "www.projectorenclosure.com"] }); const statuses = new Map<string, number>(); for (const url of [...new Set(discovered.filter((item) => item.validationPolicy === "VALIDATE_INTERNAL_NAVIGATION" && item.resolvedUrl).map((item) => item.resolvedUrl!))]) { const response = await fetch(url, { redirect: "follow", cache: "no-store", signal: AbortSignal.timeout(30_000) }); statuses.set(url, response.status); } const evaluated = discovered.map((item) => item.resolvedUrl && statuses.has(item.resolvedUrl) ? applyPublicHostLinkStatus(item, statuses.get(item.resolvedUrl)!) : item); return { evaluated, navigationalLinksEvaluated: evaluated.filter((item) => item.validationPolicy === "VALIDATE_INTERNAL_NAVIGATION").length, actualNavigationalBrokenLinks: evaluated.filter((item) => ["VALIDATE_INTERNAL_NAVIGATION", "FAIL_INVALID_NAVIGATION"].includes(item.validationPolicy) && item.result !== "PASS").length, devLinks: evaluated.filter((item) => item.reason === "DEVELOPMENT_TARGET").length, previewLinks: evaluated.filter((item) => item.reason === "PREVIEW_OR_ADMIN_TARGET").length }; }

export async function applySanAntonioBrokenNavigationRemediationUpdate(input: { principal: Principal }) {
  const existing = getSanAntonioBrokenNavigationRemediationState().receipts.at(-1); if (existing) return { receipt: existing, reused: true }; const principal = { principalId: input.principal.principalId.trim(), sessionId: input.principal.sessionId.trim() }; if (!principal.principalId || !principal.sessionId) throw new Error("SAN_ANTONIO_LINK_REMEDIATION_PRINCIPAL_REQUIRED"); const before = await inspectSanAntonioWordPressDraft("13103"); const job = await glwPageExecutionRepository.getById("f518ffb7-9216-4866-a93c-7f4793e74038"); const site = getSiteById("site-ssi-projectorenclosure"); if (!site || !job?.generatedDraft || before.identity.status !== "draft" || before.identity.slug !== "san-antonio" || before.identity.parent !== 13083 || before.identity.template !== "elementor_header_footer" || before.featuredMediaId !== 10757 || before.authority !== "POST_CONTENT" || before.elementorDataPresent || before.hash !== SAN_ANTONIO_BROKEN_NAVIGATION_BEFORE_HASH) throw new Error("SAN_ANTONIO_LINK_REMEDIATION_PREFLIGHT_FAILED");
  const repaired = applySanAntonioBrokenNavigationRemediation(before.raw); if (removeSanAntonioBrokenNavigationRemediation(repaired) !== before.raw) throw new Error("SAN_ANTONIO_LINK_REMEDIATION_NOT_REVERSIBLE"); const destinationChecks = []; for (const item of SAN_ANTONIO_LINK_REMEDIATIONS) { if (!item.newHref) { destinationChecks.push({ ...item, status: null, semanticMatch: true }); continue; } const response = await fetch(new URL(item.newHref, "https://projectorenclosure.com/"), { redirect: "follow", cache: "no-store", signal: AbortSignal.timeout(30_000) }); destinationChecks.push({ ...item, status: response.status, semanticMatch: response.status === 200 }); } if (destinationChecks.some((item) => item.newHref && (item.status !== 200 || !item.semanticMatch))) throw new Error("SAN_ANTONIO_LINK_REMEDIATION_DESTINATION_STALE"); const navigation = await validateNavigation(repaired); if (navigation.actualNavigationalBrokenLinks || navigation.devLinks || navigation.previewLinks) throw new Error("SAN_ANTONIO_LINK_REMEDIATION_VALIDATION_FAILED");
  const beforeProof = { text: textHash(before.raw), sections: sections(before.raw), media: before.mediaUrls, seo: hash(JSON.stringify(before.seo.stored)), grid: grid(before.raw), contrast: contrast(before.raw) }; const write = await writeGenesisWordPressDraft({ operation: "UPDATE", site, wordpressObjectId: "13103", artifact: { title: before.identity.title, slug: "fan-cooled-projector-enclosures/texas/san-antonio", excerpt: job.generatedDraft.excerpt, contentHtml: repaired, parentId: 13083, seo: SEO } }); if (!write.ok) throw new Error(`SAN_ANTONIO_LINK_REMEDIATION_WRITE_FAILED:${write.state}`); const after = await inspectSanAntonioWordPressDraft("13103"); const afterProof = { text: textHash(after.raw), sections: sections(after.raw), media: after.mediaUrls, seo: hash(JSON.stringify(after.seo.stored)), grid: grid(after.raw), contrast: contrast(after.raw) }; if (after.identity.status !== "draft" || after.identity.slug !== before.identity.slug || after.identity.parent !== before.identity.parent || after.identity.template !== before.identity.template || after.featuredMediaId !== before.featuredMediaId || after.authority !== "POST_CONTENT" || after.elementorDataPresent || after.hash !== hash(repaired) || JSON.stringify(beforeProof) !== JSON.stringify(afterProof) || removeSanAntonioBrokenNavigationRemediation(after.raw) !== before.raw) throw new Error("SAN_ANTONIO_LINK_REMEDIATION_READBACK_FAILED"); const receipt = { receiptId: `san-antonio-broken-navigation-remediation-${randomUUID()}`, operation: SAN_ANTONIO_BROKEN_NAVIGATION_REMEDIATION_OPERATION, principal, wordpressObjectId: "13103", wordpressStatus: "draft", beforeHash: SAN_ANTONIO_BROKEN_NAVIGATION_BEFORE_HASH, afterHash: after.hash, artifactSha: SAN_ANTONIO_APPROVED_ARTIFACT_SHA, approvedCompositionCommit: SAN_ANTONIO_APPROVED_COMPOSITION_COMMIT, remediations: destinationChecks, navigation, linkOnlyMutationProven: true, copyPreserved: true, sectionSequencePreserved: true, mediaPreserved: true, seoIdentityPreserved: true, canonicalPreserved: true, slugPreserved: true, featuredMediaPreserved: true, geometryPreserved: true, contrastAuthorityPreserved: true, publicationMutation: false, contentRegenerated: false, mediaRegenerated: false, workflowExecuted: false, newDispatch: false, createdAt: new Date().toISOString() }; return { receipt: save(receipt), reused: false };
}