import "server-only";

import { createHash, randomUUID } from "node:crypto";
import { deepClone, FoundationPersistenceConflictError, loadPersistedState, savePersistedState } from "@/modules/foundation/foundation-persistence";
import { getSiteById } from "@/modules/foundation/site-repository";
import { writeGenesisWordPressDraft } from "@/modules/foundation/wordpress-draft-writer";
import { GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT } from "@/modules/foundation/background-aware-text-contrast";
import { glwPageExecutionRepository } from "./page-execution-repository";
import { SAN_ANTONIO_APPROVED_ARTIFACT_SHA, SAN_ANTONIO_APPROVED_COMPOSITION_COMMIT } from "./san-antonio-wordpress-staging-authority";
import { inspectSanAntonioWordPressDraft } from "./san-antonio-wordpress-staging-service";
import { getSanAntonioHeroContrastState } from "./san-antonio-hero-contrast-repair-service";
import { applyBackgroundAwareContrastToSanAntonio, removeBackgroundAwareContrastFromSanAntonio, SAN_ANTONIO_SYSTEMIC_CONTRAST_BEFORE_HASH, SAN_ANTONIO_SYSTEMIC_CONTRAST_OPERATION } from "./san-antonio-background-aware-contrast-repair";

const NAMESPACE = "glw-san-antonio-background-aware-contrast-v1";
const SEO = { focusKeyphrase: "fan cooled projector enclosures San Antonio", seoTitle: "Fan Cooled Projector Enclosures San Antonio Texas", metaDescription: "Discover fan cooled projector enclosures San Antonio Texas for commercial AV protection. Learn about airflow, selection, and maintenance. Request planning assistance." };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const textHash = (value: string) => hash(value.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
const sectionSequence = (value: string) => [...value.matchAll(/<section\b[^>]*(?:id="([^"]+)")?[^>]*(?:data-media-role="([^"]+)")?[^>]*>/gi)].map((match) => match[1] || match[2] || "section");
type Principal = { principalId: string; sessionId: string };
export type SanAntonioBackgroundAwareContrastReceipt = { receiptId: string; operation: typeof SAN_ANTONIO_SYSTEMIC_CONTRAST_OPERATION; contract: typeof GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT; principal: Principal; wordpressObjectId: "13103"; wordpressStatus: "draft"; beforeHash: typeof SAN_ANTONIO_SYSTEMIC_CONTRAST_BEFORE_HASH; afterHash: string; artifactSha: typeof SAN_ANTONIO_APPROVED_ARTIFACT_SHA; approvedCompositionCommit: typeof SAN_ANTONIO_APPROVED_COMPOSITION_COMMIT; copyHashBefore: string; copyHashAfter: string; sectionSequenceBefore: string[]; sectionSequenceAfter: string[]; mediaUrlsBefore: string[]; mediaUrlsAfter: string[]; featuredMediaBefore: 10757; featuredMediaAfter: 10757; seoHashBefore: string; seoHashAfter: string; contrastOnlyMutationProven: true; contentRegenerated: false; mediaRegenerated: false; workflowExecuted: false; dispatchPerformed: false; publicationPerformed: false; createdAt: string };
type State = { receipts: SanAntonioBackgroundAwareContrastReceipt[] };
const seed = (): State => ({ receipts: [] });
function save<T>(mutate: (state: State) => { state: State; value: T }): T { for (let attempt = 0; attempt < 8; attempt += 1) { const loaded = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); const result = mutate(deepClone(loaded.state)); try { savePersistedState({ namespace: NAMESPACE, state: result.state, expectedRevision: loaded.revision }); return result.value; } catch (error) { if (!(error instanceof FoundationPersistenceConflictError) || attempt === 7) throw error; } } throw new Error("SAN_ANTONIO_SYSTEMIC_CONTRAST_CAS_EXHAUSTED"); }
export function getSanAntonioBackgroundAwareContrastState() { return deepClone(loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }).state); }

export async function applySanAntonioBackgroundAwareContrast(input: { principal: Principal }) {
  const existing = getSanAntonioBackgroundAwareContrastState().receipts.at(-1); if (existing) return { receipt: existing, reused: true };
  const principal = { principalId: input.principal.principalId.trim(), sessionId: input.principal.sessionId.trim() }; if (!principal.principalId || !principal.sessionId) throw new Error("SAN_ANTONIO_SYSTEMIC_CONTRAST_PRINCIPAL_REQUIRED");
  const heroReceipt = getSanAntonioHeroContrastState().receipts.at(-1); const job = await glwPageExecutionRepository.getById("f518ffb7-9216-4866-a93c-7f4793e74038"); const site = getSiteById("site-ssi-projectorenclosure"); const before = await inspectSanAntonioWordPressDraft("13103");
  if (!heroReceipt || !job?.generatedDraft || !site || heroReceipt.afterHash !== SAN_ANTONIO_SYSTEMIC_CONTRAST_BEFORE_HASH || before.identity.status !== "draft" || before.identity.slug !== "san-antonio" || before.identity.parent !== 13083 || before.identity.template !== "elementor_header_footer" || before.featuredMediaId !== 10757 || before.authority !== "POST_CONTENT" || before.elementorDataPresent || before.hash !== SAN_ANTONIO_SYSTEMIC_CONTRAST_BEFORE_HASH || before.h1Count !== 1) throw new Error("SAN_ANTONIO_SYSTEMIC_CONTRAST_PREFLIGHT_FAILED");
  const repaired = applyBackgroundAwareContrastToSanAntonio(before.raw); if (removeBackgroundAwareContrastFromSanAntonio(repaired) !== before.raw) throw new Error("SAN_ANTONIO_SYSTEMIC_CONTRAST_NOT_REVERSIBLE");
  const copyBefore = textHash(before.raw); const sequenceBefore = sectionSequence(before.raw); const mediaBefore = [...before.mediaUrls]; const seoBefore = hash(JSON.stringify(before.seo.stored));
  const write = await writeGenesisWordPressDraft({ operation: "UPDATE", site, wordpressObjectId: "13103", artifact: { title: before.identity.title, slug: "fan-cooled-projector-enclosures/texas/san-antonio", excerpt: job.generatedDraft.excerpt, contentHtml: repaired, parentId: 13083, seo: SEO } }); if (!write.ok) throw new Error(`SAN_ANTONIO_SYSTEMIC_CONTRAST_WRITE_FAILED:${write.state}`);
  const after = await inspectSanAntonioWordPressDraft("13103"); const afterHash = hash(repaired.trim()); const copyAfter = textHash(after.raw); const sequenceAfter = sectionSequence(after.raw); const mediaAfter = [...after.mediaUrls]; const seoAfter = hash(JSON.stringify(after.seo.stored));
  if (after.identity.status !== "draft" || after.identity.slug !== before.identity.slug || after.identity.parent !== before.identity.parent || after.identity.template !== before.identity.template || after.featuredMediaId !== before.featuredMediaId || after.authority !== before.authority || after.elementorDataPresent || after.hash !== afterHash || after.h1Count !== before.h1Count || copyAfter !== copyBefore || JSON.stringify(sequenceAfter) !== JSON.stringify(sequenceBefore) || JSON.stringify(mediaAfter) !== JSON.stringify(mediaBefore) || seoAfter !== seoBefore || removeBackgroundAwareContrastFromSanAntonio(after.raw) !== before.raw || !after.raw.includes(GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT)) throw new Error("SAN_ANTONIO_SYSTEMIC_CONTRAST_READBACK_FAILED");
  const receipt: SanAntonioBackgroundAwareContrastReceipt = { receiptId: `san-antonio-systemic-contrast-${randomUUID()}`, operation: SAN_ANTONIO_SYSTEMIC_CONTRAST_OPERATION, contract: GENESIS_BACKGROUND_AWARE_TEXT_CONTRAST_CONTRACT, principal, wordpressObjectId: "13103", wordpressStatus: "draft", beforeHash: SAN_ANTONIO_SYSTEMIC_CONTRAST_BEFORE_HASH, afterHash, artifactSha: SAN_ANTONIO_APPROVED_ARTIFACT_SHA, approvedCompositionCommit: SAN_ANTONIO_APPROVED_COMPOSITION_COMMIT, copyHashBefore: copyBefore, copyHashAfter: copyAfter, sectionSequenceBefore: sequenceBefore, sectionSequenceAfter: sequenceAfter, mediaUrlsBefore: mediaBefore, mediaUrlsAfter: mediaAfter, featuredMediaBefore: 10757, featuredMediaAfter: 10757, seoHashBefore: seoBefore, seoHashAfter: seoAfter, contrastOnlyMutationProven: true, contentRegenerated: false, mediaRegenerated: false, workflowExecuted: false, dispatchPerformed: false, publicationPerformed: false, createdAt: new Date().toISOString() };
  return { receipt: save((state) => ({ state: { receipts: [...state.receipts, receipt] }, value: deepClone(receipt) })), reused: false };
}