import "server-only";

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { captureGovernedRenderedPage } from "@/modules/foundation/governed-render-capture-browser";
import { resolvePersistenceRoot } from "@/modules/foundation/foundation-persistence";
import { signGovernedSnapshotPath } from "@/modules/foundation/governed-render-capture-orchestrator";
import { getSanAntonioStagingState } from "./san-antonio-wordpress-staging-authority";
import { getSanAntonioNativeRepairState, saveSanAntonioNativeRepairCertification, type SanAntonioNativeRepairCapture } from "./san-antonio-native-wordpress-render-repair-service";

const VIEWPORTS = [{ viewport: "DESKTOP_1440" as const, width: 1440, height: 1024, viewportClass: "DESKTOP" as const }, { viewport: "DESKTOP_1024" as const, width: 1024, height: 900, viewportClass: "DESKTOP" as const }, { viewport: "TABLET_768" as const, width: 768, height: 1024, viewportClass: "DESKTOP" as const }, { viewport: "MOBILE_375" as const, width: 375, height: 812, viewportClass: "MOBILE" as const }];
const sha = (value: Uint8Array | string) => createHash("sha256").update(value).digest("hex");

function store(receiptId: string, captureId: string, bytes: Uint8Array, width: number, height: number) { const reference = `san-antonio-native-render-artifacts/${receiptId}/${captureId}.png`; const path = join(resolvePersistenceRoot(), ...reference.split("/")); const digest = sha(bytes); mkdirSync(dirname(path), { recursive: true }); if (existsSync(path) && sha(readFileSync(path)) !== digest) throw new Error("SAN_ANTONIO_NATIVE_CAPTURE_COLLISION"); if (!existsSync(path)) writeFileSync(path, bytes); return { reference, sha256: digest, width, height }; }
export function readSanAntonioNativeRepairCapture(reference: string) { if (!reference.startsWith("san-antonio-native-render-artifacts/") || reference.includes("..")) throw new Error("SAN_ANTONIO_NATIVE_CAPTURE_REFERENCE_INVALID"); return readFileSync(join(resolvePersistenceRoot(), ...reference.split("/"))); }

export async function captureSanAntonioNativeWordPressRepair() {
  const repair = getSanAntonioNativeRepairState(); const receipt = repair.receipts.at(-1); if (!receipt) throw new Error("SAN_ANTONIO_NATIVE_REPAIR_RECEIPT_REQUIRED"); const certificationId = `san-antonio-native-render-certification-v1_1-${receipt.receiptId}`; const existing = repair.certifications.find((item) => item.certificationId === certificationId); if (existing) return { certification: existing, reused: true };
  const staging = getSanAntonioStagingState(); const stagingReceipt = staging.receipts.at(-1); if (!stagingReceipt || stagingReceipt.wordpressObjectId !== "13103") throw new Error("SAN_ANTONIO_STAGING_RECEIPT_REQUIRED");
  const assignments = [{ assignmentId: "wordpress-media:10757", semanticRole: "PRODUCT_AUTHORITY" as const, mediaId: "10757", sourceUrl: "https://projectorenclosure.com/wp-content/uploads/2024/03/Integrator-scaled-1.webp", contextId: "DOCUMENTARY" }, ...stagingReceipt.uploadedMedia.map((item) => ({ assignmentId: `wordpress-media:${item.mediaId}`, semanticRole: item.role as "CONTEXTUAL_IN_USE" | "APPLICATION_EXPERIENCE" | "LOCAL_CONTEXTUAL_ATMOSPHERE", mediaId: String(item.mediaId), sourceUrl: item.url, contextId: item.claimClass }))];
  const origin = new URL(process.env.GENESIS_RENDER_CAPTURE_INTERNAL_ORIGIN?.trim() || "http://localhost:3003").origin; const pathname = "/api/glw/pages/f518ffb7-9216-4866-a93c-7f4793e74038/native-wordpress-render-snapshot"; const query = "organizationId=ssi&siteId=site-ssi-projectorenclosure"; const signedPath = `${pathname}?${query}`; const captures: SanAntonioNativeRepairCapture[] = [];
  for (const viewport of VIEWPORTS) { const captureId = `${receipt.receiptId}-v1_1-${viewport.viewport.toLowerCase()}`; const result = await captureGovernedRenderedPage({ targetUrl: `${origin}${signedPath}`, allowedOrigins: [origin, "https://projectorenclosure.com", "https://fonts.googleapis.com", "https://fonts.gstatic.com"], internalGenesisOrigin: origin, internalAuthorization: { header: "x-genesis-render-capture", value: signGovernedSnapshotPath(signedPath) }, viewportClass: viewport.viewportClass, viewport: { width: viewport.width, height: viewport.height }, captureId, mediaAssignments: assignments }); const product = result.evidence.sections.find((item) => item.sectionId === "product-authority"); const contextual = result.evidence.sections.find((item) => item.sectionId === "contextual-in-use"); const rich = result.themeIntegration.richComposition; if (!product?.mediaBounds || !product.contentBounds || !product.headingLineCount || !contextual?.headingLineCount || !rich?.productImageBounds || !rich.productCopyBounds || !rich.contextualCopyBounds) throw new Error(`SAN_ANTONIO_NATIVE_GEOMETRY_MISSING:${viewport.viewport}`); const artifact = store(receipt.receiptId, captureId, result.bytes, result.imageWidth, result.imageHeight); captures.push({ viewport: viewport.viewport, width: viewport.width, height: viewport.height, horizontalOverflow: result.evidence.horizontalOverflow, visibleH1Count: result.themeIntegration.visibleH1Count, duplicateThemeTitleVisible: result.themeIntegration.duplicateThemeTitleVisible, duplicateThemeFeaturedMediaVisible: result.themeIntegration.duplicateThemeFeaturedMediaVisible, globalHeaderPresent: result.themeIntegration.globalHeaderPresent, globalFooterPresent: result.themeIntegration.globalFooterPresent, productSectionWidth: product.bounds.width, productMediaWidth: rich.productImageBounds.width, productCopyWidth: rich.productCopyBounds.width, productMediaRatio: rich.productImageBounds.width / product.bounds.width, productImageAspectRatio: rich.productImageBounds.width / rich.productImageBounds.height, productGridColumns: rich.productGridColumns, productHeadingLineCount: product.headingLineCount, productHeadingMaxWordFragments: rich.productHeadingMaxWordFragments, productHeadingWordBreak: rich.productHeadingWordBreak, productHeadingHyphens: rich.productHeadingHyphens, contextualHeadingLineCount: contextual.headingLineCount, contextualHeadingMaxWordFragments: rich.contextualHeadingMaxWordFragments, contextualCopyWidth: rich.contextualCopyBounds.width, mediaRendered: result.evidence.media.filter((item) => item.rendered).length, artifact, capturedAt: result.evidence.capturedAt }); }
  const failures: string[] = []; for (const capture of captures) { if (capture.horizontalOverflow !== 0) failures.push(`${capture.viewport}_OVERFLOW`); if (capture.visibleH1Count !== 1) failures.push(`${capture.viewport}_H1`); if (capture.duplicateThemeTitleVisible) failures.push(`${capture.viewport}_THEME_TITLE`); if (capture.duplicateThemeFeaturedMediaVisible) failures.push(`${capture.viewport}_THEME_MEDIA`); if (!capture.globalHeaderPresent || !capture.globalFooterPresent) failures.push(`${capture.viewport}_SHELL`); if (capture.mediaRendered !== 4) failures.push(`${capture.viewport}_MEDIA`); if (Math.abs(capture.productImageAspectRatio - 20 / 9) > .02) failures.push(`${capture.viewport}_PRODUCT_ASPECT`); if (capture.productHeadingMaxWordFragments > 1 || capture.contextualHeadingMaxWordFragments > 1 || capture.productHeadingWordBreak !== "normal" || !["none", "manual"].includes(capture.productHeadingHyphens)) failures.push(`${capture.viewport}_TYPOGRAPHY`); const desktop = capture.viewport === "DESKTOP_1440" || capture.viewport === "DESKTOP_1024"; if (desktop && (capture.productMediaRatio < .5 || capture.productMediaRatio > .6 || capture.productCopyWidth < 320)) failures.push(`${capture.viewport}_PRODUCT_GEOMETRY`); if (!desktop && (capture.productMediaRatio < .9 || capture.productCopyWidth < capture.width - 50)) failures.push(`${capture.viewport}_PRODUCT_STACK`); if (capture.contextualCopyWidth < Math.min(320, capture.width - 50)) failures.push(`${capture.viewport}_CONTEXT_MEASURE`); }
  const certification = saveSanAntonioNativeRepairCertification({ certificationId, receiptId: receipt.receiptId, captureAuthority: "SIGNED_INTERNAL_EQUIVALENT_USING_LIVE_SSI_HEADER_FOOTER_SHELL", nativePreviewAutomationAvailable: false, nativePreviewCertificationClaimed: false, captures, state: failures.length ? "FAIL" : "PASS", failures, ownerPreviewRequired: true, publicationPerformed: false, createdAt: new Date().toISOString() }); return { certification, reused: false };
}