import "server-only";

import { randomUUID } from "node:crypto";
import { deepClone, FoundationPersistenceConflictError, loadPersistedState, savePersistedState } from "@/modules/foundation/foundation-persistence";
import type { PublicVerifierFetchEvidence } from "@/modules/foundation/public-verifier-fetch-observability";

export const SAN_ANTONIO_FINAL_PUBLICATION_OPERATION = "SAN_ANTONIO_FINAL_PUBLICATION_V1" as const;
export const SAN_ANTONIO_FINAL_PUBLICATION_HASH = "fb5ad5ab311b5bc3c18ad9921efb88dd765171ff5cd69edab5d743ac8a4e05a2" as const;
export const SAN_ANTONIO_FINAL_PUBLIC_URL = "https://projectorenclosure.com/fan-cooled-projector-enclosures/texas/san-antonio/" as const;
export const SAN_ANTONIO_OWNER_APPROVAL = "CURRENT_NATIVE_WORDPRESS_PREVIEW_VISUALLY_APPROVED" as const;
const NAMESPACE = "glw-san-antonio-final-publication-v1";
type Principal = { principalId: string; sessionId: string };
export type SanAntonioPublicationAuthority = { authorityId: string; operation: typeof SAN_ANTONIO_FINAL_PUBLICATION_OPERATION; wordpressObjectId: "13103"; targetId: string; storedHash: typeof SAN_ANTONIO_FINAL_PUBLICATION_HASH; ownerApproval: typeof SAN_ANTONIO_OWNER_APPROVAL; principal: Principal; createdAt: string; expiresAt: string; consumedAt: string | null; consumedByReceiptId: string | null };
type State = { authorities: Omit<SanAntonioPublicationAuthority, "consumedAt" | "consumedByReceiptId">[]; consumptions: { authorityId: string; receiptId: string; consumedAt: string }[]; records: Record<string, unknown>[]; fetchEvidence: PublicVerifierFetchEvidence[] };
const seed = (): State => ({ authorities: [], consumptions: [], records: [], fetchEvidence: [] });
const load = () => { const loaded = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); return { ...loaded, state: { ...seed(), ...loaded.state, fetchEvidence: loaded.state.fetchEvidence ?? [] } }; };
function mutate<T>(change: (state: State) => T): T { for (let attempt = 0; attempt < 8; attempt += 1) { const loaded = load(); const state = deepClone(loaded.state); const value = change(state); try { savePersistedState({ namespace: NAMESPACE, state, expectedRevision: loaded.revision }); return value; } catch (error) { if (!(error instanceof FoundationPersistenceConflictError) || attempt === 7) throw error; } } throw new Error("SAN_ANTONIO_PUBLICATION_CAS_EXHAUSTED"); }
export const getSanAntonioFinalPublicationState = () => { const state = load().state; return { ...deepClone(state), authorities: state.authorities.map((item) => { const use = state.consumptions.find((entry) => entry.authorityId === item.authorityId); return { ...deepClone(item), consumedAt: use?.consumedAt ?? null, consumedByReceiptId: use?.receiptId ?? null }; }) }; };
export function createSanAntonioPublicationAuthority(input: { principal: Principal }) { const now = new Date(); const principal = { principalId: input.principal.principalId.trim(), sessionId: input.principal.sessionId.trim() }; if (!principal.principalId || !principal.sessionId) throw new Error("SAN_ANTONIO_PUBLICATION_PRINCIPAL_REQUIRED"); const authority = { authorityId: `san-antonio-final-publication-authority-${randomUUID()}`, operation: SAN_ANTONIO_FINAL_PUBLICATION_OPERATION, wordpressObjectId: "13103" as const, targetId: "target-campaign-ssi-site-ssi-projectorenclosure-fan-cooled-projector-enclosures-texas-cities-tx-san-antonio", storedHash: SAN_ANTONIO_FINAL_PUBLICATION_HASH, ownerApproval: SAN_ANTONIO_OWNER_APPROVAL, principal, createdAt: now.toISOString(), expiresAt: new Date(now.getTime() + 5 * 60_000).toISOString() }; return mutate((state) => { state.authorities.push(authority); return { ...deepClone(authority), consumedAt: null, consumedByReceiptId: null } satisfies SanAntonioPublicationAuthority; }); }
export function consumeSanAntonioPublicationAuthority(input: { authorityId: string; receiptId: string; principal: Principal }) { return mutate((state) => { const authority = state.authorities.find((item) => item.authorityId === input.authorityId); if (!authority || state.consumptions.some((item) => item.authorityId === authority.authorityId) || new Date(authority.expiresAt) <= new Date() || authority.principal.principalId !== input.principal.principalId || authority.principal.sessionId !== input.principal.sessionId) throw new Error("SAN_ANTONIO_PUBLICATION_AUTHORITY_INVALID_OR_CONSUMED"); const consumedAt = new Date().toISOString(); state.consumptions.push({ authorityId: authority.authorityId, receiptId: input.receiptId, consumedAt }); return { ...deepClone(authority), consumedAt, consumedByReceiptId: input.receiptId } satisfies SanAntonioPublicationAuthority; }); }
export function saveSanAntonioPublicationRecord(record: Record<string, unknown>) { return mutate((state) => { state.records.push(deepClone(record)); return deepClone(record); }); }
export function appendSanAntonioVerifierFetchEvidence(evidence: PublicVerifierFetchEvidence) { return mutate((state) => { if (state.fetchEvidence.some((item) => item.eventId === evidence.eventId)) throw new Error("SAN_ANTONIO_FETCH_EVIDENCE_DUPLICATE"); state.fetchEvidence.push(deepClone(evidence)); return deepClone(evidence); }); }