import "server-only";

import { createHash, randomUUID } from "node:crypto";
import { GENESIS_DURABLE_HEADING_CONTRAST_CONTRACT, GENESIS_DURABLE_HEADING_CONTRAST_CSS } from "@/modules/foundation/background-aware-text-contrast";
import { deepClone, FoundationPersistenceConflictError, loadPersistedState, savePersistedState } from "@/modules/foundation/foundation-persistence";
import { getSiteById } from "@/modules/foundation/site-repository";
import { writeGenesisWordPressDraft } from "@/modules/foundation/wordpress-draft-writer";
import { glwPageExecutionRepository } from "./page-execution-repository";
import { applyDurableHeadingContrastToSanAntonio, removeDurableHeadingContrastFromSanAntonio, SAN_ANTONIO_DURABLE_HEADING_CONTRAST_BEFORE_HASH, SAN_ANTONIO_DURABLE_HEADING_CONTRAST_OPERATION } from "./san-antonio-background-aware-contrast-repair";
import { inspectSanAntonioWordPressDraft } from "./san-antonio-wordpress-staging-service";

const NAMESPACE = "glw-san-antonio-durable-heading-contrast-v1";
const SEO = { focusKeyphrase: "fan cooled projector enclosures San Antonio", seoTitle: "Fan Cooled Projector Enclosures San Antonio Texas", metaDescription: "Discover fan cooled projector enclosures San Antonio Texas for commercial AV protection. Learn about airflow, selection, and maintenance. Request planning assistance." };
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const textHash = (value: string) => hash(value.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
const sectionSequence = (value: string) => [...value.matchAll(/<section\b[^>]*(?:id="([^"]+)")?[^>]*(?:data-media-role="([^"]+)")?[^>]*>/gi)].map((match) => match[1] || match[2] || "section");
const headingMarkup = (value: string, role: "CONTEXTUAL_IN_USE" | "APPLICATION_EXPERIENCE") => value.match(new RegExp(`<section\\b(?=[^>]*data-media-role="${role}")[^>]*>[\\s\\S]*?(<h2\\b[^>]*>)`, "i"))?.[1] ?? null;
const productGrid = (value: string) => value.match(/\.saw-product\{[^}]*grid-template-columns:([^;}]+)/)?.[1]?.trim() ?? null;
type Principal = { principalId: string; sessionId: string };
export type SanAntonioDurableHeadingContrastReceipt = { receiptId: string; operation: typeof SAN_ANTONIO_DURABLE_HEADING_CONTRAST_OPERATION; contract: typeof GENESIS_DURABLE_HEADING_CONTRAST_CONTRACT; principal: Principal; wordpressObjectId: "13103"; wordpressStatus: "draft"; beforeHash: typeof SAN_ANTONIO_DURABLE_HEADING_CONTRAST_BEFORE_HASH; afterHash: string; productContextH2MarkupBefore: string; productContextH2MarkupAfter: string; applicationH2MarkupBefore: string; applicationH2MarkupAfter: string; rule: typeof GENESIS_DURABLE_HEADING_CONTRAST_CSS; copyHashBefore: string; copyHashAfter: string; sectionSequenceBefore: string[]; sectionSequenceAfter: string[]; mediaUrlsBefore: string[]; mediaUrlsAfter: string[]; seoHashBefore: string; seoHashAfter: string; productGridBefore: string; productGridAfter: string; featuredMediaBefore: 10757; featuredMediaAfter: 10757; contrastOnlyMutationProven: true; contentRegenerated: false; mediaRegenerated: false; workflowExecuted: false; dispatchPerformed: false; publicationPerformed: false; createdAt: string };
type State = { receipts: SanAntonioDurableHeadingContrastReceipt[] };
const seed = (): State => ({ receipts: [] });
function save(receipt: SanAntonioDurableHeadingContrastReceipt) { for (let attempt = 0; attempt < 8; attempt += 1) { const loaded = loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }); try { savePersistedState({ namespace: NAMESPACE, state: { receipts: [...loaded.state.receipts, receipt] }, expectedRevision: loaded.revision }); return deepClone(receipt); } catch (error) { if (!(error instanceof FoundationPersistenceConflictError) || attempt === 7) throw error; } } throw new Error("SAN_ANTONIO_DURABLE_HEADING_CONTRAST_CAS_EXHAUSTED"); }
export function getSanAntonioDurableHeadingContrastState() { return deepClone(loadPersistedState<State>({ namespace: NAMESPACE, seedFactory: seed }).state); }

export async function applySanAntonioDurableHeadingContrast(input: { principal: Principal }) {
  const existing = getSanAntonioDurableHeadingContrastState().receipts.at(-1); if (existing) return { receipt: existing, reused: true };
  const principal = { principalId: input.principal.principalId.trim(), sessionId: input.principal.sessionId.trim() }; if (!principal.principalId || !principal.sessionId) throw new Error("SAN_ANTONIO_DURABLE_HEADING_CONTRAST_PRINCIPAL_REQUIRED");
  const job = await glwPageExecutionRepository.getById("f518ffb7-9216-4866-a93c-7f4793e74038"); const site = getSiteById("site-ssi-projectorenclosure"); const before = await inspectSanAntonioWordPressDraft("13103");
  const productBefore = headingMarkup(before.raw, "CONTEXTUAL_IN_USE"); const applicationBefore = headingMarkup(before.raw, "APPLICATION_EXPERIENCE");
  if (!job?.generatedDraft || !site || before.identity.status !== "draft" || before.identity.slug !== "san-antonio" || before.identity.parent !== 13083 || before.identity.template !== "elementor_header_footer" || before.featuredMediaId !== 10757 || before.authority !== "POST_CONTENT" || before.elementorDataPresent || before.hash !== SAN_ANTONIO_DURABLE_HEADING_CONTRAST_BEFORE_HASH || before.h1Count !== 1 || !productBefore || !applicationBefore) throw new Error("SAN_ANTONIO_DURABLE_HEADING_CONTRAST_PREFLIGHT_FAILED");
  const repaired = applyDurableHeadingContrastToSanAntonio(before.raw); const reversed = removeDurableHeadingContrastFromSanAntonio(repaired); const productAfter = headingMarkup(repaired, "CONTEXTUAL_IN_USE"); const applicationAfter = headingMarkup(repaired, "APPLICATION_EXPERIENCE");
  if (reversed !== before.raw || !productAfter?.includes('data-genesis-heading-authority="governed"') || !applicationAfter?.includes('data-genesis-heading-authority="governed"') || !repaired.includes(GENESIS_DURABLE_HEADING_CONTRAST_CSS)) throw new Error("SAN_ANTONIO_DURABLE_HEADING_CONTRAST_PROOF_FAILED");
  const copyBefore = textHash(before.raw); const sequenceBefore = sectionSequence(before.raw); const mediaBefore = [...before.mediaUrls]; const seoBefore = hash(JSON.stringify(before.seo.stored)); const gridBefore = productGrid(before.raw);
  const write = await writeGenesisWordPressDraft({ operation: "UPDATE", site, wordpressObjectId: "13103", artifact: { title: before.identity.title, slug: "fan-cooled-projector-enclosures/texas/san-antonio", excerpt: job.generatedDraft.excerpt, contentHtml: repaired, parentId: 13083, seo: SEO } }); if (!write.ok) throw new Error(`SAN_ANTONIO_DURABLE_HEADING_CONTRAST_WRITE_FAILED:${write.state}`);
  const after = await inspectSanAntonioWordPressDraft("13103"); const afterHash = hash(repaired.trim()); const copyAfter = textHash(after.raw); const sequenceAfter = sectionSequence(after.raw); const mediaAfter = [...after.mediaUrls]; const seoAfter = hash(JSON.stringify(after.seo.stored)); const gridAfter = productGrid(after.raw);
  if (after.identity.status !== "draft" || after.identity.slug !== before.identity.slug || after.identity.parent !== before.identity.parent || after.identity.template !== before.identity.template || after.featuredMediaId !== before.featuredMediaId || after.authority !== "POST_CONTENT" || after.elementorDataPresent || after.hash !== afterHash || after.h1Count !== before.h1Count || copyAfter !== copyBefore || JSON.stringify(sequenceAfter) !== JSON.stringify(sequenceBefore) || JSON.stringify(mediaAfter) !== JSON.stringify(mediaBefore) || seoAfter !== seoBefore || gridAfter !== gridBefore || removeDurableHeadingContrastFromSanAntonio(after.raw) !== before.raw) throw new Error("SAN_ANTONIO_DURABLE_HEADING_CONTRAST_READBACK_FAILED");
  const receipt: SanAntonioDurableHeadingContrastReceipt = { receiptId: `san-antonio-durable-heading-contrast-${randomUUID()}`, operation: SAN_ANTONIO_DURABLE_HEADING_CONTRAST_OPERATION, contract: GENESIS_DURABLE_HEADING_CONTRAST_CONTRACT, principal, wordpressObjectId: "13103", wordpressStatus: "draft", beforeHash: SAN_ANTONIO_DURABLE_HEADING_CONTRAST_BEFORE_HASH, afterHash, productContextH2MarkupBefore: productBefore, productContextH2MarkupAfter: productAfter, applicationH2MarkupBefore: applicationBefore, applicationH2MarkupAfter: applicationAfter, rule: GENESIS_DURABLE_HEADING_CONTRAST_CSS, copyHashBefore: copyBefore, copyHashAfter: copyAfter, sectionSequenceBefore: sequenceBefore, sectionSequenceAfter: sequenceAfter, mediaUrlsBefore: mediaBefore, mediaUrlsAfter: mediaAfter, seoHashBefore: seoBefore, seoHashAfter: seoAfter, productGridBefore: gridBefore ?? "", productGridAfter: gridAfter ?? "", featuredMediaBefore: 10757, featuredMediaAfter: 10757, contrastOnlyMutationProven: true, contentRegenerated: false, mediaRegenerated: false, workflowExecuted: false, dispatchPerformed: false, publicationPerformed: false, createdAt: new Date().toISOString() };
  return { receipt: save(receipt), reused: false };
}