import { NextRequest, NextResponse } from "next/server";
import { authorizeRequest, resolveRequestScope } from "@/modules/foundation/api-auth";
import { getMarketProductMatchBundle } from "@/modules/foundation/local-market-product-match-repository";
import { createDallasMarketProductMatchV1, DALLAS_MARKET_MATCH_BUNDLE_ID } from "@/modules/glw/dallas-market-product-match-service";
import { inspectDallasWordPressAuthority, inspectDallasWordPressMedia } from "@/modules/glw/dallas-wordpress-authority-inspector";
import { applyApprovedDallasV3 } from "@/modules/glw/dallas-rich-composition-apply-service";
import { getDallasApplyState } from "@/modules/glw/dallas-rich-composition-apply-repository";
import { getDallasPublicationState } from "@/modules/glw/dallas-reference-page-publication-repository";

export const dynamic = "force-dynamic";
const authorized = (request: NextRequest) => { const auth = authorizeRequest(request, "sites:read"); const scope = resolveRequestScope(request); return { auth, scope, valid: auth.ok && scope.organizationId === "ssi" && scope.siteId === "site-ssi-projectorenclosure" }; };
export async function GET(request: NextRequest) { const access = authorized(request); if (!access.valid) return NextResponse.json({ error: access.auth.ok ? "Exact Dallas scope required." : access.auth.error }, { status: access.auth.ok ? 403 : access.auth.status }); const bundle = getMarketProductMatchBundle({ organizationId: "ssi", bundleId: DALLAS_MARKET_MATCH_BUNDLE_ID }); if (!bundle) return NextResponse.json({ error: "Dallas market analysis not created." }, { status: 404 }); const include=request.nextUrl.searchParams.get("inspectWordPress") === "true";const publication=include?getDallasPublicationState():null;const reference=publication?.referenceCertifications.at(-1)??null;const revoked=Boolean(reference&&publication?.referenceRevocations.some((item)=>item.certificationId===reference.certificationId));const authority=include?await inspectDallasWordPressAuthority(reference&&!revoked?"publish":"draft"):null;const state=include?getDallasApplyState():null;const receipt=state?.receipts.at(-1)??null;const media=include&&receipt?await inspectDallasWordPressMedia([10757,...receipt.uploadedMedia.map(item=>item.mediaId)]):null;return NextResponse.json({ bundle, authority, media, apply:state?{decision:state.decisions.at(-1)??null,rollback:state.rollbacks.at(-1)??null,receipt,visualCertification:state.visualCertifications?.at(-1)??null,comparison:state.comparisons?.at(-1)??null,auditCount:state.audit.length}:null, referencePage:revoked?null:reference, referenceRevocation:revoked?publication?.referenceRevocations.at(-1):null, mutationPerformed: false }); }
export async function POST(request: NextRequest) { const access = authorized(request); if (!access.valid || !access.auth.ok || !access.auth.roles.includes("platform_admin")) return NextResponse.json({ error: "Platform-admin Dallas scope required." }, { status: 403 }); const body = await request.json().catch(() => null) as { operation?: string } | null; if (!body?.operation || Object.keys(body).some((key) => key !== "operation")) return NextResponse.json({ error: "Exact operation required." }, { status: 400 }); try { if(body.operation==="APPLY_OWNER_APPROVED_DALLAS_V3"){const result=await applyApprovedDallasV3({actor:"owner"});return NextResponse.json({...result,wordpressMutationPerformed:!result.reused,campaignMutationPerformed:false,publicationPerformed:false,dispatchPerformed:false},{status:result.reused?200:201})}if(body.operation!=="CREATE_DALLAS_MARKET_MATCH_V1")return NextResponse.json({error:"Unsupported operation."},{status:400});const bundle = await createDallasMarketProductMatchV1(); return NextResponse.json({ bundle, siteCreated: false, campaignCreated: false, campaignMutationPerformed: false, wordpressMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message.split(":")[0] : "MARKET_MATCH_FAILED", siteCreated: false, campaignCreated: false, campaignMutationPerformed: false, wordpressMutationPerformed: false, publicationPerformed: false, dispatchPerformed: false }, { status: 409 }); } }