import { NextRequest, NextResponse } from "next/server";
import { authorizeRequest, hasOrganizationScope, isRecordInScope, resolveRequestScope } from "@/modules/foundation/api-auth";
import { getSiteById } from "@/modules/foundation/site-repository";
import { getSiteIntelligenceWorkspace } from "@/modules/foundation/site-intelligence-repository";
import { addOwnerKnowledgeSource, addUrlSource, assertPublicSiteSourceUrl, decideAuthorityCandidate, getSiteAuthorityWorkspace } from "@/modules/foundation/site-product-authority-repository";
import type { AuthorityCandidateType, AuthorityDecision, SiteSourceRole } from "@/modules/foundation/site-product-authority-repository";

type Context = { params: Promise<{ siteId: string }> };
const SOURCE_ROLES = new Set<SiteSourceRole>(["BUSINESS_FACTS", "PRODUCT_SERVICE_AUTHORITY", "TECHNICAL_SPECIFICATION", "CREATIVE_REFERENCE", "OTHER_REFERENCE"]);
const TYPES = new Set<AuthorityCandidateType>(["PRODUCT", "SERVICE", "PRODUCT_FAMILY", "SERVICE_FAMILY"]);
const DECISIONS = new Set<AuthorityDecision>(["APPROVED", "QUALIFIED", "FUTURE", "REJECTED"]);

async function scoped(request: NextRequest, context: Context) { const scope = resolveRequestScope(request); const { siteId } = await context.params; const site = getSiteById(siteId); if (!hasOrganizationScope(scope) || !site || !isRecordInScope({ recordOrganizationId: site.organizationId, recordSiteId: site.siteId, scope })) return null; return site; }
function foundation(siteId: string) { const intelligence = getSiteIntelligenceWorkspace(siteId); const strategy = intelligence?.strategyRevisions.at(-1); if (!intelligence || !strategy || strategy.status !== "APPROVED" || intelligence.strategyState !== "STRATEGY_APPROVED" || intelligence.creativeState !== "CREATIVE_APPROVED") throw new Error("APPROVED_STRATEGY_AND_CREATIVE_REQUIRED"); return { intelligence, strategy }; }
function error(error: unknown) { return NextResponse.json({ error: error instanceof Error ? error.message : "PRODUCT_AUTHORITY_REQUEST_FAILED" }, { status: 422 }); }

export async function GET(request: NextRequest, context: Context) { const auth = authorizeRequest(request, "products:read"); if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status }); const site = await scoped(request, context); if (!site) return NextResponse.json({ error: "Site not found" }, { status: 404 }); try { const { intelligence, strategy } = foundation(site.siteId); return NextResponse.json({ site: { siteId: site.siteId, organizationId: site.organizationId, displayName: site.displayName }, strategy: { revision: strategy.revision, status: strategy.status }, creative: { revision: intelligence.creativeRevisions.at(-1)?.revision ?? null, state: intelligence.creativeState }, workspace: getSiteAuthorityWorkspace({ organizationId: site.organizationId, siteId: site.siteId, strategy }) }); } catch (cause) { return error(cause); } }

export async function POST(request: NextRequest, context: Context) { const auth = authorizeRequest(request, "products:create"); if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status }); const site = await scoped(request, context); if (!site) return NextResponse.json({ error: "Site not found" }, { status: 404 }); try { const { strategy } = foundation(site.siteId); const body = await request.json() as Record<string, unknown>; const action = String(body.action ?? ""); if (action === "ADD_URL_SOURCE") { const sourceRole = String(body.sourceRole) as SiteSourceRole; if (!SOURCE_ROLES.has(sourceRole)) throw new Error("SOURCE_ROLE_INVALID"); const normalized = await assertPublicSiteSourceUrl(String(body.url ?? "")); addUrlSource({ organizationId: site.organizationId, siteId: site.siteId, siteDomain: site.domain, url: normalized, sourceRole, label: String(body.label ?? ""), actor: "site-owner" }); } else if (action === "ADD_OWNER_KNOWLEDGE") { const sourceRole = String(body.sourceRole) as SiteSourceRole; if (!SOURCE_ROLES.has(sourceRole)) throw new Error("SOURCE_ROLE_INVALID"); addOwnerKnowledgeSource({ organizationId: site.organizationId, siteId: site.siteId, label: String(body.label ?? ""), statement: String(body.statement ?? ""), sourceRole, actor: "site-owner" }); } else if (action === "DECIDE_CANDIDATE") { const type = String(body.type) as AuthorityCandidateType; const decision = String(body.decision) as AuthorityDecision; if (!TYPES.has(type) || !DECISIONS.has(decision)) throw new Error("AUTHORITY_DECISION_INVALID"); decideAuthorityCandidate({ organizationId: site.organizationId, siteId: site.siteId, strategy, authorityId: String(body.authorityId), type, displayName: String(body.displayName ?? ""), description: String(body.description ?? ""), limitations: String(body.limitations ?? ""), decision, ownerAttestation: String(body.ownerAttestation ?? ""), sourceIds: Array.isArray(body.sourceIds) ? body.sourceIds.map(String) : [], actor: "site-owner" }); } else throw new Error("PRODUCT_AUTHORITY_ACTION_UNSUPPORTED"); return NextResponse.json({ workspace: getSiteAuthorityWorkspace({ organizationId: site.organizationId, siteId: site.siteId, strategy }) }); } catch (cause) { return error(cause); } }