import { NextRequest, NextResponse } from "next/server";

import { authorizeRequest, hasOrganizationScope, isRecordInScope, resolveRequestScope } from "@/modules/foundation/api-auth";
import { certifyCommercialStainlessWave2WordPress, inspectCommercialStainlessWave2Staging, listCommercialStainlessWave2WordPressStageRecords, stageCommercialStainlessWave2WordPress, summarizeCommercialStainlessWave2WordPressStageRecord, type Wave2ViewportEvidence } from "@/modules/foundation/commercial-stainless-wave2-staging";
import { getSiteById } from "@/modules/foundation/site-repository";

type Context={params:Promise<{siteId:string}>};
async function scoped(request:NextRequest,context:Context){const scope=resolveRequestScope(request);const{siteId}=await context.params;const site=getSiteById(siteId);return hasOrganizationScope(scope)&&site&&isRecordInScope({recordOrganizationId:site.organizationId,recordSiteId:site.siteId,scope})?site:null;}
const summaries=()=>listCommercialStainlessWave2WordPressStageRecords().map(summarizeCommercialStainlessWave2WordPressStageRecord);
export async function GET(request:NextRequest,context:Context){const auth=authorizeRequest(request,"sites:read");if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});const site=await scoped(request,context);if(!site)return NextResponse.json({error:"Site not found"},{status:404});try{return NextResponse.json({preflight:await inspectCommercialStainlessWave2Staging(site),records:summaries(),mutationPerformed:false,publicationMutation:false,nativeHostEvidenceAvailable:false});}catch(cause){return NextResponse.json({error:cause instanceof Error?cause.message:"COMMERCIAL_STAINLESS_WAVE2_PREFLIGHT_FAILED",records:summaries(),publicationMutation:false},{status:409});}}
export async function POST(request:NextRequest,context:Context){const auth=authorizeRequest(request,"sites:manage_integrations");if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});const site=await scoped(request,context);if(!site)return NextResponse.json({error:"Site not found"},{status:404});const body=await request.json().catch(()=>null) as null|{confirm?:string;results?:Array<{wordpressObjectId:number;viewports:Wave2ViewportEvidence[]}>};if(!body||!["STAGE_COMMERCIAL_STAINLESS_WAVE2_APPROVED_COMPOSITIONS_V1","CERTIFY_COMMERCIAL_STAINLESS_WAVE2_HOST_EQUIVALENT_V1"].includes(body.confirm??""))return NextResponse.json({error:"Explicit Wave 2 staging or host-equivalent certification confirmation is required."},{status:400});try{if(body.confirm==="CERTIFY_COMMERCIAL_STAINLESS_WAVE2_HOST_EQUIVALENT_V1")return NextResponse.json({records:certifyCommercialStainlessWave2WordPress(body.results??[]).map(summarizeCommercialStainlessWave2WordPressStageRecord),certificationPerformed:true,wordpressMutation:false,publicationMutation:false,nativeHostEvidenceAvailable:false});return NextResponse.json({records:(await stageCommercialStainlessWave2WordPress(site)).map(summarizeCommercialStainlessWave2WordPressStageRecord),mutationPerformed:true,wordpressMutation:true,publicationMutation:false});}catch(cause){return NextResponse.json({error:cause instanceof Error?cause.message:"COMMERCIAL_STAINLESS_WAVE2_STAGING_FAILED",records:summaries(),publicationMutation:false},{status:409});}}
