import type { EntitySchema } from "../schema/EntitySchema";

export const CustomerDefinition: EntitySchema = {
  entityType: "customer",

  businessIdPrefix: "CUS",

  description:
    "Represents a customer organization or individual connected to one or more companies, projects, quotes, orders, service records, and enterprise relationships.",

  display: {
    label: "Customer",
    pluralLabel: "Customers",
    icon: "users",
    primaryField: "name",
    secondaryField: "businessId",
    defaultSortField: "name",
  },

  fields: [
    {
      key: "id",
      label: "System ID",
      type: "uuid",
      required: true,
      unique: true,
      searchable: false,
      sortable: false,
      filterable: false,
      visible: false,
      editable: false,
    },
    {
      key: "businessId",
      label: "Customer ID",
      type: "string",
      required: true,
      unique: true,
      searchable: true,
      sortable: true,
      filterable: true,
      visible: true,
      editable: false,
    },
    {
      key: "companyId",
      label: "Owning Company",
      type: "uuid",
      required: true,
      searchable: false,
      sortable: true,
      filterable: true,
      visible: false,
      editable: false,
    },
    {
      key: "name",
      label: "Customer Name",
      type: "string",
      required: true,
      searchable: true,
      sortable: true,
      filterable: true,
      visible: true,
      editable: true,
      placeholder: "Enter customer name",
    },
    {
      key: "primaryContactName",
      label: "Primary Contact",
      type: "string",
      searchable: true,
      sortable: true,
      filterable: false,
      visible: true,
      editable: true,
    },
    {
      key: "primaryContactEmail",
      label: "Contact Email",
      type: "email",
      searchable: true,
      sortable: true,
      filterable: false,
      visible: true,
      editable: true,
      placeholder: "name@example.com",
    },
    {
      key: "primaryContactPhone",
      label: "Contact Phone",
      type: "phone",
      searchable: true,
      sortable: false,
      filterable: false,
      visible: true,
      editable: true,
    },
    {
      key: "industry",
      label: "Industry",
      type: "string",
      searchable: true,
      sortable: true,
      filterable: true,
      visible: true,
      editable: true,
    },
    {
      key: "website",
      label: "Website",
      type: "url",
      searchable: true,
      sortable: false,
      filterable: false,
      visible: false,
      editable: true,
    },
    {
      key: "billingAddress",
      label: "Billing Address",
      type: "text",
      searchable: true,
      sortable: false,
      filterable: false,
      visible: false,
      editable: true,
    },
    {
      key: "shippingAddress",
      label: "Shipping Address",
      type: "text",
      searchable: true,
      sortable: false,
      filterable: false,
      visible: false,
      editable: true,
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: true,
      searchable: true,
      sortable: true,
      filterable: true,
      visible: true,
      editable: true,
    },
    {
      key: "tags",
      label: "Tags",
      type: "array",
      searchable: true,
      sortable: false,
      filterable: true,
      visible: false,
      editable: true,
    },
    {
      key: "metadata",
      label: "Metadata",
      type: "metadata",
      searchable: false,
      sortable: false,
      filterable: false,
      visible: false,
      editable: true,
    },
    {
      key: "notes",
      label: "Notes",
      type: "text",
      searchable: true,
      sortable: false,
      filterable: false,
      visible: false,
      editable: true,
    },
  ],

  relationships: [],

  search: {
    enabled: true,
    defaultFields: [
      "businessId",
      "name",
      "primaryContactName",
      "primaryContactEmail",
      "primaryContactPhone",
      "industry",
      "notes",
    ],
    includeRelationships: true,
    includeArchived: false,
  },

  aiEnabled: true,
  auditEnabled: true,
  archiveEnabled: true,
};