/**
 * GenerationCompiler
 *
 * Executes a Generation Plan.
 *
 * The compiler converts a declarative plan into executable steps
 * and produces a compilation result.
 *
 * Phase 3 supports dry-run mode only (no file writing).
 * Phase 4 adds write mode with artifact record creation.
 * Phase 5 adds template rendering for entity artifacts.
 */

import { createCompilationDiagnostic } from "./CompilationDiagnostic.mjs";
import { createCompilationResult } from "./CompilationResult.mjs";
import { createArtifactRecord } from "../writers/ArtifactRecord.mjs";
import { renderEntityTemplate } from "../../templates/entity/TemplateRenderer.mjs";

/**
 * Compile a generation plan.
 *
 * @param {Object} context - Compilation context (from createCompilationContext)
 * @returns {Object} Immutable compilation result
 * @throws {Error} if context is invalid
 */
export function compilePlan(context) {
  if (!context || typeof context !== "object") {
    throw new Error("Context is required");
  }

  const { plan, mode, rootDir } = context;

  if (!plan || !Array.isArray(plan.steps)) {
    throw new Error("Context must have a valid plan with steps");
  }

  if (!mode || (mode !== "dry-run" && mode !== "write")) {
    throw new Error("Mode must be dry-run or write");
  }

  const artifacts = [];
  const diagnostics = [];
  const entityName = plan.subject || "Unknown";

  // Add info diagnostic about compilation start
  diagnostics.push(
    createCompilationDiagnostic({
      level: "info",
      code: "COMPILE_START",
      message: `Starting compilation in ${mode} mode for entity ${entityName}`,
    })
  );

  // Process each step in the plan
  for (const step of plan.steps) {
    try {
      // Render template for this artifact (Phase 5)
      let artifactContent;
      try {
        artifactContent = renderEntityTemplate(step.type, entityName);
      } catch (error) {
        // If template rendering fails, use fallback placeholder
        artifactContent = generatePlaceholderContent(
          entityName,
          step.name,
          step.type
        );
      }

      // Construct target path from step metadata or default
      const targetPath =
        step.metadata?.targetPath ||
        getDefaultTargetPath(entityName, step.type, step.name);

      // Create artifact record with unique ID
      const artifact = createArtifactRecord({
        id: `${plan.id}-${step.id}`,
        stepId: step.id,
        type: step.type,
        name: step.name,
        targetPath: targetPath,
        content: artifactContent,
        status: "planned",
        metadata: step.metadata ? { ...step.metadata } : {},
      });

      artifacts.push(artifact);

      // Add diagnostic for successful step planning
      diagnostics.push(
        createCompilationDiagnostic({
          level: "info",
          code: "STEP_PLANNED",
          message: `Planned: ${step.name}`,
          stepId: step.id,
        })
      );
    } catch (error) {
      // Add error diagnostic
      diagnostics.push(
        createCompilationDiagnostic({
          level: "error",
          code: "STEP_ERROR",
          message: `Failed to plan ${step.name}: ${error.message}`,
          stepId: step.id,
        })
      );
    }
  }

  // Add info diagnostic about compilation completion
  diagnostics.push(
    createCompilationDiagnostic({
      level: "info",
      code: "COMPILE_COMPLETE",
      message: `Compilation complete: ${artifacts.length} artifacts planned`,
    })
  );

  // Create and return immutable result
  const result = createCompilationResult({
    success: true,
    mode: mode,
    planId: plan.id,
    artifacts: artifacts,
    diagnostics: diagnostics,
  });

  return result;
}

/**
 * Generate placeholder content for an artifact.
 *
 * Fallback used when template rendering fails.
 * Clearly marks as Phase 5 placeholder with no business logic.
 */
function generatePlaceholderContent(entityName, artifactName, artifactType) {
  const timestamp = new Date().toISOString();

  const content = `/**
 * ${artifactName}
 *
 * Generated by Genesis Compiler
 * Timestamp: ${timestamp}
 *
 * This file is a Phase 4 placeholder artifact.
 * No business logic has been generated yet.
 *
 * Entity: ${entityName}
 * Artifact Type: ${artifactType}
 * Status: Planned (not implemented)
 *
 * This placeholder will be replaced with actual code
 * when template execution is implemented in Phase 5.
 */

// Placeholder: Implementation pending
`;

  return content;
}

/**
 * Get default target path for an artifact.
 *
 * All Phase 4 placeholder artifacts are written under:
 *   generated/genesis/<EntityName>/
 *
 * This keeps generated output isolated from source directories.
 */
function getDefaultTargetPath(entityName, artifactType, artifactName) {
  const base = `generated/genesis/${entityName}`;

  const typeMap = {
    "entity-definition": `${base}/${entityName}Definition.ts`,
    "repository":        `${base}/${entityName}Repository.ts`,
    "service":           `${base}/${entityName}Service.ts`,
    "validator":         `${base}/${entityName}Validator.ts`,
    "events":            `${base}/${entityName}Events.ts`,
    "permissions":       `${base}/${entityName}Permissions.ts`,
    "search":            `${base}/${entityName}Search.ts`,
    "documentation":     `${base}/${entityName}Documentation.md`,
    "tests":             `${base}/${entityName}.test.ts`,
  };

  return typeMap[artifactType] || `${base}/${artifactName.replace(/\s+/g, "")}.ts`;
}
