<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Genesis.GLW.RuntimeSupervisor.Tests</AssemblyName>
    <RootNamespace>Genesis.GLW.RuntimeSupervisor.Tests</RootNamespace>
    <SelfContained>false</SelfContained>
    <PublishAot>false</PublishAot>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Genesis.GLW.RuntimeSupervisor/Genesis.GLW.RuntimeSupervisor.csproj" />
  </ItemGroup>
</Project>
